import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import ContentSafetyActions,{CONTENT_SAFETY_CHANGED} from '../../../../components/ContentSafetyActions';
import {contentSafetyHeaders} from '../../../../lib/contentSafety';
import {useAuth} from '../../../../contexts/AuthContext';
import Link from 'next/link';
import Head from 'next/head';
import { useThemeContext } from '../../../../contexts/ThemeContext';
import { reviewDateLabel } from '../../../../lib/placePresentation';
type Review = { id:string; reviewId:string; date:string; dateSource?:string; recordedAt?:string; isEdit?:boolean; name:string; note:string|null; signals:{label:string;category:string}[] };
type Response = { place:{id:string;name:string}; total:number; page:number; includesRevisions?:boolean; reviews:Review[] };
export default function ReviewHistory(){
 const router=useRouter();const id=String(router.query.id||'');const {theme,isDark}=useThemeContext();
 const {user}=useAuth();const [refresh,setRefresh]=useState(0);
 useEffect(()=>{const changed=()=>{setPage(0);setRefresh(v=>v+1)};window.addEventListener(CONTENT_SAFETY_CHANGED,changed);return()=>window.removeEventListener(CONTENT_SAFETY_CHANGED,changed)},[]);
 const [page,setPage]=useState(0);const [data,setData]=useState<Response|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!id)return;const controller=new AbortController();setLoading(true);setError('');setData(null);contentSafetyHeaders().then(headers=>fetch(`/api/place/${encodeURIComponent(id)}/reviews?page=${page}`,{headers,signal:controller.signal})).then(r=>r.ok?r.json():Promise.reject(new Error('Reviews could not be loaded. Please try again.'))).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[id,page,refresh,user?.id]);
 return <><Head><title>Reviews · Tavvy</title></Head><main className="history"><Link href={`/app/place/${encodeURIComponent(id)}`}>← Back to {data?.place.name||'place'}</Link><h1>{data?.place.name||'Place'} reviews</h1><p>See what guests experienced and when. Older concerns remain here as the current summary changes.</p>{data?.includesRevisions&&<p>Edits are labeled. Earlier versions stay visible; they do not count as additional guests.</p>}{loading&&<p role="status">Loading reviews…</p>}{error&&<p role="alert">{error}</p>}{data?.reviews.length===0&&<p>No reviews yet.</p>}{data?.reviews.map(review=><article key={review.id}><div className="byline"><strong>{review.name}</strong><time dateTime={review.date}>{reviewDateLabel(review.date,review.dateSource)}</time></div>{review.isEdit&&<p className="date">Edited{review.recordedAt?` · saved ${reviewDateLabel(review.recordedAt)}`:''}</p>}{review.note&&<p className="note">{review.note}</p>}<ContentSafetyActions kind="place_review" contentId={review.reviewId}/><div className="chips">{review.signals.map((signal,i)=><span key={i} className={signal.category}>{signal.label}</span>)}</div></article>)}{data&&data.total>0&&<nav className="pages" aria-label="Review pages"><button disabled={page===0} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1} · {data.total} {data.includesRevisions?'entries':'reviews'}</span><button disabled={(page+1)*20>=data.total} onClick={()=>setPage(page+1)}>Next</button></nav>}</main><style jsx>{`
 .history{max-width:720px;min-height:100vh;margin:auto;padding:24px;background:${theme.background};color:${theme.text};font-family:inherit}.history>a{color:${theme.primary}}h1{margin-bottom:8px}.history>p,.date{color:${theme.textSecondary};line-height:1.5}article{border-top:1px solid ${theme.border};padding:20px 0}.byline{display:flex;justify-content:space-between;gap:12px}time,.date{color:${theme.textSecondary};font-size:13px}.note{white-space:pre-wrap;line-height:1.6;overflow-wrap:anywhere}.chips{display:flex;flex-wrap:wrap;gap:7px;margin-top:12px}.chips span{padding:6px 10px;border-radius:16px;font-size:13px;border:1px solid}.good{color:${isDark?'#56DFD9':'#066B68'}}.vibe{color:${isDark?'#D9B6FF':'#74209A'}}.headsup{color:${isDark?'#FFD38A':'#885000'}}.pages{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:24px;font-size:13px}button{background:${theme.surface};border:1px solid ${theme.border};border-radius:12px;color:${theme.text};padding:12px;min-height:44px}button:disabled{opacity:.5}button:focus-visible{outline:3px solid ${theme.primary};outline-offset:3px}
 `}</style></>;
}
