/** Read-only public compatibility endpoints. Caller supplies a viewer/anonymous client, never service-role. */
export const COLUMNS='id,slug,business_name,first_name,last_name,brokerage_name,description,short_description,bio,phone,email,website,logo_url,profile_photo_url,cover_photo_url,cover_image_url,city,state,service_areas,specialties,trade_category,years_experience,years_in_business,license_number,is_active,provider_type';
const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json','Cache-Control':'private, no-store'};
const result=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers});
const pattern=(s:string)=>'"%'+s.replace(/[\\%_]/g,'\\$&').replace(/"/g,'\\"')+'%"';
const uuid=(s:unknown)=>typeof s==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(s);
function provider(row:any){if(!row||!uuid(row.id)||row.is_active!==true||typeof row.business_name!=='string')throw new Error('profile');const p:any={};for(const key of COLUMNS.split(','))if(key in row)p[key]=row[key];return {...p,businessName:p.business_name,profilePhotoUrl:p.profile_photo_url||p.logo_url,coverPhotoUrl:p.cover_photo_url||p.cover_image_url,yearsInBusiness:p.years_in_business,licenseNumber:p.license_number,isActive:p.is_active};}
async function body(req:Request){if(!req.body)return {};const reader=req.body.getReader();let size=0;const chunks:Uint8Array[]=[];try{while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>8192){await reader.cancel();throw new Error('body');}chunks.push(value);}}finally{reader.releaseLock();}const joined=new Uint8Array(size);let n=0;for(const c of chunks){joined.set(c,n);n+=c.length;}const p=JSON.parse(new TextDecoder().decode(joined));if(!p||typeof p!=='object'||Array.isArray(p))throw new Error('body');return p;}
function text(value:unknown,max:number){if(value==null)return undefined;if(typeof value!=='string'||value.length>max)throw new Error('input');return value.trim()||undefined;}
export function createProviderPublicHandler(mode:'search'|'featured'|'profile',client:any){return async(req:Request)=>{if(req.method==='OPTIONS')return result({});if(req.method!=='POST')return result({error:'Use POST.'},405);let p:any;try{p=await body(req);for(const name of ['categorySlug','query','city','state','zipCode','slug'])p[name]=text(p[name],name==='slug'?160:120);if(p.limit!==undefined&&(!Number.isInteger(p.limit)||p.limit<1||p.limit>50))throw new Error('input');if(p.offset!==undefined&&(!Number.isInteger(p.offset)||p.offset<0||p.offset>10000))throw new Error('input');}catch{return result({error:'Invalid request.'},400);}try{
 if(mode==='profile'){if(!p.slug||(!uuid(p.slug)&&!/^[a-z0-9][a-z0-9_-]{0,159}$/i.test(p.slug)))return result({error:'Invalid profile.'},400);const {data,error}=await client.from('pro_provider_public_profiles').select(COLUMNS).eq('is_active',true).eq(uuid(p.slug)?'id':'slug',p.slug).maybeSingle();if(error)throw error;if(!data)return result({error:'Profile not found.'},404);const reviews=await client.rpc('get_pro_provider_reviews_v1',{p_provider_id:data.id,p_offset:0,p_limit:20});if(reviews.error||!Array.isArray(reviews.data?.reviews))throw new Error('reviews');const photos=await client.from('pro_photos').select('id,provider_id,image_url,caption,sort_order,created_at').eq('provider_id',data.id).order('sort_order',{ascending:true}).order('id',{ascending:true}).range(0,59);if(photos.error)throw photos.error;const publicProvider=provider(data);const publicReviews=reviews.data.reviews.map((r:any)=>({id:r.id,rating:r.rating,title:r.title,content:r.content,created_at:r.created_at,updated_at:r.updated_at}));return result({...publicProvider,pro_reviews:publicReviews,service_categories:[],provider:publicProvider,reviews:reviews.data.reviews.map((r:any)=>({id:r.id,rating:r.rating,title:r.title,content:r.content,createdAt:r.created_at,updatedAt:r.updated_at})),reviewsHasMore:reviews.data.hasMore===true,photos:(photos.data||[]).map((r:any)=>({id:r.id,url:r.image_url,caption:r.caption,sortOrder:r.sort_order,createdAt:r.created_at})),categories:[],availability:[],availabilityStatus:'unavailable'});}
 const limit=p.limit??(mode==='featured'?10:20),offset=p.offset??0;let q=client.from('pro_provider_public_profiles').select(COLUMNS,{count:'exact'}).eq('is_active',true);if(mode==='featured')q=q.eq('is_featured',true);if(p.categorySlug&&p.categorySlug!=='all')q=q.eq('trade_category',p.categorySlug);if(p.query)q=q.or(['business_name','first_name','last_name','brokerage_name'].map(f=>`${f}.ilike.${pattern(p.query)}`).join(','));if(p.city)q=q.ilike('city','%'+p.city.replace(/[\\%_]/g,'\\$&')+'%');if(p.state)q=q.eq('state',p.state);if(p.zipCode)q=q.eq('zip_code',p.zipCode);const {data,error,count}=await q.order('business_name',{ascending:true}).order('id',{ascending:true}).range(offset,offset+limit-1);if(error||!Array.isArray(data)||!Number.isInteger(count))throw new Error('read');return result(mode==='featured'?data.map(provider):{providers:data.map(provider),total:count});
 }catch{return result({error:'Profiles are unavailable. Please try again.'},503);}};}
