const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const root=fs.existsSync(path.join(__dirname,'../lib'))?path.resolve(__dirname,'..'):path.resolve(__dirname,'../..');
function load(file,dependencies={}){const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,URL,Error,Promise,process:{env:{}},console,require(name){if(name in dependencies)return dependencies[name];throw Error('Unmocked dependency '+name)}});return module.exports;}
const venue=load('lib/cruises/venueContext.ts'),id=n=>`a2200000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const context=()=>({venue_id:id(1),place_id:id(2),ship_id:id(3),universe_id:id(4),venue_name:'QA Dining',ship_name:'QA Ship',ship_slug:'qa-ship',operator_name:'QA Operator',kind:'restaurant',review_category:'restaurant',deck_label:'Deck 5',included:null,availability_note:null,description:null,official_url:'https://example.invalid/ship',accepts_reviews:true,sources:[]});
const place=()=>({id:id(2),source_type:'cruise_venue',source_id:`cruise-venue:${id(3)}:${id(1)}`,name:'Old name',tavvy_category:'restaurant',is_active:true,status:'active'});
test('ordinary place performs no cruise RPC and preserves absence semantics',async()=>{assert.equal(await venue.loadCruiseVenueContext({rpc(){assert.fail('Unexpected RPC')}},{id:id(2),source_type:'fsq'}),null)});
test('valid context binds exact venue/ship/place provenance and retains unknown inclusion',async()=>{const p=place(),calls=[];const c=await venue.loadCruiseVenueContext({rpc:async(n,args)=>{calls.push([n,args]);return{data:context()}}},p);assert.equal(c.venue_name,'QA Dining');assert.equal(c.included,null);assert.equal(c.place_id,p.id);assert.equal(calls[0][0],'get_cruise_venue_context_v1');assert.equal(calls[0][1].p_place_id,p.id);assert.equal(venue.cruiseVenueShipHref(c),'/app/cruises/qa-ship')});
test('hidden onboard context fails closed',async()=>{await assert.rejects(venue.loadCruiseVenueContext({rpc:async()=>({data:null})},place()),e=>e.reason==='hidden')});
test('RPC error and transport error remain unavailable, never ordinary or empty',async()=>{for(const rpc of[async()=>({data:null,error:{message:'private internal'}}),async()=>{throw Error('private internal')}])await assert.rejects(venue.loadCruiseVenueContext({rpc},place()),e=>e.reason==='unavailable'&&!e.message.includes('private'))});
test('malformed, mismatched or cross-ship contexts are rejected',()=>{for(const patch of[{place_id:id(9)},{ship_id:id(8)},{ship_slug:'../other'},{accepts_reviews:'true'},{included:'unknown'},{review_category:'cruise_ship'}])assert.throws(()=>venue.parseCruiseVenueContext({...context(),...patch},id(2),place().source_id),/could not be loaded/)});
test('announced context is browsable without enabling review',()=>{const c=venue.parseCruiseVenueContext({...context(),accepts_reviews:false},id(2));assert.equal(c.accepts_reviews,false)});
test('unsafe external URLs cannot become links',()=>{for(const url of['javascript:alert(1)','http://example.invalid','https://user:pass@example.invalid','data:text/html,hello'])assert.equal(venue.safeVenueWebsite(url),null);assert.equal(venue.parseCruiseVenueContext({...context(),official_url:'javascript:alert(1)',sources:[{id:'bad',publisher:'x',checked_at:'2026-01-01',source_type:'operator',url:'javascript:alert(1)'}]},id(2)).sources.length,0)});
if(fs.existsSync(path.join(root,'pages/api/place/[id].ts'))){
 const run=async(options={})=>{const calls=[],p=options.place||place();const client={from(table){calls.push(['from',table]);const result={data:table==='places'?p:[],error:null,count:0};const chain=new Proxy({}, {get(_t,k){if(k==='then')return resolve=>resolve(result);if(k==='maybeSingle')return async()=>result;if(['insert','update','delete','upsert'].includes(k))return()=>assert.fail('Real write forbidden');return()=>chain}});return chain},rpc:async(name,args)=>{calls.push(['rpc',name,args]);if(name==='get_cruise_venue_context_v1')return options.contextResult||{data:context()};if(name==='get_place_photo_safety_v1')return{data:{cover:null,photos:[]}};return{data:[],error:null}}};let subject;const handler=load('pages/api/place/[id].ts',{'@supabase/supabase-js':{createClient:()=>client},'../../../lib/placeEvidenceService':{fetchPlaceEvidence:async(_id,s)=>{subject=s;return{dataStatus:'ready'}}},'../../../lib/contentSafetyServer':{contentViewer:async()=>({client})},'../../../lib/placeHours':{},'../../../lib/cruises/venueContext':venue,'../../../lib/typesenseService':{getPlaceById:async()=>null}}).default;const response={setHeader(){},status(code){this.code=code;return this},json(body){this.body=body;return this}};await handler({query:{id:p.id}},response);return{...response,calls,subject}};
 test('actual place API returns authoritative venue context/category with canonical review ID',async()=>{const r=await run();assert.equal(r.code,200);assert.equal(r.body.place.name,'QA Dining');assert.equal(r.body.place.source_type,'cruise_venue');assert.equal(r.body.cruiseVenue.ship_id,id(3));assert.equal(r.subject.category,'restaurant');assert(r.calls.filter(c=>c[0]==='rpc'&&c[1]==='get_place_recent_reviews').every(c=>c[2].p_place_id===id(2)))});
 test('actual place API stops hidden onboard data before content reads',async()=>{const r=await run({contextResult:{data:null}});assert.equal(r.code,404);assert.equal(r.calls.filter(c=>c[0]==='from').length,1)});
 test('actual place API distinguishes unavailable backend from hidden',async()=>{const r=await run({contextResult:{error:{message:'private'},data:null}});assert.equal(r.code,503);assert(!r.body.error.includes('private'));assert.equal(r.calls.filter(c=>c[0]==='from').length,1)});
 test('ordinary API path remains functional without the new RPC',async()=>{const r=await run({place:{...place(),source_type:'user'}});assert.equal(r.code,200);assert.equal(r.body.cruiseVenue,null);assert(!r.calls.some(c=>c[1]==='get_cruise_venue_context_v1'))});
}else{
 const lookup=load('lib/placeDetailsLookup.ts',{'./placeShare':{normalizePlaceShareId:v=>v},'./cruises/venueContext':venue}).lookupPlaceDetails;
 const db=(response)=>({from(){const q={select(){return q},eq(){return q},limit:async()=>({data:[place()]})};return q},rpc:async()=>response});
 test('actual native lookup uses canonical context name and category',async()=>{const p=await lookup(id(2),db({data:context()}));assert.equal(p.id,id(2));assert.equal(p.name,'QA Dining');assert.equal(p.cruiseVenue.universe_id,id(4));assert.equal(p.tavvy_subcategory,null)});
 test('actual native lookup refuses hidden onboard fallback',async()=>{await assert.rejects(lookup(id(2),db({data:null})),/not available/)});
 test('actual native lookup surfaces unavailable context',async()=>{await assert.rejects(lookup(id(2),db({error:{message:'private'}})),/could not be loaded/)});
}
