const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require(process.env.TAVVY_TYPESCRIPT || 'typescript');
const result = { exports: {} };
const source = ts.transpileModule(fs.readFileSync('lib/placeHours.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText;
vm.runInNewContext(source, { exports: result.exports, Intl, Date });
const { parseHours, openLineFrom } = result.exports;
const weekly = Object.fromEntries(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map(day => [day, '12:00-22:00']));
const hours = parseHours(weekly);
assert.equal(openLineFrom(hours.byDow, 'America/New_York', new Date('2026-09-20T15:00:00Z')), 'Closed · opens 12 PM');
assert.equal(openLineFrom(hours.byDow, 'America/New_York', new Date('2026-09-20T17:00:00Z')), 'Open till 10 PM');
assert.equal(openLineFrom(hours.byDow, 'America/Los_Angeles', new Date('2026-09-20T17:00:00Z')), 'Closed · opens 12 PM');
assert.equal(openLineFrom(hours.byDow), '');
assert.equal(openLineFrom(hours.byDow, 'Invalid/Timezone'), '');
assert.equal(parseHours({ Monday: 'Closed' }).hoursList[1].range, 'Closed');
assert.equal(parseHours({ Monday: '' }).hoursList[1].range, 'Hours unavailable');
assert.equal(openLineFrom(parseHours({Monday:'12:00-22:00'}).byDow, 'America/New_York'), '');
const overnight = parseHours({...weekly, Saturday: '18:00-02:00'});
assert.equal(openLineFrom(overnight.byDow, 'America/New_York', new Date('2026-09-20T05:00:00Z')), 'Open till 2 AM');
assert.equal(openLineFrom(hours.byDow, 'America/New_York', new Date('2026-12-20T16:00:00Z')), 'Closed · opens 12 PM');
assert.equal(parseHours({ Monday: '25:99-27:00' }).hoursList[1].range, 'Hours unavailable');
assert.equal(parseHours({ Monday: 'Open 24 hours' }).hoursList[1].range, 'Open 24 hours');
console.log('Place hours: timezone, DST, overnight and missing-hours checks passed');
