const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const root=path.join(__dirname,'..');const exported={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(root,'lib/providerPublic.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:exported,URL,Date});const p=exported;
const id='00000000-0000-4000-8000-000000000001',row={id,slug:'qa-realtor',business_name:'QA Brokerage',first_name:'QA',last_name:'Agent',is_active:true,provider_type:'realtor'};
function client(result){const calls=[];const q=new Proxy({then:(a,b)=>Promise.resolve(result).then(a,b)},{get(t,k){if(k==='then')return t.then;return(...args)=>{calls.push([k,...args]);return q}}});return {from:name=>{calls.push(['from',name]);return q},rpc:async(name,args)=>{calls.push(['rpc',name,args]);return result},calls};}
test('explicit public projection contains no private account/billing/IP fields or nonexistent columns',()=>{for(const s of ['*','user_id','stripe_','onboarding','ip_','display_name','company_name','rating','place_id'])assert.ok(!p.PROVIDER_COLUMNS.split(',').some(v=>v===s||v.startsWith(s==='stripe_'||s==='ip_'?s:'__never')));assert.equal(p.PROVIDER_COLUMNS.includes('profile_photo_url'),true)});
test('slug resolves provider before review fetch uses actual returned UUID',async()=>{const c=client({data:row,error:null});const got=await p.getProvider(c,'qa-realtor','realtor');assert.equal(got.id,id);assert.ok(c.calls.some(x=>x[0]==='eq'&&x[1]==='slug'&&x[2]==='qa-realtor'));assert.ok(c.calls.some(x=>x[1]==='is_active'&&x[2]===true));assert.ok(c.calls.some(x=>x[1]==='provider_type'&&x[2]==='realtor'));});
test('empty profile stays null and error is distinct from not found',async()=>{assert.equal(await p.getProvider(client({data:null,error:null}),id),null);await assert.rejects(p.getProvider(client({data:null,error:{message:'offline'}}),id),/could not be loaded/)});
test('invalid ID never becomes fabricated person or executes query',async()=>{const c=client({data:row,error:null});assert.equal(await p.getProvider(c,'bad/id'),null);assert.equal(c.calls.length,0)});
test('provider projection rejects inactive and removes unexpected private fields',async()=>{await assert.rejects(p.getProvider(client({data:{...row,is_active:false},error:null}),id));const got=await p.getProvider(client({data:{...row,stripe_customer_id:'secret',user_id:'private',rating:4.8},error:null}),id);assert.equal(got.stripe_customer_id,undefined);assert.equal(got.rating,undefined)});
test('name/area/contacts use actual fields and reject executable URL or injected email',()=>{assert.equal(p.providerName(row),'QA Agent');assert.equal(p.providerArea({...row,city:'Boston',state:'MA'}),'Boston, MA');assert.equal(p.publicWebUrl('javascript:alert(1)'),null);assert.equal(p.publicWebUrl('https://user:pass@example.invalid'),null);assert.equal(p.publicWebUrl('example.invalid'),'https://example.invalid/');const c=p.providerContacts({...row,phone:'(617) 555-0100',email:'a@example.invalid?bcc=someone@example.invalid',website:'https://example.invalid'});assert.deepEqual(Array.from(c,x=>x.label),['Call','Website']);assert.equal(c[0].url,'tel:6175550100')});
test('empty and failed lists are distinct without fake fallback',async()=>{assert.equal((await p.listProviders(client({data:[],error:null}),{kind:'realtor'})).providers.length,0);await assert.rejects(p.listProviders(client({data:null,error:{}}),{kind:'realtor'}),/could not be loaded/)});
test('search escapes PostgREST punctuation and wildcards, uses known columns, stable pagination',async()=>{const c=client({data:[],error:null});await p.listProviders(c,{kind:'realtor',query:'a,b%_"',offset:24});const filter=c.calls.find(x=>x[0]==='or')[1];assert.match(filter,/first_name.ilike/);assert.match(filter,/\\%\\_/);assert.doesNotMatch(filter,/display_name|company_name/);assert.deepEqual(c.calls.find(x=>x[0]==='range'),['range',24,48]);assert.ok(c.calls.some(x=>x[0]==='order'&&x[1]==='id'))});
test('browse pages return24 with explicit hasMore and no made-up aggregates',async()=>{const c=client({data:Array(25).fill(row),error:null});const result=await p.listProviders(c,{kind:'pros',category:'plumbing'});assert.equal(result.providers.length,24);assert.equal(result.hasMore,true);assert.ok(c.calls.some(x=>x[0]==='eq'&&x[1]==='trade_category'&&x[2]==='plumbing'));assert.equal(result.providers[0].average_rating,undefined)});
test('review feed uses typed server RPC only, strips private unexpected metadata',async()=>{const c=client({data:{reviews:[{id,rating:4,content:'Actual review',created_at:'2026-09-01T12:00:00Z',ip_address:'private',user_id:'private'}],hasMore:false},error:null});const result=await p.getProviderReviews(c,id);assert.equal(c.calls[0][0],'rpc');assert.equal(c.calls[0][1],'get_pro_provider_reviews_v1');assert.equal(result.reviews[0].content,'Actual review');assert.equal(result.reviews[0].ip_address,undefined);assert.equal(result.reviews[0].user_id,undefined)});
test('review endpoint failure or invalid data never becomes no reviews',async()=>{await assert.rejects(p.getProviderReviews(client({data:null,error:{}}),id),/unavailable/);await assert.rejects(p.getProviderReviews(client({data:{reviews:[{id,rating:0,created_at:'now'}],hasMore:false},error:null}),id));});
test('photos use provider FK and allowlisted fields, no unrelated fallback image',async()=>{const c=client({data:[{id,provider_id:id,image_url:'https://example.invalid/photo.png',private:'no'}],error:null});const result=await p.getProviderPhotos(c,id);assert.equal(result.photos.length,1);assert.equal(result.photos[0].private,undefined);assert.ok(c.calls.some(x=>x[0]==='eq'&&x[1]==='provider_id'&&x[2]===id));assert.equal(c.calls.find(x=>x[0]==='select')[1].includes('*'),false)});

test('legacy unknown review dates remain unknown without dropping the feed',async()=>{const c=client({data:{reviews:[{id,rating:4,content:'Undated',created_at:null}],hasMore:false},error:null});const result=await p.getProviderReviews(c,id);assert.equal(result.reviews[0].created_at,null);assert.equal(p.providerReviewDate(null),'Date unavailable');assert.equal(p.providerReviewDate('invalid'),'Date unavailable')});

test('all public profile reads use the safe active projection, not owner rows',async()=>{for(const task of [c=>p.getProvider(c,id),c=>p.listProviders(c,{kind:'realtor'})]){const c=client({data:task.toString().includes('listProviders')?[row]:row,error:null});await task(c);assert.equal(c.calls.find(x=>x[0]==='from')[1],'pro_provider_public_profiles');}});
