const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const platform=fs.existsSync(path.join(__dirname,'../screens/RestaurantWorkspaceScreen.tsx'))?'native':'web';
const file=path.join(__dirname,platform==='native'?'../screens/RestaurantWorkspaceScreen.tsx':'../pages/app/business/[placeId].tsx');
const ast=ts.createSourceFile(file,fs.readFileSync(file,'utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),arrows={};
function visit(n){if(ts.isVariableDeclaration(n)&&ts.isIdentifier(n.name)&&n.initializer&&ts.isArrowFunction(n.initializer))arrows[n.name.text]=n.initializer.getText(ast);ts.forEachChild(n,visit)}visit(ast);
const exportsScope={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'../lib/ownerRequestScope.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:exportsScope});
function harness(provider){const rows=[],messages=[],loading=[],errors=[],calls=[];const scope=exportsScope.createOwnerRequestScope('A:place');const ctx={scope,ownerKey:'A:place',user:{id:'A'},placeId:'place',isPlaceId:()=>true,loadSequence:{current:0},supabase:{},WEEK_DAYS:['Monday'],RESTAURANT_LINKS:[],getRestaurantWorkspace:provider,
 setW:x=>rows.push(x),setWorkspace:x=>rows.push(x),setMessage:x=>messages.push(x),setError:x=>errors.push(x),setLoading:x=>loading.push(x),
 w:{canManage:true},workspace:{canManage:true},busy:false,phone:'',website:'',description:'',links:{},editHours:false,hours:{},cardId:'card',saveRestaurantDetails:async()=>calls.push('save'),linkRestaurantCard:async()=>calls.push('link')};
 for(const name of ['setLoadedFor','setPhone','setWebsite','setDescription','setHours','setLinks','setBusy','setEditHours'])ctx[name]=()=>{};
 for(const name of ['load','save','linkCard'])vm.runInNewContext(ts.transpileModule(`globalThis.${name}=${arrows[name]}`,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx);
 return{ctx,scope,rows,messages,loading,errors,calls};}
const row=name=>({place:{id:'place',name},canManage:false});
test(platform+' actual workspace load rejects late A after B and keeps B response',async()=>{let release;let count=0;const h=harness(()=>++count===1?new Promise(r=>{release=r}):Promise.resolve(row('B')));const old=h.ctx.load();h.scope.setIdentity('B:place');h.ctx.ownerKey='B:place';h.ctx.user={id:'B'};await h.ctx.load();release(row('A'));await old;assert.deepEqual(h.rows.map(r=>r.place.name),['B']);assert.equal(h.loading.at(-1),false)});
test(platform+' actual workspace load rejects late response after unmount',async()=>{let release;const h=harness(()=>new Promise(r=>{release=r}));const pending=h.ctx.load();h.scope.close();release(row('A'));await pending;assert.equal(h.rows.length,0)});
test(platform+' concurrent refresh keeps only the newest workspace',async()=>{let release,count=0;const h=harness(()=>++count===1?new Promise(r=>{release=r}):Promise.resolve(row('new')));const older=h.ctx.load();await h.ctx.load();release(row('old'));await older;assert.deepEqual(h.rows.map(r=>r.place.name),['new'])});
for(const name of ['save','linkCard'])test(platform+' '+name+' response cannot update a different account',async()=>{let release;const h=harness(async()=>row('A'));h.ctx[name==='save'?'saveRestaurantDetails':'linkRestaurantCard']=()=>new Promise(r=>{release=r});const pending=h.ctx[name](name==='save'?{preventDefault(){}}:'card');h.scope.setIdentity('B:place');release();await pending;assert.equal(h.rows.length,0);assert.equal(h.messages.filter(Boolean).length,0)});
