const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
function compile(file,dependencies={}){const exports={};const source=fs.readFileSync(path.join(__dirname,'../lib',file),'utf8');vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:id=>dependencies[id],URL,Date,process:{env:{NEXT_PUBLIC_SUPABASE_URL:'https://test.supabase.co',NEXT_PUBLIC_SUPABASE_ANON_KEY:'public-test'}}});return exports;}
const owner=compile('restaurantOwner.ts');
const id='12345678-1234-4234-8234-123456789012',claimId='22345678-1234-4234-8234-123456789012';
const valid={placeId:id,name:'Restaurant Owner',role:'Owner',email:'owner@example.com',phone:'+1 (617) 555-0100',accepted:true};
const claim={id:claimId,place_id:id,status:'pending',ownership_verified_at:null};
const verified={...claim,status:'verified',ownership_verified_at:'2026-09-21T12:00:00Z'};
test('claim requires canonical place, authorized representative and usable contacts',()=>{
 for(const bad of [{...valid,placeId:'demo-restaurant'},{...valid,accepted:false},{...valid,email:'invalid'},{...valid,name:''},{...valid,phone:'hello'},{...valid,role:'x'.repeat(81)}])assert.throws(()=>owner.validateRestaurantClaim(bad));
 assert.equal(owner.validateRestaurantClaim({...valid,email:' OWNER@example.com '}).email,'owner@example.com');
});
test('client-supplied user/status/proof never become RPC arguments',async()=>{let args;await owner.submitRestaurantClaim({rpc:async(name,data)=>{args=data;return{data:claim,error:null};}},{...valid,userId:'another-user',status:'verified',ownership_verified_at:'2026-09-21'});assert.equal(args.p_place_id,id);assert.equal(args.userId,undefined);assert.equal(args.status,undefined);assert.equal(args.ownership_verified_at,undefined);});
test('network and unconfirmed responses cannot show saved claim success',async()=>{await assert.rejects(()=>owner.submitRestaurantClaim({rpc:async()=>({data:null,error:{code:'NETWORK'}})},valid));await assert.rejects(()=>owner.submitRestaurantClaim({rpc:async()=>({data:{...claim,place_id:claimId},error:null})},valid));});
test('pending and legacy Pros verified states cannot manage a restaurant',()=>{assert.equal(owner.canManageRestaurant(claim),false);assert.equal(owner.canManageRestaurant({...claim,status:'verified'}),false);assert.equal(owner.canManageRestaurant({...verified,ownership_verified_at:'invalid'}),false);assert.equal(owner.canManageRestaurant(verified),true);});
test('pending workspace drops any accidentally returned management data',async()=>{const result=await owner.getRestaurantWorkspace({rpc:async()=>({data:{place:{id},claim,canManage:true,menu:{view_count:500},cards:[{id}]}})},id);assert.equal(result.canManage,false);assert.equal(result.cards,undefined);assert.equal(result.menu,undefined);});
test('details reject script URLs, counterfeit delivery hosts and invalid hours',()=>{const base={phone:'617-555-0100',website:'https://example.com',description:'Our restaurant'};assert.throws(()=>owner.validateRestaurantDetails({...base,website:'javascript:alert(1)'}));const links=Object.fromEntries(owner.RESTAURANT_LINKS.map(l=>[l.key,'']));assert.throws(()=>owner.validateRestaurantDetails({...base,links:{...links,doordash:'https://doordash.com.evil.example/store'}}));assert.throws(()=>owner.validateRestaurantDetails({...base,links:{...links,doordash:'https://owner@doordash.com/store'}}));const hours=Object.fromEntries(owner.WEEK_DAYS.map(d=>[d,'Closed']));assert.throws(()=>owner.validateRestaurantDetails({...base,hours:{...hours,Monday:'25:00-27:00'}}));assert.equal(owner.validateRestaurantDetails({...base,hours:{...hours,Monday:'12:00-15:00,17:00-22:00'},links:{...links,doordash:'https://www.doordash.com/store/123'}}).links.doordash,'https://www.doordash.com/store/123');});
function response(){return{code:0,body:null,setHeader(){},status(n){this.code=n;return this;},json(v){this.body=v;return this;}};}
function api(client){return compile('restaurantOwnerApi.ts',{'./restaurantOwner':owner,'@supabase/supabase-js':{createClient:()=>client}}).restaurantOwnerApi;}
test('API rejects missing and expired credentials before any data operation',async()=>{let called=false;const factory=()=>{called=true;return{};};let res=response();await api({})('claims',factory)({method:'POST',headers:{},body:valid},res);assert.equal(res.code,401);assert.equal(called,false);res=response();await api({auth:{getUser:async()=>({data:{user:null},error:{message:'expired'}})}})('claims')({method:'POST',headers:{authorization:'Bearer expired'},body:valid},res);assert.equal(res.code,401);});
test('pending API workspace cannot write while verified workspace delegates to guarded RPC',async()=>{let writes=0;let activeClaim=claim;const client={auth:{getUser:async()=>({data:{user:{id:'user'}},error:null})},rpc:async(name)=>{if(name==='get_restaurant_owner_workspace')return{data:{place:{id},claim:activeClaim,canManage:true}};writes++;return{data:id};}};const handle=api(client)('workspace');const req={method:'PATCH',headers:{authorization:'Bearer valid'},query:{placeId:id},body:{phone:'617-555-0100',website:'https://example.com',description:'Our restaurant'}};let res=response();await handle(req,res);assert.equal(res.code,403);assert.equal(writes,0);activeClaim=verified;res=response();await handle(req,res);assert.equal(res.code,200);assert.equal(res.body.saved,true);assert.equal(writes,1);});
test('malformed input gives a validation response without persisting',async()=>{let writes=0;const client={auth:{getUser:async()=>({data:{user:{id:'user'}}})},rpc:async()=>{writes++;return{data:claim};}};const res=response();await api(client)('claims')({method:'POST',headers:{authorization:'Bearer valid'},body:{...valid,accepted:false}},res);assert.equal(res.code,400);assert.equal(writes,0);});
test('inline creation validates public address and keeps contact fields private',async()=>{const draft={...owner.newRestaurantDraft('New restaurant'),street:'101 Main Street',city:'Boston',region:'MA',postcode:'02110',country:'US',name:'Owner Name',role:'Owner',email:'owner@example.com',phone:'6175550100',accepted:true};assert.throws(()=>owner.validateNewRestaurant({...draft,street:''}));assert.throws(()=>owner.validateNewRestaurant({...draft,kind:'Hotel'}));assert.throws(()=>owner.validateNewRestaurant({...draft,country:'USA'}));let args;const result=await owner.createRestaurantAndClaim({rpc:async(_,body)=>{args=body;return{data:{outcome:'created',placeId:id,claim}}}},draft,true);assert.equal(result.placeId,id);assert.equal(args.p_details.name,'New restaurant');assert.equal(args.p_details.phone,undefined);assert.equal(args.p_details.email,undefined);assert.equal(args.p_claim.email,'owner@example.com');assert.equal(args.p_request_id,draft.requestId);});
test('inline duplicate choice is returned without claiming creation; error/verified response is not pending success',async()=>{const draft={...owner.newRestaurantDraft('New restaurant'),street:'101 Main Street',city:'Boston',region:'MA',postcode:'02110',country:'US',name:'Owner Name',role:'Owner',email:'owner@example.com',phone:'6175550100',accepted:true};const result=await owner.createRestaurantAndClaim({rpc:async()=>({data:{outcome:'choose_existing',places:[{id,name:'New restaurant',exactAddress:true}]}})},draft,true);assert.equal(result.duplicates[0].id,id);assert.equal(result.placeId,undefined);await assert.rejects(()=>owner.createRestaurantAndClaim({rpc:async()=>({error:{code:'NETWORK'}})},draft,true));await assert.rejects(()=>owner.createRestaurantAndClaim({rpc:async()=>({data:{outcome:'created',placeId:id,claim:verified}})},draft,true));});
