const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const ts=require('typescript');
const source=fs.readFileSync('lib/signalCatalog.ts','utf8');const mod={exports:{}};new Function('exports',ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(mod.exports);
const {getSignalPrefixesForCategory:prefixes,signalMatchesCategory:matches,loadActiveSignalCatalog:load,loadPlaceSignalCategory:place}=mod.exports;
const catalog=JSON.parse(fs.readFileSync('docs/schema-audit/review-schema.json')).catalog;
function client(results){const calls=[];const q=new Proxy({},{get(_,k){if(k==='then')return r=>r(results.shift());return(...args)=>{calls.push([k,...args]);return q;};}});return{calls,from:n=>{calls.push(['from',n]);return q;}};}
test('web/native identical mapping',()=>assert.equal(source,fs.readFileSync('../tavvy-mobile/lib/signalCatalog.ts','utf8')));
test('category aliases and subcategory override cover real requested entities',()=>{for(const [category,prefix] of [[' RESTAURANTS ','restaurant_'],['hotel','hotel_'],['Public Bathroom','restroom_'],['Airport Bathroom','restroom_'],['park','outdoor_'],['airport','airport_'],['Service Provider','service_']])assert.ok(prefixes(category).includes(prefix),category);assert.deepEqual(prefixes('airport','Public Restroom'),['restroom_','generic_']);assert.ok(prefixes('Restaurant','SUSHI RESTAURANT').includes('sushi_'));});
test('every entity gets real active tap signals, never professional endorsements',()=>{for(const category of ['restaurant','hotel','public bathroom','park','airport','business','service provider','professional','unknown future category']){const selected=catalog.filter(r=>matches(r,category));assert.ok(selected.length>0,category);assert.ok(selected.some(r=>r.signal_type==='best_for'));assert.ok(selected.some(r=>r.signal_type==='heads_up'));assert.ok(selected.every(r=>r.signal_type!=='pro_endorsement'));}});
test('bathrooms include all 11 real restroom signals without restaurant/staff/pet/outdoor seating noise',()=>{const selected=catalog.filter(r=>matches(r,'airport','bathroom'));assert.equal(selected.filter(r=>r.slug.startsWith('restroom_')).length,11);for(const slug of ['generic_friendly_staff','generic_romantic','outdoor_seating','pet_friendly'])assert.ok(!selected.some(r=>r.slug===slug));});
test('catalog pagination does not truncate after 1,000, and propagates failures',async()=>{const db=client([{data:Array(500).fill({})},{data:Array(500).fill({})},{data:[{}]}]);assert.equal((await load(db)).length,1001);assert.deepEqual(db.calls.filter(c=>c[0]==='range'),[['range',0,499],['range',500,999],['range',1000,1499]]);await assert.rejects(load(client([{error:Error('offline')}])),/offline/);});
test('canonical/source identifiers query actual columns without mutations or retired tables',async()=>{const db=client([{data:{tavvy_category:'airport',tavvy_subcategory:'restroom'}}]);assert.deepEqual(await place(db,'11111111-1111-4111-8111-111111111111'),{primary:'airport',subcategory:'restroom'});assert.ok(db.calls.some(c=>c[0]==='eq'&&c[1]==='id'));const raw=client([{data:null},{data:{fsq_category_labels:['Dining and Drinking > Restaurant > Sushi Restaurant']}}]);assert.equal((await place(raw,'fsq-id')).primary,'Sushi Restaurant');assert.deepEqual(raw.calls.filter(c=>c[0]==='from'),[['from','places'],['from','fsq_places_raw']]);await assert.rejects(place(client([{error:Error('denied')}]),'id'),/denied/);});
test('promoted FSQ UUID retains raw category specialization',async()=>{const db=client([{data:{tavvy_category:null,tavvy_subcategory:null,source_type:'fsq',source_id:'raw-restaurant'}},{data:{fsq_category_labels:['Dining > Restaurant > Sushi Restaurant']}}]);assert.equal((await place(db,'11111111-1111-4111-8111-111111111111')).primary,'Sushi Restaurant');assert.ok(db.calls.some(c=>c[0]==='eq'&&c[1]==='fsq_place_id'&&c[2]==='raw-restaurant'));});
