import React,{useMemo,useState} from 'react';
import Head from 'next/head';
import dynamic from 'next/dynamic';
import {useRouter} from 'next/router';
import {serverSideTranslations} from 'next-i18next/serverSideTranslations';
import ToolHeader from '../../components/ToolHeader';
import {useThemeContext} from '../../contexts/ThemeContext';
import PlaceReviewGrid from '../../components/PlaceReviewGrid';
import {useBusinessReviewSummaries} from '../../lib/useBusinessReviewSummaries';
import OnTheGoOwner from '../../components/OnTheGoOwner';
import AppLayout from '../../components/AppLayout';
import {BUSINESS_FILTERS,MobileBusiness,businessDirections,businessPoint,businessTime,distanceKm,safeBusinessUrl,selectBusinesses} from '../../lib/onthego';
import {useOnTheGoDiscovery} from '../../lib/useOnTheGoDiscovery';
const BusinessMap=dynamic(()=>import('../../components/OnTheGoMap'),{ssr:false,loading:()=> <p>Loading map…</p>});
export default function OnTheGoScreen(){
 const router=useRouter();const {isDark}=useThemeContext();
 const discovery=useOnTheGoDiscovery(`${process.env.NEXT_PUBLIC_SUPABASE_URL||'https://scasgwrikoqdwlwlwcff.supabase.co'}/functions/v1/live-onthego-map-data?include_scheduled=true`);
 const [location,setLocation]=useState<[number,number]|null>(null),[locationNote,setLocationNote]=useState(''),[locating,setLocating]=useState(false),[nearby,setNearby]=useState(false);
 const [filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[layer,setLayer]=useState('standard'),[view,setView]=useState<'list'|'map'>('list');
 const locate=()=>{if(locating)return;if(!navigator.geolocation){setLocationNote('Location is unavailable. Search a city or business below.');return;}setLocating(true);navigator.geolocation.getCurrentPosition(p=>{setLocation([p.coords.latitude,p.coords.longitude]);setNearby(true);setLocationNote('Showing businesses within 50 km of your location.');setLocating(false);},()=>{setLocationNote('Location could not be accessed. Search a city or business, or try My location again.');setLocating(false);},{timeout:12000,maximumAge:60000});};
 const visible=useMemo(()=>selectBusinesses(discovery.businesses,filter,query,location,nearby),[discovery.businesses,filter,query,location,nearby]);
 const scope=JSON.stringify([filter,query,nearby,location]);
 const [page,setPage]=useState({scope:'',count:20});const shown=page.scope===scope?page.count:20;
 const displayed=visible.slice(0,shown),reviewSummary=useBusinessReviewSummaries(displayed);
 const openBusiness=(b:MobileBusiness)=>router.push(`/app/onthego/${encodeURIComponent(b.tavvy_place_id)}`,undefined,{locale:router.locale});
 return <AppLayout><Head><title>On The Go | Tavvy</title><meta name="description" content="Find mobile businesses, their live locations and upcoming stops."/></Head><ToolHeader title="On The Go" subtitle="Find food trucks, mobile services and their next stops."/><main className="onthego">
  <label className="search"><span>Search business, service or city</span><input type="search" placeholder="Coffee, car wash, Boston…" value={query} onChange={e=>{setQuery(e.target.value);if(e.target.value.trim()){setNearby(false);setLocationNote('Showing all locations matching your search. Choose Within 50 km to narrow it to your location.');}}}/></label>
  <div className="scope"><button onClick={locate} disabled={locating}>{locating?'Finding your location…':'My location'}</button><button aria-pressed={!nearby} onClick={()=>{setNearby(false);setLocationNote('Showing all locations matching your search.');}}>All locations</button>{location&&<button aria-pressed={nearby} onClick={()=>{setNearby(true);setLocationNote('Showing businesses within 50 km of your location.');}}>Within 50 km</button>}</div>
  <p className="scope-note" role="status">{locationNote||'Search uses the published service area and stop address. All locations are shown until you choose nearby.'}</p>
  <nav aria-label="Business categories">{BUSINESS_FILTERS.map(([id,name])=><button key={id} aria-pressed={id===filter} onClick={()=>setFilter(id)}>{name}</button>)}</nav>
  <div className="results-heading"><h2>{discovery.loading?'Finding mobile businesses…':`${visible.filter(b=>b.is_live).length} live · ${visible.filter(b=>!b.is_live).length} scheduled`}</h2><div className="view-switch" aria-label="Results view"><button aria-pressed={view==='list'} onClick={()=>setView('list')}>List</button><button aria-pressed={view==='map'} onClick={()=>setView('map')}>Map</button></div></div>
  {discovery.error&&<p role="alert" className="warning">{discovery.updatedAt?'Showing the last available update. ':''}{discovery.error} <button onClick={discovery.refresh} disabled={discovery.refreshing}>Retry</button></p>}
  {view==='map'&&<><div className="map-options"><span>Red: live · Purple: planned stop</span><select aria-label="Map layer" value={layer} onChange={e=>setLayer(e.target.value)}><option value="standard">Standard</option><option value="dark">Dark</option><option value="satellite">Satellite</option></select></div><div className="map"><BusinessMap businesses={visible} location={nearby?location:null} layer={layer} onSelect={openBusiness}/></div></>}
  <section aria-label="Mobile businesses" aria-live="polite">
   {discovery.loading?<p>Loading mobile businesses…</p>:!visible.length&&!discovery.error?<div className="empty"><h3>No matching mobile businesses right now</h3><p>Try a different city or service. Businesses appear when they share a live location or upcoming stop.</p><button onClick={()=>{setFilter('all');setQuery('');setNearby(false);}}>Clear filters</button></div>:displayed.map(b=>{const directions=businessDirections(b),phone=safeBusinessUrl(b.phone,'phone'),point=businessPoint(b);return <article key={b.tavvy_place_id}>
    <button className="business-main" onClick={()=>openBusiness(b)}>{b.cover_image_url?<img src={b.cover_image_url} alt=""/>:<span className="placeholder" aria-hidden="true">⌖</span>}<span><strong>{b.place_name}</strong><span className="category">{b.subcategory||b.category||'Mobile business'}</span><span className={b.is_live?'status live':'status'}>{b.is_live?'Live now':'Scheduled stop'}</span></span><span aria-hidden="true">›</span></button>
    <div className="business-body"><PlaceReviewGrid summary={reviewSummary(b)}/><p>{b.is_live?b.session_address||b.location_label||'Public address unavailable':b.next_event?.location_name}</p><p>{b.is_live?`Until ${businessTime(b.scheduled_end_at,router.locale)}`:businessTime(b.next_event?.scheduled_start,router.locale)}</p>{!b.is_live&&b.next_event?.location_address&&<p>{b.next_event.location_address}</p>}{b.today_note&&<p>{b.today_note}</p>}{b.service_area&&<p>Service area: {b.service_area}</p>}{location&&point&&<p>{distanceKm(location,point).toLocaleString(router.locale,{maximumFractionDigits:1})} km away · straight line</p>}
     <div className="actions"><button onClick={()=>openBusiness(b)}>View place & schedule</button>{directions&&<a href={directions} target="_blank" rel="noopener noreferrer">Directions ↗</a>}{phone&&<a href={phone}>Call</a>}</div></div>
   </article>})}
  </section>{visible.length>shown&&<button onClick={()=>setPage({scope,count:shown+20})}>Show more businesses ({visible.length-shown} remaining)</button>}<OnTheGoOwner/>
 </main><style jsx>{`
 .onthego{max-width:900px;margin:auto;min-height:100vh;padding:0 16px 110px;color:var(--text,#17013a);background:var(--background,#fff)}header{display:flex;gap:16px;align-items:center}h1{font-size:25px;margin:6px 0}h2{font-size:17px}p{color:var(--text-secondary,#625e70);line-height:1.5;font-size:14px}button,input,select{font:inherit;color:inherit;background:var(--surface,#fff);border:1px solid var(--border,#cfcad7);border-radius:12px;padding:11px 13px;min-height:44px}button{cursor:pointer}button:disabled{opacity:.6;cursor:wait}button[aria-pressed=true]{background:#70059b;color:#fff;border-color:#70059b}input{width:100%;box-sizing:border-box;margin-top:7px}.search{font-size:14px;font-weight:600;display:block;margin:20px 0 12px}.scope{display:flex;gap:8px;flex-wrap:wrap}.scope-note{font-size:12px}nav{display:flex;gap:8px;overflow-x:auto;padding:10px 0}nav button{white-space:nowrap}.results-heading,.map-options{display:flex;align-items:center;justify-content:space-between;gap:10px}.view-switch{display:flex;gap:6px}.map-options{font-size:12px;margin:12px 0}.map{height:48vh;min-height:290px;border-radius:18px;overflow:hidden;position:relative;z-index:0}article{border:1px solid var(--border,#dedbe4);border-radius:18px;overflow:hidden;margin:14px 0;background:var(--surface,#fff)}.business-main{width:100%;display:flex;gap:13px;align-items:center;text-align:left;border:0;border-radius:0}.business-main>span:nth-child(2){flex:1}.business-main strong{font-size:18px}.business-main img,.placeholder{height:66px;width:66px;border-radius:12px;object-fit:cover}.placeholder{display:grid;place-items:center;background:#8a05be15;color:#8a05be;font-size:32px}.category{display:block;font-size:13px;color:var(--text-secondary,#625e70);margin:5px 0}.status{display:inline-block;font-size:12px;border-radius:8px;background:#8a05be15;color:var(--link,#70059b);padding:5px 8px}.status.live{background:#dc26261a;color:${isDark?'#ff9c9c':'#bc2525'}}.business-body{padding:0 16px 16px}.business-body p{margin:7px 0}.actions{display:flex;align-items:center;gap:16px;flex-wrap:wrap;margin-top:12px}a{color:var(--link,#70059b);font-weight:600;font-size:14px;min-height:44px;display:flex;align-items:center}.warning{border:1px solid #b78038;padding:12px;border-radius:12px}.empty{padding:24px 0}button:focus-visible,input:focus-visible,select:focus-visible,a:focus-visible{outline:3px solid #b687dc;outline-offset:2px}
 `}</style></AppLayout>;
}
export async function getStaticProps({locale}:{locale:string}){return {props:{...(await serverSideTranslations(locale,['common']))}};}
