import React, {useEffect, useRef, useState} from 'react';
import Head from 'next/head';
import {IoBoatOutline, IoChevronDown} from 'react-icons/io5';
import Link from 'next/link';
import {useRouter} from 'next/router';
import {serverSideTranslations} from 'next-i18next/serverSideTranslations';
import AppLayout from '../../../components/AppLayout';
import ToolHeader from '../../../components/ToolHeader';
import {useThemeContext} from '../../../contexts/ThemeContext';
import {searchCruiseShips, getCruiseOperators, getFeaturedCruiseShips, CruiseOperator} from '../../../lib/cruises/service';
import {CruiseShipDetail, safeCruiseUrl} from '../../../lib/cruises/catalog';
import {CruiseDirectoryFilters, EMPTY_CRUISE_FILTERS, readCruiseDirectoryQuery, cruiseDirectoryQuery} from '../../../lib/cruises/directoryState';

export default function CruiseDirectory() {
 const router=useRouter(),{isDark}=useThemeContext();
 const [filters,setFilters]=useState<CruiseDirectoryFilters>(EMPTY_CRUISE_FILTERS),[ready,setReady]=useState(false);
 const [rows,setRows]=useState<CruiseShipDetail[]>([]),[featured,setFeatured]=useState<CruiseShipDetail[]>([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[featuredError,setFeaturedError]=useState('');
 const [more,setMore]=useState(false),[offset,setOffset]=useState(0),[retry,setRetry]=useState(0);
 const [operators,setOperators]=useState<CruiseOperator[]>([]),[operatorError,setOperatorError]=useState(''),[operatorLoading,setOperatorLoading]=useState(true);
 const [companyOpen,setCompanyOpen]=useState(false),[companyQuery,setCompanyQuery]=useState('');
 const companyButton=useRef<HTMLButtonElement>(null);
 const {query,kind,status,operatorId}=filters;
 useEffect(()=>{if(!router.isReady)return;setFilters(readCruiseDirectoryQuery(router.query));setOffset(0);setRows([]);setFeatured([]);setReady(true)},[router.isReady,router.query.q,router.query.kind,router.query.status,router.query.company]);
 useEffect(()=>{let active=true;setOperatorLoading(true);setOperatorError('');getCruiseOperators().then(value=>{if(active)setOperators(value)}).catch(e=>{if(active)setOperatorError(e.message)}).finally(()=>{if(active)setOperatorLoading(false)});return()=>{active=false}},[retry]);
 useEffect(()=>{if(!ready)return;let active=true;setLoading(true);setError('');const timer=setTimeout(()=>void searchCruiseShips({query,kind:kind||undefined,status,operatorId,offset}).then(result=>{if(active){setRows(old=>offset?[...old.slice(0,offset),...result.ships]:result.ships);setMore(result.hasMore)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)}),200);return()=>{active=false;clearTimeout(timer)}},[ready,query,kind,status,operatorId,offset,retry]);
 useEffect(()=>{if(!ready)return;let active=true;setFeatured([]);setFeaturedError('');getFeaturedCruiseShips({query,kind:kind||undefined,status,operatorId}).then(value=>{if(active)setFeatured(value)}).catch(e=>{if(active)setFeaturedError(e.message)});return()=>{active=false}},[ready,query,kind,status,operatorId,retry]);
 const change=(next:Partial<CruiseDirectoryFilters>)=>{const value={...filters,...next};if(value.query===query&&value.kind===kind&&value.status===status&&value.operatorId===operatorId)return;setFilters(value);setRows([]);setFeatured([]);setOffset(0);setMore(false);void router.replace({pathname:router.pathname,query:cruiseDirectoryQuery(value)},undefined,{shallow:true,scroll:false})};
 const chooseCompany=(id:string)=>{change({operatorId:id});setCompanyOpen(false);setCompanyQuery('');companyButton.current?.focus()};
 const selectedCompany=operators.find(item=>item.id===operatorId)?.name || (operatorId?'Selected cruise line':'All cruise lines');
 const renderShip=({ship}:CruiseShipDetail,compact=false)=><Link href={`/app/cruises/${ship.slug}`} locale={router.locale} key={ship.id} className={compact?'ship compact':'ship'}>{ship.photo?.permission_verified&&safeCruiseUrl(ship.photo.url)?<img src={ship.photo.url} alt={ship.photo.alt}/>:<div className="placeholder" aria-label="No verified ship photo"><IoBoatOutline size={compact?40:64}/></div>}<div><p>{ship.operator_name} · {ship.kind}</p><h2>{ship.name}</h2><span>{ship.operating_status==='announced'?'Announced · not operating':'Explore this ship'} →</span></div></Link>;
 return <><Head><title>Cruise ships | Tavvy</title></Head><AppLayout><main className={isDark?'directory dark':'directory'}><ToolHeader title="Cruises"/><p className="eyebrow">Cruise Universe</p><h1>Find your kind of ship.</h1><p>Explore verified ship details, onboard places and guest experiences.</p>
  <div className="filters"><label className="ship-search"><span>Search ships</span><input aria-label="Search ship or cruise line" placeholder="Ship or cruise line" value={query} onChange={e=>change({query:e.target.value})}/></label><label><span>Cruise type</span><select aria-label="Cruise type" value={kind} onChange={e=>change({kind:e.target.value as CruiseDirectoryFilters['kind']})}><option value="">All cruise types</option><option value="ocean">Ocean</option><option value="river">River</option><option value="expedition">Expedition</option></select></label></div>
  <div className="company"><span className="field-label">Cruise line</span><button ref={companyButton} aria-expanded={companyOpen} aria-controls="cruise-company-options" onClick={()=>setCompanyOpen(value=>!value)} className="company-toggle">{selectedCompany}<IoChevronDown aria-hidden="true"/></button>{companyOpen&&<div id="cruise-company-options" className="company-panel" onKeyDown={e=>{if(e.key==='Escape'){setCompanyOpen(false);companyButton.current?.focus()}}}><input autoFocus aria-label="Search cruise lines" placeholder="Find a cruise line" value={companyQuery} onChange={e=>setCompanyQuery(e.target.value)}/><div role="group" aria-label="Cruise lines" className="company-options"><button aria-pressed={!operatorId} onClick={()=>chooseCompany('')}>All cruise lines</button>{operators.filter(item=>item.name.toLocaleLowerCase().includes(companyQuery.trim().toLocaleLowerCase())).map(item=><button key={item.id} aria-pressed={operatorId===item.id} onClick={()=>chooseCompany(item.id)}>{item.name}</button>)}</div>{operatorLoading&&<p role="status">Loading cruise lines…</p>}{!operatorLoading&&!operatorError&&!operators.some(item=>item.name.toLocaleLowerCase().includes(companyQuery.trim().toLocaleLowerCase()))&&<p>No cruise lines match your search.</p>}</div>}{operatorError&&<p role="alert">Cruise lines are temporarily unavailable. <button onClick={()=>setRetry(v=>v+1)}>Try again</button></p>}</div>
  <div className="status">{(['operating','announced'] as const).map(value=><button key={value} aria-pressed={status===value} onClick={()=>{if(value!==status)change({status:value})}}>{value==='operating'?'Operating ships':'Announced ships'}</button>)}</div><p className="note">The catalog is growing as ships and sources are verified. Announced ships are listed separately.</p>
  {!query.trim()&&featured.length>0&&<section aria-label="Featured ships"><h2>Featured ships</h2><p className="note">A few starting points selected by Tavvy.</p><div className="featured">{featured.map(item=>renderShip(item,true))}</div></section>}{featuredError&&!query.trim()&&<p role="status">Featured ships are temporarily unavailable. <button onClick={()=>setRetry(v=>v+1)}>Try again</button></p>}
  <h2>All matching ships</h2>{error?<div role="alert"><p>{error}</p><button onClick={()=>setRetry(v=>v+1)}>Try again</button></div>:<div className="ships">{rows.map(item=>renderShip(item))}</div>}{loading&&<p role="status">Loading ships…</p>}{!loading&&!error&&!rows.length&&<p>No verified ships match these filters. Try another cruise line or ship type.</p>}{more&&!loading&&!error&&<button onClick={()=>setOffset(rows.length)}>Load more ships</button>}
 </main></AppLayout><style jsx>{`.directory{--bg:#fbf9fd;--panel:#fff;--text:#241d30;--muted:#65596f;--line:#ded5e7;--accent:#7e16a7;background:var(--bg);color:var(--text);max-width:1040px;min-height:100vh;margin:auto;padding:24px 20px 110px}.dark{--bg:#15111c;--panel:#211a2b;--text:#f7f3fa;--muted:#c1b3cd;--line:#4a3b57;--accent:#d9a2f4}h1{font-size:clamp(32px,5vw,48px)}.eyebrow{margin-top:30px;text-transform:uppercase;letter-spacing:.12em;font-size:12px}p,.note{color:var(--muted);line-height:1.6}.filters,.status{display:flex;gap:10px;margin:20px 0;flex-wrap:wrap}.filters label{display:flex;flex-direction:column;gap:8px}.ship-search{flex:1;min-width:200px}input,select,button{font:inherit;min-height:44px;padding:12px;border:1px solid var(--line);border-radius:12px;color:var(--text);background:var(--panel)}button{cursor:pointer}button[aria-pressed=true]{border-color:var(--accent);color:var(--accent);font-weight:700}.company{max-width:560px}.field-label{display:block;margin-bottom:8px}.company-toggle{display:flex;align-items:center;justify-content:space-between;gap:16px;width:100%}.company-panel{border:1px solid var(--line);border-radius:12px;padding:12px;margin-top:8px;background:var(--panel)}.company-panel input{width:100%;box-sizing:border-box}.company-options{max-height:240px;overflow:auto;display:grid;gap:6px;margin-top:10px}.company-options button{text-align:left}.ships{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;margin:24px 0}.featured{display:flex;gap:14px;overflow-x:auto;padding:4px 2px 18px;scroll-snap-type:x proximity}.directory :global(.ship){display:block;text-decoration:none;border:1px solid var(--line);border-radius:18px;overflow:hidden;color:var(--text);background:var(--panel)}.directory :global(.compact){flex:0 0 240px;scroll-snap-align:start}.directory :global(.ship img){width:100%;aspect-ratio:16/9;object-fit:cover}.directory :global(.ship .placeholder){width:100%;height:130px;display:grid;place-items:center;background:var(--bg)}.directory :global(.compact .placeholder){height:88px}.directory :global(.ship>div:last-child){padding:18px}.directory :global(.ship p){font-size:13px;color:var(--muted);line-height:1.6}.directory :global(.ship h2){margin:8px 0 18px}.directory :global(.compact h2){font-size:20px}.note{font-size:13px}:focus-visible{outline:3px solid var(--accent);outline-offset:3px}@media(max-width:600px){.ships{grid-template-columns:1fr}.ship-search{flex-basis:100%}}`}</style></>;
}
export const getServerSideProps=async({locale}:{locale:string})=>({props:{...(await serverSideTranslations(locale||'en',['common']))}});
