import {useEffect,useState} from 'react';
import {fetchMobileDetails,MOBILE_PROFILE_FIELDS,saveMobileBusinessProfile} from '../lib/onthegoDetails';
import {safeBusinessUrl} from '../lib/onthego';
export default function OnTheGoProfileEditor({placeId}:{placeId:string}){
 const [open,setOpen]=useState(false);return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary>Edit business information</summary>{open&&<Fields key={placeId} placeId={placeId}/>}</details>;
}
function Fields({placeId}:{placeId:string}){
 const [draft,setDraft]=useState<Record<string,string>|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let active=true;setDraft(null);setMessage('');fetchMobileDetails({tavvyPlaceId:placeId}).then(data=>{if(!active)return;if(!data)throw Error('Business not found.');setDraft(Object.fromEntries(MOBILE_PROFILE_FIELDS.map(([key])=>[key,String(data.place[key]||'')])));}).catch(()=>active&&setMessage('Unable to load your business information.'));return()=>{active=false;};},[placeId,attempt]);
 const save=async()=>{if(!draft||busy)return;setBusy(true);setMessage('');try{const values={...draft};for(const key of ['website','instagram','facebook','twitter','tiktok']){if(values[key]?.trim()){const url=safeBusinessUrl(values[key]);if(!url)throw Error('Enter a valid website or social URL.');values[key]=url;}}await saveMobileBusinessProfile(placeId,values);setDraft(values);setMessage('Business information saved.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to save. Your changes are still here.');}finally{setBusy(false);}};
 return <section>{draft?<><p>Your current stop is managed separately below. Usual hours do not mark you as live.</p>{MOBILE_PROFILE_FIELDS.map(([key,label])=><label key={key}>{label}{key==='description'||key==='hours_display'?<textarea disabled={busy} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} rows={3}/>:<input disabled={busy} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} type={key==='email'?'email':key==='phone'?'tel':'text'}/>}</label>)}<button type="button" disabled={busy} onClick={save}>{busy?'Saving…':'Save business information'}</button></>:message?<button onClick={()=>setAttempt(n=>n+1)}>Retry loading information</button>:<p>Loading business information…</p>}<p role="status">{message}</p><style jsx>{`label{display:block;margin:12px 0}input,textarea{display:block;box-sizing:border-box;width:100%;margin-top:6px;padding:12px;background:var(--background,#fff);color:var(--text,#17013a);border:1px solid var(--border,#ccc);border-radius:10px;font:inherit}button{padding:12px;min-height:44px;border-radius:10px;background:#70059b;color:#fff;border:0}p{font-size:14px;line-height:1.5}`}</style></section>;
}
