import OnTheGoSchedule from './OnTheGoSchedule';
import OnTheGoProfileEditor from './OnTheGoProfileEditor';
import { useState } from 'react';
import {useRouter} from 'next/router';
import { OWNER_CATEGORIES, useOnTheGoOwner } from '../lib/useOnTheGoOwner';
export default function OnTheGoOwner() {
  const owner = useOnTheGoOwner();
  const router=useRouter();
  const [name, setName] = useState(''), [area, setArea] = useState(''), [category, setCategory] = useState(OWNER_CATEGORIES[0]);
  const [point, setPoint] = useState<[number, number] | null>(null), [locationError, setLocationError] = useState('');
  const [hours, setHours] = useState('4'), [note, setNote] = useState(''), [consent, setConsent] = useState(false);
  const [eventName, setEventName] = useState(''), [eventAddress, setEventAddress] = useState(''), [start, setStart] = useState(''), [end, setEnd] = useState('');
  const locate = () => navigator.geolocation?.getCurrentPosition(p => { setPoint([p.coords.latitude, p.coords.longitude]); setLocationError(''); }, () => setLocationError('Location permission is needed to share this location.'), { timeout: 12000 });
  return <details><summary>Manage my mobile business</summary><p>Sign in to register and publish your business location. Your businesses and active sessions are restored when you return.</p>
    {!owner.signedIn&&<a href={`/app/login?redirect=${encodeURIComponent(router.asPath)}`}>Sign in to manage your business</a>}
    <button disabled={owner.busy} onClick={owner.recover}>Refresh my businesses</button><fieldset disabled={owner.busy}><label>My businesses<select value={owner.placeId} onChange={e => { owner.selectPlace(e.target.value); setPoint(null); setConsent(false); }}><option value="">Register another business</option>{owner.places.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
      {!owner.registered && <><label>Business name<input value={name} onChange={e => setName(e.target.value)} /></label><label>Category<select value={category} onChange={e => setCategory(e.target.value)}>{OWNER_CATEGORIES.map(c => <option key={c}>{c}</option>)}</select></label><label>Service area<input value={area} onChange={e => setArea(e.target.value)} /></label><button onClick={() => owner.register(name, category, area)}>Register business</button></>}
      {owner.placeId && <><OnTheGoProfileEditor placeId={owner.placeId}/>{/food|coffee|cafe|catering|ice.?cream/i.test(owner.places.find(p=>p.id===owner.placeId)?.tavvy_category||'')&&<><button onClick={async()=>{const id=await owner.enableDetails();if(id)void router.push(`/app/business/${id}`);}}>Tavvy Menu, photos, stories & eCard</button><p>Use your existing restaurant workspace. Ownership verification is required for its management tools.</p></>}<button onClick={async()=>{const id=await owner.enableDetails();if(id)void router.push(`/app/place/${id}?mobile=${owner.placeId}`);}}>Open full Tavvy place page</button><p>Enable one place page for reviews, photos and your available Tavvy features. This does not grant a verified badge.</p><button onClick={locate}>Use my current location</button>{point && <p>Selected location: {point.map(n => n.toFixed(5)).join(', ')}</p>}<p>{locationError}</p>
        <label><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} /> I agree to publish this business location. Live sessions end after the selected duration or when I end them.</label>
        {!owner.sessionId ? <><label>Duration (hours)<input type="number" min="1" max="8" value={hours} onChange={e => setHours(e.target.value)} /></label><label>Today's note<input value={note} onChange={e => setNote(e.target.value)} /></label><button disabled={!point || !consent} onClick={() => point && owner.start(...point, Number(hours), note)}>Start live session</button></> : <><button disabled={!point || !consent} onClick={() => point && owner.update(...point, note)}>Update live location</button><label>Today's note<input value={note} onChange={e => setNote(e.target.value)} /></label><label>Public address<input value={owner.address} onChange={e => owner.setAddress(e.target.value)} /></label><button onClick={owner.confirm}>Confirm public address</button><button onClick={owner.end}>End live session</button></>}
        <OnTheGoSchedule key={owner.placeId} placeId={owner.placeId} refreshVersion={owner.scheduleVersion}/><details><summary>Schedule this selected location</summary><label>Location name<input value={eventName} onChange={e => setEventName(e.target.value)} /></label><label>Address<input value={eventAddress} onChange={e => setEventAddress(e.target.value)} /></label><label>Start (local time)<input type="datetime-local" value={start} onChange={e => setStart(e.target.value)} /></label><label>End (local time)<input type="datetime-local" value={end} onChange={e => setEnd(e.target.value)} /></label><button disabled={!point || !consent} onClick={() => point && owner.schedule(eventName, eventAddress, ...point, start, end)}>Publish schedule</button></details>
      </>}
    </fieldset><p role="status">{owner.busy ? 'Saving…' : owner.message}</p>
    <style jsx>{`details { background:var(--surface,#f7f5fa);color:var(--text,#17013a); padding:14px; border-radius:12px; margin:14px 0; } summary { cursor:pointer; } fieldset { border:0; padding:0; } label { display:block; margin:10px 0; } input:not([type=checkbox]),select { display:block; width:100%; box-sizing:border-box; } input,select,button { background:var(--background,#fff); color:var(--text,#17013a); border:1px solid #666; border-radius:8px; padding:10px; margin:4px 0; } button { cursor:pointer; margin-right:8px; } button:disabled { opacity:.5; }`}</style>
  </details>;
}
