import React from 'react';
import Link from 'next/link';
import { useThemeContext } from '../contexts/ThemeContext';
import PlaceReviewGrid from './PlaceReviewGrid';
import { buildPlaceReviewSummary, PlaceReviewSummary, ReviewSummaryStatus } from '../lib/placeReviewSummary';
type Signal = { bucket?: string; label?: string; tap_total?: number; count?: number; category?: string };
interface PlaceCardProps { place: { id:string; name:string; city?:string; state_region?:string; address_line1?:string; address?:string; category?:string; signals?:Signal[]; topSignals?:Signal[]; photos?:string[]; photo_url?:string; cover_image_url?:string; evidenceStatus?:ReviewSummaryStatus; reviewSummary?:PlaceReviewSummary; tavvy_category?:string; subcategory?:string }; showReviewSummary?:boolean; onPress?:()=>void; showQuickActions?:boolean; compact?:boolean }
export default function PlaceCard({place,onPress,showReviewSummary=false}:PlaceCardProps) {
 const {theme,isDark}=useThemeContext();
 const area=[place.city,place.state_region].filter(Boolean).join(', ')||place.address_line1||place.address;
 const photo=place.photos?.[0]||place.photo_url||place.cover_image_url;
 const signals=(place.topSignals||place.signals||[]).filter(s=>(s.count??s.tap_total??0)>0).slice(0,3);
 const summary=place.reviewSummary && (!place.evidenceStatus || place.reviewSummary.status===place.evidenceStatus) ? place.reviewSummary : buildPlaceReviewSummary(null,{category:place.tavvy_category||place.category,subcategory:place.subcategory},place.evidenceStatus||'unavailable');
 const content=<><div className="thumb">{photo?<img src={photo} alt="" loading="lazy"/>:<span aria-hidden="true">⌖</span>}</div><div className="body"><h3>{place.name}</h3><p>{[place.category,area].filter(Boolean).join(' · ')}</p>{!showReviewSummary&&(place.evidenceStatus==='loading'?<p role="status">Checking guest reports…</p>:place.evidenceStatus==='unavailable'?<p>Guest reports unavailable</p>:null)}{!showReviewSummary&&signals.length>0&&<div className="signals">{signals.map((s,i)=><span key={i} data-category={s.category}>{s.label||s.bucket}<small> {s.count??s.tap_total}</small></span>)}</div>}</div>{showReviewSummary&&<div className="review-summary-slot"><PlaceReviewGrid summary={summary}/></div>}</>;
 return <>{onPress?<button type="button" className={`tavvy-place-card${showReviewSummary?' with-review-summary':''}`} onClick={onPress}>{content}</button>:<Link className={`tavvy-place-card${showReviewSummary?' with-review-summary':''}`} href={`/app/place/${encodeURIComponent(place.id)}`}>{content}</Link>}<style jsx global>{`
 .tavvy-place-card.with-review-summary{display:grid;grid-template-columns:84px minmax(0,1fr)}.tavvy-place-card .review-summary-slot{grid-column:1/-1}
 .tavvy-place-card{display:flex;width:100%;gap:14px;padding:14px;margin-bottom:12px;text-align:left;background:${theme.cardBackground};color:${theme.text};border:1px solid ${theme.border};border-radius:18px;text-decoration:none;align-items:center;cursor:pointer;font:inherit}.tavvy-place-card .thumb{width:84px;height:84px;flex-shrink:0;border-radius:12px;overflow:hidden;background:${theme.surface};display:grid;place-items:center;font-size:30px;color:${theme.textSecondary}}.tavvy-place-card .thumb img{width:100%;height:100%;object-fit:cover}.tavvy-place-card .body{min-width:0;flex:1}.tavvy-place-card h3{font-size:17px;line-height:1.3;margin:0 0 5px;overflow-wrap:anywhere}.tavvy-place-card p{font-size:13px;line-height:1.4;color:${theme.textSecondary};margin:0}.tavvy-place-card .signals{display:flex;flex-wrap:wrap;gap:5px;margin-top:8px}.tavvy-place-card .signals span{font-size:12px;line-height:1.3;padding:4px 7px;border:1px solid ${theme.border};border-radius:10px}.tavvy-place-card .signals span[data-category=good]{color:${isDark?'#56DFD9':'#066B68'}}.tavvy-place-card .signals span[data-category=vibe]{color:${isDark?'#D9B6FF':'#74209A'}}.tavvy-place-card .signals span[data-category=headsup]{color:${isDark?'#FFD38A':'#885000'}}.tavvy-place-card small{font-size:inherit;color:${theme.textSecondary}}.tavvy-place-card:focus-visible{outline:3px solid ${theme.primary};outline-offset:3px}
 `}</style></>;
}
