import {useOwnerRequestScope} from '../hooks/useOwnerRequestScope';
import {useEffect,useState} from 'react';
import dynamic from 'next/dynamic';
import {supabase} from '../lib/supabaseClient';
import {getRestaurantProfile,RestaurantProfile,saveRestaurantProfile} from '../lib/restaurantProfile';
const LocationMap=dynamic(()=>import('./RestaurantLocationMap'),{ssr:false});
export default function RestaurantProfileEditor({placeId,onSaved}:{placeId:string;onSaved:()=>void}){
 const scope=useOwnerRequestScope(placeId);
 const [profile,setProfile]=useState<RestaurantProfile|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[mapOpen,setMapOpen]=useState(false),[locating,setLocating]=useState(false);
 const load=async()=>{const valid=scope.capture();setError('');try{const next=await getRestaurantProfile(supabase,placeId);if(valid())setProfile(next);}catch(e){if(valid())setError((e as Error).message);}};
 useEffect(()=>{void load();},[placeId]);
 const change=(key:keyof RestaurantProfile,value:string)=>setProfile(p=>p?{...p,[key]:value,...(['street','city','region','postcode','country'].includes(key)?{latitude:null,longitude:null,confirmLocation:false}:{})}:p);
 const choosePin=(latitude:number,longitude:number)=>{setError('');setProfile(p=>p?{...p,latitude,longitude,confirmLocation:true}:p);};
 const locate=()=>{if(!navigator.geolocation){setError('Location is unavailable. Choose your restaurant on the map.');return;}const valid=scope.capture();setLocating(true);navigator.geolocation.getCurrentPosition(p=>{if(!valid())return;choosePin(p.coords.latitude,p.coords.longitude);setMapOpen(true);setLocating(false);},()=>{if(!valid())return;setError('Location access was unavailable. You can choose the location on the map.');setLocating(false);},{timeout:10000,enableHighAccuracy:true});};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!profile||busy)return;const valid=scope.capture();setBusy(true);setError('');setMessage('');try{await saveRestaurantProfile(supabase,placeId,profile);if(!valid())return;setMessage('Place information saved.');onSaved();}catch(e){if(valid())setError((e as Error).message);}finally{if(valid())setBusy(false);}};
 return <details className="panel" id="profile"><summary><strong>Name, address & map</strong></summary>{error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{!profile?<button type="button" onClick={load}>Load place information</button>:<form onSubmit={save}><label>Restaurant name<input required minLength={2} maxLength={120} autoComplete="organization" value={profile.name} onChange={e=>change('name',e.target.value)}/></label><label>Cuisine <span className="muted">(optional)</span><input maxLength={120} placeholder="Italian, seafood, contemporary…" value={profile.cuisine} onChange={e=>change('cuisine',e.target.value)}/></label><label>Street address<input maxLength={300} autoComplete="street-address" value={profile.street} onChange={e=>change('street',e.target.value)}/></label><div className="profile-row"><label>City<input maxLength={120} autoComplete="address-level2" value={profile.city} onChange={e=>change('city',e.target.value)}/></label><label>State / region<input maxLength={120} autoComplete="address-level1" value={profile.region} onChange={e=>change('region',e.target.value)}/></label></div><div className="profile-row"><label>Postal code<input maxLength={20} autoComplete="postal-code" value={profile.postcode} onChange={e=>change('postcode',e.target.value)}/></label><label>Country<input maxLength={120} autoComplete="country-name" value={profile.country} onChange={e=>change('country',e.target.value)}/></label></div><p className="muted">{profile.latitude===null?'Add a map pin so nearby guests can find you.':'Your restaurant has a map location.'}</p><div className="actions"><button type="button" onClick={()=>setMapOpen(!mapOpen)}>{mapOpen?'Hide map':'Choose on map'}</button><button type="button" onClick={locate} disabled={locating}>{locating?'Finding location…':"I’m here · Use this location"}</button></div>{mapOpen&&<><p>Tap the map or drag the pin to your restaurant’s entrance.</p><LocationMap latitude={profile.latitude} longitude={profile.longitude} onChange={choosePin}/></>}<button disabled={busy} style={{marginTop:20}}>{busy?'Saving…':'Save place information'}</button></form>}<style jsx>{`.profile-row{display:grid;grid-template-columns:1fr 1fr;gap:16px}.profile-row label{min-width:0}summary{cursor:pointer;min-height:44px;display:flex;align-items:center}summary::before{content:'›';margin-right:10px}details[open]>summary::before{content:'⌄'}@media(max-width:480px){.profile-row{grid-template-columns:1fr}}`}</style></details>;
}
