import Head from 'next/head';
import Link from 'next/link';
import { useThemeContext } from '../contexts/ThemeContext';
export default function RestaurantOwnerLayout({ title, children }: { title: string; children: React.ReactNode }) {
  const { theme } = useThemeContext();
  return <><Head><title>{title} · Tavvy</title><meta name="robots" content="noindex" /></Head><main className="owner" style={{ background: theme.background, color: theme.text }}><div className="wrap"><nav><Link href="/app/business">Tavvy for restaurants</Link><Link href="/app">Explore Tavvy</Link></nav>{children}</div></main><style jsx global>{`
  .owner{min-height:100vh;padding:24px 20px 80px}.owner .wrap{max-width:760px;margin:auto}.owner nav{display:flex;justify-content:space-between;gap:18px;margin-bottom:36px}.owner h1{font-size:30px;line-height:1.2}.owner h2{font-size:21px}.owner p{line-height:1.65}.owner a{color:inherit}.owner .panel{border:1px solid ${theme.border};border-radius:18px;padding:22px;margin:20px 0;background:${theme.surface}}.owner label{display:block;font-weight:650;margin:18px 0}.owner input:not([type=checkbox]):not([type=radio]),.owner textarea,.owner select{display:block;box-sizing:border-box;width:100%;padding:13px;margin-top:8px;border:1px solid ${theme.border};border-radius:10px;background:${theme.background};color:${theme.text};font:inherit}.owner textarea{min-height:110px}.owner .check{display:flex;align-items:flex-start;gap:10px;line-height:1.5}.owner .check input{margin-top:4px}.owner button,.owner .button{display:inline-block;border:0;border-radius:10px;padding:14px 18px;background:#215e50;color:white;font:inherit;font-weight:700;cursor:pointer;text-decoration:none}.owner button:disabled{opacity:.55;cursor:wait}.owner .actions{display:flex;flex-wrap:wrap;gap:12px;align-items:center}.owner .status{padding:14px;border-radius:10px;background:${theme.surface};border:1px solid ${theme.border}}.owner .error{color:${theme.text};border-left:4px solid #b42318;padding:12px}.owner .muted{color:${theme.textSecondary}}.owner .result{display:block;padding:16px 0;border-bottom:1px solid ${theme.border};text-decoration:none}.owner .result small{display:block;line-height:1.5;margin-top:6px}.owner .checklist{list-style:none;padding:0}.owner .checklist li{padding:18px 0;border-bottom:1px solid ${theme.border}}.owner .checklist strong{display:block;margin-bottom:7px}.owner .stats{display:flex;gap:24px;flex-wrap:wrap}.owner .stats strong{display:block;font-size:26px}.owner :focus-visible{outline:3px solid #8A05BE;outline-offset:3px}
  `}</style></>;
}
