import {useOwnerRequestScope} from '../hooks/useOwnerRequestScope';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/router';
import {useAuth} from '../contexts/AuthContext';
import {supabase} from '../lib/supabaseClient';
import {createRestaurantAndClaim,findRestaurantDuplicates,newRestaurantDraft,RESTAURANT_DRAFT_KEY,RESTAURANT_KINDS,RestaurantDraft,RestaurantDuplicate,submitRestaurantClaim,validateNewRestaurant} from '../lib/restaurantOwner';

const countries=[['US','United States'],['BR','Brazil'],['CA','Canada'],['MX','Mexico'],['GB','United Kingdom'],['PT','Portugal'],['ES','Spain'],['FR','France'],['IT','Italy'],['DE','Germany'],['AU','Australia']];
export default function RestaurantCreateForm({initialName,onCancel}:{initialName:string;onCancel:()=>void}){
 const router=useRouter(),{user}=useAuth();
 const [draft,setDraft]=useState<RestaurantDraft>(()=>newRestaurantDraft(initialName)),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[needsAccount,setNeedsAccount]=useState(false);
 const [duplicates,setDuplicates]=useState<RestaurantDuplicate[]|null>(null),[selection,setSelection]=useState('');
 const returnUrl=`/app/business?add=1&name=${encodeURIComponent(draft.restaurantName)}`;
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(RESTAURANT_DRAFT_KEY)||'null');if(saved?.draft&&Date.now()-saved.savedAt<86400000&&(!initialName||saved.draft.restaurantName.toLowerCase()===initialName.toLowerCase()))setDraft({...newRestaurantDraft(initialName),...saved.draft,accepted:false});}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem(RESTAURANT_DRAFT_KEY,JSON.stringify({draft,savedAt:Date.now()}))}catch{}},[draft,ready]);
 useEffect(()=>{if(user)setNeedsAccount(false);if(user?.email)setDraft(d=>d.email?d:{...d,email:user.email||''});},[user?.id]);
 const scope=useOwnerRequestScope(user?.id||'guest');
 useEffect(()=>{setBusy(false);setDuplicates(null);setSelection('');},[user?.id]);
 const field=(key:keyof RestaurantDraft,value:string|boolean)=>{setDraft(d=>({...d,[key]:value}));setDuplicates(null);setSelection('');setNeedsAccount(false);};
 const finish=async(placeId:string)=>{try{localStorage.removeItem(RESTAURANT_DRAFT_KEY)}catch{}await router.replace(`/app/business/${placeId}`)};
 const check=async(event:React.FormEvent)=>{event.preventDefault();const valid=scope.capture();setError('');try{validateNewRestaurant(draft);if(!user){setNeedsAccount(true);return;}setBusy(true);const matches=await findRestaurantDuplicates(supabase,draft);if(!valid())return;setDuplicates(matches);setSelection(matches.length?'':'new');}catch(e){if(valid())setError((e as Error).message)}finally{if(valid())setBusy(false)}};
 const save=async()=>{if(!user||!selection||busy)return;const valid=scope.capture();setBusy(true);setError('');try{if(selection!=='new'){await submitRestaurantClaim(supabase,{...draft,placeId:selection});if(!valid())return;await finish(selection);return;}const result=await createRestaurantAndClaim(supabase,draft,true);if(!valid())return;if('duplicates'in result){setDuplicates(result.duplicates);setSelection('');setError('We found a matching restaurant while saving. Choose it below or edit the address.');}else await finish(result.placeId);}catch(e){if(valid())setError((e as Error).message)}finally{if(valid())setBusy(false)}};
 if(!ready)return <p role="status">Opening your restaurant form…</p>;
 return <section className="panel"><button type="button" className="secondary" onClick={onCancel}>← Back to restaurant lookup</button><h2>Add your restaurant</h2><p>Enter the public listing details and your private ownership contact. We’ll check for an existing listing before adding anything.</p>{error&&<p className="error" role="alert">{error}</p>}
 <form onSubmit={check}>
 <h3>Restaurant details · public</h3><label htmlFor="new-restaurant-name">Restaurant name<input id="new-restaurant-name" value={draft.restaurantName} onChange={e=>field('restaurantName',e.target.value)} required maxLength={160} autoComplete="organization"/></label>
 <label htmlFor="new-restaurant-kind">Restaurant type<select id="new-restaurant-kind" value={draft.kind} onChange={e=>field('kind',e.target.value)}>{RESTAURANT_KINDS.map(k=><option key={k}>{k}</option>)}</select></label>
 <label htmlFor="new-street">Street address<input id="new-street" value={draft.street} onChange={e=>field('street',e.target.value)} required maxLength={200} autoComplete="street-address"/></label>
 <div className="restaurant-form-row"><label htmlFor="new-city">City<input id="new-city" value={draft.city} onChange={e=>field('city',e.target.value)} required maxLength={100} autoComplete="address-level2"/></label><label htmlFor="new-region">State / region<input id="new-region" value={draft.region} onChange={e=>field('region',e.target.value)} maxLength={100} autoComplete="address-level1" placeholder="e.g. FL"/></label></div>
 <div className="restaurant-form-row"><label htmlFor="new-postcode">Postal code<input id="new-postcode" value={draft.postcode} onChange={e=>field('postcode',e.target.value)} maxLength={20} autoComplete="postal-code"/></label><label htmlFor="new-country">Country<select id="new-country" value={countries.some(c=>c[0]===draft.country)?draft.country:'other'} onChange={e=>field('country',e.target.value==='other'?'':e.target.value)}>{countries.map(([code,name])=><option key={code} value={code}>{name}</option>)}<option value="other">Another country</option></select>{!countries.some(c=>c[0]===draft.country)&&<input aria-label="Country code" required maxLength={2} value={draft.country} onChange={e=>field('country',e.target.value.toUpperCase())} placeholder="2-letter country code"/>}</label></div>
 <h3>Ownership contact · private</h3><p className="muted">These details are for ownership verification. They will not appear on the public listing.</p>
 <label htmlFor="new-owner-name">Your full name<input id="new-owner-name" value={draft.name} onChange={e=>field('name',e.target.value)} required maxLength={120} autoComplete="name"/></label>
 <label htmlFor="new-owner-role">Your role<select id="new-owner-role" value={draft.role} onChange={e=>field('role',e.target.value)} required><option value="">Choose your role</option><option>Owner</option><option>Authorized manager</option></select></label>
 <label htmlFor="new-owner-email">Business email<input id="new-owner-email" value={draft.email} onChange={e=>field('email',e.target.value)} required type="email" maxLength={254} autoComplete="email"/></label>
 <label htmlFor="new-owner-phone">Contact phone<input id="new-owner-phone" value={draft.phone} onChange={e=>field('phone',e.target.value)} required type="tel" maxLength={32} autoComplete="tel"/></label>
 <label className="check"><input type="checkbox" checked={draft.accepted} required onChange={e=>field('accepted',e.target.checked)}/>I am authorized to represent this restaurant and these details are accurate.</label>
 {!needsAccount&&duplicates===null&&<button disabled={busy}>{busy?'Checking for an existing listing…':user?'Check restaurant details':'Continue'}</button>}
 </form>
 {needsAccount&&!user&&<div role="status"><h3>Save this restaurant to your account</h3><p>Your form is saved. Sign in or create an account, then continue here.</p><div className="actions"><Link className="button" href={`/app/signup?returnUrl=${encodeURIComponent(returnUrl)}&context=restaurant`}>Create a restaurant account</Link><Link href={`/app/login?returnUrl=${encodeURIComponent(returnUrl)}`}>Sign in</Link></div></div>}
 {duplicates!==null&&<section aria-labelledby="duplicate-title"><h3 id="duplicate-title">{duplicates.length?'Is this your restaurant?':'Ready to add your restaurant'}</h3>{duplicates.length>0?<><p>Choose an existing listing to keep its reviews and photos together.</p>{duplicates.map(p=><label className="check result" key={p.id}><input type="radio" name="restaurant-match" value={p.id} checked={selection===p.id} onChange={()=>setSelection(p.id)}/><span><strong>{p.name}</strong><small>{[p.street,p.city,p.region].filter(Boolean).join(', ')}</small></span></label>)}{!duplicates.some(p=>p.exactAddress)&&<label className="check"><input type="radio" name="restaurant-match" checked={selection==='new'} onChange={()=>setSelection('new')}/>My restaurant is a different location. Add a new listing.</label>}</>:<p><strong>{draft.restaurantName}</strong><br/>{[draft.street,draft.city,draft.region,draft.postcode,draft.country].filter(Boolean).join(', ')}</p>}<p>Ownership will be pending verification. Editing access is available after ownership is verified.</p><button disabled={busy||!selection} onClick={save}>{busy?'Saving restaurant…':selection==='new'?'Add restaurant & request ownership':'Request ownership of this listing'}</button></section>}
 <style jsx>{`.restaurant-form-row{display:grid;grid-template-columns:1fr 1fr;gap:14px}.restaurant-form-row label{min-width:0}@media(max-width:420px){.restaurant-form-row{grid-template-columns:1fr}}`}</style>
 </section>;
}
