const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),puppeteer=require('puppeteer');
const base=process.env.TAVVY_DELETION_BASE||'http://127.0.0.1:3847',out=process.env.TAVVY_DELETION_OUTPUT||'/private/tmp/tavvy-account-deletion-ux-20260921/results/browser';fs.mkdirSync(out,{recursive:true});
const storage='sb-scasgwrikoqdwlwlwcff-auth-token',A={id:'00000000-0000-4000-8000-000000000001',email:'qa-a@example.invalid',aud:'authenticated'},B={id:'00000000-0000-4000-8000-000000000002',email:'qa-b@example.invalid',aud:'authenticated'};
const session=user=>({access_token:user.id===A.id?'fixture.a.token':'fixture.b.token',refresh_token:'fixture-refresh',expires_at:Math.floor(Date.now()/1000)+3600,expires_in:3600,token_type:'bearer',user});
(async()=>{const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage(),errors=[],effects=[],checks=[];let actor=null;
await page.setBypassServiceWorker(true);await page.setViewport({width:390,height:844});page.on('pageerror',e=>errors.push(e.message));await page.setRequestInterception(true);
page.on('request',r=>{const u=new URL(r.url());if(u.origin===new URL(base).origin)return r.continue();if(u.hostname!=='fixture.supabase.co')return r.abort();const respond=(x,status=200)=>r.respond({status,contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS'},body:JSON.stringify(x)});if(r.method()==='OPTIONS')return respond({});if(u.pathname.includes('/functions/')||u.pathname.includes('/auth/v1/logout')||(!['GET','HEAD'].includes(r.method())&&!u.pathname.includes('/rest/v1/rpc/get_'))){effects.push({path:u.pathname,method:r.method()});return respond({error:'Unexpected write'},403)}if(u.pathname==='/auth/v1/user')return respond(actor||{},actor?200:401);if(u.pathname.includes('/profiles'))return respond({user_id:actor?.id,display_name:'QA account',is_pro:false});return respond([]);});
const visit=async p=>{const response=await page.goto(base+p,{waitUntil:'networkidle2'});assert.equal(response.status(),200);return response};
const ready=()=>page.waitForSelector('[data-deletion-status="unavailable"]');
try{
 await visit('/app/settings/delete-account');await ready();assert.match(await page.$eval('main.delete-account',e=>e.innerText),/cannot be started/);assert.equal(await page.$eval('meta[name="robots"]',e=>e.content),'noindex,nofollow');assert.equal(new URL(await page.$eval('main a[href*="login"]',e=>e.href)).searchParams.get('returnUrl'),'/app/settings/delete-account');checks.push('guest route is reachable, honest, noindex and preserves sign-in return path');
 actor=A;await page.evaluate((key,value)=>localStorage.setItem(key,JSON.stringify(value)),storage,session(A));await visit('/app/settings');await page.waitForSelector('a[href="/app/settings/delete-account"]');await Promise.all([page.waitForNavigation({waitUntil:'networkidle2'}),page.click('a[href="/app/settings/delete-account"]')]);await ready();assert.equal(await page.$('main.delete-account form'),null);assert.equal(await page.$('main.delete-account input'),null);assert.equal(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).user.id,storage),A.id);checks.push('signed-in Settings entry opens status, without fake confirmation, queue or sign-out');
 for(const [locale,width,mode,expected] of [['en',390,'light','cannot be started'],['pt',320,'dark','Não é possível'],['es',1365,'light','No se puede']]){
  await page.setViewport({width,height:844});await page.evaluate((m,l)=>{localStorage.setItem('@tavvy_theme_mode',m);localStorage.setItem('tavvy-locale',l)},mode,locale);await visit((locale==='en'?'':'/'+locale)+'/app/settings/delete-account');await ready();assert.ok((await page.$eval('main.delete-account',e=>e.innerText)).includes(expected));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,`${locale}-${width}-${mode}.png`),fullPage:true});
 }checks.push('EN/PT/ES status renders without overflow at390/320/1365px in light/dark');
 actor=B;await page.evaluate((key,s)=>{localStorage.setItem(key,JSON.stringify(s));const c=new BroadcastChannel(key);c.postMessage({event:'SIGNED_IN',session:s});setTimeout(()=>c.close(),100)},storage,session(B));await ready();assert.equal(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).user.id,storage),B.id);assert.equal(await page.$('main.delete-account form'),null);checks.push('account switch retains B session and cannot reveal a success or destructive form');
 await visit('/privacy');assert.match(await page.$eval('body',e=>e.innerText),/In-app account deletion is currently unavailable/);checks.push('privacy removes unsupported immediate-deletion promise');
 assert.deepEqual(effects,[]);assert.deepEqual(errors,[]);checks.push('zero account mutations, Edge invocations, sign-outs or browser exceptions');
 fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({pass:true,checks,realWrites:0,effects,errors},null,2));console.log(JSON.stringify({pass:true,checks},null,2));
}catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({pass:false,checks,error:e.stack,effects,errors},null,2));throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
