/** Isolated local browser only; backend reads mocked, all mutations blocked. */
const puppeteer=require('puppeteer'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),base=process.env.TAVVY_COPY_BASE||'http://127.0.0.1:3854',out=process.env.TAVVY_COPY_QA||'/private/tmp/tavvy-account-copy-browser';
const maps={};new Function('exports',ts.transpileModule(fs.readFileSync(path.join(root,'lib/releaseCopy.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(maps);
const catalogs=Object.fromEntries(['en','pt','es'].map(l=>[l,JSON.parse(fs.readFileSync(path.join(root,`public/locales/${l}/common.json`)))]));
const copy=(lang,text)=>{if(lang==='en')return text;const key=maps.RELEASE_COPY_KEYS[text]?'release.'+maps.RELEASE_COPY_KEYS[text]:maps.EXISTING_COPY_KEYS[text.toLowerCase()];return key?.split('.').reduce((o,p)=>o?.[p],catalogs[lang])||text;};
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage();await page.setViewport({width:390,height:844});await page.setBypassServiceWorker(true);const errors=[],blockedWrites=[];let checks=0;
 const user={id:'00000000-0000-4000-8000-000000000083',email:'fixture@example.invalid',created_at:'2026-01-15T00:00:00Z',aud:'authenticated',role:'authenticated',app_metadata:{},user_metadata:{}};
 const card={id:'00000000-0000-4000-8000-000000000084',full_name:'Untranslated QA Name',title:'Untranslated QA Title',slug:'local-fixture',is_published:false,view_count:0,tap_count:0};
 page.on('pageerror',e=>errors.push(e.message));await page.setRequestInterception(true);page.on('request',req=>{const u=new URL(req.url());const reply=(data,status=200)=>req.respond({status,contentType:'application/json',headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*'},body:JSON.stringify(data)});
  if(u.origin===base){if(u.pathname.startsWith('/api/'))return reply({});return req.continue();}if(['data:','blob:'].includes(u.protocol))return req.continue();if(req.method()==='OPTIONS')return reply({});if(u.pathname==='/auth/v1/user')return reply(user);if(u.pathname.endsWith('/get_my_content_blocks_v1'))return reply([]);if(req.method()!=='GET'){blockedWrites.push(u.pathname);return reply({},403);}if(u.pathname.endsWith('/digital_cards'))return reply([card]);if(u.pathname.endsWith('/profiles'))return reply({user_id:user.id,display_name:'Untranslated QA Name',created_at:user.created_at,review_count:0,saved_count:0});return reply([]);
 });
 const click=async text=>{await page.waitForFunction(text=>[...document.querySelectorAll('button')].some(e=>e.textContent.trim()===text),{},text);await page.evaluate(text=>[...document.querySelectorAll('button')].find(e=>e.textContent.trim()===text).click(),text);};
 const fits=async()=>assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 try{await page.goto(base+'/app/ecard',{waitUntil:'networkidle2'});for(const lang of ['en','pt','es']){const c=t=>copy(lang,t),pre=lang==='en'?'':'/'+lang;
   await page.evaluate(({lang,user})=>{localStorage.setItem('tavvy-locale',lang);localStorage.setItem('sb-scasgwrikoqdwlwlwcff-auth-token',JSON.stringify({access_token:'qa.fixture.token',refresh_token:'qa-refresh',expires_at:Math.floor(Date.now()/1000)+3600,token_type:'bearer',user}));},{lang,user});
   await page.goto(base+pre+'/app/ecard',{waitUntil:'networkidle2',timeout:90000});await page.waitForFunction(name=>document.body.innerText.includes(name),{},card.full_name);assert.equal(await page.$eval('h1',el=>el.textContent),c('My eCards'));assert(await page.$(`[aria-label="${c('Create eCard')}"]`));assert(await page.$(`input[placeholder="${c('Search cards...')}"]`));await page.type('input',c('Draft'));assert((await page.$eval('body',el=>el.innerText)).includes(card.full_name));await fits();await page.screenshot({path:`${out}/${lang}-hub.png`});checks++;
   await page.goto(base+pre+'/app/profile',{waitUntil:'networkidle2',timeout:90000});await page.waitForFunction(name=>document.body.innerText.includes(name),{},'Untranslated QA Name');assert((await page.$eval('body',el=>el.innerText)).includes(c('Edit Profile')));assert((await page.$eval('body',el=>el.innerText)).includes(c('Sign Out')));await fits();await page.screenshot({path:`${out}/${lang}-profile.png`});checks++;
   await page.goto(base+pre+'/app/settings',{waitUntil:'networkidle2',timeout:90000});await click(c('Blocked authors'));await page.waitForFunction(text=>document.body.innerText.includes(text),{},c('No blocked authors.'));assert(!(await page.$eval('body',el=>el.innerText)).includes('fixture@example.invalid'));await fits();await page.screenshot({path:`${out}/${lang}-blocked-authors.png`});checks++;
  }assert.deepEqual(errors,[]);assert.deepEqual(blockedWrites,[]);const result={status:'PASS',checks,languages:['en','pt','es'],realWrites:0,errors,blockedWrites};fs.writeFileSync(out+'/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }catch(e){await page.screenshot({path:out+'/failure.png'});fs.writeFileSync(out+'/failure.json',JSON.stringify({error:String(e),url:page.url(),errors,blockedWrites},null,2));throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e.message);process.exitCode=1});
