const {PGlite}=require('@electric-sql/pglite');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
const db=new PGlite(),base=path.join(__dirname,'../..');
const schema=JSON.parse(fs.readFileSync(path.join(base,'docs/schema-audit/public-schema.json')));
await db.exec(`CREATE ROLE authenticated;CREATE ROLE anon;CREATE SCHEMA auth;CREATE DOMAIN geography AS text;CREATE FUNCTION st_makepoint(double precision,double precision) RETURNS text LANGUAGE sql AS $$ SELECT $1::text || ',' || $2::text $$;CREATE FUNCTION st_setsrid(text,integer) RETURNS text LANGUAGE sql AS $$ SELECT $1 $$;CREATE FUNCTION unaccent(text) RETURNS text LANGUAGE sql AS $$ SELECT $1 $$;CREATE FUNCTION uuid_generate_v4() RETURNS uuid LANGUAGE sql AS $$ SELECT gen_random_uuid() $$;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql STABLE AS $$ SELECT current_user::text $$;
GRANT USAGE ON SCHEMA public,auth TO authenticated,anon;`);
const tables=['places','tavvy_places','atlas_universe_places','pro_business_claims','fsq_places_raw','place_reviews','place_review_signal_taps','review_items','place_signal_aggregates','place_stats','places_search','review_reports'];
for(const table of tables){
 const cols=schema.columns.filter(c=>c.table===table).map(c=>`"${c.column}" ${c.type==='_text'?'text[]':c.type}${c.default?' DEFAULT '+c.default:''}`);
 await db.exec(`CREATE TABLE ${table}(${cols.join(',')});ALTER TABLE ${table} ENABLE ROW LEVEL SECURITY;GRANT SELECT,INSERT,UPDATE,DELETE ON ${table} TO authenticated,anon;`);
}
await db.exec(`CREATE UNIQUE INDEX canonical_source ON places(source_type,source_id) WHERE source_type IS NOT NULL AND source_id IS NOT NULL;
ALTER TABLE place_reviews ADD PRIMARY KEY(id);ALTER TABLE place_review_signal_taps ADD UNIQUE(review_id,signal_id);
ALTER TABLE place_review_signal_taps ADD CHECK(intensity BETWEEN 1 AND 3);
ALTER TABLE place_review_signal_taps ADD FOREIGN KEY(review_id) REFERENCES place_reviews(id);
ALTER TABLE place_signal_aggregates ADD PRIMARY KEY(place_id,signal_id);`);
for(const p of schema.policies.filter(p=>tables.includes(p.table))) {
 // Only deployed review/place/raw policies needed; auxiliary ownership tables have no rows.
 if(!['places','fsq_places_raw','place_reviews','place_review_signal_taps','place_signal_aggregates','review_items'].includes(p.table))continue;
 await db.exec(`CREATE POLICY "${p.name}" ON ${p.table} FOR ${p.command} TO ${p.roles.join(',')}${p.using?` USING (${p.using})`:''}${p.check?` WITH CHECK (${p.check})`:''}`);
}
const details=JSON.parse(fs.readFileSync(path.join(base,'docs/schema-audit/review-constraints.json')));
await db.exec('ALTER TABLE place_stats ADD PRIMARY KEY(place_id); ALTER TABLE places_search ADD PRIMARY KEY(place_id)');
await db.exec(JSON.parse(fs.readFileSync(path.join(base,'docs/schema-audit/place-search-trigger.json'))).rows[0].definition);
await db.exec('CREATE TRIGGER places_search_sync AFTER INSERT OR UPDATE ON places FOR EACH ROW EXECUTE FUNCTION sync_places_search()');
await db.exec(details.functions.find(f=>f.name==='update_place_stats').definition);
await db.exec('CREATE TRIGGER place_stats_update AFTER INSERT ON place_reviews FOR EACH ROW EXECUTE FUNCTION update_place_stats()');
for(const filename of ['202609080005_place_author_policies.sql','202609080006_atomic_place_reviews.sql'])await db.exec(fs.readFileSync(path.join(base,'supabase/migrations',filename),'utf8'));
const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002',sig='00000000-0000-0000-0000-000000000003',sig2='00000000-0000-0000-0000-000000000004';
await db.exec(`INSERT INTO review_items(id,label,slug,signal_type,is_active) VALUES('${sig}','Clean','clean','best_for',true),('${sig2}','Quiet','quiet','vibe',true);
INSERT INTO fsq_places_raw(fsq_place_id,name,address) VALUES('fsq-restroom','Airport Bathroom','Terminal A');
SET ROLE authenticated;SELECT set_config('request.jwt.claim.sub','${a}',false);`);
const call=(id,taps,review=null)=>`SELECT save_place_review('${id}','${JSON.stringify(taps)}'::jsonb,'public','private',${review?`'${review}'`:'NULL'},'web_app') AS id`;
await db.exec(`RESET ROLE;INSERT INTO review_items(id,label,slug,signal_type,is_active) VALUES('${b}','Pro endorsement','pro','pro_endorsement',true);SET ROLE authenticated;`);
const taps=[{signal_id:sig,intensity:3}];
await assert.rejects(db.exec(`INSERT INTO places(source_type,source_id,name) VALUES('fsq','forged','Bad')`),/row-level security/);
await assert.rejects(db.exec(`INSERT INTO fsq_places_raw(fsq_place_id,name) VALUES('forged','Bad')`),/row-level security/);
await assert.rejects(db.exec(call('fsq-restroom',taps).replace("'public'","repeat('x',4001)")),/4000/);
const rid=(await db.query(call('fsq-restroom',taps))).rows[0].id;
await assert.rejects(db.exec(`INSERT INTO place_review_signal_taps(review_id,place_id,signal_id,intensity) VALUES('${rid}','${b}','${sig2}',1)`),/row-level security/);
await assert.rejects(db.exec(`UPDATE place_reviews SET place_id='${b}' WHERE id='${rid}'`),/identity/);
const place=(await db.query(`SELECT id,street FROM places WHERE source_id='fsq-restroom'`)).rows[0];
assert.equal(place.street,'Terminal A');
assert.equal((await db.query(`SELECT tap_total FROM place_signal_aggregates WHERE place_id='${place.id}'`)).rows[0].tap_total,3);
assert.equal((await db.query(call('fsq-restroom',taps))).rows[0].id,rid,'retry reuses review');
assert.equal((await db.query(`SELECT count(*)::int n FROM place_reviews`)).rows[0].n,1);
await db.exec(call(place.id,[{signal_id:sig2,intensity:2}],rid));
assert.equal((await db.query(`SELECT count(*)::int n FROM place_signal_aggregates WHERE signal_id='${sig}'`)).rows[0].n,0,'removed taps removed from aggregates');
for(const invalid of [[],[{signal_id:sig,intensity:4}],[{signal_id:b,intensity:1}],[...taps,...taps]]) await assert.rejects(db.exec(call(place.id,invalid,rid)));
assert.equal((await db.query(`SELECT intensity FROM place_review_signal_taps WHERE review_id='${rid}'`)).rows[0].intensity,2,'bad update retains prior taps');
// Force a late failure, after delete/insert, to verify actual PostgreSQL rollback.
await db.exec(`RESET ROLE;CREATE FUNCTION fail_rollup() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced aggregate failure'; END $$;
CREATE TRIGGER fail_rollup BEFORE INSERT ON place_signal_aggregates FOR EACH ROW EXECUTE FUNCTION fail_rollup();SET ROLE authenticated;`);
await assert.rejects(db.exec(call(place.id,taps,rid)),/forced aggregate failure/);
assert.equal((await db.query(`SELECT intensity FROM place_review_signal_taps WHERE review_id='${rid}'`)).rows[0].intensity,2);
await db.exec(`SELECT set_config('request.jwt.claim.sub','${b}',false)`);
await assert.rejects(db.exec(call(place.id,taps,rid)),/not owned/);
await assert.rejects(db.exec(call('unknown-google-place',taps)),/Place not found/);
await db.exec(`SET ROLE anon;SELECT set_config('request.jwt.claim.sub','',false)`);
await assert.rejects(db.exec(call(place.id,taps)),/permission denied/);
await db.exec('RESET ROLE');
await db.exec(fs.readFileSync(path.join(base,'supabase/migrations/202609080007_review_private_fields.sql'),'utf8'));
await db.exec(`SET ROLE anon;`);
await assert.rejects(db.exec('SELECT private_note_owner FROM place_reviews'),/permission denied/);
await assert.rejects(db.exec('SELECT ip_address FROM place_reviews'),/permission denied/);
assert.equal((await db.query('SELECT public_note FROM place_reviews')).rows[0].public_note,'public');
await db.exec(`SET ROLE authenticated;SELECT set_config('request.jwt.claim.sub','${b}',false)`);
assert.equal((await db.query(`SELECT * FROM get_my_place_review('${place.id}')`)).rows.length,0);
await assert.rejects(db.exec('SELECT reviewer_zip FROM place_reviews'),/permission denied/);
await db.exec(`SELECT set_config('request.jwt.claim.sub','${a}',false)`);
assert.equal((await db.query(`SELECT * FROM get_my_place_review('${place.id}')`)).rows[0].private_note_owner,'private');
assert.equal((await db.query(`SELECT * FROM get_top_signals_for_place('${place.id}')`)).rows[0].tap_count,2);
await db.exec(`RESET ROLE;DROP TRIGGER fail_rollup ON place_signal_aggregates;CREATE ROLE service_role;
GRANT USAGE ON SCHEMA public,auth TO service_role;
CREATE OR REPLACE FUNCTION auth.role() RETURNS text LANGUAGE sql STABLE AS $$ SELECT COALESCE(NULLIF(current_setting('request.jwt.claim.role',true),''),current_user::text) $$;`);
await db.exec(fs.readFileSync(path.join(base,'supabase/migrations/202609080009_admin_tap_review_moderation.sql'),'utf8'));
await db.exec(`SET ROLE authenticated`);
await assert.rejects(db.exec(`SELECT admin_moderate_place_review('${rid}','live')`),/permission denied/);
await db.exec(`SET ROLE service_role;SELECT set_config('request.jwt.claim.role','service_role',false);SELECT admin_moderate_place_review('${rid}','rejected')`);
await db.exec('RESET ROLE');
assert.equal((await db.query(`SELECT count(*)::int n FROM place_signal_aggregates WHERE place_id='${place.id}'`)).rows[0].n,0);
await db.exec(`CREATE TRIGGER fail_rollup BEFORE INSERT ON place_signal_aggregates FOR EACH ROW EXECUTE FUNCTION fail_rollup();SET ROLE service_role;`);
await assert.rejects(db.exec(`SELECT admin_moderate_place_review('${rid}','live')`),/forced aggregate failure/);
await db.exec('RESET ROLE');
assert.equal((await db.query(`SELECT status FROM place_reviews WHERE id='${rid}'`)).rows[0].status,'rejected','moderation rollup failure rolls status back');
await db.exec('DROP TRIGGER fail_rollup ON place_signal_aggregates');
await db.exec(`SET ROLE service_role;SELECT admin_moderate_place_review('${rid}','live')`);
await assert.rejects(db.exec(`SELECT admin_moderate_place_review('${rid}','approved')`),/Invalid/);
await db.exec('RESET ROLE');
assert.equal((await db.query(`SELECT tap_total FROM place_signal_aggregates WHERE place_id='${place.id}'`)).rows[0].tap_total,2);
await db.exec(`SET ROLE service_role;SELECT admin_moderate_place_review('${rid}','delete')`);
await assert.rejects(db.exec(`SELECT admin_moderate_place_review('${rid}','live')`),/not found/);
await db.exec('RESET ROLE');
assert.equal((await db.query(`SELECT count(*)::int n FROM place_review_signal_taps WHERE review_id='${rid}'`)).rows[0].n,0);
assert.equal((await db.query(`SELECT total_reviews FROM place_stats WHERE place_id='${place.id}'`)).rows[0].total_reviews,0);
await db.close();console.log('Atomic review SQL: source promotion, ownership, retry idempotence, validation, rollback, private-field protection, aggregate replacement and service-only moderation passed.');
})().catch(e=>{console.error(e);process.exit(1)});
