const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.resolve(__dirname,'../..');
function load(file,deps){const exp={};const js=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;new Function('require','exports',js)(n=>{if(n in deps)return deps[n];throw Error(n)},exp);return exp;}
const id='77000300-0000-4000-8000-000000000011',reportId='77000300-0000-4000-8000-000000000020',blockId='77000300-0000-4000-8000-000000000021';
const client={rpc:async()=>({data:null,error:null}),auth:{getSession:async()=>({data:{session:null},error:null})}};
const h=load('lib/contentSafety.ts',{'./supabaseClient':{supabase:client}});
test('canonical parent target and server acknowledgement required, not a history revision or supplied author',async()=>{const calls=[];const rpc={rpc:async(name,args)=>{calls.push({name,args});return{data:{submitted:true,reportId},error:null}}};assert.equal(await h.reportContent('place_review',id,'spam',rpc),reportId);assert.deepEqual(calls,[{name:'report_content_v1',args:{p_kind:'place_review',p_content_id:id,p_reason:'spam'}}]);await assert.rejects(()=>h.reportContent('place_review','123','spam',rpc),/identified/);await assert.rejects(()=>h.reportContent('place_review','legacy:'+id,'spam',rpc),/identified/);assert.equal(calls.length,1);});
test('report table missing, denied, server empty/false and network errors never become success',async()=>{for(const response of [{data:null,error:{code:'42P01'}},{data:null,error:{code:'42501'}},{data:null,error:null},{data:{submitted:false,reportId},error:null},{data:{submitted:true,reportId:'123'},error:null}])await assert.rejects(()=>h.reportContent('story',id,'sexual',{rpc:async()=>response}),/not saved/);await assert.rejects(()=>h.reportContent('story',id,'sexual',{rpc:async()=>{throw Error('offline')}}),/offline/);});
test('block resolves author server-side and rejects missing acknowledgement/self-block',async()=>{let args;assert.equal(await h.blockContentAuthor('story',id,{rpc:async(n,a)=>{args=a;return{data:{blocked:true,blockId},error:null}}}),blockId);assert.deepEqual(args,{p_kind:'story',p_content_id:id});await assert.rejects(()=>h.blockContentAuthor('story',id,client),/could not/);await assert.rejects(()=>h.blockContentAuthor('story',id,{rpc:async()=>({error:{message:'SAFETY_SELF_BLOCK'}})}),/yourself/);});
test('unblock fails unless the server confirms ownership-scoped removal',async()=>{await assert.rejects(()=>h.unblockAuthor(blockId,client),/could not/);await h.unblockAuthor(blockId,{rpc:async()=>({data:true,error:null})});});
test('blocked list failure is distinct from a genuinely empty list',async()=>{await assert.rejects(()=>h.listBlockedAuthors(client),/could not be loaded/);assert.deepEqual(await h.listBlockedAuthors({rpc:async()=>({data:[],error:null})}),[]);await assert.rejects(()=>h.listBlockedAuthors({rpc:async()=>({data:[{id:1}],error:null})}),/could not/);});
test('authorization travels in headers only and session errors propagate',async()=>{client.auth.getSession=async()=>({data:{session:{access_token:'fixture-token'}},error:null});assert.deepEqual(await h.contentSafetyHeaders(),{Authorization:'Bearer fixture-token'});client.auth.getSession=async()=>({data:{session:null},error:{message:'offline'}});await assert.rejects(()=>h.contentSafetyHeaders(),/session/);});
if(fs.existsSync(path.join(root,'lib/contentSafetyServer.ts')))test('API viewers isolate credentials per request and reject invalid sessions',async()=>{const calls=[];const helper=load('lib/contentSafetyServer.ts',{'@supabase/supabase-js':{createClient:(url,key,opts)=>{calls.push(opts);return{auth:{getUser:async()=>opts.global?.headers?.Authorization?.includes('bad')?{error:{},data:{user:null}}:{data:{user:{id}},error:null}}}}}});await Promise.all([helper.contentViewer({headers:{authorization:'Bearer one'}}),helper.contentViewer({headers:{authorization:'Bearer two'}})]);assert.deepEqual(calls.map(x=>x.global.headers.Authorization),['Bearer one','Bearer two']);assert.equal((await helper.contentViewer({headers:{authorization:'Bearer bad'}})).error,true);assert.equal((await helper.contentViewer({headers:{authorization:'bad'}})).error,true);});
test('new public surfaces use canonical content IDs, never caller author identity',async()=>{const calls=[];for(const kind of ['cruise_visit','place_photo','ecard_endorsement','ecard'])await h.reportContent(kind,id,'offensive',{rpc:async(name,args)=>{calls.push(args);return{data:{submitted:true,reportId},error:null}}});assert.equal(calls.length,4);for(const call of calls){assert.equal(call.p_content_id,id);assert.deepEqual(Object.keys(call).sort(),['p_content_id','p_kind','p_reason']);}});
if(fs.existsSync(path.join(root,'lib/ecard/publicSafety.ts'))){
 const safety=load('lib/ecard/publicSafety.ts',{});
 test('public eCard safety read distinguishes blocked from failure and never returns hidden notes',async()=>{assert.deepEqual(await safety.fetchPublicCardSafety({rpc:async()=>({data:{visible:false,endorsements:[{id,endorserName:'Fixture',note:'hidden',createdAt:null}]},error:null})},id),{visible:false,endorsements:[]});for(const data of [null,{}, {visible:true,endorsements:'bad'}, {visible:true,endorsements:[{note:'missing identity'}]}])await assert.rejects(()=>safety.fetchPublicCardSafety({rpc:async()=>({data,error:null})},id),/unavailable/);await assert.rejects(()=>safety.fetchPublicCardSafety({rpc:async()=>({data:{visible:true,endorsements:[]},error:{code:'42501'}})},id),/unavailable/)});
 test('public safety request carries only canonical card identity and accepts genuinely empty notes',async()=>{let args;const data=await safety.fetchPublicCardSafety({rpc:async(name,input)=>{assert.equal(name,'get_public_ecard_safety_v1');args=input;return{data:{visible:true,endorsements:[]},error:null}}},id);assert.deepEqual(args,{p_card_id:id});assert.deepEqual(data,{visible:true,endorsements:[]});});
}
