const {PGlite}=require(process.env.TAVVY_PGLITE||'/private/tmp/tavvy-evidence-tests/node_modules/@electric-sql/pglite');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
(async()=>{const db=new PGlite();await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role;CREATE TABLE public.atlas_universes(id uuid PRIMARY KEY,name text,slug text,status text);CREATE TABLE public.places(id uuid PRIMARY KEY);CREATE TABLE public.atlas_universe_places(universe_id uuid);CREATE TABLE public.universe_reviews(universe_id uuid);`);
await db.exec(fs.readFileSync(path.join(__dirname,'../../supabase/migrations/202609220001_cruise_universe_catalog.sql'),'utf8'));
await db.exec(fs.readFileSync(path.join(__dirname,'../../supabase/migrations/202609210019_cruise_directory_filters.sql'),'utf8'));
await db.exec(`INSERT INTO public.cruise_operators(id,name) VALUES ('alpha','Alpha'),('beta','Beta'),('draft-only','Draft Only');
INSERT INTO public.atlas_universes(id,name,slug,status,universe_kind) SELECT ('01900000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,'Fixture '||i,'fixture-'||i,CASE WHEN i=36 THEN 'draft' ELSE 'published' END,'cruise_ship' FROM generate_series(1,36)i;
INSERT INTO public.cruise_ships(id,universe_id,slug,name,operator_id,kind) SELECT id,id,slug,CASE WHEN right(id::text,12)::int<=30 THEN 'A'||right(id::text,12) ELSE 'Z'||right(id::text,12) END,CASE WHEN right(id::text,12)::int<=30 THEN 'alpha' WHEN right(id::text,12)::int<=35 THEN 'beta' ELSE 'draft-only' END,CASE WHEN right(id::text,12)::int IN(32,33,35) THEN 'river' ELSE 'ocean' END FROM public.atlas_universes;
INSERT INTO public.cruise_ship_sources(ship_id,id,url,publisher,checked_at,source_type) SELECT id,'official','https://example.invalid/ship','Fixture',current_date,'operator' FROM public.cruise_ships;
UPDATE public.cruise_ships SET publication_status='published',identity_verified=true,overnight_public_cruise=true,status_source_ids=ARRAY['official'],operating_status=CASE WHEN right(id::text,12)::int=35 THEN 'announced' ELSE 'operating' END WHERE right(id::text,12)::int<=35;
INSERT INTO public.cruise_ship_name_history(ship_id,name,source_ids) VALUES ('01900000-0000-4000-8000-000000000032','Former Verified',ARRAY['official']),('01900000-0000-4000-8000-000000000033','Former Unverified',ARRAY['missing']);SET ROLE anon;`);
const rows=async q=>(await db.query(q)).rows;
assert.equal((await rows("SELECT * FROM public.get_cruise_operators_v1()")).length,2);
let result=await rows("SELECT * FROM public.search_cruise_ships_v2('',NULL,'operating','beta',1,2,NULL)");assert.deepEqual(result.map(r=>r.search_cruise_ships_v2.ship.slug),['fixture-32','fixture-33']);
assert.equal((await rows("SELECT * FROM public.search_cruise_ships_v2('','river','operating','beta',0,25,NULL)")).length,2);
assert.equal((await rows("SELECT * FROM public.search_cruise_ships_v2('','river','announced','beta',0,25,NULL)")).length,1);
assert.equal((await rows("SELECT * FROM public.search_cruise_ships_v2('Former Verified',NULL,'operating','beta',0,25,NULL)")).length,1);
assert.equal((await rows("SELECT * FROM public.search_cruise_ships_v2('Former Unverified',NULL,'operating','beta',0,25,NULL)")).length,0);
result=await rows("SELECT * FROM public.search_cruise_ships_v2('',NULL,'operating','beta',0,25,ARRAY['01900000-0000-4000-8000-000000000033','01900000-0000-4000-8000-000000000031','01900000-0000-4000-8000-000000000036']::uuid[])");assert.deepEqual(result.map(r=>r.search_cruise_ships_v2.ship.slug),['fixture-33','fixture-31']);
assert.equal((await rows("SELECT * FROM public.search_cruise_ships_v2('',NULL,'operating',NULL,0,25,'{}'::uuid[])")).length,0);
assert.equal((await rows("SELECT * FROM public.search_cruise_ships_v2('',NULL,'operating',NULL,0,25,array_fill('01900000-0000-4000-8000-000000000033'::uuid,ARRAY[13]))")).length,0);
assert.equal((await rows("SELECT * FROM public.search_cruise_ships_v2('',NULL,'operating','draft-only',0,25,NULL)")).length,0);
assert.equal((await rows("SELECT * FROM public.search_cruise_ships_v2('',NULL,'retired',NULL,0,25,NULL)")).length,0);
assert.equal((await rows("SELECT * FROM public.search_cruise_ships_v1('',NULL,'operating',0,25)")).length,25);
await assert.rejects(()=>rows('SELECT * FROM public.cruise_ships'),/permission denied/);
await db.close();console.log('PASS 12 SQL gates: public facets, filter before pagination, combined scope, sourced history, editorial order, hidden ships, bounds, v1 and raw-table denial');})().catch(e=>{console.error(e.message);process.exitCode=1});
