/** Entirely local fixture API; blocks external browser requests and never touches production. */
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict'),{spawn}=require('child_process'),puppeteer=require('puppeteer');
const root=path.resolve(__dirname,'../..'),out=process.env.TAVVY_CRUISE_QA||'/private/tmp/tavvy-cruise-browser-qa',port=3057,web=3058,base=`http://127.0.0.1:${web}`,uid='dcac0000-0000-4000-8000-000000000031',sid='dcac0000-0000-4000-8000-000000000011',universe='dcac0000-0000-4000-8000-000000000001';
const user={id:uid,email:'cruise-fixture@example.invalid',aud:'authenticated',role:'authenticated',app_metadata:{},user_metadata:{}};
const source={id:'official',url:'https://example.invalid/ship',publisher:'Fixture Operator',checked_at:'2026-09-20',source_type:'operator'};
const fact=(key,value)=>({key,value,source_ids:['official'],as_of:'2026-09-20',verification:'verified'});
const detail={ship:{id:sid,universe_id:universe,slug:'fixture-voyager',name:'Fixture Voyager',operator_id:'fixture-line',operator_name:'Fixture Line',kind:'ocean',operating_status:'operating',publication_status:'published',overnight_public_cruise:true,identity_verified:true,status_source_ids:['official'],imo:null,eni:null,official_url:source.url,name_history:[],facts:[fact('year_built',2001),fact('guests_double_occupancy',2200),fact('guests_maximum',2700),fact('decks_passenger',9),fact('shops',null)],cabin_categories:[{id:'dcac0000-0000-4000-8000-000000000021',name:'Balcony',description:'Fixture cabin category description.',accessible:null,source_ids:['official']}],photo:null},sources:[source],venues:[{id:'dcac0000-0000-4000-8000-000000000022',ship_id:sid,name:'Fixture Dining Room',kind:'restaurant',place_id:'dcac0000-0000-4000-8000-000000000023',description:'Fixture venue description.',deck_label:'Deck 5',included:true,availability_note:null,source_ids:['official'],verification:'verified'}]};
detail.programs=[{id:'dcac0000-0000-4000-8000-000000000065',ship_id:sid,name:'Fixture Evening Show',kind:'show',venue_id:null,description:null,as_of:'2026-09-20',availability_note:'May vary by sailing.',source_ids:['official'],verification:'verified'}];
const announced=JSON.parse(JSON.stringify(detail));Object.assign(announced.ship,{id:'dcac0000-0000-4000-8000-000000000012',universe_id:'dcac0000-0000-4000-8000-000000000002',slug:'fixture-future',name:'Fixture Future',operating_status:'announced',kind:'river'});announced.venues=[];
const signals=[{id:'dcac0000-0000-4000-8000-000000000041',slug:'cruise_quality_food',label:'Quality food',signal_type:'best_for'},{id:'dcac0000-0000-4000-8000-000000000042',slug:'cruise_quiet_spaces',label:'Quiet spaces',signal_type:'vibe'},{id:'dcac0000-0000-4000-8000-000000000043',slug:'cruise_noisy_cabins',label:'Noisy cabins',signal_type:'heads_up'}];
let saved=null,writes=[],searches=[],safetyRequests=[],evidenceFailure=false,lookupFailure=false,feedFailure=false,blocked=false,reportFailure=false,feedOverride=null,pagingFixture=false,releaseMore=null,legacyMode=false;const server=http.createServer(async(req,res)=>{let body='';for await(const part of req)body+=part;let input={};try{input=JSON.parse(body||'{}')}catch{};res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','*');res.setHeader('Access-Control-Allow-Methods','*');res.setHeader('Content-Type','application/json');const send=(data,status=200)=>{res.statusCode=status;res.end(JSON.stringify(data))};if(req.method==='OPTIONS')return send({});const url=new URL(req.url,`http://127.0.0.1:${port}`),name=url.pathname.split('/').at(-1);
 if(url.pathname==='/auth/v1/user')return send(user);
 if(name==='get_cruise_ship_v1'&&lookupFailure)return send({message:'Fixture lookup unavailable'},503);
 if(name==='get_cruise_ship_v1')return send(input.p_slug==='fixture-future'||input.p_universe_id===announced.ship.universe_id?announced:input.p_slug==='missing'?null:detail);
 if(name==='get_cruise_operators_v1')return send([{id:'fixture-line',name:'Fixture Line'}]);
 if(name==='search_cruise_ships_v3'){searches.push(input);return send(input.p_status==='announced'?[announced]:input.p_query?.includes('none')?[]:[detail])}
 if(name==='get_cruise_universe_evidence_v1'){if(evidenceFailure)return send({message:'Fixture unavailable'},503);return send({visits:saved?[{reviewId:saved.id,userId:'fixture-pseudonym',visitedAt:saved.sailing_date+'T00:00:00.000Z',signals:saved.signals.map(s=>({slug:signals.find(i=>i.label===s.label).slug,label:s.label,category:s.category==='best_for'?'good':s.category==='heads_up'?'headsup':'vibe',intensity:s.intensity}))}]:[],snapshot:'fixture',complete:true,next_cursor:'1'})}
 if(name==='get_cruise_universe_reviews_v1'){if(pagingFixture&&input.p_offset>0){const stale={...feedOverride,id:'dcac0000-0000-4000-8000-000000000053',public_note:'Blocked author late page fixture.'};await new Promise(resolve=>{releaseMore=resolve});return send({reviews:[stale],total:2})}if(feedFailure)return send({message:'Fixture feed unavailable'},503);return send({reviews:blocked?[]:feedOverride?[feedOverride]:saved?[saved]:[],total:blocked?0:pagingFixture?2:saved?1:0})}
 if(name==='report_content_v1'){safetyRequests.push({action:'report',...input});return reportFailure?send({message:'Fixture report failure'},503):send({submitted:true,reportId:'dcac0000-0000-4000-8000-000000000071'})}
 if(name==='block_content_author_v1'){safetyRequests.push({action:'block',...input});blocked=true;return send({blocked:true,blockId:'dcac0000-0000-4000-8000-000000000072'})}
 if(name==='review_items')return send(signals);
 if(name==='save_cruise_universe_visit_v1'){writes.push(input);saved={id:'dcac0000-0000-4000-8000-000000000051',sailing_date:input.p_sailing_date,public_note:input.p_public_note,cabin_category_name:null,signals:input.p_signals.map(s=>({label:signals.find(i=>i.id===s.signal_id).label,category:signals.find(i=>i.id===s.signal_id).signal_type,intensity:s.intensity}))};return send(saved.id)}
 if(name==='atlas_universes'){if(legacyMode)return send(url.searchParams.has('parent_universe_id')?[]:{id:universe,slug:'fixture-collection',name:'Fixture Collection',status:'published',universe_kind:'place_collection'});return send({id:universe,slug:'fixture-voyager',name:detail.ship.name,status:'published',universe_kind:'cruise_ship'})}
 if(name==='universe_reviews')return feedFailure?send({message:'Fixture review refresh failure'},503):send(blocked?[]:[{id:'dcac0000-0000-4000-8000-000000000081',type:'good',text:'Legacy guest fixture text.',user_name:'Fixture Guest',created_at:'2026-09-20T12:00:00Z'}]);
 if(name==='get_my_ecard_entitlement')return send({is_pro:false});
 if(req.method!=='GET')return send({message:'Unexpected write blocked'},403);return send([]);
});
(async()=>{fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(port,'127.0.0.1',r));const log=fs.openSync(out+'/dev.log','w');const standalone=process.env.TAVVY_CRUISE_STANDALONE;const next=spawn(process.execPath,standalone?[path.join(standalone,'server.js')]:[path.join(root,'node_modules/next/dist/bin/next'),'dev','-p',String(web)],{cwd:standalone||root,env:{...process.env,HOSTNAME:'127.0.0.1',PORT:String(web),NEXT_PUBLIC_SUPABASE_URL:`http://127.0.0.1:${port}`,NEXT_PUBLIC_SUPABASE_ANON_KEY:'local-fixture-public-key'},stdio:['ignore',log,log]});let browser;
try{for(let i=0;i<80;i++){try{const r=await fetch(base+'/api/health');if(r.ok)break}catch{}await new Promise(r=>setTimeout(r,400))}if(standalone){assert(fs.existsSync(path.join(standalone,'next-i18next.config.js')),'locale config is traced into standalone');const wizard=await fetch(base+'/app/ecard/new');assert.equal(wizard.status,200,'unrelated localized SSR route keeps working in standalone');}
const html=await(await fetch(base+'/app/cruises/fixture-voyager')).text();fs.writeFileSync(out+'/initial.html',html);assert(html.includes('Fixture Voyager — cruise ship'));assert(html.includes('property="og:title" content="Fixture Voyager — cruise ship | Tavvy"'),'crawler gets ship identity without JavaScript');assert(!html.includes('property="og:image" content="https://example.invalid'),'no invented photo');lookupFailure=true;const unavailablePage=await fetch(base+'/app/cruises/fixture-voyager');assert.equal(unavailablePage.status,503,'temporary lookup outage has HTTP503 status');assert(unavailablePage.headers.get('cache-control').includes('no-store'),'outage response is not cached');lookupFailure=false;const png=await fetch(base+'/api/og/cruise/fixture-voyager');assert.equal(png.status,200);assert.equal(png.headers.get('content-type'),'image/png');fs.writeFileSync(out+'/ship-share.png',Buffer.from(await png.arrayBuffer()));
 browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewport({width:390,height:844});await page.setRequestInterception(true);page.on('request',r=>{const u=new URL(r.url());if(['http:','https:'].includes(u.protocol)&&u.hostname!=='127.0.0.1'&&u.hostname!=='localhost')return r.abort();r.continue()});await page.evaluateOnNewDocument(user=>{localStorage.setItem('tavvy-locale','en');localStorage.setItem('@tavvy_theme_mode','light');localStorage.setItem('sb-scasgwrikoqdwlwlwcff-auth-token',JSON.stringify({access_token:'qa.session.token',refresh_token:'qa-refresh',expires_at:Math.floor(Date.now()/1000)+3600,expires_in:3600,token_type:'bearer',user}))},user);
 const visit=route=>page.goto(base+route,{waitUntil:'networkidle2'}),click=async text=>{await page.waitForFunction(t=>[...document.querySelectorAll('button')].some(e=>e.textContent.trim()===t),{},text);await page.evaluate(t=>[...document.querySelectorAll('button')].find(e=>e.textContent.trim()===t).click(),text)},clean=async()=>{assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'horizontal overflow');assert.deepEqual(errors,[])};
 await visit('/app/cruises');await page.waitForSelector('.ship');assert((await page.$eval('body',e=>e.innerText)).includes('Fixture Voyager'));await click('Filters');await click('Operating ships');await click('Apply filters');await new Promise(r=>setTimeout(r,350));assert((await page.$eval('body',e=>e.innerText)).includes('Fixture Voyager'),'reselecting active status retains loaded results');await click('Filters');await click('Announced ships');await click('Apply filters');await page.waitForFunction(()=>document.body.innerText.includes('Fixture Future'));assert.equal(searches.at(-1).p_status,'announced');await page.screenshot({path:out+'/announced-directory.png',fullPage:true});await clean();
 await visit('/app/cruises/fixture-future');await page.waitForSelector('.guest-reports');assert.equal(await page.$$eval('button',a=>a.filter(e=>e.textContent==='Add your taps').length),0);assert(await page.$('[aria-label="No ship photo"]'));
 await visit('/app/cruises/fixture-voyager');await page.waitForFunction(()=>document.body.innerText.includes('No guest reports to show.'));await page.screenshot({path:out+'/ship-overview-empty.png',fullPage:true});await click('On board');assert(await page.$('a[href="/app/place/dcac0000-0000-4000-8000-000000000023"]'));assert((await page.$eval('body',e=>e.innerText)).includes('1 verified venue listings'));assert((await page.$eval('body',e=>e.innerText)).includes('Fixture Evening Show'));assert((await page.$eval('body',e=>e.innerText)).includes('May vary by sailing.'));await click('Ship information');const info=await page.$eval('body',e=>e.innerText);assert(info.includes('2,200')&&info.includes('2,700'));assert(!info.includes('Shops'));await page.screenshot({path:out+'/ship-information.png',fullPage:true});await clean();
 await click('Cabins');assert((await page.$eval('body',e=>e.innerText)).includes('Balcony'));await click('Photos & stories');await click('Overview');await click('Add your taps');await page.waitForSelector('.composer');await page.$eval('input[type=date]',e=>{const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;set.call(e,'2026-09-01');e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}))});await click('Quality food');await click('Noisy cabins');await page.type('textarea','A clear fixture note about the food.');await click('Save experience');await page.waitForFunction(()=>document.body.innerText.includes('Your experience has been saved.'));assert.equal(writes.length,1);assert.equal(writes[0].p_universe_id,universe);assert.equal(writes[0].p_signals[0].signal_id,signals[0].id);await page.waitForFunction(()=>document.body.innerText.includes('A clear fixture note'));assert((await page.$eval('[data-review-section=main]',e=>e.innerText)).includes('Noisy cabins'));await page.screenshot({path:out+'/ship-reports-saved.png',fullPage:true});await clean();
 // Replace the feed with another guest's fixture; actual author/self-block authorization is covered by the SQL gate.
 pagingFixture=true;feedOverride={...saved,id:'dcac0000-0000-4000-8000-000000000052',public_note:'Another guest shared this fixture experience.'};await visit('/app/cruises/fixture-voyager');await page.waitForFunction(()=>document.body.innerText.includes('Another guest shared'));
 await click('Report or block');await click('Report content');reportFailure=true;await click('Send report');await page.waitForFunction(()=>document.body.innerText.includes('Your report was not saved.'));assert(!(await page.$eval('body',e=>e.innerText)).includes('Report sent to Tavvy for review.'));
 reportFailure=false;await click('Send report');await page.waitForFunction(()=>document.body.innerText.includes('Report sent to Tavvy for review.'));assert.equal(safetyRequests.at(-1).p_kind,'cruise_visit');assert.equal(safetyRequests.at(-1).p_content_id,feedOverride.id);
 await click('Load more reports');for(let i=0;i<40&&!releaseMore;i++)await new Promise(r=>setTimeout(r,25));assert(releaseMore,'pagination fixture request started');await click('Report or block');await click('Block author');feedFailure=true;await click('Confirm block');await page.waitForFunction(()=>document.body.innerText.includes('Guest reports are temporarily unavailable'));assert(!(await page.$eval('body',e=>e.innerText)).includes('Another guest shared'),'failed blocked-feed refresh never retains old author text');
 releaseMore();await new Promise(r=>setTimeout(r,300));assert(!(await page.$eval('body',e=>e.innerText)).includes('Blocked author late page'),'late pagination cannot restore a blocked author');feedFailure=false;await click('Retry guest reports');await page.waitForFunction(()=>document.body.innerText.includes('No guest reports to show.'));assert((await page.$eval('.guest-reports',e=>e.innerText)).includes('Early impressions · 1 reviewer'),'personal blocking leaves global evidence intact');assert.equal(safetyRequests.at(-1).p_content_id,feedOverride.id);await page.screenshot({path:out+'/ship-blocked-author.png',fullPage:true});await clean();blocked=false;feedOverride=null;pagingFixture=false;
 evidenceFailure=true;await visit('/app/cruises/fixture-voyager');await page.waitForFunction(()=>document.body.innerText.includes('Guest reports are temporarily unavailable'));assert(!(await page.$eval('body',e=>e.innerText)).includes('No guest reports to show.'));await page.screenshot({path:out+'/ship-reports-unavailable.png',fullPage:true});await clean();
 await page.setViewport({width:1365,height:900});evidenceFailure=false;await visit('/app/cruises/fixture-voyager');await page.waitForFunction(()=>document.body.innerText.includes('A clear fixture note'));assert((await page.$eval('[data-review-section=main]',e=>e.innerText)).includes('Noisy cabins'));await page.screenshot({path:out+'/ship-desktop.png',fullPage:true});await clean();
 legacyMode=true;await page.setViewport({width:390,height:844});await visit('/app/universe/fixture-collection');await page.waitForFunction(()=>document.body.innerText.includes('Fixture Collection'));await click('Reviews');await page.waitForFunction(()=>document.body.innerText.includes('Legacy guest fixture text.'));await click('Report or block');await click('Block author');feedFailure=true;await click('Confirm block');await page.waitForFunction(()=>document.body.innerText.includes('Reviews are unavailable.'));assert(!(await page.$eval('body',e=>e.innerText)).includes('Legacy guest fixture text.'),'legacy Universe failed block refresh clears old text');assert.equal(safetyRequests.at(-1).p_kind,'universe_review');assert.equal(safetyRequests.at(-1).p_content_id,'dcac0000-0000-4000-8000-000000000081');await page.screenshot({path:out+'/legacy-universe-blocked.png',fullPage:true});await clean();
 const result={status:'PASS',checks:['SSR ship OG without JS','temporary lookup HTTP503/no-store','reselect active status preserves results','separate operating/announced directory','no review CTA for announced ship','neutral absent photo','onboard canonical venue identity','separate capacity bases and omitted unknown facts','cabins and stories sections','authenticated fixture tap save refreshes evidence/feed','unavailable evidence stays distinct from empty','390px and1365px no overflow','report error does not falsely succeed','cruise_visit parent UUID report target','block clears old text even if refresh fails','personal blocked feed preserves global summary','late pagination cannot restore blocked text','legacy Universe actual review-ID blocking clears feed on refresh failure'],mockWrites:writes.length,mockSafetyRequests:safetyRequests.length,errors};fs.writeFileSync(out+'/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}catch(e){if(browser){const pages=await browser.pages();const page=pages.at(-1);await page.screenshot({path:out+'/failure.png',fullPage:true});fs.writeFileSync(out+'/failure.txt',await page.$eval('body',e=>e.innerText))}throw e}finally{if(browser)await browser.close();next.kill('SIGTERM');await new Promise(r=>server.close(r));fs.closeSync(log)}})().catch(e=>{console.error(e);process.exitCode=1});
