const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm'),ts=require('typescript');
function load(file){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'../../lib/cruises',file+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,URL,require:n=>n==='./catalog'?catalog:{supabase:{rpc(){throw Error('Unexpected network')}}}});return exports;}
const catalog=load('catalog'),service=load('service');const clone=v=>JSON.parse(JSON.stringify(v));
const sources=[{id:'source-1',url:'https://example.invalid/official-ship',publisher:'Test operator',checked_at:'2026-09-20',source_type:'operator'}];
const ship={id:'ship-a',universe_id:'universe-a',slug:'test-ship',name:'Fixture ship',operator_name:'Fixture line',kind:'ocean',operating_status:'operating',publication_status:'published',overnight_public_cruise:true,identity_verified:true,status_source_ids:['source-1'],imo:null,eni:null,official_url:null,name_history:[],facts:[],cabin_categories:[],photo:null};
const fact=(key,value)=>({key,value,source_ids:['source-1'],as_of:'2026-09-20',verification:'verified'});
test('operating public overnight ships are separate from announced, unknown and charter-only',()=>{const variants=['operating','announced','unknown'].map(operating_status=>({ship:{...ship,operating_status},sources,venues:[]}));assert.equal(catalog.publishedCruiseShips(variants).length,1);assert.equal(catalog.publishedCruiseShips(variants,'announced')[0].ship.operating_status,'announced');assert(catalog.cruisePublicationProblems({...ship,overnight_public_cruise:false},sources).length);assert(catalog.cruisePublicationProblems({...ship,identity_verified:false},sources).length);assert.equal(catalog.cruisePublicationProblems(ship,sources).length,0);});
test('capacity bases, build dates and deck counts remain separate; absent/conflicting facts never become zero',()=>{const s={...ship,facts:[fact('year_built',2001),fact('entered_service','2002'),fact('guests_double_occupancy',2200),fact('guests_maximum',2700),fact('decks_total',12),fact('decks_passenger',9),fact('shops',null),{...fact('restaurants',10),verification:'conflicting'},fact('pools',0)]};const facts=catalog.displayCruiseFacts(s,sources);assert.equal(facts.length,7);assert.equal(facts.find(f=>f.key==='pools').value,0);assert(!facts.some(f=>f.key==='shops'||f.key==='restaurants'));});
test('only sourced verified venues for this ship show; venues do not inflate specification totals',()=>{const v={id:'v',ship_id:ship.id,name:'Fixture cafe',kind:'cafe',place_id:'canonical-place',source_ids:['source-1'],verification:'verified'};assert.equal(catalog.visibleCruiseVenues({ship,sources,venues:[v,{...v,ship_id:'other'},{...v,source_ids:[]}]}).length,1);assert.equal(catalog.displayCruiseFacts(ship,sources).length,0);assert.equal(catalog.cruiseVenueReviewCategory('cafe'),'cafe');});
test('renames preserve immutable identity; matching names alone never merge ships',()=>{assert(catalog.sameCruiseIdentity(ship,{...ship,name:'Renamed'}));assert(!catalog.sameCruiseIdentity(ship,{...ship,id:'other'}));assert(catalog.sameCruiseIdentity({...ship,imo:'1234567'},{...ship,id:'other',imo:'1234567'}));assert.equal(catalog.safeCruiseUrl('javascript:alert(1)'),null);assert.equal(catalog.safeCruiseUrl('https://user:secret@example.invalid'),null);});
test('calendar years never use thousands separators',()=>{assert.equal(catalog.formatCruiseFact(fact('year_built',2001),'en'),'2001');assert.equal(catalog.formatCruiseFact(fact('guests_maximum',2700),'en'),'2,700');});
test('read contract keeps status/kind filters and pagination; errors are unavailable, not an empty verified fleet',async()=>{const calls=[],client={rpc:async(name,args)=>{calls.push({name,args});return{data:Array.from({length:3},()=>({ship,sources,venues:[]})),error:null}}};const result=await service.searchCruiseShips({query:'  Ship ',kind:'river',status:'announced',limit:2,offset:2},client);assert.equal(result.ships.length,2);assert.equal(result.hasMore,true);assert.equal(calls[0].args.p_status,'announced');assert.equal(calls[0].args.p_kind,'river');assert.equal(calls[0].args.p_offset,2);assert.equal(calls[0].args.p_limit,3);assert.equal(calls[0].args.p_query,'Ship');await assert.rejects(()=>service.searchCruiseShips({}, {rpc:async()=>({data:null,error:{message:'offline'}})}),/temporarily unavailable/);assert.equal(await service.getCruiseShip({slug:'missing'},{rpc:async()=>({data:null,error:null})}),null);});

test('shows are sourced programs, not invented physical places',()=>{const p={id:'show',ship_id:ship.id,name:'Fixture show',kind:'show',venue_id:null,source_ids:['source-1'],as_of:'2026-09-20',verification:'verified'};assert.equal(catalog.visibleCruisePrograms({ship,sources,venues:[],programs:[p,{...p,ship_id:'other'},{...p,verification:'unverified'}]}).length,1);});

test('staging validator rejects shows assigned to another ship or a missing physical venue',()=>{const {validate}=require('../cruises/validate-catalog.cjs');const current={...ship,id:'dcac0000-0000-4000-8000-000000000011',universe_id:'dcac0000-0000-4000-8000-000000000001',operator_id:'fixture'};const program={id:'dcac0000-0000-4000-8000-000000000065',ship_id:current.id,name:'Fixture show',kind:'show',venue_id:null,source_ids:['source-1'],as_of:'2026-09-20',verification:'verified'};const payload={schemaVersion:1,operators:[{id:'fixture'}],ships:[{ship:current,sources,venues:[],programs:[program]}]};assert.equal(validate(payload).errors.length,0);const invalid=clone(payload);invalid.ships[0].programs[0].venue_id='dcac0000-0000-4000-8000-000000000099';assert(validate(invalid).errors.some(s=>s.includes('venue must belong')));invalid.ships[0].programs[0].ship_id='other';assert(validate(invalid).errors.some(s=>s.includes('belongs to another ship')));});
