const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm'),ts=require('typescript');
const cache={};function load(name){if(cache[name])return cache[name];const exports={};cache[name]=exports;vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'../../lib/cruises',name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,URL,require:n=>n.startsWith('./')?load(n.slice(2)):{supabase:{rpc(){throw Error('Unexpected network')}}}});return exports;}
const service=load('service'),state=load('directoryState'),featured=load('featured');
const src={id:'s',url:'https://example.invalid/ship',publisher:'Fixture',checked_at:'2026-09-20',source_type:'operator'};
const detail={ship:{id:'a',universe_id:'u',slug:'fixture',name:'Fixture',operator_name:'Fixture Line',operator_id:'fixture-line',kind:'river',operating_status:'operating',publication_status:'published',identity_verified:true,overnight_public_cruise:true,status_source_ids:['s'],imo:null,eni:null,name_history:[],facts:[],cabin_categories:[]},sources:[src],venues:[]};
test('company/type/status/query are sent together before paginated result slicing',async()=>{let call;const result=await service.searchCruiseShips({query:' Former ',operatorId:'fixture-line',kind:'river',status:'announced',offset:24,limit:24},{rpc:async(name,args)=>(call={name,args},{data:Array(25).fill(detail),error:null})});assert.equal(call.name,'search_cruise_ships_v2');assert.equal(call.args.p_operator_id,'fixture-line');assert.equal(call.args.p_kind,'river');assert.equal(call.args.p_status,'announced');assert.equal(call.args.p_query,'Former');assert.equal(call.args.p_offset,24);assert.equal(call.args.p_limit,25);assert.equal(result.ships.length,24);assert.equal(result.hasMore,true)});
test('company facets are independent of loaded page and fail honestly',async()=>{const companies=await service.getCruiseOperators({rpc:async(name,args)=>{assert.equal(name,'get_cruise_operators_v1');return{data:[{id:'line-a',name:'Line A'},{id:'line-b',name:'Line B'}],error:null}}});assert.equal(companies.length,2);for(const data of [null,[{id:'a',name:'A'},{id:'a',name:'A'}],[{id:'',name:'bad'}]])await assert.rejects(()=>service.getCruiseOperators({rpc:async()=>({data,error:null})}),/unavailable/)});
test('featured ships use approved stable identities and active filters, and disappear during name search',async()=>{let calls=0;const client={rpc:async(_,args)=>{calls++;assert.equal(args.p_operator_id,'msc-cruises');assert.equal(args.p_kind,'ocean');assert.equal(args.p_status,'operating');assert.equal(args.p_offset,0);assert.deepEqual(Array.from(args.p_ship_ids),Array.from(featured.FEATURED_CRUISE_SHIP_IDS));return{data:[detail],error:null}}};assert.equal((await service.getFeaturedCruiseShips({operatorId:'msc-cruises',kind:'ocean'},client)).length,1);assert.equal((await service.getFeaturedCruiseShips({query:'Prima'},client)).length,0);assert.equal(calls,1);assert.equal(new Set(featured.FEATURED_CRUISE_SHIP_IDS).size,6)});
test('missing v2 RPC fails instead of silently dropping company scope',async()=>{let calls=0;await assert.rejects(()=>service.searchCruiseShips({operatorId:'line-a'},{rpc:async name=>{calls++;assert.equal(name,'search_cruise_ships_v2');return{data:null,error:{code:'PGRST202'}}}}),/unavailable/);assert.equal(calls,1)});
test('browser Back filter state roundtrips stable IDs separately from text and rejects malformed inputs',()=>{const f={query:'A & B',kind:'river',status:'announced',operatorId:'royal-caribbean-international'};assert.deepEqual(JSON.parse(JSON.stringify(state.readCruiseDirectoryQuery(state.cruiseDirectoryQuery(f)))),f);const parsed=state.readCruiseDirectoryQuery({company:'<script>',kind:['river'],q:['x'],status:'retired'});assert.equal(parsed.operatorId,'');assert.equal(parsed.kind,'');assert.equal(parsed.query,'');assert.equal(parsed.status,'operating')});
