/** Local fixtures only. Every nonlocal browser request is blocked; no real writes. */
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict'),{spawn}=require('child_process'),puppeteer=require('puppeteer');
const root=path.resolve(__dirname,'../..'),out='/private/tmp/tavvy-cruise-filters-20260921/browser',port=3880,web=3881,base=`http://127.0.0.1:${web}`;
const ids=['df0fda09-7eb9-5a84-b6a0-30e309490456','e85fe7b0-e064-58fb-9551-7ebcaab0869a','2aa9e45d-8331-51ef-a800-1ba7547fa6d0','2b39fc3d-e069-50ec-9159-30d5aeb11814','daa9d529-d06e-5d5b-8e29-8d56b5238a33','655d958e-d185-53b7-a12b-b6fc54091a2c'];
const source={id:'s',url:'https://example.invalid/ship',publisher:'Fixture',checked_at:'2026-09-20',source_type:'operator'};
const names=['Icon of the Seas','MSC World America','Disney Wish','Carnival Celebration','Norwegian Prima','Wonder of the Seas'],ops=['royal-caribbean-international','msc-cruises','disney-cruise-line','carnival-cruise-line','norwegian-cruise-line','royal-caribbean-international'];
const opNames={'royal-caribbean-international':'Royal Caribbean International','msc-cruises':'MSC Cruises','disney-cruise-line':'Disney Cruise Line','carnival-cruise-line':'Carnival Cruise Line','norwegian-cruise-line':'Norwegian Cruise Line','alpha':'Fixture Alpha Line','river':'Fixture River Line'};
const make=(id,name,operator,kind='ocean',status='operating')=>({ship:{id,universe_id:id,slug:name.toLowerCase().replaceAll(/[^a-z0-9]+/g,'-'),name,operator_id:operator,operator_name:opNames[operator],kind,operating_status:status,publication_status:'published',identity_verified:true,overnight_public_cruise:true,status_source_ids:['s'],imo:null,eni:null,official_url:null,name_history:[],facts:[],cabin_categories:[],photo:null},sources:[source],venues:[]});
const ships=[...ids.map((id,i)=>make(id,names[i],ops[i])),...Array.from({length:30},(_,i)=>make(`01900000-0000-4000-8000-${String(i+1).padStart(12,'0')}`,`Royal Fixture ${String(i+1).padStart(2,'0')}`,'royal-caribbean-international')),make('01900000-0000-4000-8000-000000000080','Fixture River','river','river'),make('01900000-0000-4000-8000-000000000081','MSC Future','msc-cruises','ocean','announced'),...Array.from({length:30},(_,i)=>make(`01900000-0000-4000-8000-${String(i+100).padStart(12,'0')}`,`Alpha Fixture ${i}`,'alpha'))];
let facetFail=false,searchFail=false,delayRoyal=false;const searches=[],unexpected=[];
const server=http.createServer(async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','*');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');if(req.method==='OPTIONS'){res.end();return}let raw='';for await(const chunk of req)raw+=chunk;let data={};try{data=JSON.parse(raw||'{}')}catch{}const url=new URL(req.url,'http://localhost'),name=url.pathname.split('/').pop(),send=(v,status=200)=>{res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(v))};
 if(name==='get_cruise_operators_v1')return facetFail?send({message:'fixture outage'},503):send(Object.entries(opNames).map(([id,name])=>({id,name})));
 if(name==='search_cruise_ships_v2'){searches.push(data);if(searchFail)return send({message:'fixture unavailable'},503);const rows=ships.filter(({ship:s})=>s.operating_status===data.p_status&&(!data.p_kind||s.kind===data.p_kind)&&(!data.p_operator_id||s.operator_id===data.p_operator_id)&&(!data.p_ship_ids||data.p_ship_ids.includes(s.id))&&(!data.p_query||`${s.name} ${s.operator_name}`.toLowerCase().includes(data.p_query.toLowerCase()))).sort((a,b)=>data.p_ship_ids?data.p_ship_ids.indexOf(a.ship.id)-data.p_ship_ids.indexOf(b.ship.id):a.ship.name.localeCompare(b.ship.name));const result=rows.slice(data.p_offset,data.p_offset+data.p_limit);if(delayRoyal&&data.p_operator_id==='royal-caribbean-international')return setTimeout(()=>send(result),1200);return send(result)}
 if(name==='get_cruise_ship_v1')return send(ships.find(s=>s.ship.slug===data.p_slug)||null);
 if(name==='get_cruise_universe_evidence_v1')return send({snapshot:'fixture',total:0,visits:[]});
 if(name==='get_cruise_universe_reviews_v1')return send({total:0,reviews:[]});
 if(req.method!=='GET'){unexpected.push(name);return send({message:'unexpected write blocked'},403)}return send([]);
});
(async()=>{fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(port,'127.0.0.1',r));const log=fs.openSync(out+'/server.log','w');const dev=spawn(process.execPath,[path.join(root,'node_modules/next/dist/bin/next'),'dev','-p',String(web)],{cwd:root,env:{...process.env,NEXT_PUBLIC_SUPABASE_URL:`http://127.0.0.1:${port}`,NEXT_PUBLIC_SUPABASE_ANON_KEY:'local-fixture-key'},stdio:['ignore',log,log]});let browser;
 try{for(let i=0;i<100;i++){try{const r=await fetch(base+'/app/cruises');if(r.ok)break}catch{}await new Promise(r=>setTimeout(r,300))}
 browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewport({width:390,height:844});await page.setRequestInterception(true);page.on('request',req=>{const u=new URL(req.url());if(['http:','https:'].includes(u.protocol)&&!['127.0.0.1','localhost'].includes(u.hostname))return req.abort();req.continue()});await page.evaluateOnNewDocument(()=>{localStorage.setItem('tavvy-locale','en');localStorage.setItem('@tavvy_theme_mode','light')});
 const visit=url=>page.goto(base+url,{waitUntil:'networkidle2'}),click=async text=>{await page.waitForFunction(t=>[...document.querySelectorAll('button')].some(e=>e.textContent.trim()===t),{},text);await page.evaluate(t=>[...document.querySelectorAll('button')].find(e=>e.textContent.trim()===t).click(),text)},waitRows=async operator=>page.waitForFunction(op=>{const rows=[...document.querySelectorAll('.ships .ship')];return rows.length&&rows.every(e=>e.textContent.includes(op))},{},operator),shot=async name=>{assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no horizontal overflow');await page.screenshot({path:out+'/'+name+'.png',fullPage:true})};
 await visit('/app/cruises');await page.waitForSelector('.featured .ship');assert.equal(await page.$$eval('.featured .ship',rows=>rows.length),6);assert.equal(await page.$$eval('.ships .ship',rows=>rows.length),24);const geometry=await page.evaluate(()=>({padding:getComputedStyle(document.querySelector('.ships .ship>div:last-child')).padding,placeholder:document.querySelector('.ships .placeholder').getBoundingClientRect().height,compact:document.querySelector('.featured .placeholder').getBoundingClientRect().height}));assert.deepEqual(geometry,{padding:'18px',placeholder:130,compact:88});await shot('phone-default-featured');
 await click('All cruise lines');await page.type('[aria-label="Search cruise lines"]','MSC');assert.equal(await page.$$eval('.company-options button',rows=>rows.length),2);await click('MSC Cruises');await waitRows('MSC Cruises');assert(new URL(page.url()).searchParams.get('company')==='msc-cruises');await page.waitForFunction(()=>document.querySelectorAll('.featured .ship').length===1);assert.equal(await page.$$eval('.featured .ship',rows=>rows.length),1);await shot('phone-msc-filter');await click('MSC Cruises');await page.evaluate(()=>[...document.querySelectorAll('.company-options button')].find(e=>e.textContent==='MSC Cruises').click());await new Promise(r=>setTimeout(r,400));await waitRows('MSC Cruises');
 await page.click('.ships .ship');await page.waitForFunction(()=>location.pathname.includes('msc-world-america'));await page.goBack({waitUntil:'networkidle2'});await waitRows('MSC Cruises');assert.equal(await page.$eval('.company-toggle',e=>e.textContent),'MSC Cruises');
 await page.select('[aria-label="Cruise type"]','river');await page.waitForFunction(()=>document.body.innerText.includes('No verified ships match these filters.'));assert.equal(await page.$$('.featured .ship').then(a=>a.length),0);await page.select('[aria-label="Cruise type"]','ocean');await click('Announced ships');await page.waitForFunction(()=>document.querySelector('.ships')?.textContent.includes('MSC Future'));assert.equal(searches.at(-1).p_status,'announced');assert.equal(searches.at(-1).p_operator_id,'msc-cruises');await shot('phone-combined-announced');
 await visit('/app/cruises?company=royal-caribbean-international&kind=ocean');await waitRows('Royal Caribbean International');await click('Load more ships');await page.waitForFunction(()=>document.querySelectorAll('.ships .ship').length===32);assert(searches.some(s=>s.p_offset===24&&s.p_operator_id==='royal-caribbean-international'));
 await page.type('[aria-label="Search ship or cruise line"]','Wonder',{delay:25});await page.waitForFunction(()=>document.querySelectorAll('.ships .ship').length===1);assert.equal(await page.$$('.featured .ship').then(a=>a.length),0);assert.equal(searches.at(-1).p_query,'Wonder');await shot('phone-name-with-company');
 delayRoyal=true;await visit('/app/cruises?company=royal-caribbean-international');await click('Royal Caribbean International');await click('MSC Cruises');await waitRows('MSC Cruises');await new Promise(r=>setTimeout(r,1600));await waitRows('MSC Cruises');delayRoyal=false;
 facetFail=true;await visit('/app/cruises');await page.waitForFunction(()=>document.body.innerText.includes('Cruise lines are temporarily unavailable'));await shot('phone-facet-error');facetFail=false;
 searchFail=true;await visit('/app/cruises?company=msc-cruises');await page.waitForFunction(()=>document.body.innerText.includes('Cruise information is temporarily unavailable'));assert(!(await page.$eval('body',e=>e.innerText)).includes('No verified ships match these filters.'));searchFail=false;
 await page.setViewport({width:1365,height:900});await visit('/app/cruises');await page.waitForSelector('.featured .ship');await shot('desktop-featured');assert.deepEqual(errors,[]);assert.deepEqual(unexpected,[]);const result={status:'PASS',checks:16,errors,unexpectedWrites:unexpected,requests:searches.length,scope:'Mocked local browser, not production or native UI'};fs.writeFileSync(out+'/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }catch(e){if(browser){const pages=await browser.pages();const page=pages.at(-1);await page.screenshot({path:out+'/failure.png',fullPage:true});fs.writeFileSync(out+'/failure.txt',await page.$eval('body',e=>e.innerText))}throw e}finally{if(browser)await browser.close();dev.kill('SIGTERM');await new Promise(r=>server.close(r));fs.closeSync(log)}})().catch(e=>{console.error(e.message);process.exitCode=1});
