const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),ts=require('typescript'),path=require('path');
process.env.NEXT_PUBLIC_SUPABASE_URL='https://fixture.invalid';process.env.SUPABASE_SERVICE_ROLE_KEY='fixture-service';process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY='fixture-public';
const root=path.resolve(__dirname,'../..'),id='77000300-0000-4000-8000-000000000016',author='77000300-0000-4000-8000-000000000003',owner='77000300-0000-4000-8000-000000000001';
function fixture(failedRead=false,linkedPlace=false){const calls=[];class Query{constructor(role,table){this.role=role;this.table=table;this.op='read'}select(fields,opts={}){this.fields=fields;this.options=opts;return this}eq(){return this}neq(){return this}single(){return this}insert(payload){this.op='insert';this.payload=payload;return this}update(){this.op='update';return this}then(resolve){calls.push({role:this.role,table:this.table,op:this.op,fields:this.fields,head:this.options?.head,payload:this.payload});let result={data:null,error:null};if(this.role==='public'){result=failedRead?{data:null,error:{message:'fixture read denied'},count:null}:this.options?.head?{data:null,error:null,count:linkedPlace?(this.table==='ecard_endorsement_signals'?2:3):0}:{data:[],error:null}}else if(this.table==='digital_cards'&&this.op==='read')result={data:{user_id:owner,place_id:linkedPlace?'77000300-0000-4000-8000-000000000011':null,professional_category:'universal',tap_count:9},error:null};else if(this.table==='profiles')result={data:{zip_code:null},error:null};else if(this.table==='ecard_endorsements'&&this.op==='insert')result={data:{id:'77000300-0000-4000-8000-000000000035'},error:null};return Promise.resolve(result).then(resolve)}}
 const exports={};const client=(role)=>({from:table=>new Query(role,table),auth:{getUser:async()=>({data:{user:{id:author}},error:null})}});
 const code=ts.transpileModule(fs.readFileSync(path.join(root,'pages/api/ecard/endorse.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
 new Function('require','exports',code)(name=>{if(name==='@supabase/supabase-js')return{createClient:(url,key,opts)=>{if(opts){assert.equal(key,'fixture-public');assert.equal(opts.auth.persistSession,false);return client('public')}return client(key==='fixture-service'?'writer':'auth')}};if(name.endsWith('/geoip'))return{getClientIp:()=>null,resolveIpGeo:async()=>({})};throw Error(name)},exports);
 return{handler:exports.default,calls};}
async function run(fail,linkedPlace=false){const f=fixture(fail,linkedPlace);let status,body;await f.handler({method:'POST',body:{cardId:id,signals:['77000300-0000-4000-8000-000000000040'],note:'Fixture'},headers:{authorization:'Bearer fixture'},cookies:{}},{status(value){status=value;return this},json(value){body=value;return this}});return{...f,status,body};}
test('confirmed zero public total remains zero; service writer never reads public aggregates',async()=>{const result=await run(false);assert.equal(result.status,200);assert.equal(result.body.endorsementCount,0);assert.equal(result.body.evidenceStatus,'ready');assert.deepEqual(result.body.topEndorsementTags,[]);assert(result.calls.some(c=>c.role==='writer'&&c.op==='insert'));assert(result.calls.filter(c=>c.head).every(c=>c.role==='public'));assert(!result.calls.some(c=>c.role==='writer'&&c.table==='ecard_endorsement_signals'&&c.op==='read'));});
test('saved endorsement plus failed public count read returns explicit unavailable, no invented count or retryable save failure',async()=>{const result=await run(true);assert.equal(result.status,200);assert.equal(result.body.success,true);assert.equal(result.body.endorsementCount,null);assert.equal(result.body.topEndorsementTags,null);assert.equal(result.body.evidenceStatus,'unavailable');});

test('linked business endorsement preserves primary save/public totals without duplicate visit or place taps',async()=>{const result=await run(false,true);assert.equal(result.status,200);assert.equal(result.body.success,true);assert.equal(result.body.endorsementCount,5);assert.equal(result.body.evidenceStatus,'ready');const inserts=result.calls.filter(c=>c.op==='insert');assert.deepEqual(inserts.map(c=>c.table),['ecard_endorsements','ecard_endorsement_signals']);assert.equal(inserts[0].payload.endorser_id,author);assert.equal(inserts[1].payload[0].card_id,id);assert(!inserts.some(c=>['place_reviews','place_review_signal_taps'].includes(c.table)));assert(result.calls.some(c=>c.role==='public'&&c.table==='place_review_signal_taps'&&c.head));});
