/** Local fixtures only. All remote requests are intercepted; no customer writes. */
const puppeteer=require('puppeteer'),fs=require('node:fs'),assert=require('node:assert/strict');
const base=process.env.TAVVY_ECARD_BASE||'http://127.0.0.1:3838',out=process.env.TAVVY_ECARD_QA||'/private/tmp/tavvy-ecard-entitlements-20260921/browser';
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,protocolTimeout:30000,args:['--no-sandbox']});const p=await b.newPage();await p.setViewport({width:390,height:844});await p.setBypassServiceWorker(true);const uid='00000000-0000-4000-8000-000000000083',cid='00000000-0000-4000-8000-000000000098';const user={id:uid,email:'qa@example.invalid',aud:'authenticated',role:'authenticated',app_metadata:{},user_metadata:{}};
let card={id:cid,user_id:uid,full_name:'Synthetic Free Card',slug:'local-fixture',template_id:'basic',color_scheme_id:'light',theme:'classic',is_published:false,is_active:true,gallery_images:[],videos:[],featured_socials:[]},links=Array.from({length:6},(_,i)=>({id:'00000000-0000-4000-8000-'+String(i+1).padStart(12,'0'),card_id:cid,platform:'website',title:'Link '+(i+1),url:'https://example.invalid/'+i,is_active:i!==0,sort_order:i}));let failRead=false,failReplace=false;const writes=[],errors=[],checks=[];checks.push=function(...items){Array.prototype.push.apply(this,items);fs.writeFileSync(out+'/progress.json',JSON.stringify({checks:this,errors},null,2));return this.length;};
await p.evaluateOnNewDocument(user=>{localStorage.setItem('sb-scasgwrikoqdwlwlwcff-auth-token',JSON.stringify({access_token:'qa.session.token',refresh_token:'qa-refresh',expires_at:Math.floor(Date.now()/1000)+3600,expires_in:3600,token_type:'bearer',user}));localStorage.setItem('@tavvy_theme_mode','light');},user);
p.on('dialog',dialog=>dialog.accept());p.on('pageerror',e=>errors.push(e.message));await p.setRequestInterception(true);p.on('request',r=>{const u=new URL(r.url());if(u.origin===base||u.protocol==='data:'||u.protocol==='blob:')return r.continue();const send=(x,status=200)=>r.respond({status,contentType:'application/json',headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*'},body:JSON.stringify(x)});if(r.method()==='OPTIONS')return send({});if(u.pathname==='/auth/v1/user')return send(user);if(u.pathname.endsWith('/get_my_ecard_entitlement'))return send({is_pro:false,status:'free'});if(u.pathname.endsWith('/get_ecard_links_v1')){const args=JSON.parse(r.postData()||'{}');return send(failRead?{message:'fixture unavailable'}:links.filter(x=>args.p_include_inactive||x.is_active===true),failRead?503:200);}if(u.pathname.endsWith('/replace_ecard_links')){const args=JSON.parse(r.postData());if(failReplace)return send({message:'This link update is too large to save at once. Your saved links are unchanged.'},400);links=args.p_links.map((x,i)=>({...x,id:x.id||String(i),card_id:cid}));writes.push('links');return send(null);}if(u.pathname.endsWith('/digital_cards')){if(r.method()==='GET')return send(card);const data=JSON.parse(r.postData()||'{}');card={...card,...data};writes.push(data.is_published?'publish':'card');return send(card);}if(r.method()!=='GET')return send({message:'unmatched write blocked'},403);return send(null);});
const visit=url=>p.goto(base+url,{waitUntil:'networkidle2',timeout:90000});const click=async text=>{await p.waitForFunction(t=>[...document.querySelectorAll('button,summary')].some(n=>n.textContent.trim()===t),{},text);await p.evaluate(t=>[...document.querySelectorAll('button,summary')].find(n=>n.textContent.trim()===t).click(),text);};
try{
await visit('/app/ecard/new');await p.waitForSelector('[aria-label="Design category"]');await p.select('[aria-label="Design plan"]','free');for(const category of ['personal-creators','food-mobile','real-estate','faith-community','business-services','politics-public-service']){await p.select('[aria-label="Design category"]',category);await p.waitForFunction(()=>document.querySelectorAll('.gallery-slide').length>0&&!document.querySelector('button.continue').disabled);checks.push(category+' has a usable Free design');}
assert.equal(await p.$eval('.gallery-navigation',e=>e.innerText.includes('Politician Card')),true);await p.waitForSelector('iframe');await p.evaluate(()=>window.scrollTo(0,0));await p.screenshot({path:out+'/free-politician-phone.png',fullPage:true});await p.select('[aria-label="Design plan"]','all');await p.click('[aria-label="Patriot Red · Pro"]');assert.equal(await p.$eval('[aria-label="Patriot Red · Pro"]',e=>e.getAttribute('aria-disabled')),'true');assert.equal(await p.$eval('[aria-label="Classic Blue"]',e=>e.getAttribute('aria-pressed')),'true');checks.push('Other politician palette stays locked without resetting selected Free choice');await p.click('[aria-label="Classic Blue"]');await p.waitForFunction(()=>!document.querySelector('button.continue').disabled);
await p.select('[aria-label="Design category"]','real-estate');await p.waitForFunction(()=>!document.querySelector('button.continue').disabled);await p.evaluate(()=>window.scrollTo(0,0));await p.screenshot({path:out+'/free-agent-phone.png',fullPage:true});await click('Use this template');await p.type('input[name=fullName]','Synthetic Real Estate');await click('Create draft');await p.waitForSelector('.card-studio');assert.equal(card.template_id,'pro-realtor');assert.equal(card.color_scheme_id,'warm-neutral');assert.equal(card.is_published,false);checks.push('Free Agent draft reaches actual editor');await click('Publish');await p.waitForFunction(()=>document.body.innerText.includes('Your card is published and ready to share.'));assert.equal(card.is_published,true);checks.push('Free Agent publishes with six links');
card={...card,template_id:'politician-generic',color_scheme_id:'classic-blue',is_published:false};await visit(`/app/ecard/${cid}/edit`);await p.waitForSelector('[data-link-id]');assert.equal(await p.$$eval('[data-link-id]',n=>n.length),6);assert(await p.$eval('body',e=>e.innerText.includes('No plan-based link limit')));await click('Add link');await p.waitForSelector('[role=dialog],input[placeholder]');await p.screenshot({path:out+'/free-links-add-phone.png'});await p.keyboard.press('Escape');await visit(`/app/ecard/${cid}/edit`);await p.waitForSelector('[data-link-id]');await p.$eval('[aria-label="Website link title"]',e=>{e.focus();e.select()});await p.type('[aria-label="Website link title"]','Hidden retained');await p.waitForFunction(()=>document.body.innerText.includes('All changes saved'));assert.equal(links.length,6);assert.equal(links[0].is_active,false);checks.push('Six links save with hidden identity preserved');await click('Publish');await p.waitForFunction(()=>document.body.innerText.includes('Your card is published and ready to share.'));checks.push('Free Politician publishes without upsell');
card={...card,is_published:false};failReplace=true;await visit(`/app/ecard/${cid}/edit`);await p.waitForSelector('[data-link-id]');await p.type('[aria-label="Website link title"]',' changed');const before=writes.filter(x=>x==='publish').length;await click('Publish');await p.waitForFunction(()=>document.body.innerText.includes('too large'));assert.equal(writes.filter(x=>x==='publish').length,before);assert.equal(links[0].title,'Hidden retained');checks.push('Resource failure blocks publication and preserves saved links');await p.screenshot({path:out+'/resource-error-phone.png'});failReplace=false;
failRead=true;await visit(`/app/ecard/${cid}/edit`);await p.waitForFunction(()=>document.body.innerText.includes('Retry loading'));assert.equal(await p.$('.card-studio'),null);checks.push('Failed full-list read never creates editable empty list');failRead=false;
card={...card,color_scheme_id:'patriot-red'};await visit(`/app/ecard/${cid}/edit`);await p.waitForSelector('.card-studio');await click('Publish');await p.waitForSelector('[role=dialog]');checks.push('Paid palette remains paywalled on editor publication');
await visit('/app/ecard/premium');assert(await p.$eval('body',e=>e.innerText.includes('no plan-based link limit')));assert(await p.$eval('body',e=>e.innerText.includes('4.99')&&e.innerText.includes('39.99')));assert.equal(await p.$eval('body',e=>e.innerText.includes('Unlimited Links')),false);checks.push('Offer shows Free links and unchanged prices');await p.screenshot({path:out+'/offer-phone.png',fullPage:true});
await p.setViewport({width:1440,height:1000});await p.screenshot({path:out+'/offer-desktop.png',fullPage:true});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));checks.push('Desktop offer has no horizontal overflow');assert.deepEqual(errors,[]);fs.writeFileSync(out+'/result.json',JSON.stringify({pass:true,checks,mockWrites:writes.length,errors},null,2));console.log(JSON.stringify({pass:true,checks:checks.length,mockWrites:writes.length}));
}catch(e){fs.writeFileSync(out+'/failure.json',JSON.stringify({error:String(e),checks,errors},null,2));try{await p.screenshot({path:out+'/failure.png',fullPage:false})}catch{}throw e}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
