/** Mock-only browser regression: no request writes a real card or publishes one. */
const puppeteer=require('puppeteer'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const base=process.env.TAVVY_ECARD_BASE||'http://127.0.0.1:3048',out=process.env.TAVVY_ECARD_QA||'/private/tmp/tavvy-ecard-pro-extras-qa';
const uid='00000000-0000-4000-8000-000000000083',cid='00000000-0000-4000-8000-000000000098';
const originalCard={id:cid,user_id:uid,full_name:'Jordan Rivera',slug:'qa-card',title:'Designer',bio:'Thoughtful work for local businesses.',template_id:'basic',theme:'classic',gradient_color_1:'#8A05BE',gradient_color_2:'#667eea',is_published:false,is_active:true,featured_socials:[],gallery_images:[],videos:[],profile_photo_url:null,phone:'+1 555 0100',show_licensed_badge:true,badge_approval_status:'approved'};
const originalLinks=[{id:'00000000-0000-4000-8000-000000000091',card_id:cid,platform:'website',title:'My portfolio',url:'https://example.invalid/portfolio',value:'portfolio-value',sort_order:0,is_active:true},{id:'00000000-0000-4000-8000-000000000092',card_id:cid,platform:'instagram',icon:'logo-instagram',title:'Instagram updates',url:'https://example.invalid/instagram',sort_order:1,is_active:true},{id:'00000000-0000-4000-8000-000000000093',card_id:cid,platform:'phone',title:'Private number',url:'tel:15550101',value:'15550101',sort_order:2,is_active:null}];
const clone=v=>JSON.parse(JSON.stringify(v));
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});
 const page=await browser.newPage();await page.setViewport({width:390,height:844});await page.setBypassServiceWorker(true);const errors=[],writes=[],uploads=[];let card=clone(originalCard),links=clone(originalLinks),failSave=false,failLinks=false,failPlan=false,pro=true,createdPayload;
 const user={id:uid,email:'ecard@example.invalid',aud:'authenticated',role:'authenticated',app_metadata:{},user_metadata:{}};
 await page.evaluateOnNewDocument(session=>{localStorage.setItem('sb-scasgwrikoqdwlwlwcff-auth-token',JSON.stringify(session));if(!localStorage.getItem('@tavvy_theme_mode'))localStorage.setItem('@tavvy_theme_mode','light');},{access_token:'qa.session.token',refresh_token:'qa-refresh',expires_at:Math.floor(Date.now()/1000)+3600,expires_in:3600,token_type:'bearer',user});
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.setRequestInterception(true);page.on('request',async r=>{
  const u=new URL(r.url());if(!u.hostname.endsWith('.supabase.co'))return r.continue();
  const respond=(data,status=200)=>r.respond({status,contentType:'application/json',headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*'},body:JSON.stringify(data)});
  if(r.method()==='OPTIONS')return respond({});if(u.pathname==='/auth/v1/user')return respond(user);
  if(u.pathname.endsWith('/get_my_ecard_entitlement'))return respond(failPlan?{message:'mock plan unavailable'}:{is_pro:pro,is_super_admin:false,ecard_active:true,status:pro?'active':'free',plan_type:pro?'pro':'free',current_period_end:null},failPlan?503:200);
  if(u.pathname.endsWith('/digital_cards')){if(r.method()==='GET')return respond(card);const body=JSON.parse(r.postData()||'{}');writes.push({type:r.method()==='POST'?'create':body.is_published!==undefined?'publication':'card',body});if(failSave)return respond({message:'forced save failure'},500);if(r.method()==='POST'){createdPayload=body;card={...card,...body};}else card={...card,...body};return respond(card);}
  if(u.pathname.endsWith('/digital_card_links'))return respond(failLinks?{message:'mock link read unavailable'}:links,failLinks?503:200);
  if(u.pathname.endsWith('/replace_ecard_links')){const body=JSON.parse(r.postData()||'{}');writes.push({type:'links',body});if(failSave)return respond({message:'forced links failure'},500);links=body.p_links;return respond(null);}
  if(u.pathname.includes('/storage/') && r.method()!=='GET'){uploads.push(u.pathname);return respond({message:'Uploads blocked by test'},403);}if(r.method()!=='GET')return respond({message:'Unrecognized write blocked'},403);return respond(null);
 });
 const visit=async route=>{await page.goto(base+route,{waitUntil:'networkidle2',timeout:60000});};
 const click=async text=>{await page.waitForFunction(text=>[...document.querySelectorAll('button,summary')].some(e=>e.textContent.trim()===text),{},text);await page.evaluate(text=>{const e=[...document.querySelectorAll('button,summary')].find(e=>e.textContent.trim()===text);e.click()},text);};
 const field=async(selector,value)=>{await page.waitForSelector(selector);await page.focus(selector);await page.$eval(selector,e=>e.select());await page.type(selector,value);};
 const noOverflow=async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'horizontal page overflow');
 const waitSaved=()=>page.waitForFunction(()=>document.body.innerText.includes('All changes saved'));
 try{
  pro=false;links=[];await visit(`/app/ecard/${cid}/edit`);await page.waitForSelector('.card-studio');await click('More features');await click('Media');
  assert(await page.$eval('#section-media',e=>e.innerText.includes('Gallery · Pro')&&e.innerText.includes('Videos · Pro')));
  await page.evaluate(()=>{window.__pickerClicks=0;document.querySelector('#section-media input[type=file]').addEventListener('click',()=>window.__pickerClicks++);});
  const beforeFree=writes.length;await click('Add Images');await page.waitForSelector('[data-pro-extra-notice]');assert.equal(await page.evaluate(()=>window.__pickerClicks),0,'Free addition blocked before file chooser');await click('Keep editing');
  await click('Add Video');await page.waitForSelector('[data-pro-extra-notice]');assert.equal(await page.$('input[type=url]'),null,'Free addition blocked before video URL or upload modal');await page.waitForFunction(()=>Number(getComputedStyle(document.querySelector('#section-media-content')).opacity)>.99);await page.screenshot({path:out+'/free-media-before-add.png',fullPage:true});await click('Keep editing');
  const png=out+'/fixture.png';fs.writeFileSync(png,Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jLZUAAAAASUVORK5CYII=','base64'));await (await page.$('#section-media input[type=file]')).uploadFile(png);await page.waitForSelector('[data-pro-extra-notice]');assert.equal(await page.$$eval('[aria-label="Remove gallery photo"]',e=>e.length),0,'direct input dispatch cannot add Free gallery content');assert.equal(writes.length,beforeFree);assert.deepEqual(uploads,[]);
  // Every supported extra blocks NEW Free publication in both entry points, without touching saved data.
  const variants=[{gallery_images:[{id:'g',uri:base+'/images/demo-trattoria/pasta.jpg'}]},{videos:[{type:'external',url:'https://example.invalid/video.mp4'}]},{youtube_video_id:'legacy-id'},{form_block:{}},{pro_credentials:{licenseNumber:'0'}}];
  for(const extra of variants){card={...clone(originalCard),...extra};await visit(`/app/ecard/${cid}/edit`);await page.waitForSelector('.card-studio');const before=writes.length;await click('Publish');await page.waitForSelector('[role=dialog]');assert(await page.$eval('[role=dialog]',e=>e.innerText.includes('Pro')));assert.equal(writes.length,before);assert.equal(card.is_published,false);}
  card={...clone(originalCard),videos:[{type:'external',url:'https://example.invalid/video.mp4'}]};await visit(`/app/ecard/${cid}/preview`);const beforeLegacy=writes.length;await click('Publish');await page.waitForFunction(()=>document.body.innerText.includes('Premium Features Detected'));assert.equal(writes.length,beforeLegacy,'legacy full preview uses actual videos gate');
  // Empty credentials, disabled configured form and hidden links never block a clean Free card.
  card={...clone(originalCard),pro_credentials:{id:'metadata',licensed:false,yearsInBusiness:0},form_block:{enabled:false,formType:'webhook',webhookUrl:'https://example.invalid/keep'}};links=clone(originalLinks);await visit(`/app/ecard/${cid}/edit`);await page.waitForSelector('.card-studio');await click('Publish');await page.waitForFunction(()=>document.body.innerText.includes('Your card is published and ready to share.'));assert.equal(card.is_published,true);
  // Grandfathered published content stays visible and removable; sharing never rechecks extras.
  const retainedForm={enabled:true,formType:'webhook',webhookUrl:'https://example.invalid/keep',fields:[{id:'email',label:'Email'}]};card={...clone(originalCard),template_id:'business-card',is_published:true,form_block:retainedForm,gallery_images:[{id:'g',url:base+'/images/demo-trattoria/pasta.jpg',caption:'Kept caption'}],videos:[{type:'external',url:'https://example.invalid/retained.mp4'}],pro_credentials:{licenseNumber:'L-1'}};await visit(`/app/ecard/${cid}/edit`);await page.waitForSelector('.card-studio');await click('Share & QR');await page.waitForSelector('[role=dialog]');assert(await page.$eval('[role=dialog]',e=>e.innerText.includes('Share your card')));await page.keyboard.press('Escape');await click('More features');await click('Media');assert.equal(await page.$$eval('[aria-label="Remove gallery photo"]',e=>e.length),1);assert.equal(await page.$$eval('[aria-label="Remove video"]',e=>e.length),1);
  await page.click('[aria-label="Remove gallery photo"]');await waitSaved();assert.equal(card.gallery_images.length,0);assert.equal(card.is_published,true);assert.equal(card.pro_credentials.licenseNumber,'L-1');assert.equal(card.videos[0].url,'https://example.invalid/retained.mp4');await click('Professional details & contact form');await page.click('[aria-label="Show contact form on card"]');await waitSaved();assert.equal(card.form_block.enabled,false);assert.equal(card.form_block.webhookUrl,retainedForm.webhookUrl);const beforeEnable=writes.length;await page.click('[aria-label="Show contact form on card"]');await page.waitForSelector('[data-pro-extra-notice]');assert.equal(await page.$eval('[aria-label="Show contact form on card"]',e=>e.getAttribute('aria-checked')),'false');assert.equal(writes.length,beforeEnable);assert.equal(card.is_published,true);await page.screenshot({path:out+'/free-preserved-form.png',fullPage:true});
  // Pro retains the original media creation flow and can enable the saved form.
  pro=true;card={...clone(originalCard),template_id:'business-card',form_block:{...retainedForm,enabled:false}};await visit(`/app/ecard/${cid}/edit`);await page.waitForSelector('.card-studio');await click('More features');await click('Media');const chooser=page.waitForFileChooser();await click('Add Images');await (await chooser).cancel();await click('Add Video');await page.waitForSelector('input[type=url]');await field('input[type=url]','https://www.youtube.com/watch?v=demo123');await page.evaluate(()=>[...document.querySelectorAll('button')].filter(e=>e.textContent.trim()==='Add Video').at(-1).click());await waitSaved();assert.equal(card.videos[0].url,'https://www.youtube.com/watch?v=demo123');await click('Professional details & contact form');await page.click('[aria-label="Show contact form on card"]');await waitSaved();assert.equal(card.form_block.enabled,true);assert.equal(card.form_block.webhookUrl,retainedForm.webhookUrl);await click('Publish');await page.waitForFunction(()=>document.body.innerText.includes('Your card is published and ready to share.'));assert.equal(card.is_published,true);await page.screenshot({path:out+'/pro-extras-enabled.png',fullPage:true});
  await visit('/app/ecard/premium');assert(await page.$eval('.pro-extras-summary',e=>e.innerText.includes('gallery photos')&&e.innerText.includes('professional credentials')));await noOverflow();
  assert.deepEqual(errors,[]);assert.deepEqual(uploads,[]);await noOverflow();const result={status:'PASS',mockWrites:writes.length,errors,uploads,checks:['Free Pro labels before add','Free chooser and direct file input blocked','actual gallery/video/YouTube/form/credential publication gates','legacy full preview gate','default false/zero credentials and disabled forms Free','existing public media preserved/removable','existing public sharing allowed','Free disable form retains configuration; re-enable gated','Pro chooser/video/form/publish works','Pro offer labels; prices unchanged','phone layout'],screenshots:out};fs.writeFileSync(out+'/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }catch(error){await page.screenshot({path:out+'/failure.png',fullPage:true});fs.writeFileSync(out+'/failure.json',JSON.stringify({error:String(error),body:await page.$eval('body',e=>e.innerText),writes,errors,uploads},null,2));throw error;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
