/** Local-only browser fixture. Every remote request is intercepted; no real card writes. */
const puppeteer=require('puppeteer'),assert=require('node:assert/strict'),fs=require('node:fs');
const base=process.env.TAVVY_ECARD_BASE||'http://127.0.0.1:3062',out=process.env.TAVVY_ECARD_QA||'/private/tmp/tavvy-template-chooser-browser';
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage();await page.setViewport({width:390,height:844});await page.setBypassServiceWorker(true);let pro=false,created;const writes=[],errors=[];const user={id:'00000000-0000-4000-8000-000000000083',email:'qa@example.invalid',aud:'authenticated',role:'authenticated',app_metadata:{},user_metadata:{}};
page.on('pageerror',error=>errors.push(error.message));await page.setRequestInterception(true);page.on('request',r=>{const u=new URL(r.url());if(u.origin===base||u.protocol==='data:'||u.protocol==='blob:')return r.continue();const respond=(data,status=200)=>r.respond({status,contentType:'application/json',headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*'},body:JSON.stringify(data)});if(r.method()==='OPTIONS')return respond({});if(u.pathname==='/auth/v1/user')return respond(user);if(u.pathname.endsWith('/get_my_ecard_entitlement'))return respond({is_pro:pro,status:pro?'active':'free',plan_type:pro?'pro':'free'});if(u.pathname.endsWith('/digital_cards')){if(r.method()==='POST'){created=JSON.parse(r.postData());writes.push(created);return respond({...created,id:'00000000-0000-4000-8000-000000000098'});}return respond(created?{...created,id:'00000000-0000-4000-8000-000000000098'}:null);}if(u.pathname.endsWith('/digital_card_links'))return respond([]);if(r.method()!=='GET'){writes.push({blocked:r.url()});return respond({},403);}return respond(null);});
const visit=async route=>page.goto(base+route,{waitUntil:'networkidle2',timeout:90000});const click=async text=>{await page.waitForFunction(text=>[...document.querySelectorAll('button,summary')].some(e=>e.textContent.trim()===text),{},text);await page.evaluate(text=>[...document.querySelectorAll('button,summary')].find(e=>e.textContent.trim()===text).click(),text)};const fits=async()=>assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no horizontal page overflow');
try{
await visit('/ecard/templates');await page.evaluate(()=>localStorage.setItem('@tavvy_theme_mode','light'));await page.reload({waitUntil:'networkidle2'});assert.equal(await page.$$eval('[data-catalog-template]',nodes=>nodes.length),21);assert.equal(await page.$$eval('[data-catalog-scheme]',nodes=>nodes.length),123);await page.waitForSelector('iframe[title="9:16 phone preview"]');assert((await page.$$('iframe')).length<12,'only visible previews mount');const first=await(await page.$('iframe[title="9:16 phone preview"]')).contentFrame();await first.waitForSelector('[data-card-preview]');await first.waitForFunction(()=>[...document.images].filter(i=>i.src.includes('ecard-examples')).every(i=>i.complete&&i.naturalWidth>0),{timeout:60000});assert.deepEqual(await first.evaluate(()=>[innerWidth,innerHeight]),[360,640]);assert(await first.$eval('body',e=>e.innerText.includes('James Chen')));await fits();await page.screenshot({path:out+'/public-gallery-phone.png',fullPage:false});
const href=await page.$eval('[data-catalog-template="biz-traditional"] [data-catalog-scheme="navy-gold"] a',e=>e.getAttribute('href'));assert.equal(href,'/app/ecard/new?template=biz-traditional&scheme=navy-gold');await visit(href);await click('Sign in');await page.waitForFunction(()=>location.pathname.includes('/login'));assert.equal(new URL(page.url()).searchParams.get('redirect'),href,'login preserves exact design/palette');
await page.evaluate(user=>localStorage.setItem('sb-scasgwrikoqdwlwlwcff-auth-token',JSON.stringify({access_token:'qa.session.token',refresh_token:'qa-refresh',expires_at:Math.floor(Date.now()/1000)+3600,expires_in:3600,token_type:'bearer',user})),user);
await visit('/app/ecard/new');await page.waitForSelector('[aria-label="Design category"]');assert.equal(await page.$eval('[aria-label="Design category"]',e=>e.value),'business-services');assert.equal(await page.$$('.gallery-slide').then(x=>x.length),7);assert.equal(await page.$$eval('[aria-label="Design category"] option',x=>x.length),6);await page.screenshot({path:out+'/organized-business-phone.png'});
await page.select('[aria-label="Design category"]','politics-public-service');await page.waitForFunction(()=>document.querySelectorAll('.gallery-slide').length===6);assert(await page.$eval('button.continue',e=>e.disabled));await page.select('[aria-label="Design plan"]','free');await page.waitForFunction(()=>document.body.innerText.includes('No designs match these filters'));assert.equal(await page.$$('.gallery-slide').then(x=>x.length),0);assert(await page.$eval('button.continue',e=>e.disabled));await page.screenshot({path:out+'/politics-free-empty.png'});
await page.select('[aria-label="Design plan"]','all');await page.select('[aria-label="Design category"]','real-estate');await page.waitForFunction(()=>document.querySelectorAll('.gallery-slide').length===1);assert(await page.$eval('button.continue',e=>e.disabled));assert(await page.$eval('.gallery-navigation',e=>e.innerText.includes('Agent Card')));
await visit('/app/ecard/new?template=biz-traditional&scheme=forest-cream');await page.waitForSelector('.template-gallery');assert(await page.$eval('button.continue',e=>e.disabled));await page.select('[aria-label="Design plan"]','free');await page.waitForFunction(()=>!document.querySelector('button.continue').disabled);assert.equal(await page.$$('.schemes [aria-disabled=true]').then(x=>x.length),0);await fits();
await visit('/app/ecard/new?template=biz-traditional&scheme=forest-cream');await page.waitForSelector('.template-gallery');assert(await page.$eval('button.continue',e=>e.disabled),'Free cannot proceed with Pro palette');assert.equal(await page.$eval('[aria-label="Forest & Cream · Pro"]',e=>e.getAttribute('aria-pressed')),'true');await page.click('[aria-label="Navy & Gold"]');await page.waitForFunction(()=>!document.querySelector('button.continue').disabled);await click('Use this template');await page.type('input[name=fullName]','Avery Lane');await page.type('input[name=title]','Creative Director');await click('Change design or color');await page.waitForSelector('.template-gallery');await click('Use this template');assert.equal(await page.$eval('input[name=fullName]',e=>e.value),'Avery Lane');assert.equal(await page.$eval('input[name=title]',e=>e.value),'Creative Director');await click('Create draft');await page.waitForFunction(()=>location.pathname.endsWith('/edit'));assert.equal(writes.length,1);assert.equal(created.template_id,'biz-traditional');assert.equal(created.color_scheme_id,'navy-gold');assert.equal(created.card_type,'business');assert.equal(created.full_name,'Avery Lane');assert.equal(created.title,'Creative Director');assert.equal(created.is_published,false);assert.equal(created.profile_photo_url,undefined);assert.equal(created.phone,undefined);assert.equal(created.email,undefined);assert.equal(created.bio,undefined);assert.equal(created.links,undefined);assert.notEqual(created.gradient_color_1,created.gradient_color_2,'chosen palette preserved');assert(created.banner_image_url.endsWith('/soft-folds.svg'),'only reusable decoration copied');
await page.waitForSelector('.card-studio');await click('Design');await click('Templates & colors');await page.waitForSelector('[aria-label="Card designs"] iframe');assert.equal(await page.$eval('[aria-label="Card designs"] button[aria-pressed=true]',e=>e.getAttribute('aria-label').startsWith('Classic Card')),true);await fits();
await visit('/app/ecard/new?template=premium-static');await page.waitForSelector('.template-gallery');assert(await page.$eval('button.continue',e=>e.disabled),'Pro preset remains locked and visible');assert(await page.$eval('.gallery-navigation',e=>e.innerText.includes('Portrait Page')));await page.screenshot({path:out+'/locked-preset.png'});
pro=true;await page.reload({waitUntil:'networkidle2'});await page.waitForFunction(()=>!document.querySelector('button.continue').disabled);await page.screenshot({path:out+'/pro-preset.png'});assert(await page.$eval('button.continue',e=>{const r=e.getBoundingClientRect();return r.bottom<=innerHeight&&r.top>=0}),'Continue remains visible on phone');
await visit('/app/ecard/new?template=cover-card');await page.waitForFunction(()=>!document.querySelector('button.continue').disabled);assert.equal(await page.$eval('[aria-label="Design category"]',e=>e.value),'personal-creators');await click('Use this template');assert(await page.$$eval('.card-purpose label',nodes=>nodes.some(label=>label.textContent.trim()==='Personal'&&label.querySelector('input').checked)));await page.evaluate(()=>[...document.querySelectorAll('.card-purpose label')].find(label=>label.textContent.trim()==='Business').querySelector('input').click());await click('Change design or color');await page.$$eval('.schemes button',buttons=>buttons[1].click());await click('Use this template');assert(await page.$$eval('.card-purpose label',nodes=>nodes.some(label=>label.textContent.trim()==='Business'&&label.querySelector('input').checked)));
await visit('/app/ecard/new?template=full-width');await page.waitForFunction(()=>!document.querySelector('button.continue').disabled);assert.equal(await page.$eval('[aria-label="Design category"]',e=>e.value),'food-mobile');await click('Use this template');assert(await page.$$eval('.card-purpose label',nodes=>nodes.some(label=>label.textContent.trim()==='Business'&&label.querySelector('input').checked)));
await visit('/app/ecard/new');await page.waitForSelector('.template-gallery');assert.equal(await page.$('input[name=fullName]'),null,'default is design first');await click('Quick setup');await page.waitForSelector('input[name=fullName]');await click('Choose card type & template');await page.evaluate(()=>[...document.querySelectorAll('button')].find(e=>e.textContent.includes('Politician')&&e.textContent.includes('public servants')).click());await page.type('input[placeholder="Search country..."]','Brazil');await page.evaluate(()=>[...document.querySelectorAll('button')].find(e=>e.textContent.includes('Brazil')&&e.textContent.includes('Brasil')).click());await page.waitForSelector('.template-gallery');assert(await page.$eval('.gallery-navigation',e=>e.innerText.includes('Civic')));await fits();
await visit('/ecard/templates');await page.select('[aria-label="Jump to design"]','full-width');await new Promise(r=>setTimeout(r,1400));assert((await page.$$('iframe')).length<12,'scrolling releases offscreen previews');await page.screenshot({path:out+'/chef-example.png'});await page.setViewport({width:1440,height:1000});await visit('/ecard/templates');await fits();await page.screenshot({path:out+'/public-gallery-desktop.png'});
for(const [locale,categoryLabel,choice] of [['pt','Categoria de design','Negócios e serviços'],['es','Categoría de diseño','Negocios y servicios']]){await page.setViewport({width:390,height:844});await page.evaluate(lang=>localStorage.setItem('tavvy-locale',lang),locale);await visit('/'+locale+'/app/ecard/new');await page.waitForSelector('.browse-filters');assert(await page.$eval('.browse-filters',(e,args)=>e.textContent.includes(args[0])&&e.textContent.includes(args[1]),[categoryLabel,choice]));await fits();await page.screenshot({path:out+'/category-'+locale+'.png'});}
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/result.json',JSON.stringify({status:'PASS',checks:27,mockCreates:writes.length,errors,screenshots:out},null,2));console.log(JSON.stringify({status:'PASS',checks:27,mockCreates:writes.length,errors}));
}catch(error){await page.screenshot({path:out+'/failure.png'});fs.writeFileSync(out+'/failure.json',JSON.stringify({error:String(error),body:await page.$eval('body',e=>e.innerText),writes,errors},null,2));throw error;}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1});
