/** Local fixtures only. All remote requests are intercepted; no customer writes. */
const puppeteer=require('puppeteer'),fs=require('node:fs'),assert=require('node:assert/strict');
const base=process.env.TAVVY_ECARD_BASE||'http://127.0.0.1:3838',out=process.env.TAVVY_ECARD_QA||'/private/tmp/tavvy-ecard-entitlements-20260921/browser';
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,protocolTimeout:30000,args:['--no-sandbox']});const p=await b.newPage();await p.setViewport({width:390,height:844});await p.setBypassServiceWorker(true);const uid='00000000-0000-4000-8000-000000000083',cid='00000000-0000-4000-8000-000000000098';const user={id:uid,email:'qa@example.invalid',aud:'authenticated',role:'authenticated',app_metadata:{},user_metadata:{}};
let card={id:cid,user_id:uid,full_name:'Synthetic Free Card',slug:'local-fixture',template_id:'basic',color_scheme_id:'light',theme:'classic',is_published:false,is_active:true,gallery_images:[],videos:[],featured_socials:[]},links=Array.from({length:6},(_,i)=>({id:'00000000-0000-4000-8000-'+String(i+1).padStart(12,'0'),card_id:cid,platform:'website',title:'Link '+(i+1),url:'https://example.invalid/'+i,is_active:i!==0,sort_order:i}));let failRead=false,failReplace=false;const writes=[],errors=[],checks=[];checks.push=function(...items){Array.prototype.push.apply(this,items);fs.writeFileSync(out+'/progress.json',JSON.stringify({checks:this,errors},null,2));return this.length;};
await p.evaluateOnNewDocument(user=>{localStorage.setItem('sb-scasgwrikoqdwlwlwcff-auth-token',JSON.stringify({access_token:'qa.session.token',refresh_token:'qa-refresh',expires_at:Math.floor(Date.now()/1000)+3600,expires_in:3600,token_type:'bearer',user}));localStorage.setItem('@tavvy_theme_mode','light');},user);
p.on('dialog',dialog=>dialog.accept());p.on('pageerror',e=>errors.push(e.message));await p.setRequestInterception(true);p.on('request',r=>{const u=new URL(r.url());if(u.origin===base||u.protocol==='data:'||u.protocol==='blob:')return r.continue();const send=(x,status=200)=>r.respond({status,contentType:'application/json',headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*'},body:JSON.stringify(x)});if(r.method()==='OPTIONS')return send({});if(u.pathname==='/auth/v1/user')return send(user);if(u.pathname.endsWith('/get_my_ecard_entitlement'))return send({is_pro:false,status:'free'});if(u.pathname.endsWith('/get_ecard_links_v1')){const args=JSON.parse(r.postData()||'{}');return send(failRead?{message:'fixture unavailable'}:links.filter(x=>args.p_include_inactive||x.is_active===true),failRead?503:200);}if(u.pathname.endsWith('/replace_ecard_links')){const args=JSON.parse(r.postData());if(failReplace)return send({message:'This link update is too large to save at once. Your saved links are unchanged.'},400);links=args.p_links.map((x,i)=>({...x,id:x.id||String(i),card_id:cid}));writes.push('links');return send(null);}if(u.pathname.endsWith('/digital_cards')){if(r.method()==='GET')return send(card);const data=JSON.parse(r.postData()||'{}');card={...card,...data};writes.push(data.is_published?'publish':'card');return send(card);}if(r.method()!=='GET')return send({message:'unmatched write blocked'},403);return send(null);});
const visit=url=>p.goto(base+url,{waitUntil:'networkidle2',timeout:90000});const click=async text=>{await p.waitForFunction(t=>[...document.querySelectorAll('button,summary')].some(n=>n.textContent.trim()===t),{},text);await p.evaluate(t=>[...document.querySelectorAll('button,summary')].find(n=>n.textContent.trim()===t).click(),text);};
try{
for(const [id,scheme] of [['pro-realtor','warm-neutral'],['politician-generic','classic-blue']]){
 await visit('/app/ecard/new?template='+id+'&scheme='+scheme);await p.waitForSelector('.gallery-phone iframe');
 const frame=await(await p.$('.gallery-phone iframe')).contentFrame();await frame.waitForSelector('[data-card-preview]',{timeout:60000});
 await frame.waitForFunction(()=>[...document.images].filter(i=>i.src.includes('ecard-examples')).every(i=>i.complete&&i.naturalWidth>0),{timeout:60000});
 assert.deepEqual(await frame.evaluate(()=>[innerWidth,innerHeight]),[360,640]);await p.evaluate(()=>window.scrollTo(0,0));
 await p.screenshot({path:out+'/'+id+'-ready-phone.png',fullPage:true});
}
console.log('PASS two actual 9:16 Free previews fully rendered');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
