/** Approved template polish against the immediately preceding release. No network or writes. */
process.env.NODE_ENV='production';
const crypto=require('node:crypto');
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
const root=path.resolve(__dirname,'../..'),baseline=process.env.TAVVY_PUBLIC_ECARD_BASELINE,cache=new Map();
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const m={exports:{}};cache.set(file,m.exports);const compiled=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText;vm.runInNewContext(compiled,{module:m,exports:m.exports,require(name){if(name==='react')return React;if(name==='next/head')return({children})=>React.createElement(React.Fragment,null,children);if(name==='next-i18next')return{useTranslation:()=>({t:key=>key})};if(name==='next-i18next/serverSideTranslations')return{serverSideTranslations:async()=>({})};if(name==='@supabase/supabase-js')return{createClient(){throw Error('Unexpected data client during render')}};if(name.endsWith('supabaseClient'))return{supabase:{}};if(name.startsWith('.')){let base=path.resolve(path.dirname(file),name);const resolved=[base,base+'.ts',base+'.tsx',base+'.json'].find(p=>fs.existsSync(p)&&fs.statSync(p).isFile());if(!resolved)throw Error('Missing dependency '+name);if(resolved.endsWith('.json'))return JSON.parse(fs.readFileSync(resolved,'utf8'));return load(resolved);}return require(name);},console,Date,Math,URL,process:{env:{}},setTimeout,clearTimeout},{filename:file});cache.set(file,m.exports);return m.exports;}

const {mapPublicCard}=load(path.join(root,'lib/ecard/publicCardMapping.ts'));
const {TEMPLATES}=load(path.join(root,'config/eCardTemplates.ts'));
const {templatePreviewData,templateDesignDefaults}=load(path.join(root,'lib/ecard/templateExamples.ts'));
const {localExampleAssets}=load(path.join(root,'lib/ecard/templateSelection.ts'));
const Current=load(path.join(root,'components/ecard/PublicCardView.tsx')).default,Previous=baseline?load(baseline).default:null;
const raw={id:'00000000-0000-4000-8000-000000000001',slug:'qa-only',full_name:'QA Example',title:'A clear title',company:'Company subtitle',bio:'A longer description with enough words to check the breathing room.',phone:'+12025550147',email:'hello@example.invalid',website:'https://example.invalid',gradient_color_1:'#17324e',gradient_color_2:'#315773',profile_photo_url:'https://example.invalid/portrait.png',show_contact_info:true,is_published:false,gallery_images:[],videos:[]};
const render=(View,record)=>renderToStaticMarkup(React.createElement(View,{cardData:mapPublicCard(record,[]),error:null,previewOnly:true}));
const fixturePath=path.join(root,'tests/fixtures/ecard-template-polish-release-hashes.json');
if(process.env.TAVVY_CAPTURE_TEMPLATE_BASELINE==='1'){assert(Previous,'Capture requires an explicitly supplied reviewed release renderer');const hashes={};for(const t of TEMPLATES)for(const c of t.colorSchemes)hashes[t.id+'/'+c.id]=crypto.createHash('sha256').update(render(Previous,{...raw,template_id:t.id,color_scheme_id:c.id})).digest('hex');fs.mkdirSync(path.dirname(fixturePath),{recursive:true});fs.writeFileSync(fixturePath,JSON.stringify({source:'Reviewed web release before September21 Faith/Bandeira corrections; fictional fixture only.',hashes},null,2)+'\n');}
const releaseHashes=JSON.parse(fs.readFileSync(fixturePath,'utf8')).hashes;
test('all123 existing palettes outside the two approved layouts retain identical rendered markup',()=>{let count=0;for(const t of TEMPLATES)for(const s of t.colorSchemes){count++;if(['church','civic-card-flag'].includes(t.layout))continue;const record={...raw,template_id:t.id,color_scheme_id:s.id};assert.equal(crypto.createHash('sha256').update(render(Current,record)).digest('hex'),releaseHashes[t.id+'/'+s.id],t.id+'/'+s.id);}assert.equal(TEMPLATES.length,21);assert.equal(count,123);});
test('Faith collapses only empty cover, preserving uploaded banners and content',()=>{const empty=render(Current,{...raw,template_id:'church'}),withBanner=render(Current,{...raw,template_id:'church',banner_image_url:'https://example.invalid/real-banner.jpg'});assert(empty.includes('height:88px;position:relative'));assert(withBanner.includes('height:180px;position:relative'));assert(withBanner.includes('https://example.invalid/real-banner.jpg'));assert(empty.includes('padding:16px 24px 22px'));assert(empty.includes('rgba(255,255,255,0.84)'));assert(empty.includes(raw.bio));});
test('Bandeira subtitle is opaque white and custom images stay intact',()=>{const html=render(Current,{...raw,template_id:'civic-card-flag',banner_image_url:'https://example.invalid/saved-banner.jpg'});assert(html.includes('https://example.invalid/saved-banner.jpg'));const subtitle=html.match(/<p style="([^"]*)">Company subtitle<\/p>/);assert(subtitle);assert(subtitle[1].includes('color:#ffffff'));assert(subtitle[1].includes('opacity:1'));assert(html.includes('rgba(0,20,10,0.58)'));});
test('Bandeira defaults add only existing decoration and never example identity',()=>{const t=TEMPLATES.find(x=>x.id==='civic-card-flag'),defaults=templateDesignDefaults(t);assert.deepEqual(Object.keys(defaults).sort(),['banner_image_url','font_style']);assert.equal(defaults.banner_image_url,'https://tavvy.com/images/brazil-flag-vertical.jpg');assert.equal(templatePreviewData(t).card.banner_image_url,defaults.banner_image_url);const chef=templatePreviewData(TEMPLATES.find(x=>x.id==='full-width'));assert(chef.card.profile_photo_url.includes('chef-marcus-clean.png'));});
test('local preview rebases only the approved decorative flag and helper assets',()=>{assert.equal(localExampleAssets('https://tavvy.com/images/brazil-flag-vertical.jpg','http://127.0.0.1:3839'),'http://127.0.0.1:3839/images/brazil-flag-vertical.jpg');assert.equal(localExampleAssets('https://example.invalid/private.jpg','http://127.0.0.1:3839'),'https://example.invalid/private.jpg');assert.equal(localExampleAssets('https://tavvy.com/images/unrelated.jpg','http://127.0.0.1:3839'),'https://tavvy.com/images/unrelated.jpg');});
