/** Compare the moved public renderer to the last released page for every catalog template. */
process.env.NODE_ENV='production';
const crypto=require('node:crypto');
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
const root=path.resolve(__dirname,'../..'),baseline=process.env.TAVVY_PUBLIC_ECARD_BASELINE||'/private/tmp/tavvy-web-production-20260920/pages/[username].tsx',cache=new Map();
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const m={exports:{}};cache.set(file,m.exports);const compiled=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText;vm.runInNewContext(compiled,{module:m,exports:m.exports,require(name){if(name==='react')return React;if(name==='next/head')return({children})=>React.createElement(React.Fragment,null,children);if(name==='next-i18next')return{useTranslation:()=>({t:key=>key})};if(name==='next-i18next/serverSideTranslations')return{serverSideTranslations:async()=>({})};if(name==='@supabase/supabase-js')return{createClient(){throw Error('Unexpected data client during render')}};if(name.endsWith('supabaseClient'))return{supabase:{}};if(name.startsWith('.')){let base=path.resolve(path.dirname(file),name);if(file===baseline)base=path.resolve(root,'pages',name);const resolved=[base,base+'.ts',base+'.tsx',base+'.json'].find(p=>fs.existsSync(p)&&fs.statSync(p).isFile());if(!resolved)throw Error('Missing dependency '+name);if(resolved.endsWith('.json'))return JSON.parse(fs.readFileSync(resolved,'utf8'));return load(resolved);}return require(name);},console,Date,Math,process:{env:{}},setTimeout,clearTimeout},{filename:file});cache.set(file,m.exports);return m.exports;}
const {mapPublicCard}=load(path.join(root,'lib/ecard/publicCardMapping.ts')),{TEMPLATES}=load(path.join(root,'config/eCardTemplates.ts'));
const Current=load(path.join(root,'components/ecard/PublicCardView.tsx')).default;
const raw={id:'00000000-0000-4000-8000-000000000001',slug:'render-test',full_name:'Sam Example',title:'Designer',phone:'+15555550100',email:'sam@example.invalid',bio:'Card render fixture',gradient_color_1:'#223366',gradient_color_2:'#7D3388',is_published:true,featured_socials:[{platform:'instagram',url:'https://example.invalid/social'}],gallery_images:[{id:'g',url:'https://example.invalid/gallery.jpg',caption:'Work'}],form_block:{formType:'native',title:'Get in touch',buttonText:'Send',fields:[{id:'message',type:'textarea',label:'Message',required:true}]},videos:[],pronouns:'they/them',company_logo_url:'https://example.invalid/logo.png'};
const links=[{id:'link',title:'Portfolio',url:'https://example.invalid',icon:'website',sort_order:0}];
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const fixturePath=path.join(root,'tests/fixtures/ecard-public-render-hashes.json');
if(process.env.TAVVY_CAPTURE_RELEASED_ECARD==='1'){
 assert(fs.existsSync(baseline),'Capture only from the released page');const Previous=load(baseline).default,hashes={};
 for(const template of TEMPLATES){const cardData=mapPublicCard({...raw,template_id:template.id,color_scheme_id:template.colorSchemes[0]?.id},links);hashes[template.id]=hash(renderToStaticMarkup(React.createElement(Previous,{cardData,error:null,isPreview:false})));}
 fs.mkdirSync(path.dirname(fixturePath),{recursive:true});fs.writeFileSync(fixturePath,JSON.stringify({source:'Released public page before shared-renderer extraction, restaurant release 5bb63c3e, 2026-09-20',hashes},null,2)+'\n');
}
if(process.env.TAVVY_CAPTURE_APPROVED_CONTRAST==='1'){
 const fixture=JSON.parse(fs.readFileSync(fixturePath,'utf8')),template=TEMPLATES.find(t=>t.id==='biz-modern');
 const cardData=mapPublicCard({...raw,template_id:template.id,color_scheme_id:template.colorSchemes[0]?.id},links);
 fixture.intentionalChanges={'biz-modern':{reason:'Approved correction: white header text uses existing primary/secondary gradient instead of light page backdrop; layout unchanged.',hash:hash(renderToStaticMarkup(React.createElement(Current,{cardData,error:null,isPreview:false})))}};
 fs.writeFileSync(fixturePath,JSON.stringify(fixture,null,2)+'\n');
}
test('all existing public templates match released public markup after extracting shared view',()=>{const {hashes,intentionalChanges={}}=JSON.parse(fs.readFileSync(fixturePath,'utf8'));assert.deepEqual(Object.keys(intentionalChanges),['biz-modern']);assert.equal(Object.keys(hashes).length,TEMPLATES.length);for(const template of TEMPLATES){const data=mapPublicCard({...raw,template_id:template.id,color_scheme_id:template.colorSchemes[0]?.id},links);const props={cardData:data,error:null,isPreview:false};assert.equal(hash(renderToStaticMarkup(React.createElement(Current,props))),intentionalChanges[template.id]?.hash||hashes[template.id],template.id);}});
test('private preview has current unsaved content, actual forms/gallery/styles and no public metadata',()=>{const data=mapPublicCard({...raw,template_id:'basic',full_name:'Unsaved studio name',button_style:'outline',button_color:'#135724',font_style:'bold'},links);const markup=renderToStaticMarkup(React.createElement(Current,{cardData:data,error:null,previewOnly:true}));assert(markup.includes('Unsaved studio name'));assert(markup.includes('Get in touch'));assert(markup.includes('gallery.jpg'));assert(markup.includes('#135724'));assert(!markup.includes('property="og:'));assert(!markup.includes('rel="canonical"'));assert(!markup.includes('type="application/ld+json"'));});

test('modern business header uses its dark gradient rather than its light page backdrop',()=>{const template=TEMPLATES.find(t=>t.id==='biz-modern');for(const scheme of template.colorSchemes){const cardData=mapPublicCard({...raw,template_id:'biz-modern',color_scheme_id:scheme.id},links);const markup=renderToStaticMarkup(React.createElement(Current,{cardData,error:null}));assert(markup.includes(`linear-gradient(135deg, ${scheme.primary} 0%, ${scheme.secondary} 100%)`),scheme.id);}});
