/** Mock-only browser regression: no request writes a real card or publishes one. */
const puppeteer=require('puppeteer'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const base=process.env.TAVVY_ECARD_BASE||'http://127.0.0.1:3048',out=process.env.TAVVY_ECARD_QA||'/private/tmp/tavvy-ecard-studio-qa';
const uid='00000000-0000-4000-8000-000000000083',cid='00000000-0000-4000-8000-000000000098';
const originalCard={id:cid,user_id:uid,full_name:'Jordan Rivera',slug:'qa-card',title:'Designer',bio:'Thoughtful work for local businesses.',template_id:'basic',theme:'classic',gradient_color_1:'#8A05BE',gradient_color_2:'#667eea',is_published:false,is_active:true,featured_socials:[],gallery_images:[],videos:[],profile_photo_url:null,phone:'+1 555 0100',show_licensed_badge:true,badge_approval_status:'approved'};
const originalLinks=[{id:'00000000-0000-4000-8000-000000000091',card_id:cid,platform:'website',title:'My portfolio',url:'https://example.invalid/portfolio',value:'portfolio-value',sort_order:0,is_active:true},{id:'00000000-0000-4000-8000-000000000092',card_id:cid,platform:'instagram',icon:'logo-instagram',title:'Instagram updates',url:'https://example.invalid/instagram',sort_order:1,is_active:true},{id:'00000000-0000-4000-8000-000000000093',card_id:cid,platform:'phone',title:'Private number',url:'tel:15550101',value:'15550101',sort_order:2,is_active:null}];
const clone=v=>JSON.parse(JSON.stringify(v));
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});
 const page=await browser.newPage();await page.setViewport({width:390,height:844});await page.setBypassServiceWorker(true);const errors=[],writes=[];let card=clone(originalCard),links=clone(originalLinks),failSave=false,failLinks=false,failPlan=false,pro=true,createdPayload;
 const user={id:uid,email:'ecard@example.invalid',aud:'authenticated',role:'authenticated',app_metadata:{},user_metadata:{}};
 await page.evaluateOnNewDocument(session=>{localStorage.setItem('sb-scasgwrikoqdwlwlwcff-auth-token',JSON.stringify(session));if(!localStorage.getItem('@tavvy_theme_mode'))localStorage.setItem('@tavvy_theme_mode','light');},{access_token:'qa.session.token',refresh_token:'qa-refresh',expires_at:Math.floor(Date.now()/1000)+3600,expires_in:3600,token_type:'bearer',user});
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.setRequestInterception(true);page.on('request',async r=>{
  const u=new URL(r.url());if(!u.hostname.endsWith('.supabase.co'))return r.continue();
  const respond=(data,status=200)=>r.respond({status,contentType:'application/json',headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*'},body:JSON.stringify(data)});
  if(r.method()==='OPTIONS')return respond({});if(u.pathname==='/auth/v1/user')return respond(user);
  if(u.pathname.endsWith('/get_my_ecard_entitlement'))return respond(failPlan?{message:'mock plan unavailable'}:{is_pro:pro,is_super_admin:false,ecard_active:true,status:pro?'active':'free',plan_type:pro?'pro':'free',current_period_end:null},failPlan?503:200);
  if(u.pathname.endsWith('/digital_cards')){if(r.method()==='GET')return respond(card);const body=JSON.parse(r.postData()||'{}');writes.push({type:r.method()==='POST'?'create':body.is_published!==undefined?'publication':'card',body});if(failSave)return respond({message:'forced save failure'},500);if(r.method()==='POST'){createdPayload=body;card={...card,...body};}else card={...card,...body};return respond(card);}
  if(u.pathname.endsWith('/digital_card_links'))return respond(failLinks?{message:'mock link read unavailable'}:links,failLinks?503:200);
  if(u.pathname.endsWith('/replace_ecard_links')){const body=JSON.parse(r.postData()||'{}');writes.push({type:'links',body});if(failSave)return respond({message:'forced links failure'},500);links=body.p_links;return respond(null);}
  if(r.method()!=='GET')return respond({message:'Unrecognized write blocked'},403);return respond(null);
 });
 const visit=async route=>{await page.goto(base+route,{waitUntil:'networkidle2',timeout:60000});};
 const click=async text=>{await page.waitForFunction(text=>[...document.querySelectorAll('button,summary')].some(e=>e.textContent.trim()===text),{},text);await page.evaluate(text=>{const e=[...document.querySelectorAll('button,summary')].find(e=>e.textContent.trim()===text);e.click()},text);};
 const field=async(selector,value)=>{await page.waitForSelector(selector);await page.focus(selector);await page.$eval(selector,e=>e.select());await page.type(selector,value);};
 const noOverflow=async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'horizontal page overflow');
 const waitSaved=()=>page.waitForFunction(()=>document.body.innerText.includes('All changes saved'));
 try{
  await visit('/app/ecard/new');await field('input[name=fullName]','Avery Lane');await field('input[name=title]','Creative Director');await page.screenshot({path:out+'/quick-setup-mobile.png',fullPage:true});await noOverflow();
  await click('Choose card type & template');assert(await page.$eval('body',e=>e.innerText.includes('Politician')));await page.evaluate(()=>[...document.querySelectorAll('button')].find(e=>e.textContent.includes('Personal')&&e.textContent.includes('personal brand')).click());await page.waitForSelector('.template-gallery-scroll');await click('Use this template');assert.equal(await page.$eval('input[name=fullName]',e=>e.value),'Avery Lane');assert.equal(await page.$eval('input[name=title]',e=>e.value),'Creative Director');
  await click('Create draft');await page.waitForSelector('.card-studio');assert.equal(createdPayload.is_published,false);assert.equal(createdPayload.full_name,'Avery Lane');
  card=clone(originalCard);links=clone(originalLinks);await visit(`/app/ecard/${cid}/edit`);await page.waitForSelector('[data-link-id]');await noOverflow();assert.equal(await page.$$eval('[data-link-id]',e=>e.length),3);assert(await page.$eval('body',e=>e.innerText.includes('Phone · Hidden')));assert.equal(await page.$eval('[data-editor-theme]',e=>e.dataset.editorTheme),'light');
  const toolbar=await page.$$eval('.studio-actions button',nodes=>nodes.map(e=>({text:e.textContent.trim(),x:e.getBoundingClientRect().x,right:e.getBoundingClientRect().right,width:e.getBoundingClientRect().width})));assert(toolbar.every(e=>e.x>=0&&e.right<=390&&e.width>=44),'all toolbar actions fit phone');
  await page.screenshot({path:out+'/editor-content-mobile.png',fullPage:true});
  await page.click('[aria-label="Move Instagram updates up"]');await waitSaved();assert.equal(links[0].id,originalLinks[1].id);assert.equal(links[0].platform,'instagram');assert.equal(links[1].value,'portfolio-value');assert.equal(links[2].is_active,false);assert.equal(card.badge_approval_status,'approved','ordinary edits preserve existing badge approval');await click('Preview');const previewFrame=await(await page.waitForSelector('iframe[title="9:16 phone preview"]')).contentFrame();await previewFrame.waitForSelector('[data-card-preview]');assert(await previewFrame.$eval('[data-card-preview]',e=>!e.innerText.includes('Private number')));assert(await previewFrame.$eval('[data-card-preview]',e=>e.innerText.indexOf('Instagram updates')<e.innerText.indexOf('My portfolio')));await previewFrame.waitForFunction(()=>[...document.querySelectorAll('[data-card-preview] .link-btn')].every(e=>Number(getComputedStyle(e).opacity)>.99));await page.screenshot({path:out+'/editor-preview-mobile.png',fullPage:true});await click('Edit');
  failSave=true;await field('[aria-label="Instagram link title"]','Latest work');await click('Publish');await page.waitForFunction(()=>document.body.innerText.includes('Retry saving'));assert.equal(writes.filter(e=>e.type==='publication').length,0,'failed save blocks publication');assert(await page.$eval('body',e=>e.innerText.includes('Retry saving')));await page.screenshot({path:out+'/save-error-mobile.png',fullPage:true});
  failSave=false;await click('Retry saving');await waitSaved();const before=writes.length;await field('[aria-label="Instagram link title"]','Latest creative work');await click('Publish');await page.waitForFunction(()=>document.body.innerText.includes('Your card is published and ready to share.'));const sequence=writes.slice(before).map(x=>x.type);assert(sequence.indexOf('card')<sequence.indexOf('links')&&sequence.indexOf('links')<sequence.indexOf('publication'),'save card and links before publishing');assert.equal(card.is_published,true);
  await click('Share & QR');await page.waitForSelector('[role=dialog]');await page.keyboard.press('Escape');assert.equal(await page.$('[role=dialog]'),null);
  await page.setViewport({width:1365,height:960});await noOverflow();await page.screenshot({path:out+'/editor-desktop.png',fullPage:true});assert(await page.$eval('.studio-preview',e=>getComputedStyle(e).display!=='none'));
  await click('Design');await click('Typography & buttons');assert(await page.$eval('body',e=>e.innerText.toLowerCase().includes('social icon color')));await click('Images & layout');assert(await page.$eval('body',e=>e.innerText.toLowerCase().includes('company logo')));await page.screenshot({path:out+'/design-desktop.png',fullPage:true});
  await page.setViewport({width:320,height:800});await noOverflow();await page.screenshot({path:out+'/editor-320.png',fullPage:true});
  card={...clone(originalCard),template_id:'business-card'};links=[];pro=false;await visit(`/app/ecard/${cid}/edit`);await page.waitForSelector('.card-studio');await click('Publish');await page.waitForFunction(()=>document.body.innerText.includes('Your card is published and ready to share.'));assert.equal(await page.$('[role=dialog]'),null,'free business-card is not paywalled');
  card={...clone(originalCard),template_id:'pro-card',form_block:{formType:'webhook',title:'Tell me about your project',webhookUrl:'https://example.invalid/form',fields:[{id:'message',label:'Message',required:true}]}};pro=true;await visit(`/app/ecard/${cid}/edit`);await page.waitForSelector('.card-studio');await click('More features');await click('Professional details & contact form');await page.click('[aria-label="Show contact form on card"]');await waitSaved();assert.equal(card.form_block.enabled,false);assert.equal(card.form_block.webhookUrl,'https://example.invalid/form');await page.click('[aria-label="Show contact form on card"]');await waitSaved();assert.equal(card.form_block.enabled,true);assert.equal(card.form_block.fields[0].id,'message');
  card={...clone(originalCard),template_id:'civic-card',ballot_number:'123'};await visit(`/app/ecard/${cid}/edit`);await page.waitForSelector('.card-studio');await click('More features');await click('Civic details');assert(await page.$eval('body',e=>e.innerText.includes('Ballot Number')));
  card={...clone(originalCard),template_id:'mobile-business',business_type:'Food truck',description:'Seasonal bowls'};await visit(`/app/ecard/${cid}/edit`);await page.waitForSelector('.card-studio');await click('More features');await click('Mobile business');assert(await page.$eval('body',e=>e.innerText.includes('Specialties')));
  failPlan=true;await visit(`/app/ecard/${cid}/edit`);await page.waitForSelector('.studio-alert');assert(await page.$eval('.studio-actions button:last-child',e=>e.disabled));failPlan=false;await click('Retry plan check');await page.waitForFunction(()=>!document.querySelector('.studio-alert'));
  failLinks=true;await visit(`/app/ecard/${cid}/edit`);await page.waitForFunction(()=>document.body.innerText.includes('Retry loading'));assert.equal(await page.$('.card-studio'),null,'failed link read cannot open an empty editable list');failLinks=false;await click('Retry loading');await page.waitForSelector('.card-studio');
  card={...clone(originalCard),is_published:false};links=clone(originalLinks);await visit(`/app/ecard/${cid}/preview`);await click('Quick Edit');failSave=true;await page.click('[aria-label="Show contact info"]');const previewPublishCount=writes.filter(e=>e.type==='publication').length;await click('Publish');await page.waitForSelector('.preview-save-error');assert.equal(writes.filter(e=>e.type==='publication').length,previewPublishCount,'quick preview also blocks publication after failed save');failSave=false;await click('Retry saving');await page.waitForFunction(()=>!document.querySelector('.unsaved-badge'));await page.click('[aria-label="Show social icons"]');await click('Publish');await page.waitForFunction(()=>!document.querySelector('.draft-banner'));assert.equal(card.is_published,true);await page.screenshot({path:out+'/full-preview-safe-publish.png',fullPage:true});
  await visit(`/app/ecard/${cid}/edit`);await page.waitForSelector('.card-studio');
  await page.setViewport({width:390,height:844});await page.evaluate(()=>localStorage.setItem('@tavvy_theme_mode','dark'));await page.reload({waitUntil:'networkidle2'});await page.waitForSelector('[data-editor-theme="dark"]');await page.screenshot({path:out+'/editor-dark-mobile.png',fullPage:true});await noOverflow();
  await page.evaluate(()=>localStorage.setItem('@tavvy_theme_mode','light'));await visit('/app');await page.screenshot({path:out+'/home-light-search.png',fullPage:false});
  const retainedGallery={id:'old-gallery',uri:base+'/images/demo-trattoria/pasta.jpg',caption:'Existing caption',credit:'Original credit'};card={...clone(originalCard),gallery_images:[retainedGallery],youtube_video_id:'legacy-video-id',gallery_title:'Existing gallery',social_instagram:'https://example.invalid/old-social'};links=clone(originalLinks);await visit(`/app/ecard/${cid}/edit`);await page.waitForSelector('[data-link-id]');await field('[aria-label="Website link title"]','Updated portfolio');await waitSaved();assert.deepEqual(card.gallery_images,[retainedGallery],'URI gallery and metadata retained during unrelated save');assert.equal(card.youtube_video_id,'legacy-video-id');assert.equal(card.gallery_title,'Existing gallery');assert.equal(card.social_instagram,'https://example.invalid/old-social');
  card={...clone(originalCard),user_id:'00000000-0000-4000-8000-000000000055'};const beforeForeign=writes.length;await visit(`/app/ecard/${cid}/edit`);await page.waitForFunction(()=>document.body.innerText.includes('another account'));assert.equal(await page.$('.card-studio'),null);assert.equal(writes.length,beforeForeign,'foreign public card never opens writable studio');
  assert.deepEqual(errors,[],'no browser runtime errors');fs.writeFileSync(out+'/result.json',JSON.stringify({status:'PASS',mockWrites:writes.length,errors,checks:['short draft creation','template path preserves setup','reorder identity and hidden links','save failure blocks publish','save+links then publish','separate quick-preview save failure and publication gate','free executive card','form configuration preserved','civic and mobile business fields','strict link load retry','non-owner editor blocked','legacy gallery and untouched fields preserved','plan failure blocks publish','390/320/desktop layout','homepage light search'],screenshots:out},null,2));console.log(JSON.stringify({status:'PASS',screenshots:out,mockWrites:writes.length,errors}));
 }catch(error){await page.screenshot({path:out+'/failure.png',fullPage:true});fs.writeFileSync(out+'/failure.json',JSON.stringify({error:String(error),body:await page.$eval('body',e=>e.innerText),writes,errors},null,2));throw error;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
