const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),path=require('node:path');
function moduleAt(file){const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'../..',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{module:m,exports:m.exports,require:name=>name==='./formBlock'?moduleAt('lib/ecard/formBlock.ts'):({}),Date});return m.exports;}
const {editorReducer,initialEditorState}=moduleAt('lib/ecard/editorReducer.ts'),forms=moduleAt('lib/ecard/formBlock.ts');
const links=[{id:'one',platform:'phone',url:'tel:123',value:'123',is_active:true},{id:'two',platform:'website',url:'https://example.invalid',is_active:false},{id:'three',platform:'email',url:'mailto:test@example.invalid',is_active:null}];
test('reordering keeps link identity, hidden state and independent values; out of range is a no-op',()=>{const state={...initialEditorState,links};const moved=editorReducer(state,{type:'REORDER_LINKS',fromIndex:2,toIndex:0});assert.equal(moved.links[0],links[2]);assert.equal(moved.links[1],links[0]);assert.equal(moved.links[1].value,'123');assert.equal(moved.links[0].is_active,null);assert.equal(moved.isDirty,true);assert.equal(editorReducer(state,{type:'REORDER_LINKS',fromIndex:9,toIndex:0}),state);assert.equal(editorReducer(state,{type:'REORDER_LINKS',fromIndex:0,toIndex:0}),state);});
test('late save completion cannot erase an edit made while the save was in flight',()=>{const old={...initialEditorState,card:{id:'card',full_name:'Old'},links,isDirty:true};const current=editorReducer(old,{type:'SET_FIELD',field:'full_name',value:'New'});const done=editorReducer(current,{type:'SAVE_COMPLETED',snapshot:{card:old.card,links:old.links,pendingUploads:old.pendingUploads},persisted:{full_name:'Old'}});assert.equal(done.card.full_name,'New');assert.equal(done.isDirty,true);});
test('publication change keeps in-memory card content and links intact',()=>{const state={...initialEditorState,card:{id:'card',full_name:'Draft'},links,isDirty:true};const published=editorReducer(state,{type:'SET_PUBLICATION',published:true});assert.equal(published.links,links);assert.equal(published.card.full_name,'Draft');assert.equal(published.card.is_published,true);assert.equal(published.isDirty,true);});
test('form visibility changes preserve configured integrations and fields',()=>{const form={formType:'webhook',webhookUrl:'https://example.invalid/form',fields:[{id:'x',label:'Message'}]};const hidden=forms.setFormBlockEnabled(form,false);assert.equal(forms.visibleFormBlock(hidden),null);assert.equal(hidden.fields,form.fields);const visible=forms.setFormBlockEnabled(hidden,true);assert.equal(visible.webhookUrl,form.webhookUrl);assert.equal(forms.visibleFormBlock(visible),visible);assert.equal(forms.readFormBlock('bad json'),null);assert.equal(forms.visibleFormBlock(true).formType,'native');});

const premium=moduleAt('lib/ecard/premiumContent.ts');
test('empty credential defaults and disabled preserved forms do not count as active extras',()=>{for(const value of [null,[],{},'',{isLicensed:false,isInsured:false,serviceArea:''}])assert.equal(premium.hasCredentialContent(value),false);assert.equal(premium.hasCredentialContent({licenseNumber:'1234'}),true);assert.equal(premium.hasEnabledForm({formType:'native',enabled:false}),false);assert.equal(premium.hasEnabledForm({formType:'native',enabled:true}),true);});
