const {PGlite}=require('@electric-sql/pglite');const fs=require('fs');const assert=require('assert/strict');
(async()=>{const db=new PGlite(),a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',c='33333333-3333-4333-8333-333333333333';
await db.exec(`create role anon;create role authenticated;create schema auth;create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to anon,authenticated;
create table events(id uuid primary key default gen_random_uuid(),external_id text unique not null,name text not null,source text,created_at timestamptz default now(),updated_at timestamptz default now());
create table tavvy_events(id uuid primary key,name text,status text);
create table review_items(id uuid primary key,slug text,label text,icon_emoji text,signal_type text,is_active boolean,is_universal boolean);
create table event_reviews(id uuid primary key default gen_random_uuid(),event_id uuid references events,user_id uuid,public_note text,private_note_owner text,status text,source text,created_at timestamptz default now(),updated_at timestamptz default now());
create table event_review_signal_taps(id uuid primary key default gen_random_uuid(),review_id uuid references event_reviews,event_id uuid references events,signal_id uuid references review_items,intensity integer,created_at timestamptz default now());
alter table events enable row level security;create policy read_events on events for select using(true);
alter table event_reviews enable row level security;create policy read_reviews on event_reviews for select using(status='live' or user_id=auth.uid());
alter table event_review_signal_taps enable row level security;create policy unsafe on event_review_signal_taps for all using(true) with check(true);
grant all on events,event_reviews,event_review_signal_taps to anon,authenticated;
insert into tavvy_events values('${a}','Public event','published'),('${b}','Draft','draft');insert into review_items values('${a}','event_great_music','Music','🎵','best_for',true,false),('${b}','pro_expert','Expert','x','pro_endorsement',true,false),('${c}','event_old','Old','x','heads_up',false,false);`);
await db.exec(fs.readFileSync('supabase/migrations/202609080011_atomic_event_reviews.sql','utf8'));
await db.exec(`set role authenticated;set request.jwt.claim.sub='${a}';`);
const save=async(subject,signals,review=null)=>(await db.query('select save_event_review($1,$2::jsonb,$3,$4,$5) as id',[subject,JSON.stringify(signals),'Public','Private',review])).rows[0].id;
const taps=[{signal_id:a,intensity:3}];const review=await save(a,taps);
assert.equal(await save(a,[{signal_id:a,intensity:1}]),review,'repeat submit updates existing review');
let totals=(await db.query('select * from get_event_signal_totals($1)',[a])).rows;assert.equal(Number(totals[0].tap_total),1);assert.equal(Number(totals[0].review_count),1);
for(const signals of [[],[{signal_id:a,intensity:4}],[{signal_id:b,intensity:1}],[{signal_id:c,intensity:1}],[{signal_id:a,intensity:1},{signal_id:a,intensity:2}]])await assert.rejects(save(a,signals));
assert.equal(Number((await db.query('select * from get_event_signal_totals($1)',[a])).rows[0].tap_total),1,'failed replacement preserves prior taps');
await assert.rejects(save(b,taps),/verified/);await assert.rejects(save('tm_fake',taps),/verified/);
await assert.rejects(db.exec(`insert into events(external_id,name) values('tm_fake','Fake')`),/permission denied/);
assert.equal((await db.query('select private_note_owner from get_my_event_review($1)',[a])).rows[0].private_note_owner,'Private');
await assert.rejects(db.query('select private_note_owner from event_reviews'),/permission denied/);
await db.exec(`set request.jwt.claim.sub='${b}';`);await assert.rejects(save(a,taps,review),/cannot edit/);
await db.exec(`reset role;insert into events(external_id,name,source,provider_verified_at) values('tm_verified','Verified provider event','ticketmaster',now());set role authenticated;set request.jwt.claim.sub='${a}';`);
await save('tm_verified',taps);
await db.exec(`reset role;update event_reviews set status='hidden' where id='${review}';set role anon;set request.jwt.claim.sub='';`);
assert.equal((await db.query('select * from get_event_signal_totals($1)',[a])).rows.length,0);
assert.equal((await db.query('select * from event_review_signal_taps where review_id=$1',[review])).rows.length,0);
await assert.rejects(save(a,taps),/permission denied/);
await db.close();console.log('PASS event atomic ownership, identity verification, signal validation, stable updates, private fields, moderation totals and RLS');})().catch(e=>{console.error(e);process.exitCode=1;});
