const test=require('node:test'), assert=require('node:assert/strict'), fs=require('node:fs'), vm=require('node:vm'), ts=require('typescript');
function load(file, extra={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,Date,Intl,Math,Number,Error,AbortSignal,process:{env:{TICKETMASTER_API_KEY:'test',PREDICTHQ_API_KEY:'test'}},fetch:()=>{throw Error('No real requests');},...extra});return exports;}
const d=load('lib/eventDiscovery.ts');
test('both platforms share discovery contract and only deployed community columns',()=>{assert.equal(fs.readFileSync('lib/eventDiscovery.ts','utf8'),fs.readFileSync('../tavvy-mobile/lib/eventDiscovery.ts','utf8'));const columns=JSON.parse(fs.readFileSync('docs/schema-audit/public-schema.json')).columns.filter(r=>r.table==='tavvy_events').map(r=>r.column);for(const c of d.COMMUNITY_EVENT_COLUMNS.split(','))assert.ok(columns.includes(c),c);});
test('weekend begins Saturday and excludes Monday; tonight excludes tomorrow',()=>{const now=new Date(2026,8,8,12);const range=d.eventDateRange('weekend',now);assert.equal(new Date(range.startDate).getDay(),6);assert.equal(new Date(range.endDate).getDay(),1);assert.equal(new Date(range.endDate).getHours(),0);assert.equal(new Date(d.eventDateRange('tonight',now).endDate).getDate(),9);});
test('unknown prices stay unknown and zero coordinates survive normalization',()=>{const event=d.communityEvent({id:'x',name:'Name',latitude:0,longitude:0,start_datetime:'2026-09-08',price_min:null});assert.equal(event.lat,0);assert.equal(event.lng,0);assert.equal(d.eventPrice(event),'Price not listed');assert.equal(d.eventPrice({price_min:0}),'Free');assert.notEqual(d.eventPrice({price_min:0,price_max:20}),'Free');});
test('community pagination reaches page two and exact radius excludes distant events',async()=>{let page=0;const calls=[];const first=Array.from({length:500},(_,i)=>({id:String(i),name:'Real fixture',latitude:0,longitude:i===0?10:0,start_datetime:'2026-09-09'}));const db={from(table){assert.equal(table,'tavvy_events');const q={};for(const op of ['select','eq','gte','lte','lt','order'])q[op]=(...args)=>{calls.push([op,...args]);return q;};q.range=(start,end)=>{assert.equal(start,page*500);assert.equal(end,start+499);return q;};q.then=resolve=>resolve({data:page++===0?first:[{id:'last',name:'Last',latitude:0,longitude:0}],error:null});return q;}};const rows=await d.loadCommunityEvents(db,{lat:0,lng:0,radiusMiles:10,startDate:'2026-09-08',endDate:'2026-09-10'});assert.equal(rows.length,500);assert.equal(rows.at(-1).id,'last');assert.ok(calls.some(c=>c[0]==='lt'&&c[1]==='start_datetime'));});
test('query failures propagate, invalid location rejected before query',async()=>{await assert.rejects(d.loadCommunityEvents({}, {lat:100,lng:0,radiusMiles:10}),/valid location/);const q=new Proxy({then:r=>r({error:new Error('offline')})},{get(t,k){return k in t?t[k]:()=>q;}});await assert.rejects(d.loadCommunityEvents({from:()=>q},{lat:0,lng:0,radiusMiles:10}),/offline/);});
const provider=load('lib/eventProviderServer.ts').fetchVerifiedProviderEvent;
test('provider lookup rejects arbitrary identities and mismatched provider response',async()=>{await assert.rejects(provider('https://evil.test'),/Unsupported/);await assert.rejects(provider('tm_abc',async url=>{assert.match(url,/^https:\/\/app.ticketmaster.com\/discovery\/v2\/events\/abc.json/);return{ok:true,json:async()=>({id:'wrong',name:'Wrong'})};}),/did not return/);});
test('provider lookup filters PredictHQ exact id and uses verified provider title',async()=>{const event=await provider('phq_abc',async(url,options)=>{assert.equal(url,'https://api.predicthq.com/v1/events/?id=abc&limit=1');assert.equal(options.redirect,'error');return{ok:true,json:async()=>({results:[{id:'other',title:'Other'},{id:'abc',title:'Verified name',location:[0,0],start:'2026-09-08'}]})};});assert.equal(event.title,'Verified name');assert.equal(event.id,'phq_abc');assert.equal(event.lat,0);});
