const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.resolve(__dirname,'../..');
function load(file,deps={}){const exports={};const code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;new Function('require','exports',code)(n=>{if(!(n in deps))throw Error(n);return deps[n];},exports);return exports;}
const h=load('lib/onthego.ts');const now=Date.parse('2026-09-20T12:00:00Z');const b={tavvy_place_id:'11111111-1111-4111-8111-111111111111',place_name:'Café Test',category:'Food_Trucks',subcategory:'Coffee',service_area:'Boston, MA',is_live:true,session_lat:0,session_lng:0,scheduled_end_at:'2026-09-20T13:00:00Z'};
test('invalid expiry never appears live; expiry boundary and duplicates are correct',()=>{const x=h.normalizeMapData({success:true,sessions:[b,b,{...b,tavvy_place_id:'bad',scheduled_end_at:null},{...b,tavvy_place_id:'ended',scheduled_end_at:new Date(now).toISOString()}],scheduled_places:[]},now);assert.equal(x.sessions.length,1);assert.equal(h.normalizeMapData({success:true,sessions:[b],scheduled_places:[]},now+3600000).sessions.length,0);});
test('scheduled requires a real future stop and live wins same business',()=>{const future={...b,is_live:false,next_event:{latitude:0,longitude:0,location_name:'Public square',scheduled_start:'2026-09-21T12:00:00Z',scheduled_end:'2026-09-21T13:00:00Z'}};assert.equal(h.normalizeMapData({success:true,sessions:[],scheduled_places:[{...b,is_live:false},future,future]},now).scheduled.length,1);assert.equal(h.normalizeMapData({success:true,sessions:[b],scheduled_places:[future]},now).scheduled.length,0);});
test('search respects accent/plural tokens, address and category',()=>{assert(h.matchesBusiness(b,'coffee','cafe boston'));assert(h.matchesBusiness(b,'food','Boston MA'));assert(!h.matchesBusiness(b,'coffee','Miami'));assert(h.matchesBusiness({...b,is_live:false},'scheduled',''));});
test('nearby includes valid zero coordinates and excludes distant and missing points',()=>{const distant={...b,tavvy_place_id:'far',session_lat:42,session_lng:-71};assert.deepEqual(h.selectBusinesses([distant,b,{...b,tavvy_place_id:'missing',session_lat:undefined}],'all','',[0,0],true).map(x=>x.tavvy_place_id),[b.tavvy_place_id]);assert.equal(h.businessDirections(b),'https://www.google.com/maps/dir/?api=1&destination=0,0');});
test('links reject executable schemes and preserve valid contact actions',()=>{assert.equal(h.safeBusinessUrl('javascript:alert(1)'),null);assert.equal(h.safeBusinessUrl('data:text/html,x'),null);assert.equal(h.safeBusinessUrl('https://good.example'), 'https://good.example/');assert.equal(h.safeBusinessUrl('+1 (617) 555-0100','phone'),'tel:+16175550100');});
test('detail IDs require genuine canonical association and expired live state disappears',async()=>{let calls=[];const d=load('lib/onthegoDetails.ts',{'./supabaseClient':{supabase:{rpc:async(name,args)=>{calls.push({name,args});return {data:null};}}},'./onthego':h});const p={id:b.tavvy_place_id,name:'Fixture',canonical_place_id:'22222222-2222-4222-8222-222222222222'};assert.throws(()=>d.validateMobileDetails({place:p,events:[]},{canonicalPlaceId:b.tavvy_place_id},now),/verified/);assert.equal(d.validateMobileDetails({place:p,events:[],live:{session_lat:0,session_lng:0,session_address:'Square',scheduled_end_at:new Date(now).toISOString()}},{tavvyPlaceId:p.id},now).live,null);await assert.rejects(d.fetchMobileDetails({tavvyPlaceId:'fsq:unrelated'}),/Invalid/);assert.equal(calls.length,0);assert.equal(await d.fetchMobileDetails({tavvyPlaceId:p.id}),null);assert.equal(calls[0].name,'get_onthego_place');});
test('detail read failures are unavailable, not empty, and profile enable keeps exact ID',async()=>{const d=load('lib/onthegoDetails.ts',{'./supabaseClient':{supabase:{rpc:async()=>({error:{message:'offline'}})}},'./onthego':h});await assert.rejects(d.fetchMobileDetails({tavvyPlaceId:b.tavvy_place_id}),/unavailable/);await assert.rejects(d.enableMobilePlaceDetails(b.tavvy_place_id),/offline/);});
test('refresh failure preserves prior results; local expiry hides GPS without another response; unmount aborts pending work',async()=>{
 const slots=[],effects=[],cleanups=[],intervals=[];let cursor=0,requests=0,pending;
 const react={useState(initial){const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return [slots[i],value=>{slots[i]=typeof value==='function'?value(slots[i]):value;}];},useRef(initial){const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i];},useCallback(fn){cursor++;return fn;},useMemo(fn){cursor++;return fn();},useEffect(fn,deps){const i=cursor++;if(!slots[i]){slots[i]=deps;effects.push(fn);}}};
 const original={fetch:global.fetch,interval:global.setInterval,clear:global.clearInterval,now:Date.now};let currentTime=now;
 Date.now=()=>currentTime;global.setInterval=(fn,ms)=>{intervals.push({fn,ms});return intervals.length;};global.clearInterval=()=>{};
 global.fetch=async(_url,options)=>{requests++;if(requests===1)return{ok:true,json:async()=>({success:true,sessions:[b],scheduled_places:[]})};if(requests===2)throw Error('offline');return new Promise((_resolve,reject)=>{pending=options.signal;options.signal.addEventListener('abort',()=>reject(Error('aborted')));});};
 try{const hook=load('lib/useOnTheGoDiscovery.ts',{react,'./onthego':h});const render=()=>{cursor=0;return hook.useOnTheGoDiscovery('https://example.invalid/map');};render();effects.forEach(fn=>cleanups.push(fn()));await new Promise(resolve=>setImmediate(resolve));let state=render();assert.equal(state.businesses.length,1);await state.refresh();state=render();assert.match(state.error,/refresh/);assert.equal(state.businesses.length,1,'network failure must not erase useful results');currentTime=now+3600000;intervals.find(x=>x.ms===1000).fn();assert.equal(render().businesses.length,0,'expiry is independent of network success');const work=render().refresh();await Promise.resolve();cleanups.forEach(fn=>fn&&fn());await work;assert.equal(pending.aborted,true);}finally{global.fetch=original.fetch;global.setInterval=original.interval;global.clearInterval=original.clear;Date.now=original.now;}
});
test('mobile categories preserve the real main business and cruise classification',()=>{const e=load('lib/placeEvidence.ts', {'./rvCategories':load('lib/rvCategories.ts')});for(const category of ['Food Trucks','food_truck','Catering','Ice Cream'])assert.equal(e.coreForCategory(category).label,'The food');assert.equal(e.coreForCategory('Mobile Coffee').label,'The coffee & food');assert.equal(e.coreForCategory('Mobile Pet Grooming').label,'The pet care');assert.equal(e.coreForCategory('Mobile Barber').label,'The result');assert.equal(e.coreForCategory('Mobile Mechanic').label,'The service');assert.equal(e.coreForCategory('cruise_ship').label,'The onboard experience');});
test('profile save uses only authenticated RPC and reports failure without pretending saved',async()=>{let args;const d=load('lib/onthegoDetails.ts',{'./supabaseClient':{supabase:{rpc:async(name,payload)=>{args={name,payload};return {error:{message:'Not authorized'}};}}},'./onthego':h});const draft={name:'Keep my work',website:'https://example.invalid'};await assert.rejects(d.saveMobileBusinessProfile(b.tavvy_place_id,draft),/Not authorized/);assert.equal(args.name,'save_onthego_business_profile');assert.equal(args.payload.p_details,draft);assert.equal(draft.name,'Keep my work');});
