const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),ts=require('typescript');
const root=path.resolve(__dirname,'../../supabase/functions');
function compile(rel,deps,deno){const exports={};const code=ts.transpileModule(fs.readFileSync(path.join(root,rel),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}});assert(!code.diagnostics?.length);new Function('require','exports','Deno',code.outputText)(name=>{if(name.startsWith('jsr:'))return{};if(name in deps)return deps[name];throw Error(name)},exports,deno);return exports;}
function setup({authenticated=true,active=true}={}){const calls=[],rows=[];const client={auth:{getUser:async()=>{calls.push({getUser:true});return{data:{user:authenticated?{id:'owner'}:null},error:authenticated?null:{}}}},rpc:async(name,args)=>{calls.push({rpc:name,args});return name==='onthego_actor_active'?{data:active?'owner':null,error:active?null:{}}:{data:{success:true,session:{id:'session'}},error:null}},from(table){calls.push({table});const q={select(){return q},eq(){return q},gt(){return q},order(){return q},range:async()=>({data:rows,error:null})};return q;}};const factory={createClient:(url,key,options)=>{calls.push({url,key,options});return client}};const Deno={env:{get:name=>name==='SUPABASE_URL'?'https://fixture.invalid':name==='SUPABASE_ANON_KEY'?'fixture-public-key':undefined},serve:fn=>{Deno.handler=fn}};const http=compile('_shared/onthego-http.ts',{'https://esm.sh/@supabase/supabase-js@2':factory},Deno);return{calls,rows,client,factory,Deno,http};}
test('anonymous/no-user and automatic anon-key requests use public RLS client without an admin key',async()=>{for(const headers of [{},{Authorization:'Bearer fixture-public-key'}]){const f=setup();await f.http.onTheGoReader(new Request('https://fixture.invalid',{headers}));assert.equal(f.calls[0].key,'fixture-public-key');assert.deepEqual(f.calls[0].options.global.headers,{});assert(!f.calls.some(x=>x.getUser));}});
test('authenticated reader isolates valid identity, rejects invalid sessions and malformed auth',async()=>{let f=setup();await f.http.onTheGoReader(new Request('https://fixture.invalid',{headers:{Authorization:'Bearer person'}}));assert.deepEqual(f.calls[0].options.global.headers,{Authorization:'Bearer person'});f=setup({authenticated:false});await assert.rejects(()=>f.http.onTheGoReader(new Request('https://fixture.invalid',{headers:{Authorization:'Bearer person'}})),e=>e.status===401);await assert.rejects(()=>f.http.onTheGoReader(new Request('https://fixture.invalid',{headers:{Authorization:'junk'}})),e=>e.status===401);});
test('missing configuration fails closed and inactive actor is denied before owner table access',async()=>{const f=setup({active:false});await assert.rejects(()=>f.http.onTheGoActor(new Request('https://fixture.invalid',{headers:{Authorization:'Bearer person'}})),e=>e.status===403);assert.deepEqual(f.calls.filter(x=>x.rpc).map(x=>x.rpc),['onthego_actor_active']);assert(!f.calls.some(x=>x.table));f.Deno.env.get=()=>undefined;await assert.rejects(()=>f.http.onTheGoReader(new Request('https://fixture.invalid')),e=>e.status===503);});
test('transactional lifecycle forwards only action+payload under the actual user JWT',async()=>{const f=setup();const edge=compile('_shared/onthego-lifecycle.ts',{'https://esm.sh/@supabase/supabase-js@2':f.factory},f.Deno);const payload={tavvy_place_id:'fixture',latitude:0,longitude:0,duration_hours:12,menu_items:[{name:'Fixture'}]};const response=await edge.handleOnTheGo(new Request('https://fixture.invalid',{method:'POST',headers:{Authorization:'Bearer person'},body:JSON.stringify(payload)}),'start');assert.equal(response.status,201);assert.deepEqual(f.calls.find(x=>x.rpc),{rpc:'onthego_session_action',args:{action_name:'start',payload}});assert.equal(f.calls[0].key,'fixture-public-key');assert.equal(f.calls[0].options.global.headers.Authorization,'Bearer person');});
test('nearby rejects missing/invalid coordinates, limit and radius before scanning; does not call generic exec_sql',async()=>{for(const query of ['','?lat=0&lng=0&limit=-1','?lat=0&lng=0&radius_meters=-1','?lat=NaN&lng=0']){const f=setup();compile('live-sessions-nearby/index.ts',{'../_shared/onthego-http.ts':f.http},f.Deno);const r=await f.Deno.handler(new Request('https://fixture.invalid/'+query));assert.equal(r.status,400);assert(!f.calls.some(x=>x.table||x.rpc));}});
test('nearby retains zero coordinates and returns mobile identity separately from canonical place',async()=>{const f=setup();f.rows.push({id:'session',place_id:'canonical',tavvy_place_id:'mobile',session_lat:0,session_lng:0,scheduled_end_at:'2099-01-01',tavvy_places:{name:'Fixture mobile',place_type:'on_the_go',tavvy_category:'Food Trucks'},places:{name:'canonical',place_type:null}});compile('live-sessions-nearby/index.ts',{'../_shared/onthego-http.ts':f.http},f.Deno);const r=await f.Deno.handler(new Request('https://fixture.invalid/?lat=0&lng=0'));assert.equal(r.status,200);const data=await r.json();assert.equal(data.sessions[0].distance_meters,0);assert.equal(data.sessions[0].place_id,'canonical');assert.equal(data.sessions[0].tavvy_place_id,'mobile');assert(!f.calls.some(x=>x.rpc));});

test('all owner handlers reject inactive callers before constructing a privileged data client',async()=>{for(const name of ['create-onthego-place','schedule-event','my-active-session']){const f=setup({active:false});compile(name+'/index.ts',{'../_shared/onthego-http.ts':f.http,'https://esm.sh/@supabase/supabase-js@2':f.factory},f.Deno);const r=await f.Deno.handler(new Request('https://fixture.invalid',{method:'POST',headers:{Authorization:'Bearer person'},body:'{}'}));assert.equal(r.status,403);assert.equal(f.calls.filter(x=>x.key).length,1);assert(!f.calls.some(x=>x.table));}});
test('malformed registration and schedule bodies fail before data queries',async()=>{for(const name of ['create-onthego-place','schedule-event'])for(const body of ['null','[]','bad json','{}']){const f=setup();const env=f.Deno.env.get;f.Deno.env.get=name=>name==='SUPABASE_SERVICE_ROLE_KEY'?'fixture-server':env(name);compile(name+'/index.ts',{'../_shared/onthego-http.ts':f.http,'https://esm.sh/@supabase/supabase-js@2':f.factory},f.Deno);const r=await f.Deno.handler(new Request('https://fixture.invalid',{method:'POST',headers:{Authorization:'Bearer person'},body}));assert.equal(r.status,400);assert(!f.calls.some(x=>x.table));}});
test('cooldown exposes the server retry timestamp without turning a failure into success',async()=>{const f=setup();f.client.rpc=async()=>({error:{code:'P0001',message:'Please wait until 2099-01-01T00:30:00Z',details:'2099-01-01T00:30:00Z'}});const edge=compile('_shared/onthego-lifecycle.ts',{'https://esm.sh/@supabase/supabase-js@2':f.factory},f.Deno);const r=await edge.handleOnTheGo(new Request('https://fixture.invalid',{method:'POST',headers:{Authorization:'Bearer person'},body:'{}'}),'start');assert.equal(r.status,400);const body=await r.json();assert.equal(body.retry_at,'2099-01-01T00:30:00Z');assert(!body.success);});
test('all public readers and owner handlers allow preflight without auth or data access',async()=>{for(const name of ['live-onthego-map-data','live-session-details','live-sessions-nearby','get-place-schedule','create-onthego-place','schedule-event','my-active-session']){const f=setup();compile(name+'/index.ts',{'../_shared/onthego-http.ts':f.http,'https://esm.sh/@supabase/supabase-js@2':f.factory},f.Deno);const r=await f.Deno.handler(new Request('https://fixture.invalid',{method:'OPTIONS'}));assert.equal(r.status,200);assert.equal(f.calls.length,0);}});
