const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');const root=path.resolve(__dirname,'../..');
const owner='00000000-0000-4000-8000-000000000001',mine='00000000-0000-4000-8000-000000000002',other='00000000-0000-4000-8000-000000000003',eventId='00000000-0000-4000-8000-000000000004';
class HttpError extends Error{constructor(m,status=400){super(m);this.status=status}}
function fixture(name,{places=[{id:mine,name:'Private test business'}],event,events=[],active=true,readError=null,changed={id:eventId,status:'cancelled'}}={}){const calls=[];let handler;const client={from(table){let mutation=false;const steps=[];const q={select(...a){steps.push(['select',...a]);return q},eq(...a){steps.push(['eq',...a]);return q},gt(...a){steps.push(['gt',...a]);return q},in(...a){steps.push(['in',...a]);return q},or(...a){steps.push(['or',...a]);return q},order(...a){steps.push(['order',...a]);return q},range(...a){steps.push(['range',...a]);return q},limit(...a){steps.push(['limit',...a]);return q},update(value){mutation=true;steps.push(['update',value]);return q},maybeSingle(){return q},then(resolve,reject){calls.push({table,steps,mutation});return Promise.resolve({data:mutation?changed:table==='tavvy_places'?places:name==='cancel-scheduled-event'?event:events,error:readError}).then(resolve,reject)}};return q}};const Deno={serve:fn=>{handler=fn},env:{get:()=>undefined}};const exports={};new Function('require','exports','Deno',ts.transpileModule(fs.readFileSync(path.join(root,'supabase/functions',name,'index.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(n=>n.startsWith('jsr:')?{}:n.includes('esm.sh')?{createClient:()=>{throw Error('Must not construct admin without config')}}:{OnTheGoHttpError:HttpError,onTheGoError:e=>e.status||500,onTheGoActor:async()=>{if(!active)throw new HttpError('Inactive account',403);return{client,user:{id:owner}}}},exports,Deno);return{calls,handler}};
const call=(f,path='',body)=>f.handler(new Request('https://fixture.invalid/'+path,{method:body?'POST':'GET',...(body?{body:JSON.stringify(body)}:{})}));
test('a caller with one business cannot select someone else business schedule or history',async()=>{const f=fixture('my-scheduled-events');const r=await call(f,'?tavvy_place_id='+other+'&include_history=true');assert.equal(r.status,403);assert(!f.calls.some(c=>c.table==='scheduled_events'));const text=await r.text();assert(!text.includes(mine));});
test('owner list scopes both parent and events and reports bounded continuation',async()=>{const rows=Array.from({length:3},(_,i)=>({id:'fixture-'+i,tavvy_place_id:mine,scheduled_start:'2099-01-01T00:00:00Z',scheduled_end:'2099-01-01T01:00:00Z'}));const f=fixture('my-scheduled-events',{events:rows});const r=await call(f,'?tavvy_place_id='+mine+'&limit=2');assert.equal(r.status,200);const d=await r.json();assert.equal(d.upcoming_events.length,2);assert.equal(d.has_more,true);assert.equal(d.next_offset,2);assert(f.calls[0].steps.some(s=>s[0]==='eq'&&s[1]==='created_by'&&s[2]===owner));const eventRead=f.calls.find(c=>c.table==='scheduled_events');assert(eventRead.steps.some(s=>s[0]==='eq'&&s[1]==='tavvy_places.created_by'&&s[2]===owner));assert.deepEqual(eventRead.steps.find(s=>s[0]==='range'),['range',0,2]);});
test('invalid pagination/UUID and inactive actor stop before reading schedules',async()=>{for(const query of ['?limit=0','?limit=101','?offset=-1','?offset=10001','?tavvy_place_id=bad']){const f=fixture('my-scheduled-events');assert.equal((await call(f,query)).status,400);assert.equal(f.calls.length,0)}const f=fixture('my-scheduled-events',{active:false});assert.equal((await call(f)).status,403);assert.equal(f.calls.length,0)});
test('list failure is unavailable, never acknowledged as empty',async()=>{const f=fixture('my-scheduled-events',{readError:{message:'fixture failure'}});const r=await call(f);assert.equal(r.status,503);assert(!((await r.json()).success));});
const ownedEvent={id:eventId,tavvy_place_id:mine,created_by:owner,status:'scheduled',tavvy_places:{id:mine,created_by:owner,place_type:'on_the_go',is_deleted:false}};
test('cancel requires active actor AND matching event author AND current parent owner',async()=>{for(const event of [{...ownedEvent,created_by:other},{...ownedEvent,tavvy_places:{...ownedEvent.tavvy_places,created_by:other}}]){const f=fixture('cancel-scheduled-event',{event});assert.equal((await call(f,'',{event_id:eventId})).status,403);assert(!f.calls.some(c=>c.mutation))}const f=fixture('cancel-scheduled-event',{active:false});assert.equal((await call(f,'',{event_id:eventId})).status,403);assert.equal(f.calls.length,0)});
test('cancel acknowledgement requires exact conditional changed row; advisory failure is explicit',async()=>{const missing=fixture('cancel-scheduled-event',{event:ownedEvent,changed:null});assert.equal((await call(missing,'',{event_id:eventId})).status,409);const f=fixture('cancel-scheduled-event',{event:ownedEvent});const r=await call(f,'',{event_id:eventId});assert.equal(r.status,200);const d=await r.json();assert.equal(d.success,true);assert.equal(d.event_id,eventId);assert.equal(d.summary_updated,false);assert(d.warning.includes('cancelled'));const write=f.calls.find(c=>c.mutation);for(const [field,value] of [['id',eventId],['tavvy_place_id',mine],['created_by',owner],['status','scheduled']])assert(write.steps.some(s=>s[0]==='eq'&&s[1]===field&&s[2]===value));});
test('already cancelled event is idempotent and never rewrites its record',async()=>{const f=fixture('cancel-scheduled-event',{event:{...ownedEvent,status:'cancelled'}});const r=await call(f,'',{event_id:eventId});assert.equal(r.status,200);assert(!f.calls.some(c=>c.mutation));});
