const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.resolve(__dirname,'../..');
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject}};
const tick=async()=>{for(let i=0;i<8;i++)await Promise.resolve()};
function harness(){
 let actor='A',slots=[],index=0,effects=[],listener,unmounted=false,lateSets=0,view;const requests=[],enables=[],timers=[];
 const depsEqual=(a,b)=>a&&b&&a.length===b.length&&a.every((v,i)=>Object.is(v,b[i]));
 const hooks={useRef(initial){const i=index++;if(!slots[i])slots[i]={value:{current:initial}};return slots[i].value},useState(initial){const i=index++;if(!slots[i])slots[i]={value:initial};return[slots[i].value,value=>{if(unmounted)lateSets++;slots[i].value=typeof value==='function'?value(slots[i].value):value}]},useCallback(fn,deps){const i=index++;if(!slots[i]||!depsEqual(slots[i].deps,deps))slots[i]={value:fn,deps};return slots[i].value},useEffect(fn,deps){const i=index++;const old=slots[i];if(!old||!depsEqual(old.deps,deps)){slots[i]={deps,cleanup:old?.cleanup};effects.push(()=>{old?.cleanup?.();slots[i]={deps,cleanup:fn()}})}}};
 let holdAuth=null;const supabase={auth:{getSession:()=>holdAuth?holdAuth.promise:Promise.resolve({data:{session:actor?{user:{id:actor},access_token:'token-'+actor}:null}}),onAuthStateChange(fn){listener=fn;return{data:{subscription:{unsubscribe(){}}}}}},functions:{invoke(name,options){const d=deferred();requests.push({...d,name,options});return d.promise}}};
 const exports={};function load(file,dependencies){const exports={};new Function('require','exports',ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(name=>dependencies[name],exports);return exports}
 const contract=load('lib/onthegoOwnerContract.ts',{});
 const code=ts.transpileModule(fs.readFileSync(path.join(root,'lib/useOnTheGoOwner.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
 new Function('require','exports','setTimeout','clearTimeout',code)(name=>{if(name==='react')return hooks;if(name==='./supabaseClient')return{supabase};if(name==='./onthegoDetails')return{enableMobilePlaceDetails:id=>{const d=deferred();enables.push({...d,id});return d.promise}};if(name==='./onthego')return{validCoordinates:(a,b)=>Number.isFinite(a)&&Math.abs(a)<=90&&Number.isFinite(b)&&Math.abs(b)<=180};if(name==='./onthegoOwnerContract')return contract;throw Error(name)},exports,(fn,ms)=>{timers.push({fn,ms});return timers.length},()=>{});
 function render(){index=0;view=exports.useOnTheGoOwner();const pending=effects;effects=[];pending.forEach(fn=>fn());return view}
 return{render,requests,enables,get view(){return view},async switchActor(next){actor=next;listener(next?'SIGNED_IN':'SIGNED_OUT',next?{user:{id:next},access_token:'token-'+next}:null);render();const pending=timers.splice(0);pending.filter(t=>t.ms===0).forEach(t=>t.fn());await tick();render()},holdAuth(){holdAuth=deferred();return holdAuth},releaseAuth(){holdAuth=null},unmount(){unmounted=true;slots.forEach(s=>s?.cleanup?.())},get lateSets(){return lateSets}};
}
const data=(id)=>({data:{success:true,places:[{id:'business-'+id,name:'Business '+id}],sessions:[]},error:null});
async function ready(){const h=harness();h.render();await tick();h.requests[0].resolve(data('A'));await tick();h.render();return h}
test('late owner recovery cannot reintroduce another account businesses',async()=>{const h=harness();h.render();await tick();await h.switchActor('B');assert.equal(h.view.places.length,0);h.requests[1].resolve(data('B'));await tick();h.render();h.requests[0].resolve(data('A'));await tick();h.render();assert.deepEqual(h.view.places.map(p=>p.name),['Business B']);});
test('old request does not clear new account busy state or expose its result',async()=>{const h=await ready();const pending=h.view.register('New A','Food Trucks','Boston');await tick();assert.equal(h.requests[1].options.headers.Authorization,'Bearer token-A');await h.switchActor('B');h.requests[2].resolve(data('B'));await tick();h.render();const next=h.view.register('New B','Food Trucks','Boston');await tick();h.render();assert.equal(h.view.busy,true);h.requests[1].resolve({data:{success:true,place:{id:'new-a',name:'Private A'}}});await pending;h.render();assert.equal(h.view.busy,true);assert(!h.view.places.some(p=>p.id==='new-a'));h.requests[3].resolve({data:{success:true,place:{id:'new-b',name:'New B'}}});await next;h.render();assert.equal(h.view.busy,false);assert(h.view.places.some(p=>p.id==='new-b'));});
test('auth switch while resolving credentials prevents the old write entirely',async()=>{const h=await ready();const auth=h.holdAuth();const pending=h.view.register('New A','Food Trucks','Boston');await h.switchActor(null);auth.resolve({data:{session:{user:{id:'A'},access_token:'token-A'}}});await pending;h.render();assert.equal(h.requests.length,1);assert.equal(h.view.signedIn,false);assert.equal(h.view.places.length,0)});
test('late enable response cannot navigate new account, and unmount prevents state writes',async()=>{const h=await ready();const p=h.view.enableDetails();await tick();await h.switchActor(null);h.enables[0].resolve('canonical-a');assert.equal(await p,null);const m=await ready();const pending=m.view.register('New A','Food Trucks','Boston');await tick();m.unmount();m.requests[1].reject(Error('Old private failure'));await pending;assert.equal(m.lateSets,0)});
