const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.resolve(__dirname,'../..');
class HttpError extends Error{constructor(message,status=400){super(message);this.status=status}}
function load(tables={}){const calls=[],Deno={serve:fn=>{Deno.handler=fn}};const client={from(table){let after='',limit=500;const steps=[];const q={select(x){steps.push(['select',x]);return q},eq(...x){steps.push(['eq',...x]);return q},gt(key,v){steps.push(['gt',key,v]);if(key==='id')after=v;return q},gte(...x){steps.push(['gte',...x]);return q},lte(...x){steps.push(['lte',...x]);return q},or(x){steps.push(['or',x]);return q},order(...x){steps.push(['order',...x]);return q},limit(n){limit=n;return q},then(resolve,reject){calls.push({table,steps,after,limit});return Promise.resolve({data:(tables[table]||[]).filter(x=>x.id>after).slice(0,limit),error:null}).then(resolve,reject)}};return q}};const exports={};new Function('require','exports','Deno',ts.transpileModule(fs.readFileSync(path.join(root,'supabase/functions/live-onthego-map-data/index.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(name=>name.startsWith('jsr:')?{}:{onTheGoReader:async()=>client,onTheGoError:e=>e.status||500,OnTheGoHttpError:HttpError},exports,Deno);return{...exports,handler:Deno.handler,calls}}
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');const future='2099-01-01T12:00:00Z';
const business=n=>({id:id(n),name:'Private test mobile '+n,place_type:'on_the_go',tavvy_category:'Food Trucks'});
const live=(n,lat,lng)=>({id:id(n),tavvy_place_id:id(n+100),session_lat:lat,session_lng:lng,scheduled_end_at:future,tavvy_places:business(n+100)});
const stop=(n,lat,lng)=>({id:id(n),tavvy_place_id:id(n+200),latitude:lat,longitude:lng,scheduled_start:future,scheduled_end:'2099-01-01T13:00:00Z',location_name:'Private test stop',tavvy_places:business(n+200)});
test('Boston bounds apply equally to live and scheduled results; California never appears',async()=>{const f=load({live_sessions:[live(1,42.36,-71.06),live(2,34.05,-118.24)],scheduled_events:[stop(3,42.35,-71.05),stop(4,34.05,-118.24)]});const r=await f.handler(new Request('https://fixture.invalid?north=43&south=42&east=-70&west=-72'));assert.equal(r.status,200);const d=await r.json();assert.equal(d.live_count,1);assert.equal(d.scheduled_count,1);assert.equal(d.scheduled_places[0].tavvy_place_id,id(203));assert.equal(d.geojson.features.length,2);for(const c of f.calls){assert(c.steps.some(s=>s[0]==='gte'&&s[2]===42));assert(c.steps.some(s=>s[0]==='lte'&&s[2]===-70));}assert(!f.calls.some(c=>c.table==='tavvy_places'));});
test('zero center is a valid radius query for both record types and gets a server box',async()=>{const f=load({live_sessions:[live(1,0,0),live(2,1,1)],scheduled_events:[stop(3,0,.01),stop(4,42,-71)]});const r=await f.handler(new Request('https://fixture.invalid?center_lat=0&center_lng=0&radius_meters=10000'));const d=await r.json();assert.equal(d.live_count,1);assert.equal(d.scheduled_count,1);assert(f.calls.every(c=>c.steps.some(s=>s[0]==='gte'&&s[2]<0)&&c.steps.some(s=>s[0]==='lte'&&s[2]>0)));});
test('bounds crossing the dateline retain both sides and reject other longitudes',async()=>{const f=load();const p=await f.readParams(new Request('https://fixture.invalid?north=10&south=-10&west=170&east=-170'));assert(f.inScope(0,179,p));assert(f.inScope(0,-179,p));assert(!f.inScope(0,0,p));const calls=[];const q={gte(){return q},lte(){return q},or(s){calls.push(s);return q}};f.restrictLocation(q,'latitude','longitude',p);assert.deepEqual(calls,['longitude.gte.170,longitude.lte.-170']);});
test('invalid, incomplete and nonfinite scope is rejected before any data read',async()=>{for(const query of ['?north=43','?center_lat=0','?center_lat=&center_lng=0','?center_lat=NaN&center_lng=0','?radius_meters=50','?center_lat=0&center_lng=0&radius_meters=-1','?north=40&south=45&west=-72&east=-70','?include_scheduled=maybe']){const f=load();assert.equal((await f.handler(new Request('https://fixture.invalid'+query))).status,400);assert.equal(f.calls.length,0)}});
test('stable cursor pagination reads beyond the default page without truncation',async()=>{const all=Array.from({length:1001},(_,n)=>live(n+1,0,0));const f=load({live_sessions:all});const r=await f.handler(new Request('https://fixture.invalid?include_scheduled=false'));const d=await r.json();assert.equal(r.status,200);assert.equal(d.live_count,1001);assert.deepEqual(f.calls.map(c=>c.after),['',id(500),id(1000)]);assert.deepEqual(f.calls.map(c=>c.limit),[500,500,500]);});
test('full-read cap returns unavailable without a misleading partial success',async()=>{const f=load({live_sessions:Array.from({length:10001},(_,n)=>live(n+1,0,0))});const r=await f.handler(new Request('https://fixture.invalid?include_scheduled=false'));assert.equal(r.status,503);const d=await r.json();assert(!d.success);assert(!d.sessions);assert(d.error.includes('Narrow'));assert.equal(f.calls.at(-1).limit,1);});
test('scheduled next stop is the earliest matching event and a live business is not duplicated',async()=>{const first=stop(2,0,0),later={...first,id:id(3),scheduled_start:'2099-01-02T12:00:00Z'},sameLive={...stop(4,0,0),tavvy_place_id:id(101),tavvy_places:business(101)};const f=load({live_sessions:[live(1,0,0)],scheduled_events:[first,later,sameLive]});const d=await(await f.handler(new Request('https://fixture.invalid'))).json();assert.equal(d.scheduled_count,1);assert.equal(d.scheduled_places[0].next_event.scheduled_start,first.scheduled_start);});

test('map response carries only stored canonical place associations, independently of mobile and session IDs',async()=>{const a=live(1,0,0),b=stop(2,0,0),c=stop(3,0,0);a.tavvy_places.canonical_place_id=id(801);b.tavvy_places.canonical_place_id=id(802);const f=load({live_sessions:[a],scheduled_events:[b,c]});const d=await(await f.handler(new Request('https://fixture.invalid'))).json();assert.equal(d.sessions[0].canonical_place_id,id(801));assert.equal(d.scheduled_places[0].canonical_place_id,id(802));assert.equal(d.scheduled_places[1].canonical_place_id,null);assert.deepEqual(d.geojson.features.map(x=>x.properties.canonical_place_id),[id(801),id(802),null]);assert(f.calls.every(c=>c.steps.find(s=>s[0]==='select')[1].includes('canonical_place_id')));});
