const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');const root=path.resolve(__dirname,'../..');
const placeA='00000000-0000-4000-8000-000000000001',placeB='00000000-0000-4000-8000-000000000002',stopId='00000000-0000-4000-8000-000000000003';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject}};const tick=async()=>{for(let i=0;i<8;i++)await Promise.resolve()};
function harness(){let user={id:'A'},place=placeA,slots=[],index=0,effects=[],unmounted=false,lateSets=0,view;const requests=[];const equal=(a,b)=>a&&b&&a.length===b.length&&a.every((v,i)=>Object.is(v,b[i]));const hooks={useState(initial){const i=index++;if(!slots[i])slots[i]={value:initial};return[slots[i].value,v=>{if(unmounted)lateSets++;slots[i].value=typeof v==='function'?v(slots[i].value):v}]},useRef(initial){const i=index++;if(!slots[i])slots[i]={value:{current:initial}};return slots[i].value},useCallback(fn,deps){const i=index++;if(!slots[i]||!equal(slots[i].deps,deps))slots[i]={value:fn,deps};return slots[i].value},useEffect(fn,deps){const i=index++;const old=slots[i];if(!old||!equal(old.deps,deps)){slots[i]={deps,cleanup:old?.cleanup};effects.push(()=>{old?.cleanup?.();slots[i]={deps,cleanup:fn()}})}}};
const supabase={auth:{getSession:async()=>({data:{session:user?{user,access_token:'token-'+user.id}:null}})},functions:{invoke(name,options){const d=deferred();requests.push({...d,name,options});return d.promise}}};const exports={};new Function('require','exports',ts.transpileModule(fs.readFileSync(path.join(root,'lib/useOnTheGoSchedule.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(n=>n==='react'?hooks:n.includes('AuthContext')?{useAuth:()=>({user})}:n==='./supabaseClient'?{supabase}:{isBusinessUuid:v=>typeof v==='string'&&/^[a-f0-9-]{36}$/.test(v)},exports);
function render(flush=true){index=0;view=exports.useOnTheGoSchedule(place);if(flush){const next=effects;effects=[];next.forEach(fn=>fn())}return view}return{render,requests,get view(){return view},switchUser(next,nextPlace=placeB){user=next?{id:next}:null;place=nextPlace},unmount(){unmounted=true;slots.forEach(x=>x?.cleanup?.())},get lateSets(){return lateSets}}}
const row=(place=placeA)=>({id:stopId,tavvy_place_id:place,status:'scheduled',location_name:'Private fixture',latitude:0,longitude:0,scheduled_start:'2099-01-01T00:00:00Z',scheduled_end:'2099-01-01T01:00:00Z'});
const response=(place=placeA,hasMore=false)=>({data:{success:true,upcoming_events:[row(place)],has_more:hasMore,next_offset:hasMore?20:null},error:null});
async function ready(hasMore=false){const h=harness();h.render();await tick();h.requests[0].resolve(response(placeA,hasMore));await tick();h.render();return h}
test('late account A schedule and error cannot replace account B view',async()=>{const h=await ready();const refresh=h.view.refresh();await tick();h.switchUser('B');h.render(false);assert.equal(h.view.stops.length,0);assert.equal(h.view.error,'');h.render();await tick();h.requests[2].resolve(response(placeB));await tick();h.render();h.requests[1].reject(Error('A private failure'));await refresh;h.render();assert.equal(h.view.stops[0].tavvy_place_id,placeB);assert.equal(h.view.error,'')});
test('cancel failure keeps the stop and never reports success',async()=>{const h=await ready();const p=h.view.cancel(stopId);await tick();assert.equal(h.requests[1].options.headers.Authorization,'Bearer token-A');h.requests[1].resolve({error:Error('fixture failure')});assert.equal(await p,false);h.render();assert.equal(h.view.stops.length,1);assert(h.view.error.includes('could not be cancelled'));assert.equal(h.view.message,'')});
test('held pagination cannot restore a cancelled stop after exact acknowledgement',async()=>{const h=await ready(true);const page=h.view.loadMore();await tick();const cancel=h.view.cancel(stopId);await tick();h.requests[2].resolve({data:{success:true,event_id:stopId}});assert.equal(await cancel,true);await tick();h.render();assert.equal(h.view.stops.length,0);h.requests[1].resolve(response());await page;h.render();assert.equal(h.view.stops.length,0);h.requests[3].resolve({data:{success:true,upcoming_events:[],has_more:false}});await tick();h.render();assert.equal(h.view.stops.length,0);assert(h.view.message.includes('cancelled'))});
test('late cancellation after auth switch or unmount cannot modify another owner state',async()=>{const h=await ready();const p=h.view.cancel(stopId);await tick();h.switchUser('B');h.render();await tick();h.requests[2].resolve(response(placeB));await tick();h.render();h.requests[1].resolve({data:{success:true,event_id:stopId}});assert.equal(await p,false);h.render();assert.equal(h.view.stops[0].tavvy_place_id,placeB);assert.equal(h.view.message,'');const m=await ready();const late=m.view.cancel(stopId);await tick();m.unmount();m.requests[1].reject(Error('private failure'));await late;assert.equal(m.lateSets,0)});
