// Local PostgreSQL execution of the production migration, with the audited live columns.
// Run: NODE_PATH=/path/to/pglite/node_modules node scripts/tests/ordering-sql.test.cjs
const { PGlite } = require('@electric-sql/pglite');
const { readFileSync } = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
(async () => {
 const db = new PGlite();
 const id = n => `00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
 const place=id(1), otherPlace=id(2), owner=id(10), otherOwner=id(11), customer=id(20), otherCustomer=id(21);
 const dish=id(101), otherDish=id(102);
 await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE SCHEMA auth;
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 GRANT USAGE ON SCHEMA public,auth TO anon,authenticated;
 CREATE TABLE places(id uuid PRIMARY KEY,status text,ordering_enabled boolean);
 CREATE TABLE menus(id uuid PRIMARY KEY,place_id uuid REFERENCES places,is_active boolean);
 CREATE TABLE menu_categories(id uuid PRIMARY KEY,menu_id uuid REFERENCES menus);
 CREATE TABLE menu_items(id uuid PRIMARY KEY,category_id uuid REFERENCES menu_categories,place_id uuid,name text NOT NULL,price numeric,is_available boolean);
 CREATE TABLE restaurant_tables(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),place_id uuid REFERENCES places,table_number text NOT NULL,table_label text,qr_code_url text,is_active boolean DEFAULT true,created_at timestamptz DEFAULT now(),UNIQUE(place_id,table_number));
 CREATE TABLE orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),place_id uuid REFERENCES places ON DELETE CASCADE,table_id uuid REFERENCES restaurant_tables,table_number text NOT NULL,customer_id uuid,customer_name text,status text DEFAULT 'pending',subtotal numeric DEFAULT 0,tax numeric DEFAULT 0,total numeric DEFAULT 0,notes text,confirmed_by text,confirmed_at timestamptz,prepared_at timestamptz,served_at timestamptz,cancelled_at timestamptz,cancel_reason text,created_at timestamptz DEFAULT now(),updated_at timestamptz);
 CREATE TABLE order_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid REFERENCES orders ON DELETE CASCADE,menu_item_id uuid REFERENCES menu_items,name text NOT NULL,price numeric,quantity integer DEFAULT 1,notes text,status text DEFAULT 'pending',created_at timestamptz DEFAULT now());
 CREATE TABLE verified_restaurant_owners(user_id uuid,place_id uuid);
 CREATE FUNCTION has_verified_restaurant_claim(p_place_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $$ SELECT EXISTS(SELECT 1 FROM verified_restaurant_owners WHERE user_id=auth.uid() AND place_id=p_place_id) $$;
 REVOKE ALL ON FUNCTION has_verified_restaurant_claim(uuid) FROM public; GRANT EXECUTE ON FUNCTION has_verified_restaurant_claim(uuid) TO authenticated;
 -- Reproduce the audited permissive policies to prove they are removed.
 ALTER TABLE orders ENABLE ROW LEVEL SECURITY; ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
 GRANT ALL ON orders,order_items,restaurant_tables TO anon,authenticated;
 CREATE POLICY legacy_read_orders ON orders FOR SELECT USING(true);
 CREATE POLICY legacy_insert_orders ON orders FOR INSERT WITH CHECK(true);
 CREATE POLICY legacy_update_orders ON orders FOR UPDATE TO authenticated USING(true);
 CREATE POLICY legacy_read_items ON order_items FOR SELECT USING(true);
 CREATE POLICY legacy_insert_items ON order_items FOR INSERT WITH CHECK(true);
 INSERT INTO places VALUES('${place}','active',false),('${otherPlace}','active',false);
 INSERT INTO menus VALUES('${place}','${place}',true),('${otherPlace}','${otherPlace}',true);
 INSERT INTO menu_categories VALUES('${place}','${place}'),('${otherPlace}','${otherPlace}');
 INSERT INTO menu_items VALUES('${dish}','${place}','${place}','Pasta',12.34,true),('${otherDish}','${otherPlace}','${otherPlace}','Other dish',99,true);
 INSERT INTO verified_restaurant_owners VALUES('${owner}','${place}'),('${otherOwner}','${otherPlace}');`);
 const migration=readFileSync(path.join(__dirname,'../../supabase/migrations/202609210003_ordering_integrity.sql'),'utf8');
 await db.exec(migration);await db.exec(migration);
 const as = async (who,role='authenticated') => db.exec(`RESET ROLE; SET ROLE ${role}; SELECT set_config('request.jwt.claim.sub','${who||''}',false)`);
 const context = async () => (await db.query('SELECT get_place_ordering_context($1,$2) AS result',[place,'7'])).rows[0].result;
 const submit = async (options={}) => {
  const values=[options.place||place,options.table||'7',JSON.stringify(options.items||[{menu_item_id:dish,quantity:2,notes:'No cheese'}]),options.notes||'Peanut allergy',options.name||'Guest',options.key||crypto.randomUUID(),options.total??26.72];
  return (await db.query('SELECT submit_place_order($1,$2,$3::jsonb,$4,$5,$6,$7) AS result',values)).rows[0].result;
 };
 const count = async () => {await db.exec('RESET ROLE');return Number((await db.query('SELECT count(*) FROM orders')).rows[0].count)};
 await as('', 'anon');assert.equal((await context()).ready,false);
 await assert.rejects(submit(),/permission denied/);
 await assert.rejects(db.query('SELECT * FROM orders'),/permission denied/);
 await assert.rejects(db.query('SELECT * FROM restaurant_tables'),/permission denied/);
 await as(customer);await assert.rejects(submit(),/not available/);
 await assert.rejects(db.query('SELECT configure_place_ordering($1,true,825)',[place]),/ownership/);
 await as(owner);
 await assert.rejects(db.query('SELECT configure_place_ordering($1,true,825)',[place]),/active table/);
 await db.query('SELECT set_ordering_table($1,$2,true)',[place,'7']);
 await assert.rejects(db.query('SELECT configure_place_ordering($1,true,NULL)',[place]),/tax rate/);
 await db.query('SELECT configure_place_ordering($1,true,825)',[place]);
 assert.equal((await context()).taxBasisPoints,825);
 assert.equal((await context()).tableValid,true);
 await as(customer);
 const requestKey=crypto.randomUUID(),order=await submit({key:requestKey});
 assert.equal(Number(order.subtotal),24.68);assert.equal(Number(order.tax),2.04);assert.equal(Number(order.total),26.72);
 assert.equal(order.customer_id,customer);assert.equal(order.notes,'Peanut allergy');assert.equal(order.items[0].notes,'No cheese');assert.equal(order.items[0].name,'Pasta');assert.equal(Number(order.items[0].price),12.34);
 assert.equal((await submit({key:requestKey})).id,order.id,'same request returns original order');
 await assert.rejects(submit({key:requestKey,notes:'Changed'}),/different order/);
 assert.equal((await db.query('SELECT * FROM orders')).rows.length,1);
 assert.equal((await db.query('SELECT * FROM order_items')).rows.length,1);
 await assert.rejects(db.query('UPDATE orders SET status=\'served\''),/permission denied/);
 await assert.rejects(db.query('INSERT INTO orders(place_id,table_number) VALUES($1,\'7\')',[place]),/permission denied/);
 await assert.rejects(db.query('UPDATE order_items SET price=0'),/permission denied/);
 await as(otherCustomer);assert.equal((await db.query('SELECT * FROM orders')).rows.length,0);assert.equal((await db.query('SELECT * FROM order_items')).rows.length,0);
 await as(otherOwner);assert.equal((await db.query('SELECT * FROM orders')).rows.length,0);
 await assert.rejects(db.query('SELECT transition_place_order($1,\'pending\',\'confirmed\',NULL)',[order.id]),/access/);
 await as(customer);
 await assert.rejects(submit({total:1}),/MENU_CHANGED/);
 await assert.rejects(submit({items:[{menu_item_id:otherDish,quantity:1,notes:''}],total:99}),/unavailable/);
 await assert.rejects(submit({table:'unknown'}),/active table/);
 await assert.rejects(submit({items:[{menu_item_id:dish,quantity:0,notes:''}]}),/1–20/);
 await assert.rejects(submit({items:[{menu_item_id:dish,quantity:'2',notes:''}]}),/quantity/);
 await assert.rejects(submit({items:[{menu_item_id:dish,quantity:1,notes:'x'.repeat(501)}]}),/notes/);
 await assert.rejects(submit({notes:'x'.repeat(1001)}),/too long/);
 await assert.rejects(submit({items:[{menu_item_id:dish,quantity:1},{menu_item_id:dish,quantity:1}]}),/duplicate/);
 assert.equal(await count(),1,'invalid requests never leave headers');
 await db.exec(`UPDATE menu_items SET is_available=false WHERE id='${dish}'`);await as(customer);
 await assert.rejects(submit(),/unavailable/);assert.equal((await submit({key:requestKey})).id,order.id,'retry still resolves after availability changes');
 await db.exec(`RESET ROLE; UPDATE menu_items SET is_available=true WHERE id='${dish}'; UPDATE menus SET is_active=false WHERE id='${place}'`);await as(customer);await assert.rejects(submit(),/unavailable/);
 await db.exec(`RESET ROLE; UPDATE menus SET is_active=true WHERE id='${place}'; UPDATE restaurant_tables SET is_active=false WHERE place_id='${place}'`);await as(customer);await assert.rejects(submit(),/active table/);
 await db.exec(`RESET ROLE; UPDATE restaurant_tables SET is_active=true WHERE place_id='${place}'; UPDATE places SET status='inactive' WHERE id='${place}'`);await as(customer);await assert.rejects(submit(),/not accepting/);
 await db.exec(`RESET ROLE; UPDATE places SET status='active' WHERE id='${place}';
 CREATE FUNCTION test_fail_item() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'test item insert failure'; END $$;
 CREATE TRIGGER test_item_failure BEFORE INSERT ON order_items FOR EACH ROW EXECUTE FUNCTION test_fail_item();`);
 await as(customer);await assert.rejects(submit(),/test item insert failure/);assert.equal(await count(),1,'header and lines roll back together');await db.exec('DROP TRIGGER test_item_failure ON order_items');
 await as(owner);
 assert.equal((await db.query('SELECT * FROM orders')).rows.length,1);
 await assert.rejects(db.query('SELECT transition_place_order($1,\'pending\',\'ready\',NULL)',[order.id]),/not allowed/);
 const transition = async (expected,next,reason=null) => (await db.query('SELECT transition_place_order($1,$2,$3,$4) AS result',[order.id,expected,next,reason])).rows[0].result;
 await assert.rejects(transition('pending',null),/not allowed/);
 const confirmed=await transition('pending','confirmed');assert.ok(confirmed.confirmed_at);assert.equal(confirmed.items[0].status,'confirmed');
 await assert.rejects(transition('pending','confirmed'),/status changed/);
 await transition('confirmed','preparing');await transition('preparing','ready');const served=await transition('ready','served');assert.ok(served.served_at);
 await assert.rejects(transition('served','cancelled','No stock'),/not allowed/);
 await as(customer);const cancelled=await submit();await as(owner);
 await assert.rejects(db.query('SELECT transition_place_order($1,\'pending\',\'cancelled\',NULL)',[cancelled.id]),/reason/);
 await db.query('SELECT transition_place_order($1,\'pending\',\'cancelled\',\'Sold out\')',[cancelled.id]);
 await as(customer);assert.equal((await db.query('SELECT cancel_reason FROM orders WHERE id=$1',[cancelled.id])).rows[0].cancel_reason,'Sold out');
 await as(owner);await db.query('SELECT configure_place_ordering($1,true,887.5)',[place]);await as(customer);const fractionalTax=await submit({total:26.87});assert.equal(Number(fractionalTax.tax),2.19,'merchant tax supports fractional basis points');
 await as(owner);await db.query('SELECT configure_place_ordering($1,false,0)',[place]);await as(customer);await assert.rejects(submit(),/not available/);
 await db.close();console.log('PASS ordering SQL: migration replay, scoped reads, authenticated atomic submission, configured tax/server prices, availability/table/place validation, limits, idempotency, full rollback, owner-only lifecycle and cancellation.');
})().catch(error=>{console.error(error);process.exitCode=1;});
