const { PGlite }=require('@electric-sql/pglite');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
const db=new PGlite();
await db.exec(`CREATE ROLE authenticated;CREATE ROLE anon;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;CREATE SCHEMA storage;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql STABLE AS $$ SELECT coalesce(nullif(current_setting('request.jwt.claim.role',true),''),current_user::text) $$;
CREATE TABLE auth.users(id uuid PRIMARY KEY,banned_until timestamptz);CREATE TABLE public.users(id uuid PRIMARY KEY);
CREATE TABLE places(id uuid PRIMARY KEY,name text,cover_image_url text,status text DEFAULT 'active',is_active boolean DEFAULT true,latitude double precision,longitude double precision);
CREATE TABLE storage.objects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),bucket_id text,name text,owner uuid,owner_id text,metadata jsonb,created_at timestamptz DEFAULT now());
CREATE TABLE story_publish_settings(singleton boolean PRIMARY KEY,public_storage_origin text);INSERT INTO story_publish_settings VALUES(true,'https://scasgwrikoqdwlwlwcff.supabase.co');
CREATE TABLE place_photos(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),place_id uuid NOT NULL,uploaded_by uuid REFERENCES public.users(id),user_id uuid REFERENCES auth.users(id),url text NOT NULL,caption text,thumbnail_url text,is_owner_photo boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),status text NOT NULL DEFAULT 'live',flagged_count integer NOT NULL DEFAULT 0,removed_reason text,removed_at timestamptz,removed_by uuid REFERENCES public.users(id),likes_count integer DEFAULT 0,is_verified boolean DEFAULT false,is_flagged boolean DEFAULT false,flag_reason text,is_cover boolean DEFAULT false);
CREATE TABLE place_stories(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),place_id uuid,user_id uuid,media_url text,media_path text,media_type text,caption text,story_kind text,status text,created_at timestamptz DEFAULT now(),expires_at timestamptz,is_permanent boolean);
CREATE TABLE place_story_highlights(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),place_id uuid,title text,is_active boolean,position int);
CREATE TABLE place_story_highlight_items(highlight_id uuid,story_id uuid,position int);
CREATE TABLE pro_business_claims(place_id uuid,user_id uuid,claim_kind text,status text,ownership_verified_at timestamptz);
CREATE FUNCTION has_verified_restaurant_claim(p_place_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $$ SELECT auth.uid() IS NOT NULL AND EXISTS(SELECT 1 FROM public.pro_business_claims WHERE place_id=p_place_id AND user_id=auth.uid() AND claim_kind='restaurant' AND status='verified' AND ownership_verified_at IS NOT NULL) $$;
GRANT USAGE ON SCHEMA public,auth,storage TO anon,authenticated;GRANT ALL ON ALL TABLES IN SCHEMA public,storage TO anon,authenticated;
ALTER TABLE place_photos ENABLE ROW LEVEL SECURITY;ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
CREATE POLICY photo_insert_old ON place_photos FOR INSERT TO PUBLIC WITH CHECK(true);CREATE POLICY photo_read_old ON place_photos FOR SELECT TO PUBLIC USING(true);CREATE POLICY photo_delete_old ON place_photos FOR DELETE TO PUBLIC USING(auth.uid()=uploaded_by);
CREATE POLICY asset_read ON storage.objects FOR SELECT TO PUBLIC USING(true);CREATE POLICY asset_delete_old ON storage.objects FOR DELETE TO PUBLIC USING(split_part(name,'/',1)=auth.uid()::text);`);
await db.exec(fs.readFileSync(path.join(__dirname,'../../supabase/migrations/202609210007_restaurant_owner_media.sql'),'utf8'));
const uid=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`,owner=uid(1),guest=uid(2),place=uid(10),other=uid(11);
await db.exec(`INSERT INTO auth.users(id) VALUES('${owner}'),('${guest}');INSERT INTO public.users VALUES('${guest}');INSERT INTO places(id,name) VALUES('${place}','Media test'),('${other}','Other restaurant');INSERT INTO pro_business_claims VALUES('${place}','${owner}','restaurant','verified',now());`);
let serial=0;
const signIn=async(actor,role='authenticated')=>db.exec(`RESET ROLE;SET ROLE ${role};SELECT set_config('request.jwt.claim.sub','${actor||''}',false),set_config('request.jwt.claim.role','${role}',false)`);
const asset=async(actor=owner,target=place,meta={mimetype:'image/jpeg',size:500})=>{const media=`${actor}/${target}/photo-${++serial}.jpg`;await db.exec('RESET ROLE');await db.query('INSERT INTO storage.objects(bucket_id,name,owner,owner_id,metadata) VALUES($1,$2,$3,$4,$5)',['place-photos',media,actor,actor,JSON.stringify(meta)]);await signIn(actor);return media;};
const url=media=>'https://scasgwrikoqdwlwlwcff.supabase.co/storage/v1/object/public/place-photos/'+media;
const publish=async(media,target=place,caption='Our food')=>(await db.query('SELECT publish_restaurant_owner_photo($1,$2,$3) result',[target,media,caption])).rows[0].result;
const list=async(offset=0,limit=24)=>(await db.query('SELECT get_restaurant_owner_media($1,$2,$3) result',[place,offset,limit])).rows[0].result;
const ownMedia=await asset();
await signIn(null,'anon');await assert.rejects(publish(ownMedia),/permission denied/);await assert.rejects(db.query('INSERT INTO place_photos(place_id,user_id,url) VALUES($1,$2,$3)',[place,owner,url(ownMedia)]),/row-level security/);
await signIn(guest);await assert.rejects(publish(ownMedia),/PHOTO_OWNER_REQUIRED/);await assert.rejects(list(),/PHOTO_OWNER_REQUIRED/);
const guestMedia=await asset(guest);
// Existing authenticated guest flow still works, and cannot spoof owner status or another author.
const guestPhoto=(await db.query('INSERT INTO place_photos(place_id,user_id,uploaded_by,url) VALUES($1,$2,$2,$3) RETURNING id',[place,guest,url(guestMedia)])).rows[0].id;
await assert.rejects(db.query('INSERT INTO place_photos(place_id,user_id,url,is_owner_photo) VALUES($1,$2,$3,true)',[place,guest,url(guestMedia)]),/PHOTO_OWNER_REQUIRED/);
await assert.rejects(db.query('INSERT INTO place_photos(place_id,user_id,url) VALUES($1,$2,$3)',[place,owner,url(guestMedia)]),/PHOTO_AUTHOR_REQUIRED/);
await assert.rejects(db.query('INSERT INTO place_photos(place_id,user_id,url) VALUES($1,$2,$3)',[place,guest,url(ownMedia)]),/PHOTO_ASSET_NOT_OWNED/);
await signIn(owner);await assert.rejects(publish(guestMedia),/PHOTO_ASSET_NOT_OWNED/);
await assert.rejects(publish(ownMedia,other),/PHOTO_OWNER_REQUIRED/);
const photo=await publish(ownMedia);assert.equal((await publish(ownMedia)).id,photo.id,'retry idempotent');
await assert.rejects(publish(ownMedia,place,'Changed'),/PHOTO_RETRY_MISMATCH/);
assert.equal((await list()).photos.length,1);assert.equal((await list()).photos[0].id,photo.id,'guest photo not included in owner controls');
assert.equal((await db.query('SELECT uploaded_by FROM place_photos WHERE id=$1',[photo.id])).rows[0].uploaded_by,null,'owner upload does not require a fabricated public.users row');
await assert.rejects(db.query('SELECT set_restaurant_owner_cover($1,$2)',[place,guestPhoto]),/PHOTO_AUTHOR_REQUIRED/);
await assert.rejects(db.query('SELECT remove_restaurant_owner_photo($1,$2)',[place,guestPhoto]),/PHOTO_AUTHOR_REQUIRED/);
await db.query('SELECT set_restaurant_owner_cover($1,$2)',[place,photo.id]);assert.equal((await db.query('SELECT cover_image_url FROM places WHERE id=$1',[place])).rows[0].cover_image_url,photo.url);
await db.query('DELETE FROM place_photos WHERE id=$1',[guestPhoto]);assert.equal((await db.query('SELECT count(*)::int n FROM place_photos WHERE id=$1',[guestPhoto])).rows[0].n,1,'merchant direct delete cannot remove guest photo');
await db.query('DELETE FROM storage.objects WHERE name=$1',[guestMedia]);assert.equal((await db.query('SELECT count(*)::int n FROM storage.objects WHERE name=$1',[guestMedia])).rows[0].n,1,'merchant cannot remove guest storage');
const huge=await asset(owner,place,{mimetype:'image/jpeg',size:10485761});await assert.rejects(publish(huge),/PHOTO_TOO_LARGE/);
const invalid=await asset(owner,place,{mimetype:'video/mp4',size:500});await assert.rejects(publish(invalid),/PHOTO_TYPE_INVALID/);
await db.exec(`RESET ROLE;UPDATE places SET status='draft' WHERE id='${place}'`);await signIn(owner);await assert.rejects(publish(invalid),/PHOTO_PLACE_UNAVAILABLE/);
await db.exec(`RESET ROLE;UPDATE places SET status='active' WHERE id='${place}'`);await signIn(owner);
const second=await publish(await asset());const page=await list(0,1),page2=await list(page.nextOffset,1);assert.equal(page.hasMore,true);assert.equal(page2.hasMore,false);assert.notEqual(page.photos[0].id,page2.photos[0].id);assert.equal(page.totals.photos,2);
const removed=(await db.query('SELECT remove_restaurant_owner_photo($1,$2) result',[place,photo.id])).rows[0].result;assert.equal(removed.media_path,ownMedia);assert.equal((await db.query('SELECT cover_image_url FROM places WHERE id=$1',[place])).rows[0].cover_image_url,null);
await signIn(null,'anon');assert.equal((await db.query('SELECT count(*)::int n FROM place_photos WHERE id=$1',[photo.id])).rows[0].n,0,'removed metadata is hidden even with legacy permissive read policies');
await db.exec('RESET ROLE');await db.exec(`CREATE FUNCTION fail_owner_photo_receipt() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'forced receipt failure';END$$;CREATE TRIGGER fail_owner_photo_receipt BEFORE INSERT ON restaurant_owner_photo_uploads FOR EACH ROW EXECUTE FUNCTION fail_owner_photo_receipt();`);
const failed=await asset();await assert.rejects(publish(failed),/forced receipt failure/);assert.equal((await db.query('SELECT get_my_restaurant_photo_upload($1) result',[failed])).rows[0].result,null);
assert.equal((await db.query('SELECT count(*)::int n FROM place_photos WHERE url=$1',[url(failed)])).rows[0].n,0,'photo row rolled back with receipt failure');
await db.close();console.log('Owner media SQL passed: verified ownership, guest preservation, legacy customer uploads, author spoofing, asset ownership, limits, cover, pagination, removal visibility, idempotency and rollback.');
})().catch(error=>{console.error(error);process.exit(1)});
