/** Isolated local UI checks. All remote traffic is mocked; writes never reach a server. */
const puppeteer=require('puppeteer'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.resolve(__dirname,'../..'),base=process.env.TAVVY_PUBLIC_COPY_BASE||'http://127.0.0.1:3862',out=process.env.TAVVY_PUBLIC_COPY_QA||'/private/tmp/tavvy-discovery-locale-finishing-20260921/browser';
const maps={};new Function('exports',ts.transpileModule(fs.readFileSync(path.join(root,'lib/releaseCopy.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(maps);
const languages=['en','pt','es','de','ar'],catalogs=Object.fromEntries(languages.map(l=>[l,JSON.parse(fs.readFileSync(path.join(root,`public/locales/${l}/common.json`)))]));
const copy=(lang,text)=>{if(lang==='en')return text;const key=maps.RELEASE_COPY_KEYS[text]?'release.'+maps.RELEASE_COPY_KEYS[text]:maps.EXISTING_COPY_KEYS[text.toLowerCase()];return key?.split('.').reduce((o,p)=>o?.[p],catalogs[lang])||text;};
const place={id:'00000000-0000-4000-8000-000000000039',name:'Untranslated Camp Name',tavvy_category:'rv_camping',tavvy_subcategory:'campground',city:'Boston',region:'MA',cover_image_url:null,photos:[],status:'active'};
const article={id:'00000000-0000-4000-8000-000000000041',title:'Untranslated article title',slug:'local-only-fixture',excerpt:'Untranslated excerpt',cover_image_url:'/images/ecard-examples/soft-folds.svg',author_name:'Untranslated Author',author_avatar_url:'/images/ecard-examples/cedar-mark.svg',category_id:null,status:'published',published_at:'2026-09-20T00:00:00Z'};
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage();await page.setViewport({width:390,height:844});await page.setBypassServiceWorker(true);let checks=0;const errors=[],blockedWrites=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setRequestInterception(true);page.on('request',req=>{const u=new URL(req.url());const reply=(data,status=200)=>req.respond({status,contentType:'application/json',headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*'},body:JSON.stringify(data)});
 if(u.origin===base){if(u.pathname.startsWith('/api/'))return reply({places:[],results:[],data:[]});return req.continue();}if(['data:','blob:'].includes(u.protocol))return req.continue();if(req.method()==='OPTIONS')return reply({});
 if(u.pathname.endsWith('/rpc/get_place_review_evidence'))return reply({visits:[],complete:true,snapshot:'2026-09-21T00:00:00Z'});
 if(req.method()!=='GET'){blockedWrites.push(u.pathname);return reply({},403);}if(u.pathname.endsWith('/places'))return reply([place]);if(u.pathname.endsWith('/atlas_articles'))return reply([article]);if(u.hostname==='ipapi.co')return reply({city:'Boston',region_code:'MA',latitude:42.36,longitude:-71.06});return reply([]);
 });
 const body=()=>page.$eval('body',e=>e.innerText),fits=async()=>assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 try{for(const lang of languages){const c=x=>copy(lang,x),pre=lang==='en'?'':'/'+lang; if(page.url().startsWith(base))await page.evaluate(l=>localStorage.setItem('tavvy-locale',l),lang);
  await page.goto(base+pre+'/app',{waitUntil:'networkidle2',timeout:90000});await page.waitForFunction(v=>document.body.innerText.replace(/\s+/g,' ').includes(v),{},c('Find your next happy place.'));await fits();await page.screenshot({path:`${out}/${lang}-discover.png`});checks++;
  await page.goto(base+pre+'/app/rv-camping',{waitUntil:'networkidle2',timeout:90000});await page.waitForFunction(v=>document.body.innerText.replace(/\s+/g,' ').includes(v),{},place.name);await page.waitForFunction(v=>document.body.innerText.replace(/\s+/g,' ').includes(v),{},c('No recent concerns reported'));let text=await body();for(const message of ['Find your perfect campsite.','Browse all locations. Search a place or city to narrow the list.','RV Parks','Campgrounds','The Main Thing','The campsite'])assert(text.includes(c(message)),lang+':'+message);assert(await page.$(`input[placeholder="${c('Search places or cities')}"]`));await fits();await page.screenshot({path:`${out}/${lang}-rv.png`});checks++;
  await page.goto(base+pre+'/app/atlas',{waitUntil:'networkidle2',timeout:90000});await page.waitForFunction(v=>document.body.innerText.replace(/\s+/g,' ').includes(v),{},article.title);text=await body();for(const message of ['Your guide to the exceptional.','FEATURED STORY','Read Article'])assert(text.includes(c(message)),lang+':'+message);assert(text.includes(article.author_name));assert(await page.$(`input[placeholder="${c('Search articles...')}"]`));await fits();await page.screenshot({path:`${out}/${lang}-atlas.png`});await page.type('input','no-results-fixture');await page.waitForFunction(v=>document.body.innerText.replace(/\s+/g,' ').includes(v),{},c('No articles found.'));assert((await body()).includes('no-results-fixture'));checks++;
 }assert.deepEqual(errors,[]);assert.deepEqual(blockedWrites,[]);const result={status:'PASS',checks,languages,realWrites:0,errors,blockedWrites};fs.writeFileSync(out+'/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }catch(e){await page.screenshot({path:out+'/failure.png'});fs.writeFileSync(out+'/failure.json',JSON.stringify({error:String(e),url:page.url(),errors,blockedWrites},null,2));throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e.message);process.exitCode=1});
