const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),ts=require('typescript');
const root=path.resolve(__dirname,'../..'),mobile=process.env.TAVVY_MOBILE_SOURCE||path.resolve(root,'../tavvy-mobile');
const locales=['en','es','pt','fr','de','it','ja','ko','zh','ru','ar','tr','hi','id','th','vi','nl'];
const catalog=(repo,locale)=>JSON.parse(fs.readFileSync(path.join(repo,repo===root?'public/locales':'i18n/locales',locale,repo===root?'common.json':'translation.json')));
function source(file){return ts.createSourceFile(file,fs.readFileSync(file,'utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX)}
test('all existing locales have matching nonempty release messages and interpolation tokens',()=>{const en=catalog(root,'en').release;assert(Object.keys(en).length>=193);for(const locale of locales){const data=catalog(root,locale).release;assert.deepEqual(Object.keys(data).sort(),Object.keys(en).sort());for(const key in en){assert.equal(typeof data[key],'string');assert(data[key].trim(),locale+'.'+key);assert.deepEqual(data[key].match(/{{[^}]+}}/g)||[],en[key].match(/{{[^}]+}}/g)||[]);}if(fs.existsSync(mobile))assert.deepEqual(catalog(mobile,locale).release,data);}});
test('translations never feed state, route, payload or enum operations',()=>{for(const repo of [root,mobile]){if(!fs.existsSync(repo))continue;const dirs=repo===root?['pages/app','components/ecard','components/TabBar.tsx']:['screens','components/ecard','components/StoriesRow.tsx','App.tsx'];let calls=0;const scan=p=>{if(fs.statSync(p).isDirectory()){for(const f of fs.readdirSync(p))scan(path.join(p,f));return;}if(!p.endsWith('.tsx'))return;const s=source(p);const walk=n=>{if(ts.isCallExpression(n)&&n.expression.getText(s)==='copy'){calls++;let ancestor=n.parent;while(ancestor&&!ts.isJsxExpression(ancestor)){if(ts.isCallExpression(ancestor)){const name=ancestor.expression.getText(s);assert(!/^(set[A-Z]|dispatch$|go$|.*\.(navigate|push|replace|update|insert)$|createCard$|handleFieldChange$)/.test(name),`${p}: translated data passed to ${name}`);}ancestor=ancestor.parent;}}ts.forEachChild(n,walk)};walk(s);};dirs.map(d=>path.join(repo,d)).filter(p=>fs.existsSync(p)).forEach(scan);assert(calls>50);}});
test('native submitted searches invalidate delayed autocomplete before showing results',async()=>{if(!fs.existsSync(mobile))return;const s=source(path.join(mobile,'screens/HomeScreen.tsx'));let submit;const find=n=>{if(ts.isVariableDeclaration(n)&&n.name.getText(s)==='handleSearchSubmit')submit=n.initializer;ts.forEachChild(n,find)};find(s);assert(submit);const js=ts.transpileModule('const submit='+submit.getText(s)+';', {compilerOptions:{target:ts.ScriptTarget.ES2020}}).outputText;
 let staleApplied=false,cancelled=false;const ref={current:7},timer={current:99};const staleRequest=ref.current;
 const deps={searchQuery:'trattoria tavvy',diningNeed:'',searchRequestId:ref,searchDebounceRef:timer,clearTimeout:n=>{assert.equal(n,99);cancelled=true},setIsSearchingAddress:()=>{},setSearchSuggestions:()=>{},Keyboard:{dismiss(){}},setIsSearchFocused:()=>{},navigation:{navigate(){}}};const run=new Function(...Object.keys(deps),js+'return submit;')(...Object.values(deps));await run();if(staleRequest===ref.current)staleApplied=true;assert.equal(cancelled,true);assert.equal(timer.current,null);assert.equal(staleApplied,false);
 const text=s.getFullText();assert(text.includes('isSearchFocused && searchQuery.trim().length > 0 && (searchSuggestions.length > 0 || isSearchingAddress)'));const overlay=text.slice(text.indexOf('Full-Screen Search Suggestions Overlay'),text.indexOf('Suggestions List',text.indexOf('Full-Screen Search Suggestions Overlay')));assert(overlay.includes('onSubmitEditing={() => void handleSearchSubmit()}'));assert(!text.includes('getCategoryFallbackImage'));assert(!text.includes('Top Contributors'));});
