/** Mock-only browser regression: no request writes a real card or publishes one. */
const puppeteer=require('puppeteer'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const base=process.env.TAVVY_ECARD_BASE||'http://127.0.0.1:3048',out=process.env.TAVVY_ECARD_QA||'/private/tmp/tavvy-release-language-qa';
const uid='00000000-0000-4000-8000-000000000083',cid='00000000-0000-4000-8000-000000000098';
const originalCard={id:cid,user_id:uid,full_name:'Jordan Rivera',slug:'qa-card',title:'Designer',bio:'Thoughtful work for local businesses.',template_id:'basic',theme:'classic',gradient_color_1:'#8A05BE',gradient_color_2:'#667eea',is_published:false,is_active:true,featured_socials:[],gallery_images:[],videos:[],profile_photo_url:null,phone:'+1 555 0100',show_licensed_badge:true,badge_approval_status:'approved'};
const originalLinks=[{id:'00000000-0000-4000-8000-000000000091',card_id:cid,platform:'website',title:'My portfolio',url:'https://example.invalid/portfolio',value:'portfolio-value',sort_order:0,is_active:true},{id:'00000000-0000-4000-8000-000000000092',card_id:cid,platform:'instagram',icon:'logo-instagram',title:'Instagram updates',url:'https://example.invalid/instagram',sort_order:1,is_active:true},{id:'00000000-0000-4000-8000-000000000093',card_id:cid,platform:'phone',title:'Private number',url:'tel:15550101',value:'15550101',sort_order:2,is_active:null}];
const clone=v=>JSON.parse(JSON.stringify(v));
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});
 const page=await browser.newPage();await page.setViewport({width:390,height:844});await page.setBypassServiceWorker(true);const errors=[],writes=[];let card=clone(originalCard),links=clone(originalLinks),failSave=false,failLinks=false,failPlan=false,pro=true,createdPayload;
 const user={id:uid,email:'ecard@example.invalid',aud:'authenticated',role:'authenticated',app_metadata:{},user_metadata:{}};
 await page.evaluateOnNewDocument(session=>{localStorage.setItem('sb-scasgwrikoqdwlwlwcff-auth-token',JSON.stringify(session));if(!localStorage.getItem('@tavvy_theme_mode'))localStorage.setItem('@tavvy_theme_mode','light');},{access_token:'qa.session.token',refresh_token:'qa-refresh',expires_at:Math.floor(Date.now()/1000)+3600,expires_in:3600,token_type:'bearer',user});
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.setRequestInterception(true);page.on('request',async r=>{
  const u=new URL(r.url());if(!u.hostname.endsWith('.supabase.co'))return r.continue();
  const respond=(data,status=200)=>r.respond({status,contentType:'application/json',headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*'},body:JSON.stringify(data)});
  if(r.method()==='OPTIONS')return respond({});if(u.pathname==='/auth/v1/user')return respond(user);
  if(u.pathname.endsWith('/get_my_ecard_entitlement'))return respond(failPlan?{message:'mock plan unavailable'}:{is_pro:pro,is_super_admin:false,ecard_active:true,status:pro?'active':'free',plan_type:pro?'pro':'free',current_period_end:null},failPlan?503:200);
  if(u.pathname.endsWith('/digital_cards')){if(r.method()==='GET')return respond(card);const body=JSON.parse(r.postData()||'{}');writes.push({type:r.method()==='POST'?'create':body.is_published!==undefined?'publication':'card',body});if(failSave)return respond({message:'forced save failure'},500);if(r.method()==='POST'){createdPayload=body;card={...card,...body};}else card={...card,...body};return respond(card);}
  if(u.pathname.endsWith('/digital_card_links'))return respond(failLinks?{message:'mock link read unavailable'}:links,failLinks?503:200);
  if(u.pathname.endsWith('/replace_ecard_links')){const body=JSON.parse(r.postData()||'{}');writes.push({type:'links',body});if(failSave)return respond({message:'forced links failure'},500);links=body.p_links;return respond(null);}
  if(r.method()!=='GET')return respond({message:'Unrecognized write blocked'},403);return respond(null);
 });
 const visit=async route=>{await page.goto(base+route,{waitUntil:'networkidle2',timeout:60000});};
 const click=async text=>{await page.waitForFunction(text=>[...document.querySelectorAll('button,summary')].some(e=>e.textContent.trim()===text),{},text);await page.evaluate(text=>{const e=[...document.querySelectorAll('button,summary')].find(e=>e.textContent.trim()===text);e.click()},text);};
 const field=async(selector,value)=>{await page.waitForSelector(selector);await page.focus(selector);await page.$eval(selector,e=>e.select());await page.type(selector,value);};
 const noOverflow=async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'horizontal page overflow');
 const waitSaved=()=>page.waitForFunction(()=>document.body.innerText.includes('All changes saved'));
 try{
  const en=JSON.parse(fs.readFileSync(path.join(__dirname,'../../public/locales/en/common.json'))).release;
  const copy=(locale,text)=>{const lang=JSON.parse(fs.readFileSync(path.join(__dirname,`../../public/locales/${locale}/common.json`))).release;const k=Object.keys(en).find(k=>en[k]===text);assert(k,'Missing release key '+text);return lang[k];};
  await page.evaluateOnNewDocument(()=>{if(!localStorage.getItem('tavvy-locale'))localStorage.setItem('tavvy-locale','en');Object.defineProperty(navigator,'languages',{get:()=>['en-US']});});
  const choose=async name=>{await page.evaluate(name=>[...document.querySelectorAll('.language-item')].find(e=>e.textContent.includes(name)).click(),name);};
  await visit('/app/settings/language');await choose('العربية');await page.waitForFunction(()=>document.documentElement.lang==='ar'&&document.documentElement.dir==='rtl');assert.equal(await page.evaluate(()=>localStorage.getItem('tavvy-locale')),'ar');await noOverflow();await page.screenshot({path:out+'/arabic-language.png',fullPage:true});
  await choose('Português');await page.waitForFunction(()=>document.documentElement.lang==='pt'&&document.documentElement.dir==='ltr');await page.reload({waitUntil:'networkidle2'});assert.equal(await page.evaluate(()=>document.documentElement.lang),'pt');
  await visit('/pt/app/settings');assert(!(await page.$eval('body',e=>e.innerText)).includes('🇺🇸 English'));assert((await page.$eval('body',e=>e.innerText)).toLowerCase().includes('português'));
  await visit('/pt/app/apps');assert(await page.$eval('h1',e=>e.textContent)===copy('pt','What would you like to do?'));await field('.search input','eCard');const hrefs=await page.$$eval('a.tool',a=>a.map(e=>e.getAttribute('href')));assert(hrefs.some(h=>h.endsWith('/app/ecard')));await noOverflow();await page.screenshot({path:out+'/portuguese-tools.png',fullPage:true});
  await visit(`/pt/app/ecard/${cid}/edit`);await page.waitForSelector('.card-studio');assert.equal(await page.$eval('input[placeholder="Jordan Rivera"]',e=>e.value).catch(()=>originalCard.full_name),originalCard.full_name);
  await click(copy('pt','Design'));await click(copy('pt','Content'));await page.click('[aria-label="Move Instagram updates up"]');await page.waitForFunction(text=>document.body.innerText.includes(text),{},copy('pt','All changes saved'));assert.equal(links[0].platform,'instagram');assert.equal(links.find(l=>l.platform==='website').value,'portfolio-value');assert.equal(card.full_name,'Jordan Rivera');assert.equal(card.template_id,'basic');assert.equal(card.is_published,false);
  await click(copy('pt','More features'));await click(copy('pt','Media'));await page.waitForFunction(()=>Number(getComputedStyle(document.querySelector('#section-media-content')).opacity)>.99);await noOverflow();await page.screenshot({path:out+'/portuguese-studio.png',fullPage:true});
  pro=false;await visit(`/pt/app/ecard/${cid}/edit`);await page.waitForSelector('.card-studio');await click(copy('pt','More features'));await click(copy('pt','Media'));await click(copy('pt','Add Images'));await page.waitForSelector('[data-pro-extra-notice]');assert((await page.$eval('[data-pro-extra-notice]',e=>e.innerText)).includes(copy('pt','Requires Pro')));assert.equal(card.is_published,false);
  await visit('/pt/app/settings/language');await choose('Español');await page.waitForFunction(()=>document.documentElement.lang==='es');
  const searches=[];await page.setRequestInterception(true);page.on('request',r=>{});
  await page.evaluateOnNewDocument(()=>{window.__languageSearches=[];const nativeFetch=window.fetch;window.fetch=(url,options)=>{if(String(url).startsWith('/api/search?')){window.__languageSearches.push(String(url));return Promise.resolve(new Response(JSON.stringify({suggestions:[],dining:true,location:{kind:'named',label:'Boston, MA'}}),{headers:{'Content-Type':'application/json'}}));}return nativeFetch(url,options);};});
  await visit('/es/app/search?q=Italian%20restaurants%20near%20Boston%2C%20MA');await page.waitForFunction(()=>window.__languageSearches.length>0);await click(copy('es','Quiet conversation'));await page.waitForFunction(()=>location.search.includes('need=quiet'));assert((await page.$eval('.resolved-location',e=>e.textContent)).includes('Boston, MA'));assert(!(await page.$eval('body',e=>e.innerText)).includes('temporarily unavailable'));assert((await page.evaluate(()=>window.__languageSearches)).every(u=>!u.includes('Tranquilo')));await noOverflow();await page.screenshot({path:out+'/spanish-search.png',fullPage:true});
  assert.deepEqual(errors,[]);const result={status:'PASS',mockWrites:writes.length,checks:['Arabic client switch applies RTL without reload','Portuguese switch restores LTR and persists','Settings reflects selected language','translated Tools keeps canonical eCard route','translated editor tabs preserve internal IDs','link reordering and atomic save preserve platform/value/user content','Free Pro gate translated without publication','Spanish dining preference keeps quiet enum and Boston query','390px layouts'],errors,screenshots:out};fs.writeFileSync(out+'/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }catch(error){await page.screenshot({path:out+'/failure.png',fullPage:true});fs.writeFileSync(out+'/failure.json',JSON.stringify({error:String(error),body:await page.$eval('body',e=>e.innerText),writes,errors},null,2));throw error;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
