const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),puppeteer=require('puppeteer');
const base=process.env.TAVVY_OWNER_BASE||'http://127.0.0.1:3835',out=process.env.TAVVY_OWNER_OUTPUT||'/private/tmp/tavvy-restaurant-journey-20260921/owner-browser';fs.mkdirSync(out,{recursive:true});
const pid='00000000-0000-4000-8000-000000000001',mid='00000000-0000-4000-8000-000000000002',cid='00000000-0000-4000-8000-000000000003',iid='00000000-0000-4000-8000-000000000004';
const userA={id:'00000000-0000-4000-8000-000000000005',email:'owner-a@example.invalid',aud:'authenticated'},userB={id:'00000000-0000-4000-8000-000000000006',email:'owner-b@example.invalid',aud:'authenticated'};
const session=user=>({access_token:user.id===userA.id?'fixture.a.token':'fixture.b.token',refresh_token:'fixture-refresh',expires_at:Math.floor(Date.now()/1000)+3600,expires_in:3600,token_type:'bearer',user});
(async()=>{const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage();await page.setBypassServiceWorker(true);await page.setViewport({width:390,height:844});const checks=[],writes=[],errors=[],networkErrors=[];let actor=userA,access='verified',mutation='fail',readFailure='',heldClaim=null,holdClaim=false;
page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>networkErrors.push({url:r.url(),error:r.failure()?.errorText}));await page.setRequestInterception(true);page.on('request',request=>{
 const u=new URL(request.url());if(u.hostname!=='fixture.supabase.co'){if(u.origin!==new URL(base).origin)return request.abort();return request.continue()};
 const respond=(data,status=200)=>request.respond({status,contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':request.headers()['access-control-request-headers']||'*','Access-Control-Allow-Methods':'GET,POST,PATCH,DELETE,OPTIONS'},body:JSON.stringify(data)});
 if(request.method()==='OPTIONS')return respond({});if(u.pathname.includes('/auth/v1/user'))return respond(actor);
 const table=u.pathname.split('/').at(-1);
 if(request.method()!=='GET'){const body=JSON.parse(request.postData()||'{}');writes.push({table,body});if(table==='get_restaurant_owner_workspace')return respond({place:{id:pid,name:'QA Restaurant',phone:'6175550100'},claim:{id:cid,place_id:pid,status:actor.id===userA.id?'verified':'pending',ownership_verified_at:actor.id===userA.id?'2026-09-01T12:00:00Z':null,business_email:actor.email,created_at:'2026-09-01T12:00:00Z'},canManage:actor.id===userA.id,cards:actor.id===userA.id?[{id:iid,full_name:'Private A card',is_published:false}]:[]});if(mutation==='fail')return respond({message:'Synthetic write rejected',code:'42501'},403);if(mutation==='zero')return respond(null);return respond({id:table==='menu_items'?iid:table==='menu_categories'?cid:mid});}
 if(table===readFailure)return respond({message:'Synthetic read unavailable'},503);
 if(table==='pro_business_claims'&&u.searchParams.get('select')!=='id')return respond(actor.id===userA.id?[{id:cid,place_id:pid,business_name:'Private A claim',status:'pending',ownership_verified_at:null}]:[]);
 if(table==='pro_business_claims'){const data=access==='verified'&&actor.id===userA.id?[{id:cid}]:[];if(holdClaim){holdClaim=false;heldClaim=()=>respond(data);return;}return respond(data)}
 if(table==='places')return respond({id:pid,name:'QA Restaurant'});
 if(table==='menus')return respond({id:mid,place_id:pid,name:'QA Menu',style:'visual',photo_gallery_enabled:true,show_cover:false});
 if(table==='menu_categories')return respond([{id:cid,menu_id:mid,name:'Dinner',sort_order:0}]);
 if(table==='menu_items')return respond([{id:iid,category_id:cid,name:'QA Pasta',price:18,is_available:true,meal_period:'all_day',dietary_tags:[]}]);return respond([]);
});
const visit=p=>page.goto(base+p,{waitUntil:'networkidle2'}),click=async label=>{await page.waitForFunction(label=>[...document.querySelectorAll('button,a')].some(e=>e.textContent.trim()===label),{},label);await page.evaluate(label=>[...document.querySelectorAll('button,a')].find(e=>e.textContent.trim()===label).click(),label)};
const setSession=async user=>page.evaluate(s=>localStorage.setItem('sb-scasgwrikoqdwlwlwcff-auth-token',JSON.stringify(s)),session(user));
const switchActor=async user=>{actor=user;await page.evaluate(s=>{localStorage.setItem('sb-scasgwrikoqdwlwlwcff-auth-token',JSON.stringify(s));const channel=new BroadcastChannel('sb-scasgwrikoqdwlwlwcff-auth-token');channel.postMessage({event:'SIGNED_IN',session:s});setTimeout(()=>channel.close(),100)},session(user));};
try{
 await visit(`/place/${pid}/menu-editor?tab=settings`);await click('Sign In');await page.waitForFunction(()=>location.pathname==='/app/login');assert.equal(new URL(page.url()).searchParams.get('returnUrl'),`/place/${pid}/menu-editor?tab=settings`);checks.push('anonymous editor sign-in preserves exact return path');
 await setSession(userA);access='pending';await visit(`/place/${pid}/menu-editor`);await page.waitForFunction(()=>document.body.innerText.includes('Restaurant access required'));assert.equal(await page.$('.me-tabs'),null);checks.push('pending ownership exposes no editing controls');
 access='verified';
 for(const mode of ['light','dark']){await page.evaluate(mode=>localStorage.setItem('@tavvy_theme_mode',mode),mode);await visit(`/place/${pid}/menu-editor?tab=settings`);await page.waitForSelector('.appearance-settings');const colors=await page.$eval('.me-container',e=>({background:getComputedStyle(e).backgroundColor,preview:getComputedStyle(document.querySelector('.appearance-preview.elegant_ivory')).backgroundColor}));const red=Number(colors.background.match(/\d+/)[0]);assert.ok(mode==='dark'?red<80:red>200);assert.equal(colors.preview,'rgb(247, 243, 234)');await page.screenshot({path:path.join(out,`menu-editor-${mode}.png`),fullPage:true});}checks.push('owner editor follows manual Light/Dark while ivory menu preview retains its chosen design');
 await page.waitForSelector('.appearance-settings');await page.click('input[value="elegant_ivory"]');await page.click('.appearance-gallery input');await click('Save Settings');await page.waitForFunction(()=>document.body.innerText.includes('Error saving settings'));assert.equal(writes.at(-1).body.style,'elegant_ivory');assert.equal(writes.at(-1).body.photo_gallery_enabled,false);checks.push('failed design save retains edits and reports failure');
 mutation='success';await click('Save Settings');await page.waitForFunction(()=>document.body.innerText.includes('Settings saved'));checks.push('confirmed design save keeps style and gallery independent');
 await click('Promotions');mutation='zero';await click('Save Promotions');await page.waitForFunction(()=>document.body.innerText.includes('Error saving promotions'));checks.push('zero-row promotion update is not reported as saved');
 await click('Categories');await click('+ Add Category');await page.$eval('.me-modal input',e=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,'Lunch');e.dispatchEvent(new Event('input',{bubbles:true}))});mutation='fail';await click('Add Category');await page.waitForFunction(()=>document.body.innerText.includes('Error saving category'));assert.ok(await page.$('.me-modal'));checks.push('failed category save preserves the edit form');
 await visit(`/place/${pid}/menu-editor`);await page.waitForSelector('.me-item-row');await page.click('.me-item-actions .me-btn-edit');await page.$$eval('.me-modal select',els=>{const e=els.find(el=>[...el.options].some(o=>o.value==='breakfast'));e.value='dinner';e.dispatchEvent(new Event('change',{bubbles:true}))});mutation='success';await click('Update Item');await page.waitForFunction(()=>!document.querySelector('.me-modal'));assert.equal(writes.at(-1).body.meal_period,'dinner');checks.push('item meal-period selection reaches confirmed save payload');
 readFailure='menus';await visit(`/place/${pid}/menu-editor`);await page.waitForFunction(()=>document.body.innerText.includes('The menu could not be loaded'));assert.doesNotMatch(await page.$eval('body',e=>e.innerText),/Create a restaurant menu/);checks.push('failed menu load cannot masquerade as missing menu');readFailure='';
 holdClaim=true;await page.goto(base+`/place/${pid}/menu-editor`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.body.innerText.includes('Loading menu editor'));while(!heldClaim)await new Promise(r=>setTimeout(r,20));await switchActor(userB);await page.waitForFunction(()=>document.body.innerText.includes('Restaurant access required'));await heldClaim();heldClaim=null;await new Promise(r=>setTimeout(r,300));assert.equal(await page.$('.me-tabs'),null);checks.push('late owner-A access response cannot expose editor to owner B');
 actor=userA;await setSession(userA);await visit(`/app/business/${pid}`);await page.waitForFunction(()=>document.body.innerText.includes('Ownership verified'));assert.match(await page.$eval('body',e=>e.textContent),/Private A card/);await switchActor(userB);await page.waitForFunction(()=>document.body.innerText.includes('Awaiting ownership verification'));assert.doesNotMatch(await page.$eval('body',e=>e.textContent),/Private A card/);assert.equal(await page.$('#owner-phone'),null);checks.push('workspace hides previous owner cards and controls on identity switch');
 actor=userA;await setSession(userA);await visit('/app/business');await page.waitForFunction(()=>document.body.innerText.includes('Private A claim'));await switchActor(userB);await page.waitForFunction(()=>!document.body.innerText.includes('Private A claim'));checks.push('saved claim list hides previous-account entries on account switch');
 assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);checks.push('mobile owner layout has no overflow or runtime exception');await page.screenshot({path:path.join(out,'pending-workspace.png'),fullPage:true});fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({passed:true,checks,syntheticWrites:writes.length},null,2));console.log(JSON.stringify({passed:true,checks}));
}catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({passed:false,checks,error:e.stack,errors,networkErrors},null,2));throw e;}finally{if(heldClaim)await heldClaim().catch(()=>{});await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
