const puppeteer = require('puppeteer');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.TAVVY_DEMO_BASE || 'http://localhost:3811';
const out = '/private/tmp/tavvy-demo-qa';
fs.mkdirSync(out, { recursive: true });
(async () => {
 const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true, args: ['--no-sandbox'] });
 const page = await browser.newPage();
 await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 1 });
 const cdp = await page.createCDPSession();
 await cdp.send('Page.setDownloadBehavior', { behavior: 'allow', downloadPath: out });
 const errors = []; const writes = [];
 page.on('pageerror', e => errors.push(e.message));
 page.on('request', r => { if (/\/rest\/v1\/(orders|order_items|reviews|menu_analytics|menu_item_analytics)/.test(r.url()) && r.method() === 'POST') writes.push(r.url()); });
 const visit = async path => { await page.goto(base + path, { waitUntil: 'networkidle2' }); };
 const text = () => page.evaluate(() => document.body.innerText);
 const click = async label => { await page.waitForFunction(label => [...document.querySelectorAll('button,a')].some(e => (e.textContent.trim() === label || e.getAttribute('aria-label') === label)), {}, label); await page.evaluate(label => { const e = [...document.querySelectorAll('button,a')].find(e => (e.textContent.trim() === label || e.getAttribute('aria-label') === label)); e.click(); }, label); };
 try {
  await visit('/app/demo/restaurant');
  await page.evaluate(() => { for (const k of Object.keys(localStorage)) if(k.startsWith('tavvy:restaurant-demo:')) localStorage.removeItem(k); });
  await page.reload({waitUntil:'networkidle2'});
  assert.match(await text(), /Reviews · \d+ people/);
  assert.equal(await page.$$eval('.tvr.compact [data-review-section]', els=>els.length),4);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth > innerWidth),false,'place overflows mobile viewport');
  await page.screenshot({path:out+'/place-mobile.png',fullPage:true});
  await click('Add a review'); await click('Fresh Pasta'); await click('Friendly Service'); await click('Add 2 taps to the demo');
  // Individual reviews live on the Reviews tab (Overview keeps only the bars).
  await click('Reviews'); assert.match(await text(), /You · Demo visit/);
  await page.reload({waitUntil:'networkidle2'}); await click('Reviews'); assert.match(await text(), /You · Demo visit/);
  await visit('/place/demo-trattoria/menu?view=list'); await click('See Full Menu');
  assert.equal(await page.$$eval('.menu-item',els=>els.length),16);
  await click('Filters');
  await page.evaluate(()=>[...document.querySelectorAll('button')].find(e=>e.textContent.includes('Vegan')).click());
  assert.match(await text(), /dishes match/);
  const matched=await page.$$eval('.menu-item',els=>els.length);assert.ok(matched>0&&matched<16);
  await click('Clear filters');assert.equal(await page.$$eval('.menu-item',els=>els.length),16);
  assert.equal(await page.$$eval('.menu-item.filtered-out',els=>els.length),0);
  await page.screenshot({path:out+'/menu-mobile.png',fullPage:true});
  await visit('/place/demo-trattoria/menu-gallery?dish=demo-burrata');
  assert.match(await text(),/Burrata/);
  await page.screenshot({path:out+'/gallery-mobile.png'});
  await visit('/app/demo/restaurant-showcase');
  await page.$eval('input[type=number]',el=>{const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;set.call(el,'29');el.dispatchEvent(new Event('input',{bubbles:true}));});
  await click('Save demo menu');
  assert.match(await text(), /Demo menu updated/);
  await click('Publish demo story'); assert.match(await text(), /demo story is published/);
  await visit('/place/demo-trattoria/menu?view=list'); await click('See Full Menu'); assert.match(await page.$eval('#menu-item-demo-rigatoni',el=>el.innerText),/29.00/);
  await visit('/app/demo/restaurant?tab=media'); assert.match(await text(),/Fresh pasta, made here every morning/);
  await page.evaluate(()=>document.querySelector('.media-scroll video').closest('button').click());
  await page.waitForFunction(()=>document.querySelector('.media-modal video')?.readyState>=2);
  assert.ok(await page.$eval('.media-modal video',el=>el.duration)>15);
  await page.screenshot({path:out+'/story-mobile.png'});
  await visit('/app/demo/restaurant-card'); await click('QR code');
  await page.waitForSelector('.qr svg');
  for(const file of ['trattoria-tavvy-demo.vcf','trattoria-tavvy-demo-qr.svg']) { const path = out + '/' + file; if(fs.existsSync(path)) fs.unlinkSync(path); }
  await click('Save contact'); await click('Download QR code');
  for(let i=0;i<100 && (!fs.existsSync(out+'/trattoria-tavvy-demo.vcf') || !fs.existsSync(out+'/trattoria-tavvy-demo-qr.svg'));i++) await new Promise(r=>setTimeout(r,50));
  assert.match(fs.readFileSync(out+'/trattoria-tavvy-demo.vcf','utf8'),/FN:Trattoria Tavvy/);
  assert.match(fs.readFileSync(out+'/trattoria-tavvy-demo-qr.svg','utf8'),/<svg/);
  await page.evaluate(()=>{window.demoBridgeMessages=[];window.ReactNativeWebView={postMessage: m=>window.demoBridgeMessages.push(JSON.parse(m))};});
  await click('Save contact'); await click('Download QR code');
  await page.waitForFunction(()=>window.demoBridgeMessages.some(m=>m.type==='download-qr'));
  assert.equal(await page.evaluate(()=>window.demoBridgeMessages.some(m=>m.type==='download-contact' && m.content.includes('BEGIN:VCARD'))),true);
  await page.evaluate(()=>delete window.ReactNativeWebView);
  await page.screenshot({path:out+'/ecard-mobile.png',fullPage:true});
  await visit('/app/demo/restaurant?tab=details'); await click('◷ Reserve a tableChoose your evening').catch(async()=>{await page.evaluate(()=>[...document.querySelectorAll('button')].find(e=>e.textContent.includes('Reserve a table')).click());});
  await page.$eval('input[type=date]',el=>{const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;set.call(el,'2026-12-20');el.dispatchEvent(new Event('input',{bubbles:true}));});
  await click('Try a reservation'); assert.match(await text(),/demo reservation is confirmed/);
  await visit('/place/demo-trattoria/order?table=7');
  await page.click('.order-add-btn'); await page.click('.order-add-btn');
  await page.click('.order-cart-fab');
  assert.match(await page.$eval('.order-cart-drawer',el=>el.innerText), /36.00/);
  await page.type('.order-cart-item-notes', 'Sauce on the side');
  await page.type('.order-customer-name', 'Demo guest');
  await page.waitForFunction(()=>document.querySelector('.order-cart-drawer').getAnimations().every(a=>a.playState==='finished'));
  await page.click('.order-place-btn');
  await page.waitForFunction(()=>document.body.innerText.includes('Your demo order is ready to follow'));
  for (const status of ['Confirmed by Waiter','Preparing','Ready','Served']) await click('Show next step: ' + status);
  assert.match(await page.evaluate(()=>JSON.parse(localStorage.getItem('tavvy:restaurant-demo:order:v1')).status), /served/);
  await visit('/app/demo/restaurant-showcase'); assert.match(await text(), /Sauce on the side/);
  assert.equal(await page.$$eval('.feature>img', els=>els.every(e=>e.getBoundingClientRect().height<250)),true,'showcase images are not constrained');
  await page.click('input[type=checkbox]'); await click('Save demo menu');
  await visit('/place/demo-trattoria/menu?view=list'); await click('See Full Menu');
  assert.equal(await page.$('#menu-item-demo-rigatoni'),null,'unavailable dish still shown');
  await visit('/app/demo/restaurant-showcase'); await click('Reset this demo for the next presentation');
  // Tabs are local state (replaceState): the URL keeps the tab across a reload, and Back leaves the place rather than the tab.
  await visit('/app/demo/restaurant'); await click('Reviews'); assert.match(await text(), /Recent reviews/); await page.reload({waitUntil:'networkidle2'}); assert.match(page.url(), /tab=reviews/); assert.match(await text(), /Recent reviews/);
  await click('Overview'); assert.match(await text(), /Tavvy Places/);
  await page.emulateMediaFeatures([{name:'prefers-color-scheme',value:'light'}]);
  await page.evaluate(()=>localStorage.setItem('@tavvy_theme_mode','system')); await page.reload({waitUntil:'networkidle2'});
  await page.screenshot({path:out+'/place-light-mobile.png',fullPage:true});
  await visit('/app/demo/restaurant-website'); assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:out+'/website-mobile.png',fullPage:true});
  await visit('/place/demo-trattoria/order?table=7');
  await page.screenshot({path:out+'/order-mobile.png',fullPage:true});
  await page.setViewport({width:1280,height:900,deviceScaleFactor:1}); await visit('/app/demo/restaurant-showcase');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'showcase overflows desktop');
  await page.screenshot({path:out+'/showcase-desktop.png',fullPage:true});
  assert.deepEqual(writes,[],'demo wrote production merchant data');
  assert.deepEqual(errors,[],'browser errors');
  console.log('PASS: place, review persistence, menu, filters, gallery, owner menu edit, story publishing, video playback, eCard QR, reservation, order submission/progress/notes, dish availability, reset, browser back and mobile/desktop layout.');
 } catch(e) { await page.screenshot({path:out+'/failure.png',fullPage:true}); console.log('FAILED AT',page.url()); throw e; } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
