/** Local browser fixtures only. No real place/account writes. */
const fs=require('fs'),assert=require('node:assert/strict'),puppeteer=require('puppeteer');
const base=process.env.TAVVY_RV_BASE||'http://127.0.0.1:3049',out=process.env.TAVVY_RV_QA||'/private/tmp/tavvy-tools-rv-release-20260921/browser';
const row=(n,name,sub='campground')=>({id:`dcac0000-0000-4000-8000-${String(n).padStart(12,'0')}`,name,tavvy_category:sub.includes('National')?'attraction':'rv_camping',tavvy_subcategory:sub,city:'Fixture City',region:'Fixture Region',cover_image_url:null,photos:[],status:'active'});
const all=Array.from({length:29},(_,i)=>row(i+1,'Fixture Camp '+String(i+1).padStart(2,'0'))),park=row(101,'Fixture National Park','[Landmarks and Outdoors > Park > National Park]'),needle=row(102,'Remote Needle Camp');
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await puppeteer.launch({headless:'shell',args:['--no-sandbox','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows']});const page=await browser.newPage();const originalWait=page.waitForFunction.bind(page);page.waitForFunction=(fn,options={},...args)=>originalWait(fn,{polling:100,...options},...args);await page.bringToFront();let calls=[],writes=[],errors=[],hold=false,release=null,fail=false;
try{await page.setViewport({width:390,height:844});await page.setBypassServiceWorker(true);await page.evaluateOnNewDocument(()=>{localStorage.setItem('@tavvy_theme_mode','light');localStorage.setItem('tavvy-locale','en')});page.on('pageerror',e=>errors.push(e.message));await page.setRequestInterception(true);page.on('request',async r=>{const u=new URL(r.url()),reply=(v,status=200)=>r.respond({status,contentType:'application/json',headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*'},body:JSON.stringify(v)});if(r.method()==='OPTIONS')return reply({});if(u.hostname.endsWith('.supabase.co')&&u.pathname.endsWith('/rpc/get_place_review_evidence')&&r.method()==='POST')return reply({visits:[],snapshot:'local-rv-review-fixture',complete:true,next_cursor:null});if(!['GET','HEAD'].includes(r.method())){writes.push(u.pathname);return reply({},403)}
 if(u.hostname.endsWith('.supabase.co')){
  if(u.pathname.endsWith('/places')){const filter=u.searchParams.get('or')||'',offset=Number(u.searchParams.get('offset')||0),limit=Number(u.searchParams.get('limit')||25);calls.push({filter,offset,limit,order:u.searchParams.get('order')});if(fail)return reply({message:'Fixture outage'},503);let rows=filter.includes('%Remote%')?[needle]:filter.includes('tavvy_category.eq.rv_camping')?all:filter.includes('national_park')?[park]:[];const response=rows.slice(offset,offset+limit);if(hold&&offset===24)await new Promise(resolve=>release=resolve);return reply(response)}
  if(u.pathname.includes('/auth/'))return reply({user:null});return reply([]);
 }
 if(u.origin===base&&u.pathname.startsWith('/api/'))return reply({places:[],results:[]});if(u.origin===base||u.protocol==='data:')return r.continue();return r.abort();});
 const click=async text=>{await page.waitForFunction(t=>[...document.querySelectorAll('button')].some(e=>e.textContent.trim().endsWith(t)),{},text);await page.evaluate(t=>[...document.querySelectorAll('button')].find(e=>e.textContent.trim().endsWith(t)).click(),text)};
 const count=n=>page.waitForFunction(n=>document.querySelectorAll('.tavvy-place-card').length===n,{},n);
 await page.goto(base+'/app/rv-camping',{waitUntil:'networkidle2'});await count(24);await page.waitForFunction(()=>document.querySelectorAll('[data-review-summary=empty]').length===24);assert.equal(await page.$$eval('[data-review-tile]',xs=>xs.length),96);assert(calls[0].filter.includes('tavvy_subcategory'));assert(calls[0].order.includes('name.asc')&&calls[0].order.includes('id.asc'));assert((await page.$eval('body',e=>e.innerText)).includes('Browse all locations.'));assert.equal(await page.$$eval('.tavvy-place-card img',x=>x.length),0);assert(!(await page.$eval('body',e=>e.innerText)).includes('Near You'));
 await click('Load more places');await count(29);assert.equal(calls.at(-1).offset,24);assert.equal(await page.$$eval('.tavvy-place-card',xs=>new Set(xs.map(e=>e.getAttribute('href'))).size),29);
 await click('National Parks');await count(1);assert.equal(await page.$eval('.tavvy-place-card',e=>e.getAttribute('href')),'/app/place/'+park.id);assert((await page.$eval('body',e=>e.innerText)).includes('Fixture National Park'));await page.screenshot({path:out+'/national-park-light390.png',fullPage:true});
 await click('All');await count(24);hold=true;await click('Load more places');for(let i=0;i<50&&!release;i++)await new Promise(r=>setTimeout(r,20));assert(release);await click('National Parks');await count(1);release();await new Promise(r=>setTimeout(r,300));await count(1);assert(!(await page.$eval('body',e=>e.innerText)).includes('Fixture Camp 25'));hold=false;
 await click('All');await count(24);await page.type('input[type=search]','Remote Needle',{delay:10});await page.waitForFunction(()=>document.body.innerText.includes('Remote Needle Camp'));await count(1);assert.equal(await page.$eval('input[type=search]',e=>e.value),'Remote Needle');assert(calls.at(-1).filter.includes('region.ilike'));await page.reload({waitUntil:'networkidle2'});await page.waitForFunction(()=>document.querySelector('input[type=search]').value==='Remote Needle');await count(1);
 await page.$eval('input[type=search]',e=>{const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;set.call(e,'');e.dispatchEvent(new Event('input',{bubbles:true}))});await count(24);fail=true;await click('Beaches');await page.waitForSelector('[role=alert]');assert(!(await page.$eval('body',e=>e.innerText)).includes('No places found'));fail=false;await click('Try again');await page.waitForFunction(()=>document.body.innerText.includes('No places found'));
 await page.evaluateOnNewDocument(()=>localStorage.setItem('@tavvy_theme_mode','dark'));await page.setViewport({width:1280,height:900});await page.goto(base+'/app/rv-camping?category=national-parks',{waitUntil:'networkidle2'});await count(1);assert.equal(await page.$eval('.rv-screen',e=>getComputedStyle(e).backgroundColor),'rgb(18, 13, 28)');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:out+'/national-park-dark1280.png',fullPage:true});assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);
 const result={status:'PASS',checks:['all RV cards share the four-part actual-evidence grid','server category aliases before pagination','stable24+nextpage29canonicalplaces','no fabricated images or nearby claim','National Park canonical link','late pagination ignored afterfilterchange','search queries wholecatalog and survivesreload','error distinctfromempty and retry','light390dark1280'],pageErrors:errors,writes:0};fs.writeFileSync(out+'/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}catch(e){await page.screenshot({path:out+'/failure.png',fullPage:true});fs.writeFileSync(out+'/failure.txt',await page.$eval('body',e=>e.innerText));throw e}finally{await browser.close()}})().catch(e=>{console.error(e.stack);process.exitCode=1});
