const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),ts=require('typescript');
const root=path.resolve(__dirname,'../..');
function load(file,overrides={},cache={}){if(cache[file])return cache[file];const exports={};cache[file]=exports;const code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','exports','setTimeout','clearTimeout',code)(name=>{if(name in overrides)return overrides[name];if(name==='./supabaseClient')return{supabase:{}};return load(path.posix.normalize(path.posix.join(path.posix.dirname(file),name+'.ts')),overrides,cache)},exports,setTimeout,clearTimeout);return exports}
const {loadReviewSummaries}=load('lib/reviewSummaryLoader.ts');const {buildPlaceEvidence}=load('lib/placeEvidence.ts');
const subjects=[{id:'rv-one',category:'rv_camping',subcategory:'dump_station'}];
test('successful empty evidence retains dump-station identity; missing rows never become fake zero reviews',async()=>{const empty=buildPlaceEvidence([],subjects[0]);const good=await loadReviewSummaries(subjects,{load:async()=>new Map([['rv-one',empty]])});assert.equal(good['rv-one'].status,'empty');assert.match(good['rv-one'].tiles[0].detail,/dump/i);const missing=await loadReviewSummaries(subjects,{load:async()=>new Map()});assert.equal(missing['rv-one'].status,'unavailable');});
test('failed and hung summary requests leave loading state without inventing reports',async()=>{for(const load of [async()=>{throw Error('offline')},()=>new Promise(()=>{})]){const result=await loadReviewSummaries(subjects,{load,timeoutMs:5});assert.equal(result['rv-one'].status,'unavailable');assert(result['rv-one'].tiles.every(t=>t.count==null));}});
test('RV catalog summary updates preserve current cards and ignore late results after filter changes',async()=>{
 const slots=[],effects=[],timers=new Map(),catalogRequests=[],summaryRequests=[];let cursor=0,nextTimer=0,dirty=true,current,category='all';
 const same=(a,b)=>a&&b&&a.length===b.length&&a.every((x,i)=>Object.is(x,b[i]));
 const react={useRef(initial){const i=cursor++;return slots[i]||(slots[i]={current:initial})},useState(initial){const i=cursor++;if(!(i in slots))slots[i]=initial;return[slots[i],v=>{slots[i]=typeof v==='function'?v(slots[i]):v;dirty=true}]},useCallback(fn,deps){const i=cursor++;if(!slots[i]||!same(slots[i].deps,deps))slots[i]={deps,fn};return slots[i].fn},useEffect(fn,deps){const i=cursor++;const old=slots[i];if(!old||!same(old.deps,deps)){old?.cleanup?.();slots[i]={deps};effects.push(()=>slots[i].cleanup=fn())}}};
 const code=ts.transpileModule(fs.readFileSync(path.join(root,'hooks/useRVCatalog.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 const deps={react,'../lib/rvCatalog':{fetchRVCatalog:args=>new Promise(resolve=>catalogRequests.push({args,resolve}))},'../lib/reviewSummaryLoader':{loadReviewSummaries:args=>new Promise(resolve=>summaryRequests.push({args,resolve}))},'../lib/placeReviewSummary':load('lib/placeReviewSummary.ts')};const exports={};new Function('require','exports','setTimeout','clearTimeout',code)(n=>{assert(n in deps,n);return deps[n]},exports,fn=>{const id=++nextTimer;timers.set(id,fn);return id},id=>timers.delete(id));
 const render=()=>{for(let i=0;dirty&&i<20;i++){dirty=false;cursor=0;current=exports.useRVCatalog(category,'');effects.splice(0).forEach(f=>f())}return current};
 const tick=async()=>{render();const pending=[...timers.values()];timers.clear();pending.forEach(f=>f());await new Promise(r=>setImmediate(r));return render()};
 const place=id=>({id,name:id,tavvy_category:'rv_camping',tavvy_subcategory:'dump_station'});await tick();catalogRequests[0].resolve({places:[place('old')],hasMore:true,nextOffset:1});await tick();assert.equal(current.reviewSummaries.old.status,'loading');assert.equal(current.places[0].id,'old');
 category='dump-stations';dirty=true;await tick();catalogRequests[1].resolve({places:[place('new')],hasMore:true,nextOffset:1});await tick();summaryRequests[1].resolve({new:{status:'empty',tiles:[]}});await tick();summaryRequests[0].resolve({old:{status:'ready',tiles:[]}});await tick();assert.equal(current.places[0].id,'new');assert.equal(current.reviewSummaries.new.status,'empty');assert.equal(current.reviewSummaries.old,undefined);
 current.loadMore();await tick();catalogRequests[2].resolve({places:[place('more')],hasMore:false,nextOffset:2});await tick();assert.equal(current.reviewSummaries.new.status,'empty');assert.equal(current.reviewSummaries.more.status,'loading');summaryRequests[2].resolve({more:{status:'unavailable',tiles:[]}});await tick();assert.equal(current.reviewSummaries.more.status,'unavailable');assert.equal(current.places.length,2);
});
