const { PGlite } = require('@electric-sql/pglite');
const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict');
(async () => {
  const db = new PGlite();
  await db.exec(`CREATE ROLE authenticated; CREATE ROLE anon; CREATE ROLE service_role BYPASSRLS;
  CREATE SCHEMA auth; CREATE SCHEMA storage;
  CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
  CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql STABLE AS $$SELECT current_user::text$$;
  CREATE TABLE auth.users(id uuid PRIMARY KEY,banned_until timestamptz);
  CREATE TABLE places(id uuid PRIMARY KEY,is_active boolean DEFAULT true,status text DEFAULT 'active',latitude double precision,longitude double precision);
  CREATE TABLE atlas_universe_places(universe_id uuid,place_id uuid);
  CREATE TABLE atlas_universes(id uuid PRIMARY KEY);
  CREATE TABLE storage.objects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),bucket_id text,name text,owner uuid,owner_id text,metadata jsonb,created_at timestamptz DEFAULT now());
  CREATE TABLE place_stories(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),place_id uuid NOT NULL,user_id uuid NOT NULL REFERENCES auth.users(id),media_url text NOT NULL,media_type text NOT NULL CHECK(media_type IN ('image','video')),caption text,created_at timestamptz DEFAULT now(),expires_at timestamptz NOT NULL DEFAULT now()+interval '24 hours',thumbnail_url text,status text NOT NULL DEFAULT 'active',is_permanent boolean NOT NULL DEFAULT false,tags text[],updated_at timestamptz NOT NULL DEFAULT now(),universe_id uuid REFERENCES atlas_universes(id));
  CREATE TABLE place_story_highlights(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),place_id uuid NOT NULL,title text NOT NULL,cover_story_id uuid REFERENCES place_stories(id) ON DELETE SET NULL,position integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
  CREATE TABLE place_story_highlight_items(highlight_id uuid REFERENCES place_story_highlights(id) ON DELETE CASCADE,story_id uuid REFERENCES place_stories(id) ON DELETE CASCADE,position integer NOT NULL DEFAULT 0,PRIMARY KEY(highlight_id,story_id));
  CREATE TABLE story_reports(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),story_id uuid NOT NULL,reporter_user_id uuid NOT NULL,reason text NOT NULL,created_at timestamptz DEFAULT now());
  CREATE TABLE user_strikes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES auth.users(id),reason text NOT NULL,story_id uuid,issued_by uuid,created_at timestamptz DEFAULT now(),expires_at timestamptz);
  CREATE TABLE pro_business_claims(place_id uuid,user_id uuid,claim_kind text,status text,ownership_verified_at timestamptz);
  CREATE FUNCTION has_verified_restaurant_claim(p_place_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $$SELECT auth.uid() IS NOT NULL AND EXISTS(SELECT 1 FROM public.pro_business_claims WHERE place_id=p_place_id AND user_id=auth.uid() AND claim_kind='restaurant' AND status='verified' AND ownership_verified_at IS NOT NULL)$$;
  REVOKE ALL ON FUNCTION has_verified_restaurant_claim(uuid) FROM PUBLIC,anon;GRANT EXECUTE ON FUNCTION has_verified_restaurant_claim(uuid) TO authenticated;
  CREATE FUNCTION manage_story_permanence() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN UPDATE place_stories SET is_permanent=true WHERE id=NEW.id;RETURN NEW;END$$;
  CREATE TRIGGER trigger_manage_story_permanence AFTER INSERT OR DELETE ON place_stories FOR EACH ROW EXECUTE FUNCTION manage_story_permanence();
  GRANT USAGE ON SCHEMA public,auth,storage TO authenticated,anon;GRANT ALL ON ALL TABLES IN SCHEMA public,storage TO authenticated,anon;
  ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
  CREATE POLICY "Authenticated users can upload stories" ON storage.objects FOR INSERT TO authenticated WITH CHECK(bucket_id='place-stories');
  CREATE POLICY "Users can delete own stories" ON storage.objects FOR DELETE TO authenticated USING(bucket_id='place-stories');
  CREATE POLICY "Stories are publicly viewable" ON storage.objects FOR SELECT TO PUBLIC USING(bucket_id='place-stories');
  `);
  const migration = fs.readFileSync(path.join(__dirname, '../../supabase/migrations/202609210002_authenticated_story_publishing.sql'), 'utf8');
  await db.exec(migration);
  await db.exec(fs.readFileSync(path.join(__dirname, '../../supabase/migrations/202609210004_story_active_place_status.sql'), 'utf8'));
  const uid = n => `00000000-0000-0000-0000-${String(n).padStart(12, '0')}`;
  const a = uid(1), b = uid(2), owner = uid(3), place = uid(10), inactive = uid(11), missingCoords = uid(12);
  await db.exec(`INSERT INTO auth.users(id) VALUES('${a}'),('${b}'),('${owner}');
    INSERT INTO places(id,latitude,longitude) VALUES('${place}',42,-71),('${inactive}',42,-71),('${missingCoords}',null,null);
    UPDATE places SET is_active=false WHERE id='${inactive}';
    INSERT INTO pro_business_claims VALUES('${place}','${owner}','restaurant','verified',now());`);
  let serial = 0;
  const signIn = async (id, role = 'authenticated') => db.exec(`RESET ROLE;SET ROLE ${role};SELECT set_config('request.jwt.claim.sub','${id || ''}',false);`);
  const asset = async (id = a, target = place, meta = { mimetype: 'image/jpeg', size: 500 }, pathOwner = id) => {
    const media = `${pathOwner}/${target}/photo-${++serial}.jpg`;
    await db.exec('RESET ROLE');
    await db.query('INSERT INTO storage.objects(bucket_id,name,owner,owner_id,metadata) VALUES($1,$2,$3,$4,$5)', ['place-stories', media, id, id, JSON.stringify(meta)]);
    await signIn(id); return media;
  };
  const publish = async (media, target = place, kind = 'customer', lat = 42, lng = -71, caption = 'A story') => (await db.query(
    'SELECT publish_place_story($1::uuid,$2,$3,$4,$5,NULL,$6,$7,NULL) result', [target, media, 'image', kind, caption, lat, lng])).rows[0].result;
  const initialMedia = await asset();
  await signIn(null, 'anon'); await assert.rejects(publish(initialMedia), /permission denied/);
  await signIn(null); await assert.rejects(publish(initialMedia), /STORY_AUTH_REQUIRED/);
  await signIn(a); await assert.rejects(publish(initialMedia, uid(90)), /STORY_PLACE_INVALID/);
  await assert.rejects(publish(initialMedia, inactive), /STORY_PLACE_INVALID/);
  await db.exec(`RESET ROLE;UPDATE places SET status='inactive' WHERE id='${place}'`);
  await signIn(a);await assert.rejects(publish(initialMedia), /STORY_PLACE_INVALID/);
  await db.exec(`RESET ROLE;UPDATE places SET status=NULL WHERE id='${place}'`);
  await signIn(a);await assert.rejects(db.query('SELECT get_story_publish_access($1)',[place]),/STORY_LOCATION_REQUIRED/);
  await db.exec(`RESET ROLE;UPDATE places SET status='active' WHERE id='${place}'`);await signIn(a);
  await assert.rejects(publish(initialMedia, missingCoords), /STORY_PLACE_LOCATION_MISSING/);
  await assert.rejects(publish(initialMedia, place, 'customer', null, null), /STORY_LOCATION_REQUIRED/);
  await assert.rejects(publish(initialMedia, place, 'customer', 45, -71), /STORY_OUTSIDE_RADIUS/);
  await assert.rejects(publish(initialMedia, place, 'customer', NaN, -71), /STORY_LOCATION_REQUIRED/);
  await assert.rejects(publish(initialMedia, place, 'owner_highlight', null, null), /STORY_OWNER_REQUIRED/);
  await db.exec(`RESET ROLE;UPDATE auth.users SET banned_until=now()+interval '1 day' WHERE id='${a}'`);
  await signIn(a);await assert.rejects(publish(initialMedia), /STORY_ACCOUNT_RESTRICTED/);
  await db.exec(`RESET ROLE;UPDATE auth.users SET banned_until=now()-interval '1 day' WHERE id='${a}';INSERT INTO user_strikes(user_id,reason) VALUES('${a}','moderation'),('${a}','moderation')`);
  await signIn(a);await assert.rejects(publish(initialMedia), /STORY_ACCOUNT_RESTRICTED/);
  await db.exec(`RESET ROLE;UPDATE user_strikes SET expires_at=now()-interval '1 hour' WHERE user_id='${a}'`);
  await signIn(a);
  const customer = await publish(initialMedia);
  assert.equal(customer.user_id, a);assert.equal(customer.is_permanent, false);assert.equal(customer.story_kind, 'customer');
  assert.equal(Date.parse(customer.expires_at) - Date.parse(customer.created_at), 72*3600*1000);
  assert.equal(customer.media_url, `https://scasgwrikoqdwlwlwcff.supabase.co/storage/v1/object/public/place-stories/${initialMedia}`);
  assert.equal((await publish(initialMedia)).id, customer.id, 'same media is idempotent');
  await assert.rejects(publish(initialMedia, place, 'customer', 42, -71, 'Changed'), /STORY_RETRY_MISMATCH/);
  await assert.rejects(db.exec(`INSERT INTO place_stories(place_id,user_id,media_url,media_type) VALUES('${place}','${a}','https://evil.example/a.jpg','image')`), /permission denied/);
  await assert.rejects(db.exec(`UPDATE place_stories SET is_permanent=true WHERE id='${customer.id}'`), /permission denied/);
  await assert.rejects(db.exec(`INSERT INTO user_strikes(user_id,reason) VALUES('${b}','merchant dislike')`), /permission denied/);
  const foreignMedia = await asset(b);
  await signIn(a);await assert.rejects(publish(foreignMedia), /STORY_MEDIA_NOT_OWNED/);
  const forgedOwner = await asset(b, place, { mimetype: 'image/jpeg', size: 500 }, a);
  await signIn(a);await assert.rejects(publish(forgedOwner), /STORY_MEDIA_NOT_OWNED/);
  const huge = await asset(a, place, { mimetype: 'image/jpeg', size: 52428801 });await assert.rejects(publish(huge), /STORY_MEDIA_TOO_LARGE/);
  const badMime = await asset(a, place, { mimetype: 'text/html', size: 500 });await assert.rejects(publish(badMime), /STORY_MEDIA_TYPE_INVALID/);
  const noMeta = await asset(a, place, {});await assert.rejects(publish(noMeta), /STORY_MEDIA_METADATA_MISSING/);
  // Insert policy protects folder identity, and successful author upload can be cleaned up.
  await assert.rejects(db.query('INSERT INTO storage.objects(bucket_id,name,owner,owner_id,metadata) VALUES($1,$2,$3,$4,$5)', ['place-stories', `${b}/${place}/forged.jpg`, a, a, '{}']), /row-level security/);
  await db.query('DELETE FROM storage.objects WHERE name=$1', [huge]);
  assert.equal((await db.query('SELECT count(*)::int n FROM storage.objects WHERE name=$1', [huge])).rows[0].n,0);
  await db.query('DELETE FROM storage.objects WHERE name=$1', [foreignMedia]);
  assert.equal((await db.query('SELECT count(*)::int n FROM storage.objects WHERE name=$1', [foreignMedia])).rows[0].n,1);
  const ownerMedia = await asset(owner);
  const highlightStory = await publish(ownerMedia,place,'owner_highlight',null,null);
  assert.equal(highlightStory.is_permanent,true);
  const save = async (stories, id = null) => (await db.query('SELECT save_owner_story_highlight($1,$2,$3,$4,true) result', [place,id,'Food',stories])).rows[0].result;
  await assert.rejects(save([customer.id]), /STORY_HIGHLIGHT_CONTENT_INVALID/);
  const highlight = await save([highlightStory.id]);
  await db.exec(`RESET ROLE;UPDATE places SET status='draft' WHERE id='${place}'`);
  await signIn(owner);await assert.rejects(save([highlightStory.id],highlight.id),/STORY_PLACE_INVALID/);
  await db.exec(`RESET ROLE;UPDATE places SET status='active' WHERE id='${place}'`);await signIn(owner);
  await assert.rejects(save([customer.id],highlight.id), /STORY_HIGHLIGHT_CONTENT_INVALID/);
  assert.equal((await db.query('SELECT story_id FROM place_story_highlight_items WHERE highlight_id=$1',[highlight.id])).rows[0].story_id,highlightStory.id,'rejected edit preserved previous highlight');
  await db.query('SELECT report_place_story($1,$2)', [customer.id,'other']);
  await db.query('SELECT report_place_story($1,$2)', [customer.id,'other']);
  assert.equal((await db.query('SELECT status FROM place_stories WHERE id=$1',[customer.id])).rows[0].status,'active','owner report does not hide customer story');
  await assert.rejects(db.query('SELECT delete_my_place_story($1)',[customer.id]),/STORY_AUTHOR_REQUIRED/);
  await signIn(b);await assert.rejects(save([highlightStory.id]),/STORY_OWNER_REQUIRED/);
  await assert.rejects(db.exec(`DELETE FROM place_story_highlights WHERE id='${highlight.id}'`),/permission denied/);
  // Rate limits include deleted stories, and cannot be bypassed by deleting a post.
  await publish(await asset(a));await publish(await asset(a));
  const fourth=await asset(a);await assert.rejects(publish(fourth),/STORY_PLACE_LIMIT/);
  await db.query('SELECT delete_my_place_story($1)',[customer.id]);await assert.rejects(publish(fourth),/STORY_PLACE_LIMIT/);
  await db.exec(`RESET ROLE;UPDATE story_publish_settings SET daily_limit=3`);
  await signIn(a);await assert.rejects(publish(fourth),/STORY_DAILY_LIMIT/);
  await db.exec(`RESET ROLE;UPDATE story_publish_settings SET daily_limit=10;UPDATE place_stories SET expires_at=now()-interval '1 hour'`);
  await signIn(null,'anon');const visible=(await db.query('SELECT id FROM place_stories')).rows;
  assert.deepEqual(visible.map(x=>x.id),[highlightStory.id],'only explicit owner highlight remains after expiry');
  await db.exec('RESET ROLE');
  await db.exec(`CREATE FUNCTION fail_story_insert() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'forced story failure';END$$;CREATE TRIGGER fail_story_insert BEFORE INSERT ON place_stories FOR EACH ROW EXECUTE FUNCTION fail_story_insert();`);
  const rollbackMedia=await asset(b);await assert.rejects(publish(rollbackMedia),/forced story failure/);
  assert.equal((await db.query('SELECT get_my_story_by_media($1) result',[rollbackMedia])).rows[0].result,null);
  await db.exec('RESET ROLE;DROP TRIGGER fail_story_insert ON place_stories');
  const recovered=await publish(rollbackMedia);assert.ok(recovered.id);
  await db.close();console.log('Story SQL passed: auth, canonical place, restrictions, GPS, media ownership/size/type, limits, expiry, owner distinction, immutable customer moderation, highlight rollback, retries and transaction rollback.');
})().catch(error=>{console.error(error);process.exit(1)});
