// English country names and ISO region codes for matching imported place records.
export const CITY_COUNTRY_CODES: Record<string, string> = {
  "ascension island": "AC",
  "andorra": "AD",
  "united arab emirates": "AE",
  "afghanistan": "AF",
  "antigua & barbuda": "AG",
  "anguilla": "AI",
  "albania": "AL",
  "armenia": "AM",
  "curaçao": "CW",
  "angola": "AO",
  "antarctica": "AQ",
  "argentina": "AR",
  "american samoa": "AS",
  "austria": "AT",
  "australia": "AU",
  "aruba": "AW",
  "åland islands": "AX",
  "azerbaijan": "AZ",
  "bosnia & herzegovina": "BA",
  "barbados": "BB",
  "bangladesh": "BD",
  "belgium": "BE",
  "burkina faso": "HV",
  "bulgaria": "BG",
  "bahrain": "BH",
  "burundi": "BI",
  "benin": "DY",
  "st. barthélemy": "BL",
  "bermuda": "BM",
  "brunei": "BN",
  "bolivia": "BO",
  "caribbean netherlands": "BQ",
  "brazil": "BR",
  "bahamas": "BS",
  "bhutan": "BT",
  "myanmar (burma)": "MM",
  "bouvet island": "BV",
  "botswana": "BW",
  "belarus": "BY",
  "belize": "BZ",
  "canada": "CA",
  "cocos (keeling) islands": "CC",
  "congo - kinshasa": "ZR",
  "central african republic": "CF",
  "congo - brazzaville": "CG",
  "switzerland": "CH",
  "côte d’ivoire": "CI",
  "cook islands": "CK",
  "chile": "CL",
  "cameroon": "CM",
  "china": "CN",
  "colombia": "CO",
  "clipperton island": "CP",
  "sark": "CQ",
  "costa rica": "CR",
  "serbia": "YU",
  "cuba": "CU",
  "cape verde": "CV",
  "christmas island": "CX",
  "cyprus": "CY",
  "czechia": "CZ",
  "germany": "DE",
  "diego garcia": "DG",
  "djibouti": "DJ",
  "denmark": "DK",
  "dominica": "DM",
  "dominican republic": "DO",
  "algeria": "DZ",
  "ceuta & melilla": "EA",
  "ecuador": "EC",
  "estonia": "EE",
  "egypt": "EG",
  "western sahara": "EH",
  "eritrea": "ER",
  "spain": "ES",
  "ethiopia": "ET",
  "european union": "EU",
  "eurozone": "EZ",
  "finland": "FI",
  "fiji": "FJ",
  "falkland islands": "FK",
  "micronesia": "FM",
  "faroe islands": "FO",
  "france": "FX",
  "gabon": "GA",
  "united kingdom": "UK",
  "grenada": "GD",
  "georgia": "GE",
  "french guiana": "GF",
  "guernsey": "GG",
  "ghana": "GH",
  "gibraltar": "GI",
  "greenland": "GL",
  "gambia": "GM",
  "guinea": "GN",
  "guadeloupe": "GP",
  "equatorial guinea": "GQ",
  "greece": "GR",
  "south georgia & south sandwich islands": "GS",
  "guatemala": "GT",
  "guam": "GU",
  "guinea-bissau": "GW",
  "guyana": "GY",
  "hong kong sar china": "HK",
  "heard & mcdonald islands": "HM",
  "honduras": "HN",
  "croatia": "HR",
  "haiti": "HT",
  "hungary": "HU",
  "canary islands": "IC",
  "indonesia": "ID",
  "ireland": "IE",
  "israel": "IL",
  "isle of man": "IM",
  "india": "IN",
  "british indian ocean territory": "IO",
  "iraq": "IQ",
  "iran": "IR",
  "iceland": "IS",
  "italy": "IT",
  "jersey": "JE",
  "jamaica": "JM",
  "jordan": "JO",
  "japan": "JP",
  "kenya": "KE",
  "kyrgyzstan": "KG",
  "cambodia": "KH",
  "kiribati": "KI",
  "comoros": "KM",
  "st. kitts & nevis": "KN",
  "north korea": "KP",
  "south korea": "KR",
  "kuwait": "KW",
  "cayman islands": "KY",
  "kazakhstan": "KZ",
  "laos": "LA",
  "lebanon": "LB",
  "st. lucia": "LC",
  "liechtenstein": "LI",
  "sri lanka": "LK",
  "liberia": "LR",
  "lesotho": "LS",
  "lithuania": "LT",
  "luxembourg": "LU",
  "latvia": "LV",
  "libya": "LY",
  "morocco": "MA",
  "monaco": "MC",
  "moldova": "MD",
  "montenegro": "ME",
  "st. martin": "MF",
  "madagascar": "MG",
  "marshall islands": "MH",
  "north macedonia": "MK",
  "mali": "ML",
  "mongolia": "MN",
  "macao sar china": "MO",
  "northern mariana islands": "MP",
  "martinique": "MQ",
  "mauritania": "MR",
  "montserrat": "MS",
  "malta": "MT",
  "mauritius": "MU",
  "maldives": "MV",
  "malawi": "MW",
  "mexico": "MX",
  "malaysia": "MY",
  "mozambique": "MZ",
  "namibia": "NA",
  "new caledonia": "NC",
  "niger": "NE",
  "norfolk island": "NF",
  "nigeria": "NG",
  "vanuatu": "VU",
  "nicaragua": "NI",
  "netherlands": "NL",
  "norway": "NO",
  "nepal": "NP",
  "nauru": "NR",
  "niue": "NU",
  "new zealand": "NZ",
  "oman": "OM",
  "panama": "PA",
  "peru": "PE",
  "french polynesia": "PF",
  "papua new guinea": "PG",
  "philippines": "PH",
  "pakistan": "PK",
  "poland": "PL",
  "st. pierre & miquelon": "PM",
  "pitcairn islands": "PN",
  "puerto rico": "PR",
  "palestinian territories": "PS",
  "portugal": "PT",
  "palau": "PW",
  "paraguay": "PY",
  "qatar": "QA",
  "outlying oceania": "QO",
  "réunion": "RE",
  "zimbabwe": "ZW",
  "romania": "RO",
  "russia": "SU",
  "rwanda": "RW",
  "saudi arabia": "SA",
  "solomon islands": "SB",
  "seychelles": "SC",
  "sudan": "SD",
  "sweden": "SE",
  "singapore": "SG",
  "st. helena": "SH",
  "slovenia": "SI",
  "svalbard & jan mayen": "SJ",
  "slovakia": "SK",
  "sierra leone": "SL",
  "san marino": "SM",
  "senegal": "SN",
  "somalia": "SO",
  "suriname": "SR",
  "south sudan": "SS",
  "são tomé & príncipe": "ST",
  "el salvador": "SV",
  "sint maarten": "SX",
  "syria": "SY",
  "eswatini": "SZ",
  "tristan da cunha": "TA",
  "turks & caicos islands": "TC",
  "chad": "TD",
  "french southern territories": "TF",
  "togo": "TG",
  "thailand": "TH",
  "tajikistan": "TJ",
  "tokelau": "TK",
  "timor-leste": "TP",
  "turkmenistan": "TM",
  "tunisia": "TN",
  "tonga": "TO",
  "türkiye": "TR",
  "trinidad & tobago": "TT",
  "tuvalu": "TV",
  "taiwan": "TW",
  "tanzania": "TZ",
  "ukraine": "UA",
  "uganda": "UG",
  "u.s. outlying islands": "UM",
  "united nations": "UN",
  "united states": "US",
  "uruguay": "UY",
  "uzbekistan": "UZ",
  "vatican city": "VA",
  "st. vincent & grenadines": "VC",
  "vietnam": "VN",
  "venezuela": "VE",
  "british virgin islands": "VG",
  "u.s. virgin islands": "VI",
  "wallis & futuna": "WF",
  "samoa": "WS",
  "pseudo-accents": "XA",
  "pseudo-bidi": "XB",
  "kosovo": "XK",
  "yemen": "YE",
  "mayotte": "YT",
  "south africa": "ZA",
  "zambia": "ZM",
  "unknown region": "ZZ",
  "united states of america": "US",
  "usa": "US",
  "uk": "GB"
};
