/** Public provider identity is pro_providers.id, never a canonical place ID. */
export const PROVIDER_COLUMNS = 'id,slug,business_name,first_name,last_name,brokerage_name,description,short_description,bio,phone,email,website,logo_url,profile_photo_url,cover_photo_url,cover_image_url,city,state,service_areas,specialties,trade_category,years_experience,years_in_business,license_number,is_active,provider_type';
export const PROVIDER_PHOTO_COLUMNS = 'id,provider_id,image_url,caption,sort_order';
export type ProviderKind = 'realtor' | 'pros';
export type PublicProvider = {id:string;slug:string;business_name:string;first_name?:string;last_name?:string;brokerage_name?:string;description?:string;short_description?:string;bio?:string;phone?:string;email?:string;website?:string;logo_url?:string;profile_photo_url?:string;cover_photo_url?:string;cover_image_url?:string;city?:string;state?:string;service_areas?:string[];specialties?:string[];trade_category?:string;years_experience?:number;years_in_business?:number;license_number?:string;is_verified?:boolean;is_active:boolean;provider_type?:string};
export type ProviderReview = {id:string;rating:number;title:string|null;content:string|null;created_at:string|null;updated_at:string|null;main_tap:string|null;good_tap:string|null;vibe_tap:string|null;heads_up_tap:string|null};
export type ProviderPhoto = {id:string;provider_id:string;image_url:string;caption:string|null};
type Client = {from(name:string):any;rpc(name:string,args:Record<string,unknown>):PromiseLike<{data:any;error:any}>};
export const isProviderId=(v:unknown):v is string=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);
export const providerName=(p:PublicProvider)=>p.provider_type==='realtor'?[p.first_name,p.last_name].filter(Boolean).join(' ').trim()||p.business_name:p.business_name;
export const providerArea=(p:PublicProvider)=>[p.city,p.state].filter(Boolean).join(', ')||p.service_areas?.join(' · ')||'';
export function publicWebUrl(value:unknown):string|null{if(typeof value!=='string'||!value.trim()||/[\r\n]/.test(value))return null;try{const v=value.trim();const u=new URL(/^[a-z][a-z0-9+.-]*:/i.test(v)?v:`https://${v}`);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password&&u.hostname.includes('.')?u.toString():null;}catch{return null;}}
export function providerContacts(p:PublicProvider):{label:string;url:string}[]{const result:{label:string;url:string}[]=[];const phone=p.phone?.trim();if(phone&&/^[+\d() .-]{5,40}$/.test(phone))result.push({label:'Call',url:`tel:${phone.replace(/[^+\d]/g,'')}`});const email=p.email?.trim();if(email&&/^[^\s@?&#]+@[^\s@?&#]+\.[^\s@?&#]+$/.test(email))result.push({label:'Email',url:`mailto:${email}`});const website=publicWebUrl(p.website);if(website)result.push({label:'Website',url:website});return result;}
function projection(row:any):PublicProvider{if(!row||!isProviderId(row.id)||typeof row.business_name!=='string'||typeof row.slug!=='string'||row.is_active!==true)throw new Error('Provider data is unavailable.');const clean:any={};for(const key of PROVIDER_COLUMNS.split(','))if(Object.prototype.hasOwnProperty.call(row,key))clean[key]=row[key];for(const key of ['service_areas','specialties'])clean[key]=Array.isArray(row[key])?row[key].filter((x:unknown)=>typeof x==='string'):[];return clean;}
function active(query:any,kind?:ProviderKind){query=query.eq('is_active',true);return kind==='realtor'?query.eq('provider_type','realtor'):kind==='pros'?query.in('provider_type',['pro','contractor','other']):query;}
function literalPattern(value:string){return '"%'+value.replace(/[\\%_]/g,'\\$&').replace(/"/g,'\\"')+'%"';}
export type ProviderSearch={kind:ProviderKind;query?:string;category?:string;location?:string;specialty?:string;offset?:number};
export async function listProviders(client:Client,params:ProviderSearch):Promise<{providers:PublicProvider[];hasMore:boolean}>{const offset=params.offset??0;if(!Number.isInteger(offset)||offset<0||offset>10000)throw new Error('Refresh this search.');let q=active(client.from('pro_provider_public_profiles').select(PROVIDER_COLUMNS),params.kind);const term=params.query?.trim().slice(0,120);if(term){const pattern=literalPattern(term);q=q.or(['business_name','first_name','last_name','brokerage_name','city','state'].map(f=>`${f}.ilike.${pattern}`).join(','));}if(params.category)q=q.eq('trade_category',params.category);if(params.specialty)q=q.contains('specialties',[params.specialty]);if(params.location?.trim()){const pattern=literalPattern(params.location.trim().slice(0,100));q=q.or(['city','state','zip_code'].map(f=>`${f}.ilike.${pattern}`).join(','));}const {data,error}=await q.order('business_name',{ascending:true}).order('id',{ascending:true}).range(offset,offset+24);if(error||!Array.isArray(data))throw new Error('Profiles could not be loaded. Please try again.');return {providers:data.slice(0,24).map(projection),hasMore:data.length>24};}
export async function getProvider(client:Client,key:string,kind?:ProviderKind):Promise<PublicProvider|null>{if(!isProviderId(key)&&!/^[a-z0-9][a-z0-9_-]{0,159}$/i.test(key))return null;const {data,error}=await active(client.from('pro_provider_public_profiles').select(PROVIDER_COLUMNS),kind).eq(isProviderId(key)?'id':'slug',key).maybeSingle();if(error)throw new Error('This profile could not be loaded. Please try again.');return data?projection(data):null;}
/** A server-filtered typed feed; never query the raw table (it contains private IP metadata). */
export async function getProviderReviews(client:Client,id:string,offset=0):Promise<{reviews:ProviderReview[];hasMore:boolean}>{if(!isProviderId(id)||!Number.isInteger(offset)||offset<0||offset>10000)throw new Error('Reviews could not be loaded.');const {data,error}=await client.rpc('get_pro_provider_reviews_v1',{p_provider_id:id,p_offset:offset,p_limit:20});if(error||!data||!Array.isArray(data.reviews)||typeof data.hasMore!=='boolean')throw new Error('Reviews are unavailable. Please try again.');const reviews=data.reviews.map((r:any)=>{if(!isProviderId(r?.id)||!Number.isInteger(r.rating)||r.rating<1||r.rating>5)throw new Error('Reviews are unavailable. Please try again.');return {id:r.id,rating:r.rating,title:typeof r.title==='string'?r.title:null,content:typeof r.content==='string'?r.content:null,created_at:typeof r.created_at==='string'?r.created_at:null,updated_at:typeof r.updated_at==='string'?r.updated_at:null,main_tap:typeof r.main_tap==='string'?r.main_tap:null,good_tap:typeof r.good_tap==='string'?r.good_tap:null,vibe_tap:typeof r.vibe_tap==='string'?r.vibe_tap:null,heads_up_tap:typeof r.heads_up_tap==='string'?r.heads_up_tap:null};});return {reviews,hasMore:data.hasMore};}
export async function getProviderPhotos(client:Client,id:string):Promise<{photos:ProviderPhoto[];hasMore:boolean}>{if(!isProviderId(id))throw new Error('Photos could not be loaded.');const {data,error}=await client.from('pro_photos').select(PROVIDER_PHOTO_COLUMNS).eq('provider_id',id).order('sort_order',{ascending:true}).order('id',{ascending:true}).range(0,59);if(error||!Array.isArray(data))throw new Error('Photos are unavailable. Please try again.');return {photos:data.filter(r=>r.provider_id===id&&isProviderId(r.id)&&publicWebUrl(r.image_url)).map(r=>({id:r.id,provider_id:id,image_url:r.image_url,caption:typeof r.caption==='string'?r.caption:null})),hasMore:data.length===60};}

export function providerReviewDate(value:string|null):string{return value&&Number.isFinite(Date.parse(value))?new Date(value).toLocaleDateString():'Date unavailable';}
