/** Explicit UI copy only. Never apply to user or place content. */
export const RELEASE_COPY_KEYS: Record<string, string> = {
  "Design category": "ecardBrowse1",
  "Design plan": "ecardBrowse2",
  "All plans": "ecardBrowse3",
  "Business & Services": "ecardBrowse4",
  "Personal & Creators": "ecardBrowse5",
  "Food & Mobile Businesses": "ecardBrowse6",
  "Real Estate": "ecardBrowse7",
  "Faith & Community": "ecardBrowse8",
  "Politics & Public Service": "ecardBrowse9",
  "No designs match these filters. Choose All plans or another category.": "ecardBrowse10",
  "Free design. Some colors require Pro.": "ecardBrowse11",
  "Profile Card": "ecardBrowse12",
  "Portrait Page": "ecardBrowse13",

  "Airports": "atlasCategoryAirports",
  "Campuses": "atlasCategoryCampuses",
  "Family & Kids": "atlasCategoryFamilyKids",
  "Food & Drink": "atlasCategoryFoodDrink",
  "Hospitals": "atlasCategoryHospitals",
  "Malls": "atlasCategoryMalls",
  "Ports": "atlasCategoryPorts",
  "Stadiums": "atlasCategoryStadiums",
  "Theme Parks": "atlasCategoryThemeParks",
  "Travel Tips": "atlasCategoryTravelTips",
  "Venues": "atlasCategoryVenues",
  "Cruises": "cruiseToolTitle",
  "Explore ocean, river and expedition ships.": "cruiseToolDescription",
  "Good night": "publicFinishGoodNight",
  "What are you in the mood for?": "publicFinishMoodSearch",
  "Your guide to the exceptional.": "publicFinishAtlasTagline",
  "Search articles...": "publicFinishAtlasSearch",
  "Loading articles...": "publicFinishAtlasLoading",
  "FEATURED STORY": "publicFinishAtlasFeatured",
  "Read Article": "publicFinishAtlasRead",
  "All Articles": "publicFinishAtlasAll",
  "No articles found.": "publicFinishAtlasEmpty",
  "Find your perfect campsite.": "publicFinishRVTagline",
  "Search places or cities": "publicFinishPlacesOrCities",
  "Browse all locations. Search a place or city to narrow the list.": "publicFinishBrowseScope",
  "RV Parks": "publicFinishRVParks",
  "Campgrounds": "publicFinishCampgrounds",
  "National Parks": "publicFinishNationalParks",
  "Beaches": "publicFinishBeaches",
  "Boondocking": "publicFinishBoondocking",
  "Overnight Parking": "publicFinishOvernightParking",
  "Dump Stations": "publicFinishDumpStations",
  "Loading places…": "publicFinishPlacesLoading",
  "Load more places": "publicFinishPlacesMore",
  "Try another place, city or category.": "publicFinishPlacesEmptyHint",
  "Places are temporarily unavailable. Please try again.": "publicFinishPlacesUnavailable",
  "Recent reviews": "publicFinishRecentReviews",
  "The Main Thing": "publicFinishMainThing",
  "The Good": "publicFinishTheGood",
  "The Vibe": "publicFinishTheVibe",
  "Heads Up": "publicFinishHeadsUp",
  "Loading recent reviews…": "publicFinishReviewsLoading",
  "Recent reviews unavailable": "publicFinishReviewsUnavailable",
  "More recent reviews needed": "publicFinishReviewsNeeded",
  "Recent concerns reported": "publicFinishConcernsRecent",
  "No recent concerns reported": "publicFinishNoConcernsRecent",
  "The campsite": "publicFinishCampsite",
  "The beach experience": "publicFinishBeachExperience",
  "The food": "publicFinishFood",
  "One person mentioned this": "publicFinishMentionedOne",
  "{{count}} people mentioned this": "publicFinishMentionedMany",
  "By": "publicFinishByAuthor",

  "Discover": "navDiscover",
  "Tools": "navTools",
  "Saved": "navSaved",
  "Profile": "navProfile",
  "Appearance": "appearance",
  "Use device setting": "deviceTheme",
  "Light": "light",
  "Dark": "dark",
  "Content": "content",
  "Design": "design",
  "More features": "moreFeatures",
  "Save": "save",
  "Saving…": "saving",
  "All changes saved": "savedAll",
  "Unsaved changes": "unsaved",
  "Could not save": "saveFailed",
  "Retry saving": "retrySave",
  "Publish": "publish",
  "Publishing…": "publishing",
  "Published": "published",
  "Draft": "draft",
  "Preview": "preview",
  "Edit": "edit",
  "Share": "share",
  "Close": "close",
  "Keep editing": "keepEditing",
  "View Pro plan": "viewPro",
  "Links & actions": "linksActions",
  "Templates & colors": "templatesColors",
  "Typography & buttons": "typographyButtons",
  "Images & layout": "imagesLayout",
  "Professional details & contact form": "professionalForm",
  "Civic details": "civicDetails",
  "Mobile business": "mobileBusiness",
  "Publication & sharing": "publicationSharing",
  "Media": "media",
  "Gallery": "gallery",
  "Videos": "videos",
  "Contact Form": "contactForm",
  "Add Images": "addImages",
  "Add Video": "addVideo",
  "Where": "where",
  "Apply": "apply",
  "Near me": "nearMe",
  "Search": "search",
  "No tools found": "noTools",
  "Clear search": "clearSearch",
  "Share your card": "shareCard",
  "Share & QR": "shareQR",
  "My cards": "myCards",
  "Card preview": "cardPreview",
  "Back to editing": "backEditing",
  "Open full preview": "openPreview",
  "QR code": "qrCode",
  "Copy link": "copyLink",
  "Cancel": "cancel",
  "Name": "name",
  "Full name": "fullName",
  "Title": "title",
  "Bio": "bio",
  "Phone": "phone",
  "Website": "website",
  "Pro features": "proFeatures",
  "Pro feature": "proFeature",
  "Gallery · Pro": "galleryPro",
  "Videos · Pro": "videosPro",
  "Contact Form · Pro": "formPro",
  "A LITTLE HELP FOR EVERY DAY": "toolsEyebrow",
  "What would you like to do?": "toolsTitle",
  "Find your next stop. Meet the right people. Make yourself at home.": "toolsIntro",
  "Search food, places, people and more": "toolsSearch",
  "A good place to start": "toolsStart",
  "Try a word like food, cards or places.": "toolsEmptyHint",
  "Show all tools": "toolsAll",
  "Find your next stop": "toolsDiscover",
  "Good food, new places and a little adventure.": "toolsDiscoverDescription",
  "People who can help": "toolsConnect",
  "Find local expertise and keep the conversation going.": "toolsConnectDescription",
  "Your everyday essentials": "toolsPersonal",
  "Keep useful things close and make Tavvy yours.": "toolsPersonalDescription",
  "Get more out of Tavvy": "toolsMore",
  "Food Menu": "foodMenu",
  "Universes": "universes",
  "On The Go": "onTheGo",
  "Rides": "rides",
  "RV & Camping": "camping",
  "Cities": "cities",
  "Happening Now": "happening",
  "Experiences": "experiences",
  "Atlas": "atlas",
  "Pros": "pros",
  "Realtors": "realtors",
  "Messages": "messages",
  "eCard": "ecard",
  "Wallet": "wallet",
  "Create": "create",
  "Account": "account",
  "Settings": "settings",
  "Find a dish you’re craving nearby.": "foodMenuDescription",
  "Explore parks, airports and places within them.": "universesDescription",
  "Find food trucks and mobile businesses.": "onTheGoDescription",
  "Plan your next theme park adventure.": "ridesDescription",
  "Find somewhere to park, camp and unwind.": "campingDescription",
  "Get to know a new city.": "citiesDescription",
  "See local events and what’s coming up.": "happeningDescription",
  "Explore a path of places or create your own.": "experiencesDescription",
  "Browse guides and stories about places.": "atlasDescription",
  "Find local professionals for your next project.": "prosDescription",
  "Connect with real estate professionals.": "realtorsDescription",
  "Pick up your conversations.": "messagesDescription",
  "Create a digital card that introduces you.": "ecardDescription",
  "Return to places you want to remember.": "savedDescription",
  "Keep business cards and contacts together.": "walletDescription",
  "Add a place, business or something new.": "createDescription",
  "Manage your profile and personal details.": "accountDescription",
  "Set up Tavvy the way you like it.": "settingsDescription",
  "City, state or any location": "cityPlaceholder",
  "Location access was not available. Enter a city instead.": "locationDenied",
  "Location is unavailable. Enter a city instead.": "locationUnavailable",
  "What matters for this meal?": "mealQuestion",
  "Search places, categories, cities...": "searchPlaceholder",
  "Checking guest reports…": "checkingReviews",
  "Saved changes update your published card.": "publicSaveNote",
  "Your draft is private until you publish.": "privateDraftNote",
  "Updates as you edit. Preview actions do not contact anyone.": "previewNote",
  "Your existing content stays on your card.": "existingPreserved",
  "Gallery photos, embedded videos, contact forms and professional credentials are Pro extras.": "proExtrasSummary",
  "Contact forms are included with Pro. Existing form settings are preserved when you turn the form off.": "formOffNote",
  "Adding gallery photos": "galleryAddPro",
  "Adding embedded videos": "videoAddPro",
  "Enabling a contact form": "formEnablePro",
  "Requires Pro": "proRequired",
  "Show contact form on card": "showForm",
  "Unpublish card": "unpublish",
  "Retry plan check": "retryPlan",
  "Dismiss": "dismiss",
  "Free plan": "freePlan",
  "Pro plan": "proPlan",
  "Back to cards": "backCards",
  "Edit card": "editCard",
  "Save PNG": "savePNG",
  "Share link": "shareLink",
  "Your card is published and ready to share.": "publishedConfirmation",
  "Card link copied.": "linkCopied",
  "Your latest changes have not saved. Retry saving before publishing.": "saveBeforePublish",
  "Choose how Tavvy looks on this device.": "appearanceHelp",
  "Phone preview": "phonePreview",
  "9:16 phone preview": "phonePreviewRatio",
  "Scroll inside to see the full card": "scrollPreview",
  "Loading preview…": "loadingPreview",
  "Retry preview": "retryPreview",
  "The preview could not load. Your changes are still in the editor.": "previewFailed",
  "This preview could not be prepared. Return to Edit to continue.": "previewInvalid",
  "New photos appear here after they finish saving.": "pendingPhotos",
  "Blocked authors": "accountFinish1",
  "Blocked authors are hidden from your reviews, stories, photos, eCards and community comments. Place summaries still include all eligible public experiences.": "accountFinish2",
  "Sign in to manage content and blocked authors.": "accountFinish3",
  "No blocked authors.": "accountFinish4",
  "Unblock": "accountFinish5",
  "Loading…": "accountFinish6",
  "My eCards": "accountFinish7",
  "Create eCard": "accountFinish8",
  "Search cards...": "accountFinish9",
  "No cards match": "accountFinish10",
  "Edit Card": "accountFinish11",
  "View Stats": "accountFinish12",
  "Copy Link": "accountFinish13",
  "Duplicate": "accountFinish14",
  "Copying": "accountFinish15",
  "Stats": "accountFinish16",
  "Delete": "accountFinish17",
  "Delete Card?": "accountFinish18",
  "Untitled Card": "accountFinish19",
  "Live": "accountFinish20",
  "Create your first eCard": "accountFinish21",
  "Create your first digital card": "accountFinish22",
  "Share your professional identity with a beautiful digital business card": "accountFinish23",
  "Tap here to get started with your digital card": "accountFinish24",
  "Could not load card data.": "accountFinish25",
  "Failed to duplicate card.": "accountFinish26",
  "Failed to delete card.": "accountFinish27",
  "Failed to delete card. Please try again.": "accountFinish28",
  "This will permanently remove": "accountFinish29",
  "and all its data. This cannot be undone.": "accountFinish30",
  "Welcome to Tavvy": "accountFinish31",
  "A savvy way of tapping. Discover and share the vibe of places around you.": "accountFinish32",
  "Explore more Tavvy": "accountFinish33",
  "Explore more": "accountFinish34",
  "Log In": "accountFinish35",
  "Create Account": "accountFinish36",
  "Follow me on": "accountFinish37",
  "Edit Profile": "accountFinish38",
  "Points": "accountFinish39",
  "Badges": "accountFinish40",
  "Day Streak": "accountFinish41",
  "Account Information": "accountFinish42",
  "Member Since": "accountFinish43",
  "Account Type": "accountFinish44",
  "Status": "accountFinish45",
  "Trusted Contributor": "accountFinish46",
  "My Digital Card": "accountFinish47",
  "Help & Support": "accountFinish48",
  "Sign Out": "accountFinish49",
  "Are you sure you want to sign out?": "accountFinish50",
  "Failed to sign out": "accountFinish51",
  "Version": "accountFinish52",
  "Sign in to view your profile": "accountFinish53",
  "Create an account to save places, leave reviews, and more": "accountFinish54",
  "Sign In": "accountFinish55",
  "Don't have an account? Sign Up": "accountFinish56",
  "My Reviews": "accountFinish57",
  "No reviews yet": "accountFinish58",
  "Start exploring and leave your first review!": "accountFinish59",
  "Explore Places": "accountFinish60",
  "No saved places": "accountFinish61",
  "Save places you want to visit later": "accountFinish62",
  "Recently": "accountFinish63",
  "Tavvy Legend": "accountFinish64",
  "Tavvy Master": "accountFinish65",
  "Tavvy Expert": "accountFinish66",
  "Tavvy Explorer": "accountFinish67",
  "Tavvy Starter": "accountFinish68",
  "Newcomer": "accountFinish69",
  "Legend": "accountFinish70",
  "Master": "accountFinish71",
  "Expert": "accountFinish72",
  "Explorer": "accountFinish73",
  "Starter": "accountFinish74",
  "to": "accountFinish75",
  "Loading your card...": "accountFinish76",
  "No Digital Card Yet": "accountFinish77",
  "Create your digital business card to share your contact info instantly with anyone.": "accountFinish78",
  "Create My Card": "accountFinish79",
  "Retry loading card": "accountFinish80",
  "Back to Cards": "accountFinish81",
  "Return to editor": "accountFinish83",
  "Current edits · No actions sent": "accountFinish84",
  "Call": "accountFinish85",
  "Text": "accountFinish86",
  "Web": "accountFinish87",
  "Card": "accountFinish88",
  "Links": "accountFinish89",
  "My Links": "accountFinish90",
  "Share Your Card": "accountFinish91",
  "Card Not Published": "accountFinish92",
  "Your card is saved as a draft. Publish it first to share with others.": "accountFinish93",
  "Go to Dashboard to Publish": "accountFinish94",
  "QR Code": "accountFinish95",
  "Let others scan to view your card": "accountFinish96",
  "Share via...": "accountFinish97",
  "AirDrop, Messages, and more": "accountFinish98",
  "SMS / Text": "accountFinish99",
  "Send via text message": "accountFinish100",
  "Share on WhatsApp": "accountFinish101",
  "Send via email": "accountFinish102",
  "Copy card URL to clipboard": "accountFinish103",
  "Share Contact File": "accountFinish104",
  "Send as .vcf contact card": "accountFinish105",
  "Save to My Contacts": "accountFinish106",
  "Scan to View Card": "accountFinish107"
};

/** Existing translated UI labels, reused without changing their catalogs. */
export const EXISTING_COPY_KEYS: Record<string, string> = {
  "tavvy": "common.appName",
  "loading...": "common.loading",
  "error": "common.error",
  "retry": "common.retry",
  "cancel": "common.cancel",
  "save": "common.save",
  "delete": "common.delete",
  "edit": "common.edit",
  "close": "common.close",
  "back": "common.back",
  "next": "common.next",
  "done": "common.done",
  "search": "common.search",
  "filter": "common.filter",
  "sort": "common.sort",
  "share": "common.share",
  "copy": "common.copy",
  "copied!": "common.copied",
  "view all": "common.viewAll",
  "see more": "common.seeMore",
  "see less": "common.seeLess",
  "no results found": "common.noResults",
  "try again": "common.tryAgain",
  "learn more": "common.learnMore",
  "get started": "common.getStarted",
  "sign in": "common.signIn",
  "sign up": "common.signUp",
  "sign out": "common.signOut",
  "profile": "common.profile",
  "settings": "common.settings",
  "help": "common.help",
  "about": "common.about",
  "contact": "common.contact",
  "privacy": "common.privacy",
  "terms": "common.terms",
  "language": "common.language",
  "theme": "common.theme",
  "dark": "common.dark",
  "light": "common.light",
  "system": "common.system",
  "yes": "common.yes",
  "no": "common.no",
  "ok": "common.ok",
  "confirm": "common.confirm",
  "submit": "common.submit",
  "apply": "common.apply",
  "reset": "common.reset",
  "clear": "common.clear",
  "select": "common.select",
  "upload": "common.upload",
  "download": "common.download",
  "remove": "common.remove",
  "add": "common.add",
  "create": "common.create",
  "update": "common.update",
  "publish": "common.publish",
  "draft": "common.draft",
  "preview": "common.preview",
  "send": "common.send",
  "reply": "common.reply",
  "forward": "common.forward",
  "optional": "common.optional",
  "required": "common.required",
  "enabled": "common.enabled",
  "disabled": "common.disabled",
  "on": "common.on",
  "off": "common.off",
  "all": "common.all",
  "none": "common.none",
  "other": "common.other",
  "more": "common.more",
  "less": "common.less",
  "new": "common.new",
  "popular": "common.popular",
  "featured": "common.featured",
  "recommended": "common.recommended",
  "verified": "common.verified",
  "free": "common.free",
  "home": "navigation.home",
  "explore": "navigation.explore",
  "apps": "navigation.apps",
  "atlas": "navigation.atlas",
  "universes": "navigation.universes",
  "pros": "navigation.pros",
  "saved": "navigation.saved",
  "map": "navigation.map",
  "list": "navigation.list",
  "menu": "navigation.menu",
  "find a spot that fits your moment": "home.title",
  "discover places through real signals, not star ratings": "home.subtitle",
  "what are you in the mood for?": "home.searchPlaceholder",
  "near you": "home.nearYou",
  "trending": "home.trending",
  "happening now": "home.happeningNow",
  "explore tavvy": "home.exploreTavvy",
  "top contributors": "home.topContributors",
  "did you know?": "home.didYouKnow",
  "stories": "home.stories",
  "your story": "home.yourStory",
  "add story": "home.addStory",
  "good morning": "home.greeting.morning",
  "good afternoon": "home.greeting.afternoon",
  "good evening": "home.greeting.evening",
  "good night": "home.greeting.night",
  "find your perfect spot in seconds. not hours.": "home.tagline",
  "near me": "home.nearMe",
  "surprise": "home.surprise",
  "what's your mood?": "home.whatsYourMood",
  "hungry": "home.hungry",
  "thirsty": "home.thirsty",
  "restaurants & food": "home.restaurantsFood",
  "bars & cafes": "home.barsCafes",
  "live now": "home.liveNow",
  "see all": "home.seeAll",
  "hours left": "home.hoursLeft",
  "starts at": "home.startsAt",
  "all day today": "home.allDayToday",
  "experiences nearby": "home.experiencesNearby",
  "explore something new": "home.exploreSomethingNew",
  "events, activities & hidden gems": "home.eventsActivities",
  "tavvy uses tap-based signals instead of star ratings to give you honest, structured insights about places.": "home.didYouKnowText",
  "community members making a difference": "home.communityMembers",
  "day streak": "home.dayStreak",
  "taps": "home.taps",
  "quick finds": "home.quickFinds",
  "experiences": "home.experiences",
  "cities": "home.cities",
  "discover cities": "home.discoverCities",
  "explore cities around the world": "home.exploreCities",
  "there": "home.greetingName",
  "curated worlds of experiences": "home.curatedWorlds",
  "signals": "home.signals",
  "signal search": "signalSearch.title",
  "combine signals to find your perfect spot": "signalSearch.subtitle",
  "filter signals...": "signalSearch.filterPlaceholder",
  "searching": "signalSearch.searching",
  "results": "signalSearch.results",
  "places": "signalSearch.places",
  "combined taps": "signalSearch.combinedTaps",
  "loading signals...": "signalSearch.loadingSignals",
  "no places found": "signalSearch.noResults",
  "try removing some signals or selecting different ones": "signalSearch.noResultsHint",
  "nearby": "places.nearby",
  "recent": "places.recent",
  "category": "places.category",
  "distance": "places.distance",
  "open now": "places.openNow",
  "closed": "places.closedNow",
  "hours": "places.hours",
  "address": "places.address",
  "phone": "places.phone",
  "website": "places.website",
  "directions": "places.directions",
  "reviews": "places.reviews",
  "photos": "places.photos",
  "add review": "places.addReview",
  "add photo": "places.addPhoto",
  "report": "places.report",
  "claim this place": "places.claim",
  "best for": "places.bestFor",
  "vibe": "places.vibe",
  "heads up": "places.headsUp",
  "no signals yet": "places.noSignals",
  "be the first to add signals": "places.beFirst",
  "details": "places.details",
  "information": "places.information",
  "services": "places.services",
  "description": "places.description",
  "features": "places.features",
  "amenities": "places.amenities",
  "parking": "places.parking",
  "accessibility": "places.accessibility",
  "price range": "places.priceRange",
  "rating": "places.rating",
  "tap signals": "places.tapSignals",
  "add signal": "places.addSignal",
  "share place": "places.sharePlace",
  "save place": "places.savePlace",
  "get directions": "places.getDirections",
  "call now": "places.callNow",
  "visit website": "places.visitWebsite",
  "write a review": "places.writeReview",
  "see all reviews": "places.seeAllReviews",
  "see all photos": "places.seeAllPhotos",
  "similar places": "places.similarPlaces",
  "nearby places": "places.nearbyPlaces",
  "restaurants": "categories.restaurants",
  "cafes": "categories.cafes",
  "bars": "categories.bars",
  "gas stations": "categories.gas",
  "shopping": "categories.shopping",
  "hotels": "categories.hotels",
  "rv & camping": "categories.rvCamping",
  "attractions": "categories.attractions",
  "healthcare": "categories.healthcare",
  "entertainment": "categories.entertainment",
  "outdoors": "categories.outdoors",
  "nightlife": "categories.nightlife",
  "beauty & spa": "categories.beauty",
  "fitness": "categories.fitness",
  "education": "categories.education",
  "automotive": "categories.automotive",
  "pets": "categories.pets",
  "financial services": "categories.financial",
  "discover places by category": "atlas.subtitle",
  "explore categories": "atlas.exploreCategories",
  "featured places": "atlas.featuredPlaces",
  "owner spotlight": "atlas.ownerSpotlight",
  "local favorites": "atlas.localFavorites",
  "newly added": "atlas.newlyAdded",
  "search places...": "atlas.searchPlaces",
  "all categories": "atlas.allCategories",
  "top picks": "atlas.topPicks",
  "browse all": "atlas.browseAll",
  "owner story": "atlas.ownerStory",
  "meet the owner": "atlas.meetTheOwner",
  "read more": "atlas.readMore",
  "explore themed collections": "universes.subtitle",
  "airports": "universes.airports",
  "theme parks": "universes.themeParks",
  "beaches": "universes.beaches",
  "mountains": "universes.mountains",
  "join universe": "universes.join",
  "members": "universes.members",
  "about this universe": "universes.about",
  "universe rules": "universes.rules",
  "moderators": "universes.moderators",
  "posts": "universes.posts",
  "events": "universes.events",
  "leaderboard": "universes.leaderboard",
  "create post": "universes.createPost",
  "joined members": "universes.joinedMembers",
  "recent activity": "universes.recentActivity",
  "explore all universes": "universes.exploreAll",
  "my universes": "universes.myUniverses",
  "trending universes": "universes.trending",
  "new universes": "universes.new",
  "tavvy pros": "pros.title",
  "find verified professionals": "pros.subtitle",
  "find a pro": "pros.findPro",
  "categories": "pros.categories",
  "pros near you": "pros.nearYou",
  "top rated": "pros.topRated",
  "verified pro": "pros.verified",
  "licensed": "pros.licensed",
  "insured": "pros.insured",
  "get quote": "pros.getQuote",
  "portfolio": "pros.portfolio",
  "service area": "pros.serviceArea",
  "availability": "pros.availability",
  "response time": "pros.responseTime",
  "projects completed": "pros.projectsCompleted",
  "years experience": "pros.yearsExperience",
  "tavvy shield": "pros.shield",
  "shield protected": "pros.shieldProtected",
  "pro dashboard": "pros.dashboard",
  "my projects": "pros.myProjects",
  "new project": "pros.newProject",
  "project details": "pros.projectDetails",
  "project title": "pros.projectTitle",
  "project description": "pros.projectDescription",
  "budget": "pros.projectBudget",
  "timeline": "pros.projectTimeline",
  "location": "pros.projectLocation",
  "submit project": "pros.submitProject",
  "project submitted!": "pros.projectSubmitted",
  "your project has been submitted successfully. pros will reach out to you soon.": "pros.projectSubmittedMessage",
  "register as pro": "pros.register",
  "pro login": "pros.login",
  "business name": "pros.businessName",
  "business type": "pros.businessType",
  "license number": "pros.licenseNumber",
  "insurance information": "pros.insuranceInfo",
  "certifications": "pros.certifications",
  "background check": "pros.backgroundCheck",
  "join tavvy pros": "pros.joinTavvyPros",
  "become a verified pro": "pros.becomeVerified",
  "grow your business": "pros.growBusiness",
  "connect with clients": "pros.connectClients",
  "manage projects": "pros.manageProjects",
  "track performance": "pros.trackPerformance",
  "forgot password": "pros.forgotPassword",
  "reset password": "pros.resetPassword",
  "your saved places and lists": "saved.subtitle",
  "lists": "saved.lists",
  "create list": "saved.createList",
  "add to list": "saved.addToList",
  "remove from list": "saved.removeFromList",
  "no saved places yet": "saved.noSaved",
  "start saving places you love": "saved.startSaving",
  "professionals": "saved.pros",
  "edit profile": "profile.editProfile",
  "my reviews": "profile.myReviews",
  "my photos": "profile.myPhotos",
  "my lists": "profile.myLists",
  "contributions": "profile.contributions",
  "badges": "profile.badges",
  "level": "profile.level",
  "points": "profile.points",
  "streak": "profile.streak",
  "joined": "profile.joined",
  "followers": "profile.followers",
  "following": "profile.following",
  "bio": "profile.bio",
  "social links": "profile.socialLinks",
  "account settings": "profile.accountSettings",
  "change password": "profile.changePassword",
  "delete account": "profile.deleteAccount",
  "email": "auth.email",
  "password": "auth.password",
  "confirm password": "auth.confirmPassword",
  "forgot password?": "auth.forgotPassword",
  "create account": "auth.createAccount",
  "already have an account?": "auth.alreadyHaveAccount",
  "don't have an account?": "auth.dontHaveAccount",
  "or continue with": "auth.orContinueWith",
  "google": "auth.google",
  "apple": "auth.apple",
  "by signing up, you agree to our": "auth.termsAgree",
  "and": "auth.and",
  "full name": "auth.fullName",
  "username": "auth.username",
  "phone number": "auth.phone",
  "verification code": "auth.verificationCode",
  "send code": "auth.sendCode",
  "verify code": "auth.verifyCode",
  "resend code": "auth.resendCode",
  "new password": "auth.newPassword",
  "confirm new password": "auth.confirmNewPassword",
  "update password": "auth.updatePassword",
  "password updated successfully": "auth.passwordUpdated",
  "check your email for reset instructions": "auth.checkEmail",
  "account": "settings.account",
  "notifications": "settings.notifications",
  "help & support": "settings.help",
  "send feedback": "settings.feedback",
  "rate app": "settings.rateApp",
  "version": "settings.version",
  "dark mode": "settings.darkMode",
  "auto-translate reviews": "settings.autoTranslate",
  "push notifications": "settings.pushNotifications",
  "email notifications": "settings.emailNotifications",
  "live business alerts": "settings.liveBusinessAlerts",
  "privacy & security": "settings.privacySection",
  "location sharing": "settings.locationSharing",
  "share usage data": "settings.shareUsageData",
  "preferences": "settings.preferencesSection",
  "distance unit": "settings.distanceUnit",
  "default map layer": "settings.defaultMapLayer",
  "contact support": "settings.contactSupport",
  "legal": "settings.legalSection",
  "terms of service": "settings.termsOfService",
  "privacy policy": "settings.privacyPolicy",
  "faq": "settings.faq",
  "miles": "settings.miles",
  "kilometers": "settings.kilometers",
  "standard": "settings.standard",
  "satellite": "settings.satellite",
  "hybrid": "settings.hybrid",
  "terrain": "settings.terrain",
  "select language": "settings.selectLanguage",
  "select distance unit": "settings.selectDistanceUnit",
  "select map layer": "settings.selectMapLayer",
  "select your preferred language. the app will display content in your chosen language where translations are available.": "settings.languageDescription",
  "search places, categories, pros...": "search.placeholder",
  "recent searches": "search.recent",
  "popular searches": "search.popular",
  "suggestions": "search.suggestions",
  "try a different search term": "search.tryDifferent",
  "filters": "search.filters",
  "sort by": "search.sortBy",
  "relevance": "search.relevance",
  "apply filters": "search.applyFilters",
  "clear filters": "search.clearFilters",
  "place": "search.place",
  "something went wrong": "errors.generic",
  "network error. please check your connection.": "errors.network",
  "not found": "errors.notFound",
  "please sign in to continue": "errors.unauthorized",
  "you don't have permission to do this": "errors.forbidden",
  "server error. please try again later.": "errors.serverError",
  "request timed out. please try again.": "errors.timeout",
  "please enter a valid email": "errors.invalidEmail",
  "password must be at least 8 characters": "errors.invalidPassword",
  "passwords do not match": "errors.passwordMismatch",
  "this field is required": "errors.requiredField",
  "file is too large": "errors.fileTooLarge",
  "invalid file format": "errors.invalidFormat",
  "location access denied": "errors.locationDenied",
  "saved successfully": "success.saved",
  "deleted successfully": "success.deleted",
  "updated successfully": "success.updated",
  "sent successfully": "success.sent",
  "copied to clipboard": "success.copied",
  "account created!": "success.accountCreated",
  "profile updated!": "success.profileUpdated",
  "review submitted!": "success.reviewSubmitted",
  "photo uploaded!": "success.photoUploaded",
  "message sent!": "success.messageSent",
  "now": "time.now",
  "today": "time.today",
  "yesterday": "time.yesterday",
  "tomorrow": "time.tomorrow",
  "this week": "time.thisWeek",
  "this month": "time.thisMonth",
  "ago": "time.ago",
  "in": "time.in",
  "minutes": "time.minutes",
  "days": "time.days",
  "weeks": "time.weeks",
  "months": "time.months",
  "years": "time.years",
  "upcoming events": "events.upcoming",
  "events near you": "events.nearby",
  "event details": "events.details",
  "date": "events.date",
  "time": "events.time",
  "venue": "events.venue",
  "price": "events.price",
  "get tickets": "events.getTickets",
  "add to calendar": "events.addToCalendar",
  "share event": "events.share",
  "protection built into discovery": "shield.subtitle",
  "verified identity": "shield.verifiedIdentity",
  "payment protection": "shield.paymentProtection",
  "real activity signals": "shield.realSignals",
  "how it works": "shield.howItWorks",
  "protected by tavvy shield": "shield.protectedBy",
  "verified professional": "shield.verifiedPro",
  "background checked": "shield.backgroundChecked",
  "money-back guarantee": "shield.moneyBackGuarantee",
  "digital business card": "ecard.title",
  "create your card": "ecard.create",
  "edit card": "ecard.edit",
  "share card": "ecard.share",
  "templates": "ecard.templates",
  "customize": "ecard.customize",
  "links": "ecard.links",
  "contact info": "ecard.contact",
  "social media": "ecard.social",
  "analytics": "ecard.analytics",
  "views": "ecard.views",
  "saves": "ecard.saves",
  "ecard dashboard": "ecard.dashboard",
  "my cards": "ecard.myCards",
  "create new card": "ecard.createNew",
  "choose a template": "ecard.chooseTemplate",
  "personal information": "ecard.personalInfo",
  "first name": "ecard.firstName",
  "last name": "ecard.lastName",
  "job title": "ecard.jobTitle",
  "company": "ecard.company",
  "facebook": "ecard.facebook",
  "instagram": "ecard.instagram",
  "x (twitter)": "ecard.twitter",
  "linkedin": "ecard.linkedin",
  "tiktok": "ecard.tiktok",
  "youtube": "ecard.youtube",
  "github": "ecard.github",
  "custom link": "ecard.customLink",
  "add link": "ecard.addLink",
  "remove link": "ecard.removeLink",
  "design": "ecard.design",
  "colors": "ecard.colors",
  "primary color": "ecard.primaryColor",
  "background color": "ecard.backgroundColor",
  "text color": "ecard.textColor",
  "font": "ecard.font",
  "layout": "ecard.layout",
  "profile photo": "ecard.profilePhoto",
  "upload photo": "ecard.uploadPhoto",
  "remove photo": "ecard.removePhoto",
  "logo": "ecard.logo",
  "upload logo": "ecard.uploadLogo",
  "qr code": "ecard.qrCode",
  "download qr code": "ecard.downloadQR",
  "share via": "ecard.shareVia",
  "copy link": "ecard.copyLink",
  "premium": "ecard.premium",
  "upgrade to premium": "ecard.upgradePremium",
  "premium features": "ecard.premiumFeatures",
  "multiple cards": "ecard.multipleCards",
  "custom domain": "ecard.customDomain",
  "advanced analytics": "ecard.advancedAnalytics",
  "remove watermark": "ecard.removeWatermark",
  "priority support": "ecard.prioritySupport",
  "find the perfect spot": "rv.subtitle",
  "campgrounds": "rv.campgrounds",
  "rv parks": "rv.rvParks",
  "hookups": "rv.hookups",
  "pet friendly": "rv.petFriendly",
  "wifi": "rv.wifi",
  "showers": "rv.showers",
  "laundry": "rv.laundry",
  "store": "rv.store",
  "pool": "rv.pool",
  "water": "rv.water",
  "electric": "rv.electric",
  "sewer": "rv.sewer",
  "full hookup": "rv.fullHookup",
  "pull-through": "rv.pullThrough",
  "back-in": "rv.backIn",
  "tent sites": "rv.tentSites",
  "cabins": "rv.cabins",
  "glamping": "rv.glamping",
  "yurts": "rv.yurts",
  "rides & attractions": "rides.title",
  "discover thrilling experiences": "rides.subtitle",
  "roller coasters": "rides.rollerCoasters",
  "water rides": "rides.waterRides",
  "family rides": "rides.familyRides",
  "shows": "rides.shows",
  "dining": "rides.dining",
  "wait time": "rides.waitTime",
  "height requirement": "rides.height",
  "fast pass available": "rides.fastPass",
  "thrill level": "rides.thrill",
  "duration": "rides.duration",
  "capacity": "rides.capacity",
  "tickets": "rides.tickets",
  "souvenirs": "rides.souvenirs",
  "tours": "rides.tours",
  "park map": "rides.mapOfPark",
  "schedule": "rides.schedule",
  "realtors": "realtors.title",
  "find your perfect home": "realtors.subtitle",
  "find a realtor": "realtors.findRealtor",
  "buying agent": "realtors.buyingAgent",
  "selling agent": "realtors.sellingAgent",
  "specialties": "realtors.specialties",
  "listings": "realtors.listings",
  "sold homes": "realtors.soldHomes",
  "contact realtor": "realtors.contact",
  "residential": "realtors.residential",
  "commercial": "realtors.commercial",
  "luxury": "realtors.luxury",
  "investment": "realtors.investment",
  "first-time buyer": "realtors.firstTimeBuyer",
  "relocation": "realtors.relocation",
  "property types": "realtors.propertyTypes",
  "house": "realtors.house",
  "condo": "realtors.condo",
  "townhouse": "realtors.townhouse",
  "apartment": "realtors.apartment",
  "land": "realtors.land",
  "match with a realtor": "realtors.matchWithRealtor",
  "start matching": "realtors.startMatching",
  "what are you looking for?": "realtors.whatLookingFor",
  "buying": "realtors.buying",
  "selling": "realtors.selling",
  "renting": "realtors.renting",
  "preferred area": "realtors.preferredArea",
  "contact information": "realtors.contactInfo",
  "my location": "map.myLocation",
  "zoom in": "map.zoomIn",
  "zoom out": "map.zoomOut",
  "layers": "map.layers",
  "traffic": "map.traffic",
  "transit": "map.transit",
  "biking": "map.biking",
  "walking": "map.walking",
  "driving": "map.driving",
  "search this area": "map.searchThisArea",
  "show list": "map.showList",
  "show map": "map.showMap",
  "filter results": "map.filterResults",
  "add a place": "add.title",
  "place name": "add.placeName",
  "city": "add.city",
  "state": "add.state",
  "zip code": "add.zipCode",
  "country": "add.country",
  "add photos": "add.addPhotos",
  "business hours": "add.hours",
  "set hours": "add.setHours",
  "submit place": "add.submit",
  "save draft": "add.saveDraft",
  "write your review...": "add.writeReview",
  "select rating": "add.selectRating",
  "upload photos": "add.uploadPhotos",
  "story title": "add.storyTitle",
  "tell your story...": "add.storyContent",
  "submit review": "add.submitReview",
  "submit story": "add.submitStory",
  "frequently asked questions": "help.faq",
  "contact us": "help.contactUs",
  "report a bug": "help.reportBug",
  "feature request": "help.featureRequest",
  "community": "help.community",
  "documentation": "help.documentation",
  "getting started": "help.gettingStarted",
  "account help": "help.accountHelp",
  "© {{year}} tavvy, inc. all rights reserved.": "legal.copyright",
  "cookie policy": "legal.cookiePolicy",
  "disclaimer": "legal.disclaimer",
  "mark all as read": "notifications.markAllRead",
  "no notifications yet": "notifications.noNotifications",
  "new review on your place": "notifications.newReview",
  "new follower": "notifications.newFollower",
  "new message": "notifications.newMessage",
  "project update": "notifications.projectUpdate",
  "messages": "messages.title",
  "no messages yet": "messages.noMessages",
  "type a message...": "messages.typeMessage",
  "online": "messages.online",
  "offline": "messages.offline",
  "last seen": "messages.lastSeen",
  "typing...": "messages.typing",
  "tools & shortcuts": "apps.subtitle",
  "search apps...": "apps.searchApps",
  "all apps": "apps.allApps",
  "appearance": "apps.appearance",
  "ecard": "apps.ecard",
  "on the go": "apps.onTheGo",
  "rides": "apps.rides",
  "wallet": "apps.wallet",
  "happening": "apps.happening",
  "vote": "civic.vote",
  "community pulse": "civic.communityPulse",
  "support {{pct}}%": "civic.supportPct",
  "improve {{pct}}%": "civic.improvePct",
  "disagree {{pct}}%": "civic.disagreePct",
  "proposals": "civic.proposals",
  "q&a": "civic.qna",
  "goals": "civic.goals",
  "no proposals yet": "civic.noProposals",
  "{{pct}}% support • {{total}} votes": "civic.supportVotes",
  "support": "civic.support",
  "improve": "civic.improve",
  "disagree": "civic.disagree",
  "what would you like to know?": "civic.askPlaceholder",
  "sending...": "civic.sending",
  "ask": "civic.ask",
  "no questions yet. be the first to ask!": "civic.noQuestions",
  "no commitments posted yet": "civic.noCommitments",
  "completed": "civic.completed",
  "in progress": "civic.inProgress",
  "planned": "civic.planned",
  "votes": "civic.votes",
  "question submitted! the candidate will be notified.": "civic.questionSubmitted",
  "{{name}}'s answer": "civic.candidateAnswer",
  "who i recommend": "civic.whoIRecommend",
  "your question has been submitted and is pending approval.": "civic.questionPending",
  "pending questions": "civic.pendingQuestions",
  "no pending questions to review": "civic.noPendingQuestions",
  "approve": "civic.approve",
  "reject": "civic.reject",
  "approve & answer": "civic.approveAndAnswer",
  "type your answer (optional)...": "civic.typeAnswer",
  "endorsements": "endorsement.title",
  "{{count}} total endorsements": "endorsement.totalCount",
  "no endorsements yet. be the first!": "endorsement.noEndorsements",
  "endorse {{name}} →": "endorsement.endorseButton",
  "thank you for your endorsement!": "endorsement.thankYou",
  "what stood out?": "endorsement.whatStoodOut",
  "tap to select · tap again to make it stronger": "endorsement.tapInstructions",
  "add a note (optional)...": "endorsement.notePlaceholder",
  "submitting...": "endorsement.submitting",
  "continue →": "endorsement.continue",
  "strengths": "endorsement.catStrengths",
  "politics": "endorsement.catPolitics",
  "sales skills": "endorsement.catSales",
  "real estate": "endorsement.catRealEstate",
  "food & dining": "endorsement.catFoodDining",
  "health & wellness": "endorsement.catHealthWellness",
  "beauty": "endorsement.catBeauty",
  "home services": "endorsement.catHomeServices",
  "legal & finance": "endorsement.catLegalFinance",
  "creative & marketing": "endorsement.catCreativeMarketing",
  "education & coaching": "endorsement.catEducationCoaching",
  "tech & it": "endorsement.catTechIt",
  "events & entertainment": "endorsement.catEventsEntertainment",
  "highly recommended": "endorsement.signalHighlyRecommended",
  "trustworthy": "endorsement.signalTrustworthy",
  "responsive": "endorsement.signalResponsive",
  "expert": "endorsement.signalExpert",
  "reliable": "endorsement.signalReliable",
  "great communicator": "endorsement.signalGreatCommunicator",
  "goes above & beyond": "endorsement.signalGoesAboveBeyond",
  "on time": "endorsement.signalOnTime",
  "transparent": "endorsement.signalTransparent",
  "keeps promises": "endorsement.signalKeepsPromises",
  "community leader": "endorsement.signalCommunityLeader",
  "clear communicator": "endorsement.signalClearCommunicator",
  "fair & just": "endorsement.signalFairJust",
  "gets things done": "endorsement.signalGetsThingsDone",
  "innovative ideas": "endorsement.signalInnovativeIdeas",
  "fights for people": "endorsement.signalFightsForPeople",
  "great closer": "endorsement.signalGreatCloser",
  "knowledgeable": "endorsement.signalKnowledgeable",
  "follows through": "endorsement.signalFollowsThrough",
  "data-driven": "endorsement.signalDataDriven",
  "persistent": "endorsement.signalPersistent",
  "market expert": "endorsement.signalMarketExpert",
  "great negotiator": "endorsement.signalGreatNegotiator",
  "always available": "endorsement.signalAlwaysAvailable",
  "creative solutions": "endorsement.signalCreativeSolutions",
  "detail oriented": "endorsement.signalDetailOriented",
  "got best price": "endorsement.signalGotBestPrice",
  "great food": "endorsement.signalGreatFood",
  "fast service": "endorsement.signalFastService",
  "friendly staff": "endorsement.signalFriendlyStaff",
  "clean": "endorsement.signalClean",
  "good value": "endorsement.signalGoodValue",
  "great presentation": "endorsement.signalGreatPresentation",
  "thorough": "endorsement.signalThorough",
  "puts you at ease": "endorsement.signalPutsYouAtEase",
  "great results": "endorsement.signalGreatResults",
  "clear explanations": "endorsement.signalClearExplanations",
  "skilled": "endorsement.signalSkilled",
  "creative": "endorsement.signalCreative",
  "listens well": "endorsement.signalListensWell",
  "punctual": "endorsement.signalPunctual",
  "attention to detail": "endorsement.signalAttentionToDetail",
  "quality work": "endorsement.signalQualityWork",
  "fair pricing": "endorsement.signalFairPricing",
  "left it clean": "endorsement.signalLeftItClean",
  "on schedule": "endorsement.signalOnSchedule",
  "stands behind work": "endorsement.signalStandsBehindWork",
  "fair & honest": "endorsement.signalFairHonest",
  "strategic": "endorsement.signalStrategic",
  "clear advice": "endorsement.signalClearAdvice",
  "confidential": "endorsement.signalConfidential",
  "creative vision": "endorsement.signalCreativeVision",
  "great eye": "endorsement.signalGreatEye",
  "delivers results": "endorsement.signalDeliversResults",
  "innovative": "endorsement.signalInnovative",
  "understands brand": "endorsement.signalUnderstandsBrand",
  "inspiring": "endorsement.signalInspiring",
  "goal-oriented": "endorsement.signalGoalOriented",
  "patient": "endorsement.signalPatient",
  "tracks progress": "endorsement.signalTracksProgress",
  "problem solver": "endorsement.signalProblemSolver",
  "fast turnaround": "endorsement.signalFastTurnaround",
  "security-minded": "endorsement.signalSecurityMinded",
  "up to date": "endorsement.signalUpToDate",
  "smart solutions": "endorsement.signalSmartSolutions",
  "honest diagnosis": "endorsement.signalHonestDiagnosis",
  "quick service": "endorsement.signalQuickService",
  "warranty backed": "endorsement.signalWarrantyBacked",
  "quality parts": "endorsement.signalQualityParts",
  "great energy": "endorsement.signalGreatEnergy",
  "well organized": "endorsement.signalWellOrganized",
  "perfect vibe": "endorsement.signalPerfectVibe",
  "memorable": "endorsement.signalMemorable",
  "creative ideas": "endorsement.signalCreativeIdeas",
  "loves animals": "endorsement.signalLovesAnimals",
  "gentle": "endorsement.signalGentle",
  "clean facility": "endorsement.signalCleanFacility",
  "friendly": "endorsement.signalFriendly",
  "send message": "messaging.sendMessage",
  "message {{name}}": "messaging.messageTo",
  "private conversation": "messaging.privateConversation",
  "start a conversation with {{name}}": "messaging.startConversation",
  "your message will be sent privately": "messaging.yourMessagePrivate",
  "loading messages...": "messaging.loading",
  "just now": "messaging.justNow",
  "log in to send a message": "messaging.loginRequired",
  "inbox": "inbox.title",
  "primary": "inbox.primary",
  "spam": "inbox.spam",
  "no spam messages": "inbox.noSpam",
  "not spam": "inbox.notSpam",
  "type a reply...": "inbox.typeReply",
  "loading geo analytics...": "geo.loading",
  "no geo data available yet.": "geo.noData",
  "total endorsements": "geo.totalEndorsements",
  "total votes": "geo.totalVotes",
  "zip/ip mismatch rate": "geo.mismatchRate",
  "total mismatches": "geo.totalMismatches",
  "high mismatch rate detected": "geo.mismatchAlert",
  "{{rate}}% of interactions show a different ip location than the self-reported zip code. this could indicate users accessing from different locations or potential misrepresentation.": "geo.mismatchAlertDesc",
  "self-reported zip": "geo.selfReported",
  "ip-based zip": "geo.ipBased",
  "by city": "geo.byCity",
  "reported locations": "geo.reportedLocations",
  "detected locations (ip)": "geo.detectedLocations",
  "city breakdown": "geo.cityBreakdown",
  "mismatches": "geo.mismatches",
  "no location data available": "geo.noLocationData",
  "+ {{count}} more locations": "geo.andMore",
  "needs improvement": "geo.needsImprovement",
  "self-reported vs ip detection": "geo.dualSourceComparison",
  "compare what users report as their location versus where their ip address indicates they are. high mismatch rates may indicate users accessing from different locations than reported.": "geo.dualSourceDesc",
  "self-reported (zip)": "geo.selfReportedTitle",
  "ip-detected location": "geo.ipDetectedTitle",
  "zip code is required": "signup.zipCodeRequired",
  "enter your zip code": "signup.zipCodePlaceholder",
  "address (optional)": "signup.addressOptional",
  "street address": "signup.addressPlaceholder",
  "add your location": "zipPrompt.title",
  "please add your zip code to continue. this helps us provide better local information.": "zipPrompt.description",
  "full address (optional)": "zipPrompt.addressLabel",
  "save & continue": "zipPrompt.save",
  "skip for now": "zipPrompt.skip",
  "the good": "signals.theGood",
  "the vibe": "signals.theVibe",
  "what this place does best": "signals.theGoodDesc",
  "what it feels like": "signals.theVibeDesc",
  "what to watch out for": "signals.headsUpDesc",
  "be the first to leave a signal!": "signals.beFirstToTap",
  "tap to select": "signals.tapToSelect",
  "tap again to make it stronger": "signals.tapAgainStronger",
  "submit signals": "signals.submitSignals",
  "community signals": "signals.communitySignals",
  "signal breakdown": "signals.signalBreakdown"
};

Object.assign(RELEASE_COPY_KEYS, {
  "Find your next happy place.": "discoveryTitle",
  "Good food, new adventures, and people you can trust.": "discoverySubtitle",
  "Map": "map",
  "Surprise": "surprise",
  "Let Tavvy decide": "letTavvyDecide",
  "Search by vibe": "searchByVibe",
  "What's your mood?": "moodQuestion",
  "Hungry": "hungry",
  "Restaurants & Food": "restaurantsFood",
  "Thirsty": "thirsty",
  "Bars & Cafes": "barsCafes",
  "Places to explore": "placesToExplore",
  "Find good food and the signals that matter.": "foodSignals",
  "Find a stay that feels right for you.": "rightStay",
  "Stories are coming soon": "storiesSoon",
  "Great stories about your favorite places are about to go live. Stay tuned!": "storiesSoonMessage",
  "Create your eCard": "createECard",
  "Start with your name. Add links and customize your card next.": "setupIntro",
  "Photo is optional": "photoOptional",
  "Title / role": "titleRole",
  "(optional)": "optional",
  "Creating draft…": "creatingDraft",
  "Create draft": "createDraft",
  "Your full name": "yourFullName",
  "Primary color": "primaryColor",
  "Choose card type & template": "chooseTypeTemplate",
  "All tools": "allTools",
  "Restart Required": "restartRequired",
  "Please restart the app for the layout changes to take effect.": "restartMessage"
});
Object.assign(RELEASE_COPY_KEYS, {
  "Find your next theme park adventure.": "ridesDescription",
  "Discover the places within parks, airports and more.": "universesDescription",
  "Find local people to help with your next project.": "prosDescription",
  "Get to know a new neighborhood or city.": "citiesDescription",
  "Explore guides and ideas for your next trip.": "atlasDescription",
  "Your card stays private until you publish.": "privateDraftNote",
  "Retry save": "retrySave",
  "Contact Form · Pro": "formPro"
});

Object.assign(RELEASE_COPY_KEYS, {"Great food": "needFood", "Quiet conversation": "needQuiet", "Quick visit": "needQuick", "Good value": "needValue"});

Object.assign(RELEASE_COPY_KEYS, {"Any location": "anyLocation", "Search is temporarily unavailable.": "searchUnavailable", "Retry search": "retrySearch", "Searching…": "searching", "Checking guest reports…": "checkingReports", "Try another search or location.": "tryAnotherSearch", "Search is temporarily unavailable": "searchUnavailable", "Searching...": "searching"});

// Settings and eCard creation: explicit interface copy, never saved card content.
Object.assign(RELEASE_COPY_KEYS, {
  "Choose your look": "finishChooseYourLook",
  "Quick setup": "finishQuickSetup",
  "Choose a card type": "finishChooseACardType",
  "Close card creation": "finishCloseCardCreation",
  "New eCard": "finishNewECard",
  "Change design or color": "finishChangeDesignOrColor",
  "Use this template": "finishUseThisTemplate",
  "Card type & country": "finishCardTypeCountry",
  "Personal": "finishPersonal",
  "Politician": "finishPolitician",
  "Civic / Public Service": "finishCivicPublicService",
  "Checking your plan…": "finishCheckingYourPlan",
  "Pro design": "finishProDesign",
  "Pro design or color": "finishProDesignOrColor",
  "This design or color requires Pro. Choose an available option or review your plan.": "finishThisDesignOrColorRequiresProChoose",
  "Previous template": "finishPreviousTemplate",
  "Next template": "finishNextTemplate",
  "Swipe to browse templates": "finishSwipeToBrowseTemplates",
  "No templates available for this category": "finishNoTemplatesAvailableForThisCategory",
  "Close preview": "finishClosePreview",
  "Start with your name. Everything else can be added in the editor.": "finishStartWithYourNameEverythingElseCan",
  "Name *": "finishName",
  "Your name or business name": "finishYourNameOrBusinessName",
  "Hide optional setup": "finishHideOptionalSetup",
  "Add title or choose a starting color": "finishAddTitleOrChooseAStartingColor",
  "Title / Role": "finishTitleRole",
  "e.g. CEO, Designer, Agent": "finishEGCEODesignerAgent",
  "Primary Color": "finishPrimaryColor",
  "Create card": "finishCreateCard",
  "Permission needed": "finishPermissionNeeded",
  "Camera permission is required to take a photo.": "finishCameraPermissionIsRequiredToTakeA",
  "Failed to pick image. Please try again.": "finishFailedToPickImagePleaseTryAgain",
  "Your photo could not upload. Your setup is still here; please try again.": "finishYourPhotoCouldNotUploadYourSetup",
  "Could not create card": "finishCouldNotCreateCard",
  "Card was not returned after creation. Please try again.": "finishCardWasNotReturnedAfterCreationPlease",
  "Failed to create card. Please try again.": "finishFailedToCreateCardPleaseTryAgain",
  "Select your country": "finishSelectYourCountry",
  "Choose where the politician operates": "finishChooseWhereThePoliticianOperates",
  "Search country...": "finishSearchCountry",
  "What kind of card?": "finishWhatKindOfCard",
  "Select the type that best fits your needs": "finishSelectTheTypeThatBestFitsYour",
  "For your company, store, or service": "finishForYourCompanyStoreOrService",
  "Your personal brand & link page": "finishYourPersonalBrandLinkPage",
  "For public servants & candidates": "finishForPublicServantsCandidates",
  "Live Business Alerts": "finishLiveBusinessAlerts",
  "Privacy & Security": "finishPrivacySecurity",
  "Share Usage Data": "finishShareUsageData",
  "Preferences": "finishPreferences",
  "Distance Unit": "finishDistanceUnit",
  "Choose your preferred distance unit": "finishChooseYourPreferredDistanceUnit",
  "Miles": "finishMiles",
  "Kilometers": "finishKilometers",
  "Default Map Layer": "finishDefaultMapLayer",
  "Choose your default map style": "finishChooseYourDefaultMapStyle",
  "Brazil": "finishBrazil",
  "United States": "finishUnitedStates",
  "United Kingdom": "finishUnitedKingdom",
  "Canada": "finishCanada",
  "Mexico": "finishMexico",
  "Colombia": "finishColombia",
  "Spain": "finishSpain",
  "France": "finishFrance",
  "Germany": "finishGermany",
  "Australia": "finishAustralia",
  "India": "finishIndia",
  "Nigeria": "finishNigeria",
  "Japan": "finishJapan",
  "This permanently removes your sign-in, private profile, cards, reviews, saved activity, uploaded files, and live location sessions. Shared business and payroll history may remain without an account ownership link. Public place, event, and campground listings remain without your creator link. Stripe subscriptions linked to your account will be canceled; Apple or Google subscriptions must be managed in your store subscription settings.": "finishThisPermanentlyRemovesYourSignInPrivate",
  "Take Photo": "finishTakePhoto",
  "Loading your account…": "finishWeb1",
  "Sign in to save your card as a private draft.": "finishWeb2",
  "All templates and card types are available to browse.": "finishWeb3",
  "Your photo could not upload. Please retry; your details are still here.": "finishWeb4",
  "Your draft could not be created. Please retry; your details are still here.": "finishWeb5",
  "Swipe through real phone previews.": "finishWeb6",
  "Card type": "finishWeb7",
  "Browse templates": "finishWeb8",
  "Example content only. Your details will appear on your card.": "finishWeb9",
  "This design or color requires Pro. Choose a Free option to continue.": "finishWeb10",
  "Color": "finishWeb11",
  "Free": "finishWeb12",
  "Profile photo file": "finishWeb13",
  "Choose optional profile photo": "finishWeb14",
  "Selected profile": "finishWeb15",
  "e.g. Designer, Founder, Agent": "finishWeb16",
  "Use {{color}} as primary color": "finishWeb17",
  "Preview {{name}}": "finishWeb18",
  "{{name}} template": "finishWeb19",
  "Card designs": "finishWeb20",
  "Pro required": "finishWeb21",
  "Create eCard": "finishWeb22",
  "eCard designs": "finishWeb23",
  "Explore every Tavvy eCard design with real phone previews. Choose your look, then make it yours.": "finishWeb24",
  "My eCards": "finishWeb25",
  "Create an eCard": "finishWeb26",
  "Find your look.": "finishWeb27",
  "Explore real phone previews. Choose a design and color, then add your own details.": "finishWeb28",
  "Fictional examples for inspiration. Your card starts with your information.": "finishWeb29",
  "Design filters": "finishWeb30",
  "All designs": "finishWeb31",
  "Free designs": "finishWeb32",
  "Pro designs": "finishWeb33",
  "Jump to": "finishWeb34",
  "Jump to design": "finishWeb35",
  "Choose a design": "finishWeb36",
  "Free design": "finishWeb37",
  "{{name}} color options": "finishWeb38",
  "Use {{name}}, {{scheme}}": "finishWeb39",
  "Use design": "finishWeb40",
  "Your next introduction starts here.": "finishWeb41",
  "Choose your design": "finishWeb42",
  "Clear country search": "finishWeb43",
  "Civic Card": "finishWeb44",
  "Traditional business card. Logo, photo, name, title, company, and all contact details.": "finishWeb45",
  "Modern split layout. Colored header with logo and name, white bottom with contacts.": "finishWeb46",
  "Ultra-clean design. Lots of whitespace, thin typography, subtle accents.": "finishWeb47",
  "Simple link-in-bio style. Profile photo, name, and stacked link buttons.": "finishWeb48",
  "Elegant creative style. Script name, soft colors, perfect for personal brands.": "finishWeb49",
  "A real digital business card. Company logo, contact info, professional layout.": "finishWeb50",
  "The ultimate pro card. Industry, services, service area — all in one.": "finishWeb51",
  "Full cover photo on top with logo overlay. Clean white bottom with contact rows.": "finishWeb52",
  "Full-screen hero photo with your name overlaid. Bold and premium.": "finishWeb53",
  "Arch-framed photo with intro text. Perfect for realtors and agents.": "finishWeb54",
  "Bold colors with wave divider. Great for consultants and creatives.": "finishWeb55",
  "Structured corporate layout. Company logo, action icons, about section.": "finishWeb56",
  "Full-width hero photo that scrolls with content. Same premium feel, no parallax.": "finishWeb57",
  "Brazilian political e-Card. Candidate photo, ballot number, party identity, interactive proposals, and civic engagement.": "finishWeb58",
  "Brazilian flag as background with gradient overlay. Patriotic design with full civic features.": "finishWeb59",
  "Bold split-layout design. Large candidate photo with strong typography and high-contrast sections.": "finishWeb60",
  "Clean, modern design with white card on colored background. Elegant and professional.": "finishWeb61",
  "High-energy campaign style with diagonal cuts, bold CTA buttons, and rally-inspired design.": "finishWeb62",
  "Political e-Card for candidates and public servants worldwide. Photo, bio, platform positions, endorsements, and civic engagement.": "finishWeb63",
  "Perfect for food trucks, pop-ups, and mobile vendors. Cover photo, full menu with categories and prices, Tavvy endorsements, and location info.": "finishWeb64",
  "Designed for churches and faith communities. Cover banner, service times, sermon links, give button, and events.": "finishWeb65"
});

// Atlas audio controls; voice IDs and playback values remain unchanged.
Object.assign(RELEASE_COPY_KEYS, {
  "Listen to this article": "atlasListen",
  "Audio is not available for this article yet.": "atlasUnavailable",
  "Female": "atlasFemale",
  "Male": "atlasMale",
  "Play": "atlasPlay",
  "Pause": "atlasPause",
  "Audio position": "atlasPosition",
  "Back 15 seconds": "atlasBack",
  "Playback speed": "atlasSpeed",
  "Forward 15 seconds": "atlasForward",
  "Audio could not play. Tap Play to try again.": "atlasPlayError"
});

Object.assign(RELEASE_COPY_KEYS, {"Business": "creationBusiness", "Card for": "creationCardFor"});

Object.assign(RELEASE_COPY_KEYS, {"Joined": "accountFinishJoined", "Deleting...": "accountFinishDeleting"});

// Equivalent app-authored discovery labels share existing translations.
Object.assign(RELEASE_COPY_KEYS, {
  "Search Results": "publicFinishSearchResults",
  "Search results": "publicFinishSearchResults",
  "Search places or locations": "publicFinishSearchLocations",
  "Location is off. Enter a city to find places.": "locationDenied",
  "Location is unavailable. Enter a city to find places.": "locationUnavailable"
});

// Approved Free/Pro offer; prices and saved customer content are unchanged.
Object.assign(RELEASE_COPY_KEYS, {
  "No plan-based link limit": "ecardFreeOffer1",
  "Free includes a design in every category and no plan-based link limit. Pro adds premium designs, galleries, embedded videos, contact forms and professional credentials.": "ecardFreeOffer2",
  "Premium designs": "ecardFreeOffer3",
  "Choose from premium layouts and color palettes.": "ecardFreeOffer4",
  "Photo galleries": "ecardFreeOffer5",
  "Show multiple photos on your card.": "ecardFreeOffer6",
  "Embedded videos": "ecardFreeOffer7",
  "Add playable videos to your card.": "ecardFreeOffer8",
  "Contact forms": "ecardFreeOffer9",
  "Let visitors send an inquiry from your card.": "ecardFreeOffer10",
  "Professional credentials": "ecardFreeOffer11",
  "Display your professional credentials.": "ecardFreeOffer12"
});
