import React,{useState} from 'react';
import Head from 'next/head';
import Link from 'next/link';
import {useRouter} from 'next/router';
import AppLayout from '../AppLayout';
import ToolHeader from '../ToolHeader';
import {useThemeContext} from '../../contexts/ThemeContext';
import {supabase} from '../../lib/supabaseClient';
import {useProviderRead} from '../../hooks/useProviderRead';
import {listProviders,providerName,providerArea,publicWebUrl,ProviderKind} from '../../lib/providerPublic';
export default function ProviderDirectory({kind,category}:{kind:ProviderKind;category?:string}){const {theme}=useThemeContext();const router=useRouter();const [query,setQuery]=useState('');const [location,setLocation]=useState('');const [submitted,setSubmitted]=useState({query:'',location:''});const [specialty,setSpecialty]=useState('');const [offset,setOffset]=useState(0);const params={kind,category,...submitted,specialty,offset};const state=useProviderRead(JSON.stringify(params),()=>listProviders(supabase,params));const title=kind==='realtor'?'Browse Realtors':category?`${category.replace(/-/g,' ')} professionals`:'Browse Pros';return <AppLayout><Head><title>{title} · Tavvy</title></Head><div className="directory" style={{background:theme.background,color:theme.text}}><ToolHeader title={title}/><main><form onSubmit={e=>{e.preventDefault();setOffset(0);setSubmitted({query,location});}}><label>Search {kind==='realtor'?'Realtors':'professionals'}<input aria-label="Search profiles" value={query} maxLength={120} onChange={e=>setQuery(e.target.value)} placeholder="Name, business or city"/></label>{kind==='pros'?<label>City, state or ZIP<input value={location} onChange={e=>setLocation(e.target.value)}/></label>:null}<button type="submit">Search</button></form>{kind==='realtor'?<><label>Specialty<select value={specialty} onChange={e=>{setOffset(0);setSpecialty(e.target.value)}}>{['','Luxury','First-Time','Investment','Relocation','Commercial','Waterfront'].map(s=><option key={s} value={s}>{s||'All specialties'}</option>)}</select></label><Link href="/app/realtors/match/start" locale={router.locale}>Find my Realtor match</Link></>:<Link href="/app/pros/new-project" locale={router.locale}>Start a project</Link>}
 {state.loading?<p role="status">Loading profiles…</p>:state.error?<div role="alert"><p>{state.error}</p><button onClick={state.retry}>Try again</button></div>:!state.value?.providers.length?<p>No matching profiles to show. Try another name or location.</p>:<div className="cards">{state.value.providers.map(p=><Link key={p.id} href={`/app/${kind==='realtor'?'realtor':'pros/provider'}/${p.id}`} locale={router.locale} className="card">{publicWebUrl(p.profile_photo_url||p.logo_url)?<img src={publicWebUrl(p.profile_photo_url||p.logo_url)!} alt=""/>:<span className="initial" aria-hidden>{providerName(p).charAt(0)}</span>}<div><h2>{providerName(p)}</h2>{p.brokerage_name?<p>{p.brokerage_name}</p>:null}{providerArea(p)?<p>{providerArea(p)}</p>:null}{p.specialties?.length?<p>{p.specialties.slice(0,3).join(' · ')}</p>:null}</div></Link>)}</div>}
 <div className="pages">{offset>0?<button onClick={()=>setOffset(n=>Math.max(0,n-24))}>Previous profiles</button>:null}{state.value?.hasMore?<button onClick={()=>setOffset(n=>n+24)}>More profiles</button>:null}</div></main></div><style jsx>{`.directory{min-height:100vh;padding-bottom:110px}main{max-width:900px;margin:auto;padding:20px}form{display:flex;gap:12px;flex-wrap:wrap;align-items:end;margin-bottom:16px}label{display:flex;flex-direction:column;gap:6px;flex:1;min-width:170px}input,select,button{font:inherit;min-height:46px;border:1px solid ${theme.border};border-radius:12px;background:${theme.surface};color:${theme.text};padding:10px 14px}button{cursor:pointer}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:14px;margin-top:24px}.cards :global(.card){display:flex;align-items:center;gap:16px;min-width:0;background:${theme.surface};border:1px solid ${theme.border};border-radius:16px;padding:16px;color:inherit;text-decoration:none}.cards img,.initial{width:64px;height:64px;flex-shrink:0;border-radius:50%;object-fit:cover}.initial{display:flex;align-items:center;justify-content:center;font-size:26px;background:${theme.background}}h2{font-size:18px;margin:0}p{font-size:14px;color:${theme.textSecondary};line-height:1.5}select{margin-bottom:14px;max-width:360px}.pages{display:flex;gap:12px;margin-top:20px}`}</style></AppLayout>;}
