import React,{useState,useEffect} from 'react';
import Head from 'next/head';
import Link from 'next/link';
import {useRouter} from 'next/router';
import AppLayout from '../AppLayout';
import ToolHeader from '../ToolHeader';
import ContentSafetyActions,{CONTENT_SAFETY_CHANGED} from '../ContentSafetyActions';
import ProviderReviewForm from './ProviderReviewForm';
import {providerTapLabel,ProviderTapKind} from '../../lib/providerReviewTaps';
import {useThemeContext} from '../../contexts/ThemeContext';
import {useAuth} from '../../contexts/AuthContext';
import {supabase} from '../../lib/supabaseClient';
import {useProviderRead} from '../../hooks/useProviderRead';
import {getProvider,getProviderReviews,getProviderPhotos,providerName,providerArea,providerContacts,providerReviewDate,publicWebUrl,PublicProvider,ProviderKind} from '../../lib/providerPublic';

function Reviews({id,kind}:{id:string;kind:ProviderTapKind}){const [offset,setOffset]=useState(0);const feed=useProviderRead(JSON.stringify(['reviews',id,offset]),()=>getProviderReviews(supabase,id,offset));useEffect(()=>{window.addEventListener(CONTENT_SAFETY_CHANGED,feed.retry);return()=>window.removeEventListener(CONTENT_SAFETY_CHANGED,feed.retry);},[feed.retry]);return <section aria-labelledby="reviews-title"><h2 id="reviews-title">Customer reviews</h2>{feed.loading?<p role="status">Loading reviews…</p>:feed.error?<div role="alert"><p>{feed.error}</p><button onClick={feed.retry}>Retry reviews</button></div>:feed.value?.reviews.length?<>{feed.value.reviews.map(review=><article key={review.id} style={{borderBottom:'1px solid',padding:'16px 0'}}><div><strong>{review.rating} / 5</strong><span> · {providerReviewDate(review.created_at)}</span>{review.updated_at&&review.updated_at!==review.created_at?<span> · Edited</span>:null}</div>{review.title?<h3>{review.title}</h3>:null}{(['main','good','vibe','heads_up'] as const).map(d=>providerTapLabel(kind,d,review[`${d}_tap`])?<span key={d} style={{display:'inline-block',margin:'4px 6px 4px 0',padding:'5px 9px',borderRadius:99,border:'1px solid currentColor'}}>{d==='main'?(kind==='realtor'?'The real estate service':'The work'):d==='good'?'The Good':d==='vibe'?(kind==='realtor'?'Their Style':'The Vibe'):'Heads Up'}: {providerTapLabel(kind,d,review[`${d}_tap`])}</span>:null)}{review.content?<p style={{whiteSpace:'pre-wrap'}}>{review.content}</p>:null}<ContentSafetyActions kind="pro_review" contentId={review.id}/></article>)}</>:<p>No reviews to show.</p>}{offset>0?<button onClick={()=>setOffset(n=>Math.max(0,n-20))}>Previous reviews</button>:null}{feed.value?.hasMore?<button onClick={()=>setOffset(n=>n+20)}>More reviews</button>:null}</section>;}
function Photos({id}:{id:string}){const state=useProviderRead(`photos:${id}`,()=>getProviderPhotos(supabase,id));return <section><h2>Profile photos</h2>{state.loading?<p role="status">Loading photos…</p>:state.error?<div role="alert">{state.error}<button onClick={state.retry}>Retry photos</button></div>:state.value?.photos.length?<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(140px,1fr))',gap:12}}>{state.value.photos.map(p=><figure key={p.id} style={{margin:0}}><a href={p.image_url} target="_blank" rel="noopener noreferrer"><img src={p.image_url} alt={p.caption||'Profile photo'} style={{width:'100%',aspectRatio:'4/3',objectFit:'cover',borderRadius:12}}/></a>{p.caption?<figcaption>{p.caption}</figcaption>:null}</figure>)}</div>{state.value.hasMore?<p>Showing the first 60 photos.</p>:null}</>:<p>No photos added.</p>}</section>;}
function LoadedProfile({provider:p}:{provider:PublicProvider}){const {theme}=useThemeContext();const {user}=useAuth();const router=useRouter();const [tab,setTab]=useState<'overview'|'photos'>('overview');const [shareState,setShareState]=useState('');const [reviewVersion,setReviewVersion]=useState(0);const name=providerName(p);const image=publicWebUrl(p.profile_photo_url||p.logo_url);const cover=publicWebUrl(p.cover_photo_url||p.cover_image_url);const realtor=p.provider_type==='realtor';const share=async()=>{const url=`https://tavvy.com/app/${realtor?'realtor':'pros/provider'}/${p.id}`;try{if(navigator.share)await navigator.share({title:name,url});else if(navigator.clipboard){await navigator.clipboard.writeText(url);setShareState('Link copied.');}else setShareState(url);}catch(e){if((e as Error).name!=='AbortError')setShareState('The link could not be shared. Please try again.');}};return <>
 {cover?<img className="cover" src={cover} alt=""/>:null}<div className="identity">{image?<img className="portrait" src={image} alt={name}/>:<span className="initial" aria-hidden>{name.charAt(0)}</span>}<h2 className="name">{name}</h2>{p.brokerage_name?<p>{p.brokerage_name}</p>:null}{providerArea(p)?<p>{providerArea(p)}</p>:null}<div className="actions">{providerContacts(p).map(c=><a key={c.label} href={c.url} target={c.label==='Website'?'_blank':undefined} rel="noopener noreferrer">{c.label}</a>)}<button onClick={share}>Share</button></div>{shareState?<p role="status">{shareState}</p>:null}{!realtor?<Link href="/app/pros/new-project" locale={router.locale}>Start a project</Link>:<Link href="/app/realtors/match/start" locale={router.locale}>Find my Realtor match</Link>}</div>
 <nav aria-label="Profile sections" className="tabs">{(['overview','photos'] as const).map(t=><button aria-current={tab===t?'page':undefined} key={t} onClick={()=>setTab(t)}>{t==='overview'?'Overview':'Photos'}</button>)}</nav>{tab==='photos'?<Photos key={`${user?.id}:${p.id}`} id={p.id}/>:<><Reviews key={`${user?.id}:${p.id}:${reviewVersion}`} id={p.id} kind={realtor?'realtor':'pro'}/><ProviderReviewForm providerId={p.id} kind={realtor?'realtor':'pro'} signedIn={!!user} onSaved={()=>setReviewVersion(n=>n+1)}/><section><h2>About</h2><p>{p.bio||p.description||p.short_description||'This professional has not added a description.'}</p>{p.specialties?.length?<><h3>Specialties</h3><div className="tags">{p.specialties.map(s=><span key={s}>{s}</span>)}</div></>:null}{p.trade_category?<p>Services: {p.trade_category.replace(/[_-]/g,' ')}</p>:null}{(p.years_experience??p.years_in_business)!=null?<p>{p.years_experience??p.years_in_business} years of experience listed</p>:null}{p.license_number?<p>License listed by this professional: {p.license_number}</p>:null}{p.service_areas?.length?<p>Service areas: {p.service_areas.join(', ')}</p>:null}</section></>}
 <style jsx>{`.cover{width:100%;max-height:220px;object-fit:cover;border-radius:18px}.identity{text-align:center;padding:24px 0}.portrait,.initial{height:88px;width:88px;border-radius:50%;object-fit:cover;display:inline-flex;align-items:center;justify-content:center;background:${theme.surface};font-size:36px}.name{font-size:26px;margin:14px 0 6px}.identity p{margin:6px 0;color:${theme.textSecondary}}.actions{display:flex;gap:10px;justify-content:center;flex-wrap:wrap;margin:20px 0}.actions a,.actions button,.tabs button{min-height:44px;padding:10px 18px;border:1px solid ${theme.border};border-radius:12px;color:${theme.text};background:${theme.surface};text-decoration:none;cursor:pointer;font:inherit}.tabs{display:flex;gap:10px;border-bottom:1px solid ${theme.border};padding-bottom:16px}.tabs button[aria-current]{border-color:${theme.primary};font-weight:700}section{padding:20px 0;border-bottom:1px solid ${theme.border}}.tags{display:flex;gap:8px;flex-wrap:wrap}.tags span{padding:8px 12px;border-radius:12px;background:${theme.surface}}`}</style></>;}
export default function ProviderProfile({kind}:{kind?:ProviderKind}){const router=useRouter();const id=typeof router.query.id==='string'?router.query.id:'';const {user}=useAuth();const {theme}=useThemeContext();const state=useProviderRead(JSON.stringify(['profile',kind,id]),()=>getProvider(supabase,id,kind));const title=kind==='realtor'?'Realtor profile':'Professional profile';return <AppLayout><Head><title>{state.value?providerName(state.value):title} · Tavvy</title></Head><div style={{minHeight:'100vh',background:theme.background,color:theme.text,paddingBottom:110}}><ToolHeader title={title}/><main style={{maxWidth:760,margin:'0 auto',padding:20,overflowWrap:'anywhere'}}>{state.loading?<p role="status">Loading profile…</p>:state.error?<div role="alert"><h2>Profile unavailable</h2><p>{state.error}</p><button onClick={state.retry}>Try again</button></div>:!state.value?<><h2>Profile not found</h2><p>This profile may no longer be available.</p><Link href={kind==='realtor'?'/app/realtors/browse':'/app/pros'} locale={router.locale}>Back to {kind==='realtor'?'Realtors':'Pros'}</Link></>:<LoadedProfile key={`${user?.id}:${state.value.id}`} provider={state.value}/>}</main></div></AppLayout>;}
