// Tavvy eCard Templates Configuration
// Each template can have multiple color schemes
// Multi-page feature requires $4.99/month subscription

export interface ColorScheme {
  id: string;
  name: string;
  primary: string;      // Main gradient start
  secondary: string;    // Main gradient end
  accent: string;       // Buttons, highlights
  text: string;         // Primary text color
  textSecondary: string; // Secondary text color
  background: string;   // Card background
  cardBg: string;       // Inner card background (for minimal templates)
  border?: string;      // Border color (for luxury templates)
  isFree?: boolean;     // If true, available to all users (white, black, basic gradient)
}

export interface Template {
  id: string;
  name: string;
  description: string;
  category: 'professional' | 'creative' | 'minimal' | 'luxury' | 'fun';
  previewImage: string; // Local asset or URL
  isPremium: boolean;   // If true, requires any paid subscription ($4.99/mo consumer)
  isProOnly?: boolean;  // If true, only available to Tavvy Pros with active membership
  proCategories?: string[]; // Pro categories this template is best for (e.g., 'handyman', 'realtor')
  features: string[];   // List of features this template supports
  colorSchemes: ColorScheme[];
  layout: {
    photoPosition: 'top' | 'left' | 'right' | 'center' | 'cover';
    photoSize: 'small' | 'medium' | 'large' | 'cover';
    photoStyle: 'circle' | 'rounded' | 'square' | 'ornate' | 'cover';
    buttonStyle: 'rounded' | 'pill' | 'square' | 'outline' | 'frosted' | 'minimal';
    fontFamily: 'modern' | 'classic' | 'elegant' | 'playful' | 'executive';
    showBorder: boolean;
    borderStyle?: 'solid' | 'ornate' | 'gradient' | 'accent';
    backgroundPattern?: 'none' | 'icons' | 'geometric' | 'motion' | 'texture';
  };
}

export const TEMPLATES: Template[] = [
  // ============ FREE TEMPLATES ============
  {
    id: 'classic-blue',
    name: 'Classic',
    description: 'Clean professional look with gradient background',
    category: 'professional',
    previewImage: 'classic-blue',
    isPremium: false,
    features: ['gradient-bg', 'action-buttons', 'social-icons'],
    colorSchemes: [
      {
        id: 'white',
        name: 'White',
        primary: '#FFFFFF',
        secondary: '#F5F5F5',
        accent: 'rgba(0,0,0,0.1)',
        text: '#1A1A1A',
        textSecondary: '#666666',
        background: '#FFFFFF',
        cardBg: '#FFFFFF',
        isFree: true,
      },
      {
        id: 'black',
        name: 'Black',
        primary: '#1A1A1A',
        secondary: '#333333',
        accent: 'rgba(255,255,255,0.15)',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.7)',
        background: '#1A1A1A',
        cardBg: '#1A1A1A',
        isFree: true,
      },
      {
        id: 'blue',
        name: 'Ocean Blue',
        primary: '#1E90FF',
        secondary: '#00BFFF',
        accent: 'rgba(255,255,255,0.2)',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.8)',
        background: 'linear-gradient(180deg, #1E90FF 0%, #00BFFF 100%)',
        cardBg: 'transparent',
        isFree: true,
      },
      {
        id: 'navy',
        name: 'Navy',
        primary: '#1a2a4a',
        secondary: '#2d4a6f',
        accent: 'rgba(255,255,255,0.15)',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.7)',
        background: 'linear-gradient(180deg, #1a2a4a 0%, #2d4a6f 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'emerald',
        name: 'Emerald',
        primary: '#065f46',
        secondary: '#10b981',
        accent: 'rgba(255,255,255,0.2)',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.8)',
        background: 'linear-gradient(180deg, #065f46 0%, #10b981 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'purple',
        name: 'Royal Purple',
        primary: '#581c87',
        secondary: '#9333ea',
        accent: 'rgba(255,255,255,0.2)',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.8)',
        background: 'linear-gradient(180deg, #581c87 0%, #9333ea 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'sunset',
        name: 'Sunset',
        primary: '#f97316',
        secondary: '#ec4899',
        accent: 'rgba(255,255,255,0.2)',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.8)',
        background: 'linear-gradient(180deg, #f97316 0%, #ec4899 100%)',
        cardBg: 'transparent',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'large',
      photoStyle: 'circle',
      buttonStyle: 'frosted',
      fontFamily: 'modern',
      showBorder: false,
    },
  },
  {
    id: 'minimal-white',
    name: 'Minimal',
    description: 'Clean white card with subtle accents',
    category: 'minimal',
    previewImage: 'minimal-white',
    isPremium: false,
    features: ['white-card', 'list-layout', 'subtle-icons'],
    colorSchemes: [
      {
        id: 'teal',
        name: 'Teal',
        primary: '#14b8a6',
        secondary: '#0d9488',
        accent: '#14b8a6',
        text: '#1f2937',
        textSecondary: '#6b7280',
        background: '#0f172a',
        cardBg: '#FFFFFF',
      },
      {
        id: 'purple',
        name: 'Purple',
        primary: '#8b5cf6',
        secondary: '#7c3aed',
        accent: '#8b5cf6',
        text: '#1f2937',
        textSecondary: '#6b7280',
        background: '#1e1b4b',
        cardBg: '#FFFFFF',
      },
      {
        id: 'rose',
        name: 'Rose',
        primary: '#f43f5e',
        secondary: '#e11d48',
        accent: '#f43f5e',
        text: '#1f2937',
        textSecondary: '#6b7280',
        background: '#1c1917',
        cardBg: '#FFFFFF',
      },
      {
        id: 'slate',
        name: 'Slate',
        primary: '#475569',
        secondary: '#334155',
        accent: '#475569',
        text: '#1f2937',
        textSecondary: '#6b7280',
        background: '#0f172a',
        cardBg: '#FFFFFF',
      },
    ],
    layout: {
      photoPosition: 'top',
      photoSize: 'medium',
      photoStyle: 'circle',
      buttonStyle: 'pill',
      fontFamily: 'modern',
      showBorder: false,
    },
  },
  {
    id: 'creator',
    name: 'Creator',
    description: 'Bold and vibrant for content creators',
    category: 'creative',
    previewImage: 'creator',
    isPremium: false,
    features: ['gradient-bg', 'bold-buttons', 'social-focus'],
    colorSchemes: [
      {
        id: 'pink-purple',
        name: 'Pink Purple',
        primary: '#ec4899',
        secondary: '#8b5cf6',
        accent: 'rgba(255,255,255,0.25)',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'orange-red',
        name: 'Fire',
        primary: '#f97316',
        secondary: '#ef4444',
        accent: 'rgba(255,255,255,0.25)',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(135deg, #f97316 0%, #ef4444 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'cyan-blue',
        name: 'Electric',
        primary: '#06b6d4',
        secondary: '#3b82f6',
        accent: 'rgba(255,255,255,0.25)',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(135deg, #06b6d4 0%, #3b82f6 100%)',
        cardBg: 'transparent',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'large',
      photoStyle: 'circle',
      buttonStyle: 'pill',
      fontFamily: 'modern',
      showBorder: false,
    },
  },

  // ============ MORE FREE TEMPLATES ============
  {
    id: 'kids-fun',
    name: 'Kids & Fun',
    description: 'Colorful playful design with doodles',
    category: 'fun',
    previewImage: 'kids-fun',
    isPremium: false,
    features: ['colorful-buttons', 'playful-icons', 'doodle-bg'],
    colorSchemes: [
      {
        id: 'sky-blue',
        name: 'Sky Blue',
        primary: '#87CEEB',
        secondary: '#B0E0E6',
        accent: '#FFD700',
        text: '#1f2937',
        textSecondary: '#4b5563',
        background: '#87CEEB',
        cardBg: 'transparent',
      },
      {
        id: 'mint',
        name: 'Mint',
        primary: '#98FB98',
        secondary: '#90EE90',
        accent: '#FF69B4',
        text: '#1f2937',
        textSecondary: '#4b5563',
        background: '#98FB98',
        cardBg: 'transparent',
      },
      {
        id: 'lavender',
        name: 'Lavender',
        primary: '#E6E6FA',
        secondary: '#DDA0DD',
        accent: '#FFB6C1',
        text: '#1f2937',
        textSecondary: '#4b5563',
        background: '#E6E6FA',
        cardBg: 'transparent',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'large',
      photoStyle: 'circle',
      buttonStyle: 'pill',
      fontFamily: 'playful',
      showBorder: false,
    },
  },
  {
    id: 'modern-professional',
    name: 'Modern Pro',
    description: 'Clean card on blurred dark background',
    category: 'professional',
    previewImage: 'modern-professional',
    isPremium: false,
    features: ['white-card', 'dark-bg', 'cta-buttons'],
    colorSchemes: [
      {
        id: 'teal',
        name: 'Teal',
        primary: '#0d9488',
        secondary: '#14b8a6',
        accent: '#14b8a6',
        text: '#1f2937',
        textSecondary: '#6b7280',
        background: '#0f172a',
        cardBg: '#FFFFFF',
      },
      {
        id: 'blue',
        name: 'Blue',
        primary: '#2563eb',
        secondary: '#3b82f6',
        accent: '#3b82f6',
        text: '#1f2937',
        textSecondary: '#6b7280',
        background: '#0f172a',
        cardBg: '#FFFFFF',
      },
      {
        id: 'green',
        name: 'Green',
        primary: '#059669',
        secondary: '#10b981',
        accent: '#10b981',
        text: '#1f2937',
        textSecondary: '#6b7280',
        background: '#0f172a',
        cardBg: '#FFFFFF',
      },
    ],
    layout: {
      photoPosition: 'top',
      photoSize: 'small',
      photoStyle: 'circle',
      buttonStyle: 'pill',
      fontFamily: 'modern',
      showBorder: false,
    },
  },

  // ============ PREMIUM TEMPLATES ($4.99/mo) ============
  {
    id: 'neon-creator',
    name: 'Neon Creator',
    description: 'Vibrant neon style for influencers',
    category: 'creative',
    previewImage: 'neon-creator',
    isPremium: true,
    features: ['neon-glow', 'rainbow-ring', 'follower-badge', 'gradient-bg'],
    colorSchemes: [
      {
        id: 'pink-purple',
        name: 'Pink Purple',
        primary: '#ec4899',
        secondary: '#8b5cf6',
        accent: 'rgba(255,255,255,0.3)',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, #ec4899 0%, #8b5cf6 50%, #1e1b4b 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'cyan-purple',
        name: 'Cyber',
        primary: '#06b6d4',
        secondary: '#8b5cf6',
        accent: 'rgba(255,255,255,0.3)',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, #06b6d4 0%, #8b5cf6 50%, #0f172a 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'orange-pink',
        name: 'Sunset',
        primary: '#f97316',
        secondary: '#ec4899',
        accent: 'rgba(255,255,255,0.3)',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, #f97316 0%, #ec4899 50%, #1e1b4b 100%)',
        cardBg: 'transparent',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'large',
      photoStyle: 'ornate',
      buttonStyle: 'frosted',
      fontFamily: 'modern',
      showBorder: false,
    },
  },
  {
    id: 'luxury-gold',
    name: 'Luxury',
    description: 'Elegant black and gold with ornate details',
    category: 'luxury',
    previewImage: 'luxury-gold',
    isPremium: true,
    features: ['ornate-border', 'gold-accents', 'premium-fonts'],
    colorSchemes: [
      {
        id: 'black-gold',
        name: 'Black & Gold',
        primary: '#0a0a0a',
        secondary: '#1a1a1a',
        accent: '#d4af37',
        text: '#d4af37',
        textSecondary: 'rgba(212,175,55,0.8)',
        background: 'linear-gradient(180deg, #0a0a0a 0%, #1a1a1a 100%)',
        cardBg: '#0a0a0a',
        border: '#d4af37',
      },
      {
        id: 'navy-gold',
        name: 'Navy & Gold',
        primary: '#0f172a',
        secondary: '#1e293b',
        accent: '#d4af37',
        text: '#d4af37',
        textSecondary: 'rgba(212,175,55,0.8)',
        background: 'linear-gradient(180deg, #0f172a 0%, #1e293b 100%)',
        cardBg: '#0f172a',
        border: '#d4af37',
      },
      {
        id: 'black-silver',
        name: 'Black & Silver',
        primary: '#0a0a0a',
        secondary: '#1a1a1a',
        accent: '#c0c0c0',
        text: '#c0c0c0',
        textSecondary: 'rgba(192,192,192,0.8)',
        background: 'linear-gradient(180deg, #0a0a0a 0%, #1a1a1a 100%)',
        cardBg: '#0a0a0a',
        border: '#c0c0c0',
      },
      {
        id: 'burgundy-gold',
        name: 'Burgundy & Gold',
        primary: '#450a0a',
        secondary: '#7f1d1d',
        accent: '#d4af37',
        text: '#d4af37',
        textSecondary: 'rgba(212,175,55,0.8)',
        background: 'linear-gradient(180deg, #450a0a 0%, #7f1d1d 100%)',
        cardBg: '#450a0a',
        border: '#d4af37',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'medium',
      photoStyle: 'ornate',
      buttonStyle: 'outline',
      fontFamily: 'elegant',
      showBorder: true,
      borderStyle: 'ornate',
    },
  },
  {
    id: 'dark-pro',
    name: 'Dark Pro',
    description: 'Sleek dark theme with gold accents',
    category: 'professional',
    previewImage: 'dark-pro',
    isPremium: true,
    features: ['dark-theme', 'gold-accents', 'modern-layout'],
    colorSchemes: [
      {
        id: 'dark-gold',
        name: 'Dark Gold',
        primary: '#18181b',
        secondary: '#27272a',
        accent: '#d4af37',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.7)',
        background: '#09090b',
        cardBg: '#18181b',
        border: '#d4af37',
      },
      {
        id: 'dark-teal',
        name: 'Dark Teal',
        primary: '#18181b',
        secondary: '#27272a',
        accent: '#14b8a6',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.7)',
        background: '#09090b',
        cardBg: '#18181b',
        border: '#14b8a6',
      },
      {
        id: 'dark-blue',
        name: 'Dark Blue',
        primary: '#18181b',
        secondary: '#27272a',
        accent: '#3b82f6',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.7)',
        background: '#09090b',
        cardBg: '#18181b',
        border: '#3b82f6',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'medium',
      photoStyle: 'circle',
      buttonStyle: 'rounded',
      fontFamily: 'modern',
      showBorder: true,
      borderStyle: 'solid',
    },
  },
  {
    id: 'fun-colorful',
    name: 'Fun',
    description: 'Playful and colorful for casual use',
    category: 'fun',
    previewImage: 'fun-colorful',
    isPremium: true,
    features: ['colorful', 'playful-icons', 'rounded-elements'],
    colorSchemes: [
      {
        id: 'pastel',
        name: 'Pastel',
        primary: '#a5f3fc',
        secondary: '#fbcfe8',
        accent: '#fde047',
        text: '#1f2937',
        textSecondary: '#4b5563',
        background: 'linear-gradient(180deg, #a5f3fc 0%, #fbcfe8 100%)',
        cardBg: 'rgba(255,255,255,0.9)',
      },
      {
        id: 'neon',
        name: 'Neon',
        primary: '#22d3ee',
        secondary: '#f472b6',
        accent: '#a3e635',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(135deg, #22d3ee 0%, #f472b6 100%)',
        cardBg: 'rgba(0,0,0,0.3)',
      },
      {
        id: 'rainbow',
        name: 'Rainbow',
        primary: '#f87171',
        secondary: '#818cf8',
        accent: '#34d399',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(135deg, #f87171 0%, #fbbf24 25%, #34d399 50%, #22d3ee 75%, #818cf8 100%)',
        cardBg: 'rgba(255,255,255,0.15)',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'large',
      photoStyle: 'circle',
      buttonStyle: 'pill',
      fontFamily: 'playful',
      showBorder: false,
    },
  },

  // ============ NEW FREE TEMPLATES ============
  {
    id: 'business-card',
    name: 'Business Card',
    description: 'Traditional business card style layout',
    category: 'professional',
    previewImage: 'business-card',
    isPremium: false,
    features: ['horizontal-layout', 'contact-info', 'company-logo'],
    colorSchemes: [
      {
        id: 'white-blue',
        name: 'Corporate Blue',
        primary: '#1e40af',
        secondary: '#3b82f6',
        accent: '#1e40af',
        text: '#1f2937',
        textSecondary: '#6b7280',
        background: '#f8fafc',
        cardBg: '#FFFFFF',
      },
      {
        id: 'white-green',
        name: 'Corporate Green',
        primary: '#166534',
        secondary: '#22c55e',
        accent: '#166534',
        text: '#1f2937',
        textSecondary: '#6b7280',
        background: '#f8fafc',
        cardBg: '#FFFFFF',
      },
      {
        id: 'white-red',
        name: 'Corporate Red',
        primary: '#991b1b',
        secondary: '#ef4444',
        accent: '#991b1b',
        text: '#1f2937',
        textSecondary: '#6b7280',
        background: '#f8fafc',
        cardBg: '#FFFFFF',
      },
      {
        id: 'white-black',
        name: 'Monochrome',
        primary: '#18181b',
        secondary: '#3f3f46',
        accent: '#18181b',
        text: '#1f2937',
        textSecondary: '#6b7280',
        background: '#f8fafc',
        cardBg: '#FFFFFF',
      },
    ],
    layout: {
      photoPosition: 'left',
      photoSize: 'small',
      photoStyle: 'square',
      buttonStyle: 'rounded',
      fontFamily: 'classic',
      showBorder: true,
      borderStyle: 'solid',
    },
  },
  {
    id: 'gradient-wave',
    name: 'Gradient Wave',
    description: 'Modern wave pattern with smooth gradients',
    category: 'creative',
    previewImage: 'gradient-wave',
    isPremium: false,
    features: ['wave-pattern', 'gradient-bg', 'modern-buttons'],
    colorSchemes: [
      {
        id: 'ocean',
        name: 'Ocean',
        primary: '#0ea5e9',
        secondary: '#06b6d4',
        accent: 'rgba(255,255,255,0.25)',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, #0ea5e9 0%, #06b6d4 50%, #0891b2 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'forest',
        name: 'Forest',
        primary: '#22c55e',
        secondary: '#16a34a',
        accent: 'rgba(255,255,255,0.25)',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, #22c55e 0%, #16a34a 50%, #15803d 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'berry',
        name: 'Berry',
        primary: '#a855f7',
        secondary: '#d946ef',
        accent: 'rgba(255,255,255,0.25)',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, #a855f7 0%, #d946ef 50%, #c026d3 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'coral',
        name: 'Coral',
        primary: '#fb7185',
        secondary: '#f43f5e',
        accent: 'rgba(255,255,255,0.25)',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, #fb7185 0%, #f43f5e 50%, #e11d48 100%)',
        cardBg: 'transparent',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'large',
      photoStyle: 'circle',
      buttonStyle: 'frosted',
      fontFamily: 'modern',
      showBorder: false,
    },
  },
  {
    id: 'photo-focus',
    name: 'Photo Focus',
    description: 'Large photo with overlay text',
    category: 'creative',
    previewImage: 'photo-focus',
    isPremium: false,
    features: ['large-photo', 'text-overlay', 'minimal-ui'],
    colorSchemes: [
      {
        id: 'dark-overlay',
        name: 'Dark Overlay',
        primary: '#000000',
        secondary: '#1f2937',
        accent: '#FFFFFF',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.8)',
        background: 'rgba(0,0,0,0.6)',
        cardBg: 'transparent',
      },
      {
        id: 'light-overlay',
        name: 'Light Overlay',
        primary: '#FFFFFF',
        secondary: '#f3f4f6',
        accent: '#1f2937',
        text: '#1f2937',
        textSecondary: 'rgba(31,41,55,0.8)',
        background: 'rgba(255,255,255,0.85)',
        cardBg: 'transparent',
      },
      {
        id: 'gradient-overlay',
        name: 'Gradient Overlay',
        primary: '#8b5cf6',
        secondary: '#ec4899',
        accent: '#FFFFFF',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, rgba(139,92,246,0.8) 0%, rgba(236,72,153,0.8) 100%)',
        cardBg: 'transparent',
      },
    ],
    layout: {
      photoPosition: 'top',
      photoSize: 'large',
      photoStyle: 'square',
      buttonStyle: 'pill',
      fontFamily: 'modern',
      showBorder: false,
    },
  },

  // ============ NEW PREMIUM TEMPLATES ============
  {
    id: 'social-star',
    name: 'Social Star',
    description: 'Optimized for social media influencers',
    category: 'creative',
    previewImage: 'social-star',
    isPremium: true,
    features: ['follower-count', 'social-grid', 'verified-badge', 'gradient-bg'],
    colorSchemes: [
      {
        id: 'instagram',
        name: 'Instagram',
        primary: '#833AB4',
        secondary: '#FD1D1D',
        accent: '#FCB045',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(45deg, #833AB4 0%, #FD1D1D 50%, #FCB045 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        primary: '#00f2ea',
        secondary: '#ff0050',
        accent: '#FFFFFF',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(135deg, #000000 0%, #121212 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'youtube',
        name: 'YouTube',
        primary: '#FF0000',
        secondary: '#282828',
        accent: '#FFFFFF',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(180deg, #FF0000 0%, #282828 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'twitter',
        name: 'X / Twitter',
        primary: '#000000',
        secondary: '#14171A',
        accent: '#1DA1F2',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: '#000000',
        cardBg: 'transparent',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'large',
      photoStyle: 'circle',
      buttonStyle: 'pill',
      fontFamily: 'modern',
      showBorder: false,
    },
  },
  {
    id: 'elegant-script',
    name: 'Elegant Script',
    description: 'Sophisticated design with script typography',
    category: 'luxury',
    previewImage: 'elegant-script',
    isPremium: true,
    features: ['script-font', 'elegant-borders', 'premium-feel'],
    colorSchemes: [
      {
        id: 'champagne',
        name: 'Champagne',
        primary: '#fef3c7',
        secondary: '#fde68a',
        accent: '#92400e',
        text: '#78350f',
        textSecondary: '#92400e',
        background: 'linear-gradient(180deg, #fef3c7 0%, #fde68a 100%)',
        cardBg: 'rgba(255,255,255,0.5)',
        border: '#92400e',
      },
      {
        id: 'rose-gold',
        name: 'Rose Gold',
        primary: '#fecdd3',
        secondary: '#fda4af',
        accent: '#9f1239',
        text: '#881337',
        textSecondary: '#9f1239',
        background: 'linear-gradient(180deg, #fecdd3 0%, #fda4af 100%)',
        cardBg: 'rgba(255,255,255,0.5)',
        border: '#9f1239',
      },
      {
        id: 'ivory',
        name: 'Ivory',
        primary: '#fafaf9',
        secondary: '#e7e5e4',
        accent: '#44403c',
        text: '#1c1917',
        textSecondary: '#44403c',
        background: 'linear-gradient(180deg, #fafaf9 0%, #e7e5e4 100%)',
        cardBg: 'rgba(255,255,255,0.7)',
        border: '#44403c',
      },
      {
        id: 'midnight',
        name: 'Midnight',
        primary: '#1e1b4b',
        secondary: '#312e81',
        accent: '#c4b5fd',
        text: '#e0e7ff',
        textSecondary: '#c4b5fd',
        background: 'linear-gradient(180deg, #1e1b4b 0%, #312e81 100%)',
        cardBg: 'rgba(0,0,0,0.3)',
        border: '#c4b5fd',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'medium',
      photoStyle: 'ornate',
      buttonStyle: 'outline',
      fontFamily: 'elegant',
      showBorder: true,
      borderStyle: 'ornate',
    },
  },

  // ============ MORE PREMIUM TEMPLATES ============
  {
    id: 'corporate',
    name: 'Corporate',
    description: 'Professional business card style',
    category: 'professional',
    previewImage: 'corporate',
    isPremium: true,
    features: ['business-layout', 'company-branding', 'contact-cta'],
    colorSchemes: [
      {
        id: 'navy-white',
        name: 'Navy & White',
        primary: '#1e3a5f',
        secondary: '#2d5a87',
        accent: '#FFFFFF',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, #1e3a5f 0%, #2d5a87 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'charcoal',
        name: 'Charcoal',
        primary: '#374151',
        secondary: '#4b5563',
        accent: '#10b981',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, #374151 0%, #4b5563 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'burgundy',
        name: 'Burgundy',
        primary: '#7f1d1d',
        secondary: '#991b1b',
        accent: '#fcd34d',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, #7f1d1d 0%, #991b1b 100%)',
        cardBg: 'transparent',
      },
    ],
    layout: {
      photoPosition: 'left',
      photoSize: 'small',
      photoStyle: 'square',
      buttonStyle: 'rounded',
      fontFamily: 'classic',
      showBorder: false,
    },
  },
  {
    id: 'artist-portfolio',
    name: 'Artist Portfolio',
    description: 'Creative showcase for artists',
    category: 'creative',
    previewImage: 'artist-portfolio',
    isPremium: true,
    features: ['gallery-layout', 'creative-fonts', 'portfolio-links'],
    colorSchemes: [
      {
        id: 'gallery-white',
        name: 'Gallery White',
        primary: '#FFFFFF',
        secondary: '#f3f4f6',
        accent: '#1f2937',
        text: '#1f2937',
        textSecondary: '#6b7280',
        background: '#FFFFFF',
        cardBg: '#f9fafb',
      },
      {
        id: 'dark-gallery',
        name: 'Dark Gallery',
        primary: '#0a0a0a',
        secondary: '#171717',
        accent: '#FFFFFF',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.7)',
        background: '#0a0a0a',
        cardBg: '#171717',
      },
      {
        id: 'warm-gallery',
        name: 'Warm Gallery',
        primary: '#fef3c7',
        secondary: '#fde68a',
        accent: '#78350f',
        text: '#78350f',
        textSecondary: '#92400e',
        background: 'linear-gradient(180deg, #fef3c7 0%, #fde68a 100%)',
        cardBg: 'rgba(255,255,255,0.5)',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'large',
      photoStyle: 'square',
      buttonStyle: 'outline',
      fontFamily: 'elegant',
      showBorder: true,
      borderStyle: 'solid',
    },
  },
  {
    id: 'music-artist',
    name: 'Music Artist',
    description: 'For musicians, DJs, and producers',
    category: 'creative',
    previewImage: 'music-artist',
    isPremium: true,
    features: ['music-links', 'streaming-icons', 'tour-dates'],
    colorSchemes: [
      {
        id: 'spotify-green',
        name: 'Spotify Green',
        primary: '#1DB954',
        secondary: '#191414',
        accent: '#1DB954',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, #191414 0%, #121212 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'vinyl-black',
        name: 'Vinyl Black',
        primary: '#0a0a0a',
        secondary: '#1a1a1a',
        accent: '#f97316',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.8)',
        background: '#0a0a0a',
        cardBg: '#1a1a1a',
      },
      {
        id: 'neon-club',
        name: 'Neon Club',
        primary: '#ec4899',
        secondary: '#8b5cf6',
        accent: '#22d3ee',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(135deg, #ec4899 0%, #8b5cf6 50%, #22d3ee 100%)',
        cardBg: 'transparent',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'large',
      photoStyle: 'circle',
      buttonStyle: 'pill',
      fontFamily: 'modern',
      showBorder: false,
    },
  },
  {
    id: 'real-estate',
    name: 'Real Estate',
    description: 'For property professionals',
    category: 'professional',
    previewImage: 'real-estate',
    isPremium: true,
    features: ['property-links', 'contact-cta', 'professional-layout'],
    colorSchemes: [
      {
        id: 'luxury-gold',
        name: 'Luxury Gold',
        primary: '#1f2937',
        secondary: '#374151',
        accent: '#d4af37',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, #1f2937 0%, #374151 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'modern-blue',
        name: 'Modern Blue',
        primary: '#1e40af',
        secondary: '#3b82f6',
        accent: '#FFFFFF',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, #1e40af 0%, #3b82f6 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'earth-tones',
        name: 'Earth Tones',
        primary: '#78350f',
        secondary: '#92400e',
        accent: '#fef3c7',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, #78350f 0%, #92400e 100%)',
        cardBg: 'transparent',
      },
    ],
    layout: {
      photoPosition: 'top',
      photoSize: 'medium',
      photoStyle: 'rounded',
      buttonStyle: 'rounded',
      fontFamily: 'classic',
      showBorder: false,
    },
  },
  {
    id: 'fitness-coach',
    name: 'Fitness Coach',
    description: 'For trainers and wellness pros',
    category: 'creative',
    previewImage: 'fitness-coach',
    isPremium: true,
    features: ['booking-link', 'social-proof', 'energy-design'],
    colorSchemes: [
      {
        id: 'energy-orange',
        name: 'Energy Orange',
        primary: '#f97316',
        secondary: '#ea580c',
        accent: '#FFFFFF',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(180deg, #f97316 0%, #ea580c 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'power-red',
        name: 'Power Red',
        primary: '#dc2626',
        secondary: '#b91c1c',
        accent: '#FFFFFF',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(180deg, #dc2626 0%, #b91c1c 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'zen-green',
        name: 'Zen Green',
        primary: '#059669',
        secondary: '#047857',
        accent: '#FFFFFF',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(180deg, #059669 0%, #047857 100%)',
        cardBg: 'transparent',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'large',
      photoStyle: 'circle',
      buttonStyle: 'pill',
      fontFamily: 'modern',
      showBorder: false,
    },
  },
  {
    id: 'restaurant',
    name: 'Restaurant',
    description: 'For food and hospitality',
    category: 'professional',
    previewImage: 'restaurant',
    isPremium: true,
    features: ['menu-link', 'reservation-cta', 'location-map'],
    colorSchemes: [
      {
        id: 'bistro-red',
        name: 'Bistro Red',
        primary: '#991b1b',
        secondary: '#7f1d1d',
        accent: '#fef3c7',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, #991b1b 0%, #7f1d1d 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'cafe-brown',
        name: 'Café Brown',
        primary: '#78350f',
        secondary: '#451a03',
        accent: '#fef3c7',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, #78350f 0%, #451a03 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'modern-black',
        name: 'Modern Black',
        primary: '#0a0a0a',
        secondary: '#171717',
        accent: '#d4af37',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.8)',
        background: '#0a0a0a',
        cardBg: '#171717',
      },
    ],
    layout: {
      photoPosition: 'top',
      photoSize: 'large',
      photoStyle: 'rounded',
      buttonStyle: 'rounded',
      fontFamily: 'elegant',
      showBorder: false,
    },
  },
  {
    id: 'tech-startup',
    name: 'Tech Startup',
    description: 'Modern tech company vibe',
    category: 'professional',
    previewImage: 'tech-startup',
    isPremium: true,
    features: ['product-links', 'team-section', 'modern-design'],
    colorSchemes: [
      {
        id: 'cyber-blue',
        name: 'Cyber Blue',
        primary: '#0ea5e9',
        secondary: '#0284c7',
        accent: '#FFFFFF',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(180deg, #0ea5e9 0%, #0284c7 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'dark-mode',
        name: 'Dark Mode',
        primary: '#18181b',
        secondary: '#27272a',
        accent: '#22d3ee',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.8)',
        background: '#09090b',
        cardBg: '#18181b',
      },
      {
        id: 'gradient-tech',
        name: 'Gradient Tech',
        primary: '#6366f1',
        secondary: '#8b5cf6',
        accent: '#FFFFFF',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
        cardBg: 'transparent',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'medium',
      photoStyle: 'rounded',
      buttonStyle: 'rounded',
      fontFamily: 'modern',
      showBorder: false,
    },
  },
  {
    id: 'wedding',
    name: 'Wedding',
    description: 'Elegant event and wedding style',
    category: 'luxury',
    previewImage: 'wedding',
    isPremium: true,
    features: ['event-details', 'rsvp-link', 'elegant-design'],
    colorSchemes: [
      {
        id: 'blush-pink',
        name: 'Blush Pink',
        primary: '#fdf2f8',
        secondary: '#fce7f3',
        accent: '#be185d',
        text: '#831843',
        textSecondary: '#9d174d',
        background: 'linear-gradient(180deg, #fdf2f8 0%, #fce7f3 100%)',
        cardBg: 'rgba(255,255,255,0.7)',
        border: '#be185d',
      },
      {
        id: 'sage-green',
        name: 'Sage Green',
        primary: '#ecfdf5',
        secondary: '#d1fae5',
        accent: '#065f46',
        text: '#064e3b',
        textSecondary: '#065f46',
        background: 'linear-gradient(180deg, #ecfdf5 0%, #d1fae5 100%)',
        cardBg: 'rgba(255,255,255,0.7)',
        border: '#065f46',
      },
      {
        id: 'classic-white',
        name: 'Classic White',
        primary: '#FFFFFF',
        secondary: '#f5f5f4',
        accent: '#d4af37',
        text: '#1c1917',
        textSecondary: '#44403c',
        background: '#FFFFFF',
        cardBg: '#fafaf9',
        border: '#d4af37',
      },
      {
        id: 'navy-gold',
        name: 'Navy & Gold',
        primary: '#1e3a5f',
        secondary: '#2d5a87',
        accent: '#d4af37',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, #1e3a5f 0%, #2d5a87 100%)',
        cardBg: 'transparent',
        border: '#d4af37',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'medium',
      photoStyle: 'ornate',
      buttonStyle: 'outline',
      fontFamily: 'elegant',
      showBorder: true,
      borderStyle: 'ornate',
    },
  },

  // ============ PRO-ONLY TEMPLATES (Included with Tavvy Pro Subscription) ============
  
  // Template 1: Icon Luxe - Elegant background icons/patterns for service providers
  {
    id: 'pro-icon-luxe',
    name: 'Icon Luxe',
    description: 'Elegant background patterns with strong typography. Perfect for service providers.',
    category: 'professional',
    previewImage: 'pro-icon-luxe',
    isPremium: false,
    isProOnly: true,
    proCategories: ['handyman', 'plumber', 'electrician', 'cleaner', 'pet-services', 'contractor'],
    features: ['icon-pattern-bg', 'accent-border', 'badge-area', 'action-icons', 'category-icons'],
    colorSchemes: [
      {
        id: 'slate-teal',
        name: 'Slate & Teal',
        primary: '#1e293b',
        secondary: '#334155',
        accent: '#14b8a6',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.8)',
        background: 'linear-gradient(180deg, #1e293b 0%, #334155 100%)',
        cardBg: 'transparent',
        border: '#14b8a6',
      },
      {
        id: 'navy-orange',
        name: 'Navy & Orange',
        primary: '#1e3a5f',
        secondary: '#2d4a6f',
        accent: '#f97316',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.8)',
        background: 'linear-gradient(180deg, #1e3a5f 0%, #2d4a6f 100%)',
        cardBg: 'transparent',
        border: '#f97316',
      },
      {
        id: 'charcoal-lime',
        name: 'Charcoal & Lime',
        primary: '#27272a',
        secondary: '#3f3f46',
        accent: '#84cc16',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.8)',
        background: 'linear-gradient(180deg, #27272a 0%, #3f3f46 100%)',
        cardBg: 'transparent',
        border: '#84cc16',
      },
      {
        id: 'deep-blue-gold',
        name: 'Deep Blue & Gold',
        primary: '#172554',
        secondary: '#1e3a8a',
        accent: '#fbbf24',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.8)',
        background: 'linear-gradient(180deg, #172554 0%, #1e3a8a 100%)',
        cardBg: 'transparent',
        border: '#fbbf24',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'large',
      photoStyle: 'circle',
      buttonStyle: 'pill',
      fontFamily: 'modern',
      showBorder: true,
      borderStyle: 'accent',
      backgroundPattern: 'icons',
    },
  },

  // Template 2: Image Focus - Full-bleed background image with overlay
  {
    id: 'pro-image-focus',
    name: 'Image Focus',
    description: 'Stunning full-bleed background image. Ideal for realtors, food, and premium services.',
    category: 'professional',
    previewImage: 'pro-image-focus',
    isPremium: false,
    isProOnly: true,
    proCategories: ['realtor', 'food-truck', 'photographer', 'event-planner', 'restaurant', 'catering'],
    features: ['full-bleed-image', 'gradient-overlay', 'floating-actions', 'badge-area', 'showcase-area'],
    colorSchemes: [
      {
        id: 'dark-overlay',
        name: 'Dark Overlay',
        primary: 'rgba(0,0,0,0.7)',
        secondary: 'rgba(0,0,0,0.4)',
        accent: '#FFFFFF',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.85)',
        background: 'linear-gradient(180deg, rgba(0,0,0,0.3) 0%, rgba(0,0,0,0.8) 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'warm-overlay',
        name: 'Warm Overlay',
        primary: 'rgba(120,53,15,0.7)',
        secondary: 'rgba(180,83,9,0.4)',
        accent: '#fef3c7',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(180deg, rgba(120,53,15,0.3) 0%, rgba(120,53,15,0.85) 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'cool-overlay',
        name: 'Cool Overlay',
        primary: 'rgba(30,58,138,0.7)',
        secondary: 'rgba(59,130,246,0.4)',
        accent: '#dbeafe',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(180deg, rgba(30,58,138,0.3) 0%, rgba(30,58,138,0.85) 100%)',
        cardBg: 'transparent',
      },
      {
        id: 'green-overlay',
        name: 'Green Overlay',
        primary: 'rgba(6,78,59,0.7)',
        secondary: 'rgba(16,185,129,0.4)',
        accent: '#d1fae5',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(180deg, rgba(6,78,59,0.3) 0%, rgba(6,78,59,0.85) 100%)',
        cardBg: 'transparent',
      },
    ],
    layout: {
      photoPosition: 'cover',
      photoSize: 'cover',
      photoStyle: 'cover',
      buttonStyle: 'frosted',
      fontFamily: 'elegant',
      showBorder: false,
      backgroundPattern: 'none',
    },
  },

  // Template 3: Minimal Executive - Clean, trust-focused design
  {
    id: 'pro-minimal-executive',
    name: 'Minimal Executive',
    description: 'Clean and authoritative. Perfect for realtors, consultants, and coaches.',
    category: 'minimal',
    previewImage: 'pro-minimal-executive',
    isPremium: false,
    isProOnly: true,
    proCategories: ['realtor', 'consultant', 'coach', 'financial-advisor', 'lawyer', 'accountant'],
    features: ['white-card', 'accent-line', 'badge-prominent', 'minimal-icons', 'executive-typography'],
    colorSchemes: [
      {
        id: 'white-navy',
        name: 'White & Navy',
        primary: '#FFFFFF',
        secondary: '#f8fafc',
        accent: '#1e3a5f',
        text: '#1e293b',
        textSecondary: '#64748b',
        background: '#f1f5f9',
        cardBg: '#FFFFFF',
        border: '#1e3a5f',
      },
      {
        id: 'cream-forest',
        name: 'Cream & Forest',
        primary: '#fefce8',
        secondary: '#fef9c3',
        accent: '#166534',
        text: '#1c1917',
        textSecondary: '#57534e',
        background: '#f5f5f4',
        cardBg: '#fefce8',
        border: '#166534',
      },
      {
        id: 'white-burgundy',
        name: 'White & Burgundy',
        primary: '#FFFFFF',
        secondary: '#fef2f2',
        accent: '#7f1d1d',
        text: '#1c1917',
        textSecondary: '#57534e',
        background: '#fafafa',
        cardBg: '#FFFFFF',
        border: '#7f1d1d',
      },
      {
        id: 'white-charcoal',
        name: 'White & Charcoal',
        primary: '#FFFFFF',
        secondary: '#f4f4f5',
        accent: '#27272a',
        text: '#18181b',
        textSecondary: '#71717a',
        background: '#e4e4e7',
        cardBg: '#FFFFFF',
        border: '#27272a',
      },
    ],
    layout: {
      photoPosition: 'top',
      photoSize: 'medium',
      photoStyle: 'rounded',
      buttonStyle: 'minimal',
      fontFamily: 'executive',
      showBorder: true,
      borderStyle: 'accent',
      backgroundPattern: 'none',
    },
  },

  // Template 4: On The Go Dynamic - For mobile businesses
  {
    id: 'pro-on-the-go',
    name: 'On The Go',
    description: 'Dynamic and active. Designed for mobile businesses and on-the-go services.',
    category: 'creative',
    previewImage: 'pro-on-the-go',
    isPremium: false,
    isProOnly: true,
    proCategories: ['mobile-detailer', 'food-truck', 'mobile-groomer', 'delivery', 'mobile-mechanic', 'mobile-notary'],
    features: ['motion-elements', 'location-badge', 'service-area', 'quick-actions', 'dynamic-bg'],
    colorSchemes: [
      {
        id: 'electric-blue',
        name: 'Electric Blue',
        primary: '#0ea5e9',
        secondary: '#0284c7',
        accent: '#fbbf24',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(135deg, #0ea5e9 0%, #0284c7 100%)',
        cardBg: 'transparent',
        border: '#fbbf24',
      },
      {
        id: 'vibrant-orange',
        name: 'Vibrant Orange',
        primary: '#f97316',
        secondary: '#ea580c',
        accent: '#FFFFFF',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(135deg, #f97316 0%, #ea580c 100%)',
        cardBg: 'transparent',
        border: '#FFFFFF',
      },
      {
        id: 'fresh-green',
        name: 'Fresh Green',
        primary: '#22c55e',
        secondary: '#16a34a',
        accent: '#fef08a',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(135deg, #22c55e 0%, #16a34a 100%)',
        cardBg: 'transparent',
        border: '#fef08a',
      },
      {
        id: 'purple-energy',
        name: 'Purple Energy',
        primary: '#a855f7',
        secondary: '#9333ea',
        accent: '#fcd34d',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.9)',
        background: 'linear-gradient(135deg, #a855f7 0%, #9333ea 100%)',
        cardBg: 'transparent',
        border: '#fcd34d',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'medium',
      photoStyle: 'circle',
      buttonStyle: 'pill',
      fontFamily: 'modern',
      showBorder: true,
      borderStyle: 'accent',
      backgroundPattern: 'motion',
    },
  },

  // Template 5: Dark Premium - High-end luxury feel
  {
    id: 'pro-dark-premium',
    name: 'Dark Premium',
    description: 'Luxurious dark theme with metallic accents. For high-end services.',
    category: 'luxury',
    previewImage: 'pro-dark-premium',
    isPremium: false,
    isProOnly: true,
    proCategories: ['luxury-realtor', 'high-end-services', 'vip-experiences', 'premium-consultant', 'executive-coach'],
    features: ['dark-bg', 'metallic-accents', 'subtle-texture', 'premium-typography', 'badge-area'],
    colorSchemes: [
      {
        id: 'black-gold',
        name: 'Black & Gold',
        primary: '#0a0a0a',
        secondary: '#171717',
        accent: '#d4af37',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.75)',
        background: 'linear-gradient(180deg, #0a0a0a 0%, #171717 100%)',
        cardBg: 'transparent',
        border: '#d4af37',
      },
      {
        id: 'charcoal-silver',
        name: 'Charcoal & Silver',
        primary: '#18181b',
        secondary: '#27272a',
        accent: '#a1a1aa',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.75)',
        background: 'linear-gradient(180deg, #18181b 0%, #27272a 100%)',
        cardBg: 'transparent',
        border: '#a1a1aa',
      },
      {
        id: 'black-rose-gold',
        name: 'Black & Rose Gold',
        primary: '#0c0a09',
        secondary: '#1c1917',
        accent: '#b76e79',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.75)',
        background: 'linear-gradient(180deg, #0c0a09 0%, #1c1917 100%)',
        cardBg: 'transparent',
        border: '#b76e79',
      },
      {
        id: 'midnight-platinum',
        name: 'Midnight & Platinum',
        primary: '#020617',
        secondary: '#0f172a',
        accent: '#e2e8f0',
        text: '#FFFFFF',
        textSecondary: 'rgba(255,255,255,0.75)',
        background: 'linear-gradient(180deg, #020617 0%, #0f172a 100%)',
        cardBg: 'transparent',
        border: '#e2e8f0',
      },
    ],
    layout: {
      photoPosition: 'center',
      photoSize: 'medium',
      photoStyle: 'circle',
      buttonStyle: 'outline',
      fontFamily: 'elegant',
      showBorder: true,
      borderStyle: 'gradient',
      backgroundPattern: 'texture',
    },
  },
];

// Multi-page subscription price ID (to be set from Stripe)
export const MULTI_PAGE_PRICE_ID = 'price_XXXXXX'; // Replace with actual Stripe price ID

// Helper functions
export const getTemplateById = (id: string): Template | undefined => {
  return TEMPLATES.find(t => t.id === id);
};

export const getFreeTemplates = (): Template[] => {
  return TEMPLATES.filter(t => !t.isPremium && !t.isProOnly);
};

export const getPremiumTemplates = (): Template[] => {
  return TEMPLATES.filter(t => t.isPremium && !t.isProOnly);
};

export const getProOnlyTemplates = (): Template[] => {
  return TEMPLATES.filter(t => t.isProOnly === true);
};

export const getTemplatesForUser = (isPro: boolean, hasPremiumSubscription: boolean): Template[] => {
  return TEMPLATES.filter(t => {
    // Pro-only templates require Pro membership
    if (t.isProOnly) return isPro;
    // Premium templates require premium subscription
    if (t.isPremium) return hasPremiumSubscription;
    // Free templates available to all
    return true;
  });
};

export const getProTemplatesByCategory = (proCategory: string): Template[] => {
  return TEMPLATES.filter(t => t.isProOnly && t.proCategories?.includes(proCategory));
};

export const getTemplatesByCategory = (category: Template['category']): Template[] => {
  return TEMPLATES.filter(t => t.category === category);
};

export const getColorSchemeById = (templateId: string, colorSchemeId: string): ColorScheme | undefined => {
  const template = getTemplateById(templateId);
  return template?.colorSchemes.find(cs => cs.id === colorSchemeId);
};

export default TEMPLATES;
