import React,{useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/router';
import ContentSafetyActions,{CONTENT_SAFETY_CHANGED} from '../ContentSafetyActions';
import {useAuth} from '../../contexts/AuthContext';
import {CruiseShip} from '../../lib/cruises/catalog';
import {PlaceEvidence,isCurrentWarning} from '../../lib/placeEvidence';
import {CruiseReview,CruiseSignal,fetchCruiseEvidence,fetchCruiseReviews,fetchCruiseSignals,saveCruiseVisit} from '../../lib/cruises/reviews';
export default function CruiseReviewPanel({ship}:{ship:CruiseShip}){
 const router=useRouter(),{user}=useAuth();const [evidence,setEvidence]=useState<PlaceEvidence|null>(null),[reviews,setReviews]=useState<CruiseReview[]>([]),[total,setTotal]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
 const generation=useRef(0),pagination=useRef<number|null>(null);const[loadingMore,setLoadingMore]=useState(false);
 const [open,setOpen]=useState(false),[signals,setSignals]=useState<CruiseSignal[]>([]),[selected,setSelected]=useState<Record<string,number>>({}),[date,setDate]=useState(''),[cabin,setCabin]=useState(''),[note,setNote]=useState(''),[saving,setSaving]=useState(false),[formError,setFormError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;const request=++generation.current;pagination.current=null;setLoadingMore(false);setLoading(true);setError('');setReviews([]);setTotal(0);void Promise.all([fetchCruiseEvidence(ship.universe_id),fetchCruiseReviews(ship.universe_id)]).then(([next,feed])=>{if(active&&request===generation.current){setEvidence(next);setReviews(feed.reviews);setTotal(feed.total)}}).catch(e=>{if(active&&request===generation.current)setError(e.message)}).finally(()=>{if(active&&request===generation.current)setLoading(false)});return()=>{active=false;if(generation.current===request)generation.current++};},[ship.universe_id,refresh,user?.id]);
 useEffect(()=>{const refreshFeed=()=>{generation.current++;setReviews([]);setTotal(0);setLoading(true);setRefresh(v=>v+1)};window.addEventListener(CONTENT_SAFETY_CHANGED,refreshFeed);return()=>window.removeEventListener(CONTENT_SAFETY_CHANGED,refreshFeed)},[]);
 const loadMore=async()=>{const request=generation.current;if(pagination.current===request)return;pagination.current=request;setLoadingMore(true);try{const more=await fetchCruiseReviews(ship.universe_id,reviews.length);if(generation.current!==request)return;setReviews(current=>[...current,...more.reviews]);setTotal(more.total)}catch(e){if(generation.current===request)setError((e as Error).message)}finally{if(generation.current===request){pagination.current=null;setLoadingMore(false)}}};
 const start=async()=>{if(!user){await router.push('/app/login?redirect='+encodeURIComponent(router.asPath));return;}setOpen(true);setFormError('');try{setSignals(await fetchCruiseSignals())}catch(e){setFormError((e as Error).message)}};
 const save=async(event:React.FormEvent)=>{event.preventDefault();if(saving)return;setSaving(true);setFormError('');try{await saveCruiseVisit({universeId:ship.universe_id,sailingDate:date,signals:Object.entries(selected).map(([signalId,intensity])=>({signalId,intensity})),publicNote:note,cabinCategoryId:cabin||null});setMessage('Your experience has been saved.');setOpen(false);setRefresh(v=>v+1)}catch(e){setFormError((e as Error).message)}finally{setSaving(false)}};
 const cells=evidence?[{id:'main',name:'The onboard experience',items:[...evidence.coreSignals,...evidence.coreConcerns.map(item=>({...item,label:'Concern: '+item.label}))]},{id:'good',name:'The Good',items:evidence.goodSignals.filter(s=>!evidence.coreSignals.some(c=>c.label===s.label))},{id:'vibe',name:'The Vibe',items:evidence.vibeSignals},{id:'heads',name:'Heads Up',items:evidence.warnings.filter(isCurrentWarning)}]:[];
 return <section className="guest-reports"><div className="title"><div><h2>What guests experienced</h2><p>Reports describe a sailing, not every trip this ship makes.</p></div>{ship.operating_status==='operating'&&<button onClick={start}>Add your taps</button>}</div>{message&&<p role="status">{message}</p>}{loading?<p role="status">Loading guest reports…</p>:error||evidence?.dataStatus==='unavailable'?<div role="alert"><p>{error||evidence?.unavailableReason}</p><button onClick={()=>setRefresh(v=>v+1)}>Retry guest reports</button></div>:<><div className="evidence-grid">{cells.map(cell=><details key={cell.id} className={cell.id}><summary><span>{cell.name}</span><strong>{cell.items[0]?.label||'No reports yet'}</strong><small>{cell.items[0]?`${cell.items[0].reports} guest${cell.items[0].reports===1?'':'s'}`:'Be the first to share your experience'}</small></summary>{cell.items.slice(1).map(item=><p key={item.label}>{item.label} · {item.reports} guests</p>)}</details>)}</div><p className="note">{evidence?.recentReviewers||0} distinct guest{evidence?.recentReviewers===1?'':'s'} in the last 6 months. Older concerns remain in history; fewer recent mentions do not prove a repair.</p><h3>Recent guest reports</h3><p className="note">Blocked authors are hidden from your reports feed. Ship summaries still include all eligible public experiences.</p>{reviews.map(review=><article key={review.id}><p className="date">Sailing date: {review.sailing_date} · reported by the guest{review.cabin_category_name?` · ${review.cabin_category_name}`:''}</p><div className="tags">{review.signals?.map(s=><span key={s.label} className={s.category}>{s.label}{s.intensity>1?` · ${s.intensity} taps`:''}</span>)}</div>{review.public_note&&<p>{review.public_note}</p>}<ContentSafetyActions kind="cruise_visit" contentId={review.id}/></article>)}{!reviews.length&&<p>No guest reports to show.</p>}{reviews.length<total&&<button disabled={loadingMore} onClick={loadMore}>{loadingMore?'Loading reports…':'Load more reports'}</button>}</>}
 {open&&<form onSubmit={save} className="composer"><h3>Share your ship experience</h3><p>Describe your own sailing. For a specific restaurant or shop, use that venue’s page.</p><label>Sailing date<input type="date" required max={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/></label>{ship.cabin_categories.length>0&&<label>Cabin category (optional)<select value={cabin} onChange={e=>setCabin(e.target.value)}><option value="">Prefer not to say</option>{ship.cabin_categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}{(['best_for','vibe','heads_up'] as const).map(group=><fieldset key={group}><legend>{group==='best_for'?'The Good':group==='vibe'?'The Vibe':'Heads Up'}</legend><div className="choices">{signals.filter(s=>s.signal_type===group).map(signal=><div key={signal.id}><button type="button" aria-pressed={!!selected[signal.id]} onClick={()=>setSelected(current=>{const next={...current};if(next[signal.id])delete next[signal.id];else next[signal.id]=1;return next})}>{signal.label}</button>{selected[signal.id]&&<select aria-label={`${signal.label} intensity`} value={selected[signal.id]} onChange={e=>setSelected(current=>({...current,[signal.id]:Number(e.target.value)}))}>{[1,2,3].map(n=><option key={n} value={n}>{n} tap{n>1?'s':''}</option>)}</select>}</div>)}</div></fieldset>)}<label>Public note (optional)<textarea maxLength={4000} rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="What would help another guest decide?"/></label><p className="note">Do not include your cabin number or current whereabouts. A new report for the same sailing date updates your report while preserving its issue history.</p>{formError&&<p role="alert">{formError}</p>}<div className="actions"><button type="button" disabled={saving} onClick={()=>setOpen(false)}>Cancel</button><button disabled={saving||!date||!Object.keys(selected).length}>{saving?'Saving…':'Save experience'}</button></div></form>}
 <style jsx>{`.title{display:flex;justify-content:space-between;align-items:center;gap:18px;flex-wrap:wrap}.title h2{margin-bottom:8px}.title p,.note,.date{font-size:13px;line-height:1.6;opacity:.8}.evidence-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:20px 0}.evidence-grid details{border:1px solid var(--line);background:var(--panel);border-radius:16px;padding:16px}.evidence-grid summary{cursor:pointer;list-style:none}.evidence-grid span,.evidence-grid strong,.evidence-grid small{display:block}.evidence-grid span{font-size:13px;margin-bottom:12px}.evidence-grid strong{font-size:17px}.evidence-grid small{font-size:12px;margin-top:8px;opacity:.75}.heads{border-top:3px solid #bf852d!important}.main{border-top:3px solid #9453ab!important}.good{border-top:3px solid #329d96!important}.vibe{border-top:3px solid #7e62d1!important}article{padding:18px 0;border-bottom:1px solid var(--line)}.tags,.choices,.actions{display:flex;gap:8px;flex-wrap:wrap}.tags span{border:1px solid var(--line);padding:6px 9px;border-radius:20px;font-size:12px}.tags .heads_up{border-color:#b98236}button,select,input,textarea{font:inherit;color:inherit;background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:11px 13px;min-height:44px}button{cursor:pointer}button:disabled{opacity:.5;cursor:default}button[aria-pressed=true]{border-color:var(--accent);box-shadow:inset 0 0 0 1px var(--accent)}.composer{margin-top:24px;padding:20px;border:1px solid var(--line);border-radius:16px;background:var(--panel)}.composer label{display:flex;flex-direction:column;gap:8px;margin:18px 0}fieldset{border:0;padding:0;margin:20px 0}legend{margin-bottom:10px;font-weight:700}.choices>div{display:flex;gap:4px}textarea{resize:vertical}.actions{justify-content:flex-end}:focus-visible{outline:3px solid var(--accent);outline-offset:3px}@media(max-width:360px){.evidence-grid{gap:8px}.evidence-grid details{padding:12px}.choices>div{flex-wrap:wrap}}`}</style></section>;
}
