import { useOwnerRequestScope } from '../../../hooks/useOwnerRequestScope';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState, useRef } from 'react';
import { useAuth } from '../../../contexts/AuthContext';
import { supabase } from '../../../lib/supabaseClient';
import { claimStatusLabel, getRestaurantWorkspace, isPlaceId, linkRestaurantCard, OwnerWorkspace, RESTAURANT_LINKS, saveRestaurantDetails, WEEK_DAYS } from '../../../lib/restaurantOwner';
import RestaurantOwnerLayout from '../../../components/RestaurantOwnerLayout';
import RestaurantProfileEditor from '../../../components/RestaurantProfileEditor';

export default function RestaurantWorkspacePage(){
 const router=useRouter(),{user,loading:authLoading}=useAuth();const placeId=typeof router.query.placeId==='string'?router.query.placeId:'';
 const [workspaceData,setWorkspace]=useState<OwnerWorkspace|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const ownerKey=`${user?.id||''}:${placeId}`,scope=useOwnerRequestScope(ownerKey),loadSequence=useRef(0);
 const [loadedFor,setLoadedFor]=useState('');const workspace=loadedFor===ownerKey?workspaceData:null;
 const [phone,setPhone]=useState(''),[website,setWebsite]=useState(''),[description,setDescription]=useState(''),[cardId,setCardId]=useState('');
 const [hours,setHours]=useState<Record<string,string>>({}),[links,setLinks]=useState<Record<string,string>>({}),[editHours,setEditHours]=useState(false);
 const load=async(background=false)=>{
  if(!user||!isPlaceId(placeId))return false;
  const valid=scope.capture(),request=++loadSequence.current,current=()=>valid()&&request===loadSequence.current;
  if(!background)setLoading(true);setError('');
  try{const w=await getRestaurantWorkspace(supabase,placeId);if(!current())return false;setWorkspace(w);setLoadedFor(ownerKey);setPhone(w.place.phone||'');setWebsite(w.place.website||'');setDescription(w.place.description||'');setHours(Object.fromEntries(WEEK_DAYS.map(day=>[day,typeof(w.place.hours as any)?.[day]==='string'?(w.place.hours as any)[day]:''])));setLinks(Object.fromEntries(RESTAURANT_LINKS.map(l=>[l.key,w.links?.[l.key]||''])));return true;}
  catch(error){if(current())setError((error as Error).message);return false;}finally{if(current())setLoading(false);}
 };
 useEffect(()=>{setBusy(false);setMessage('');setError('');setCardId('');setEditHours(false);if(user&&isPlaceId(placeId))void load();else if(!authLoading)setLoading(false);},[user?.id,placeId,authLoading]);
 useEffect(()=>{if(!workspace?.canManage)return;const fragment=router.asPath.split('#')[1];if(fragment&&['profile','details','ecard'].includes(fragment))requestAnimationFrame(()=>{const section=document.getElementById(fragment);if(section instanceof HTMLDetailsElement){section.open=true;section.scrollIntoView({block:'start'});}});},[workspace?.canManage,router.asPath]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!workspace?.canManage||busy)return;const valid=scope.capture();setBusy(true);setMessage('');setError('');try{await saveRestaurantDetails(supabase,placeId,{phone,website,description,links,...(editHours?{hours}:{})});if(!valid())return;await load(true);if(valid()){setEditHours(false);setMessage('Restaurant details saved.');}}catch(error){if(valid())setError((error as Error).message);}finally{if(valid())setBusy(false);}};
 const linkCard=async()=>{if(!workspace?.canManage||busy)return;const valid=scope.capture();setBusy(true);setError('');setMessage('');try{await linkRestaurantCard(supabase,placeId,cardId);if(!valid())return;await load(true);if(valid())setMessage('Your eCard is linked to this restaurant.');}catch(error){if(valid())setError((error as Error).message);}finally{if(valid())setBusy(false);}};
 const profileSaved=()=>{const valid=scope.capture();void load(true).then(()=>{if(valid())setMessage('Place information saved.');});};
 const linkedCard=workspace?.cards?.find(c=>c.place_id===placeId),claim=workspace?.claim||null;
 return <RestaurantOwnerLayout title={workspace?.place.name||'Your restaurant'}><h1>{workspace?.place.name||'Your restaurant'}</h1>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="status" role="status">{message}</p>}{authLoading||loading?<p>Loading your workspace…</p>:!user?<div className="panel"><p>Sign in to continue setting up your restaurant.</p><Link className="button" href={`/app/login?returnUrl=${encodeURIComponent(`/app/business/${placeId}`)}`}>Sign in</Link></div>:!workspace?<button onClick={()=>void load()}>Try again</button>:<><p><Link href={`/app/place/${placeId}`}>View your public place page →</Link></p><section className="panel"><h2>{claimStatusLabel(claim)}</h2>{!claim?<><p>Request ownership to manage this restaurant.</p><Link className="button" href={`/app/business/claim?placeId=${placeId}`}>Request ownership</Link></>:!workspace.canManage?<><p>Your request is saved. Editing becomes available after ownership is independently verified. You can return here to check the decision.</p><p>Submitted {new Date(claim.created_at).toLocaleDateString()} · {claim.business_email}</p>{claim.review_notes&&<p>{claim.review_notes}</p>}<button onClick={()=>void load()}>Refresh status</button></>:<p>Your restaurant workspace is ready. Changes below publish to your real place.</p>}</section>
 <section className="panel"><h2>Your setup checklist</h2><ul className="checklist"><li><strong>{workspace.canManage?'✓':'1.'} Verify ownership</strong>{claimStatusLabel(claim)}</li>{[{title:'Name & location',done:!!(workspace.place.name&&workspace.place.street&&workspace.place.city),href:'#profile',text:'Keep your address and map location accurate'},{title:'Contact & hours',done:!!workspace.place.phone&&!!workspace.place.hours&&Object.values(workspace.place.hours as object).some(Boolean),href:'#details',text:'Hours, phone, social and delivery links'},{title:'Tavvy Menu',done:!!workspace.menu?.is_active,href:`/place/${placeId}/menu-editor`,text:'Add dishes, photos, dietary information and prices'},{title:'Restaurant eCard',done:!!linkedCard?.is_published,href:'#ecard',text:'Connect your restaurant to a shareable digital card'},{title:'Photos & stories',done:(workspace.storyCount||0)>0,href:`/app/business/${placeId}/media`,text:'Choose your cover photo and manage your restaurant’s media'}].map((step,i)=><li key={step.title}><strong>{step.done?'✓':`${i+2}.`} {step.title}</strong><p className="muted">{step.text}</p>{workspace.canManage?<Link href={step.href} onClick={()=>{if(step.href.startsWith('#')){const panel=document.querySelector(step.href);if(panel instanceof HTMLDetailsElement)panel.open=true;}}}>{step.done?'Manage':'Set up'} →</Link>:<span className="muted">Available after ownership verification</span>}</li>)}</ul></section>
 {workspace.canManage&&<><RestaurantProfileEditor key={ownerKey} placeId={placeId} onSaved={profileSaved}/><details className="panel" id="details"><summary><strong>Contact, hours & links</strong></summary><form onSubmit={save}><label htmlFor="owner-phone">Public phone<input id="owner-phone" type="tel" maxLength={32} value={phone} onChange={e=>setPhone(e.target.value)} /></label><label htmlFor="owner-site">Website<input id="owner-site" type="url" placeholder="https://" maxLength={2048} value={website} onChange={e=>setWebsite(e.target.value)} /></label><label htmlFor="owner-about">About your restaurant<textarea id="owner-about" maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)} /></label><details className="owner-subsection"><summary>Weekly hours</summary><p className="muted">Use your restaurant’s local time. Enter 09:00-17:00, Closed, or Open 24 hours. Split hours: 12:00-15:00,17:00-22:00. Leave unknown days blank.</p><label className="check"><input type="checkbox" checked={editHours} onChange={e=>setEditHours(e.target.checked)} />Update the weekly schedule</label>{editHours&&WEEK_DAYS.map(day=><label key={day}>{day}<input value={hours[day]||''} onChange={e=>setHours({...hours,[day]:e.target.value})} placeholder="Not provided" maxLength={120} /></label>)}</details><details className="owner-subsection"><summary>Social & delivery links</summary><p className="muted">Paste the exact profiles and restaurant listings you control. Leave a service blank if your restaurant does not use it.</p>{RESTAURANT_LINKS.map(l=><label key={l.key}>{l.label}<input type="url" value={links[l.key]||''} onChange={e=>setLinks({...links,[l.key]:e.target.value})} placeholder={`https://${l.domain}/…`} maxLength={2048} /></label>)}</details><button disabled={busy}>{busy?'Saving…':'Save contact information'}</button></form></details>
 <details className="panel" id="ecard"><summary><strong>Restaurant eCard</strong></summary>{linkedCard&&<p><Link href={`/app/ecard/${linkedCard.id}/edit`}>Edit {linkedCard.full_name} →</Link></p>}<p>Create your restaurant card, then choose it here to connect it to this place.</p><p><Link href="/app/ecard/new">Create an eCard →</Link></p><label htmlFor="owner-card">Your eCards<select id="owner-card" value={cardId} onChange={e=>setCardId(e.target.value)}><option value="">Choose a card</option>{workspace.cards?.filter(c=>!c.place_id||c.place_id===placeId).map(c=><option key={c.id} value={c.id}>{c.full_name}{c.is_published?'':' (draft)'}</option>)}</select></label><button disabled={busy||!cardId} onClick={linkCard}>Connect this eCard</button></details>
 <section className="panel"><h2>Table ordering</h2><p>Configure ordering readiness and tax before accepting table orders.</p><div className="actions"><Link href={`/place/${placeId}/ordering-settings`}>Ordering settings →</Link><Link href={`/place/${placeId}/dashboard`}>Kitchen orders →</Link></div></section><details className="panel"><summary><strong>Menu activity</strong></summary>{workspace.menu?<><div className="stats"><div><strong>{workspace.menu.view_count??'—'}</strong>Menu opens</div><div><strong>{workspace.menu.share_count??'—'}</strong>Menu shares</div></div><p className="muted">Existing recorded totals for this menu. These are not unique visitors, completed orders, or restaurant revenue.</p></>:<p>Publish your Tavvy Menu to begin building your restaurant’s presence.</p>}</details></>}
 </>}<style jsx>{`summary{cursor:pointer;min-height:44px;display:flex;align-items:center;font-size:18px}summary::before{content:'›';margin-right:10px}details[open]>summary::before{content:'⌄'}.owner-subsection{border-top:1px solid currentColor;padding:12px 0;margin:18px 0}.owner-subsection summary{font-size:16px}:global(.checklist){display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px}`}</style></RestaurantOwnerLayout>;
}
