import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { useAuth } from '../../../contexts/AuthContext';
import { supabase } from '../../../lib/supabaseClient';
import { getRestaurantWorkspace, isPlaceId, OwnerPlace, submitRestaurantClaim } from '../../../lib/restaurantOwner';
import RestaurantOwnerLayout from '../../../components/RestaurantOwnerLayout';

export default function ClaimRestaurant() {
  const router=useRouter(), {user,loading:authLoading}=useAuth();
  const placeId=typeof router.query.placeId==='string'?router.query.placeId:'';
  const returnUrl=`/app/business/claim?placeId=${encodeURIComponent(placeId)}`;
  const [place,setPlace]=useState<OwnerPlace|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [name,setName]=useState(''),[role,setRole]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[accepted,setAccepted]=useState(false);
  useEffect(()=>{let active=true;if(!isPlaceId(placeId))return;setError('');supabase.from('places').select('id,name,street,city,region').eq('id',placeId).maybeSingle().then(({data,error})=>{if(active){if(error||!data)setError('This place could not be found. Return to restaurant lookup.');else setPlace(data);}});return()=>{active=false;};},[placeId]);
  useEffect(()=>{let active=true;if(!user||!isPlaceId(placeId))return;setEmail(user.email||'');getRestaurantWorkspace(supabase,placeId).then(w=>{if(active&&w.claim)router.replace(`/app/business/${placeId}`);}).catch(()=>{if(active)setError('Your existing claim status could not be checked. Refresh before submitting.');});return()=>{active=false;};},[user?.id,placeId]);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!user||!place)return;setBusy(true);setError('');try{await submitRestaurantClaim(supabase,{placeId,name,role,email,phone,accepted});await router.replace(`/app/business/${placeId}`);}catch(error){setError((error as Error).message);}finally{setBusy(false);}};
  return <RestaurantOwnerLayout title="Claim your restaurant"><h1>{place?`Claim ${place.name}`:'Claim your restaurant'}</h1>{place&&<p>{[place.street,place.city,place.region].filter(Boolean).join(', ')}</p>}{error&&<p className="error" role="alert">{error}</p>}{!isPlaceId(placeId)&&router.isReady?<p><Link href="/app/business">Find your restaurant first →</Link></p>:authLoading?<p>Checking your account…</p>:!user?<section className="panel"><h2>Keep your restaurant connected to your account</h2><p>Sign in or create an account to request ownership. We’ll bring you back to this restaurant.</p><div className="actions"><Link className="button" href={`/app/signup?returnUrl=${encodeURIComponent(returnUrl)}&context=restaurant`}>Create a restaurant account</Link><Link href={`/app/login?returnUrl=${encodeURIComponent(returnUrl)}`}>Sign in</Link></div></section>:place&&<form className="panel" onSubmit={submit}><h2>Tell us how you represent this restaurant</h2><p>Your contact details are used for ownership verification and are not published on the place page. Submitting a request does not grant editing access.</p><label htmlFor="claim-name">Your full name<input id="claim-name" required maxLength={120} autoComplete="name" value={name} onChange={e=>setName(e.target.value)} /></label><label htmlFor="claim-role">Your role<input id="claim-role" required maxLength={80} placeholder="Owner or authorized manager" value={role} onChange={e=>setRole(e.target.value)} /></label><label htmlFor="claim-email">Business email<input id="claim-email" type="email" required maxLength={254} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} /></label><label htmlFor="claim-phone">Contact phone<input id="claim-phone" type="tel" required maxLength={32} autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)} /></label><label className="check"><input type="checkbox" required checked={accepted} onChange={e=>setAccepted(e.target.checked)} />I am authorized to represent this restaurant and the information is accurate.</label><button disabled={busy}>{busy?'Saving request…':'Submit ownership request'}</button></form>}</RestaurantOwnerLayout>;
}
